### ISSUE TITLE
Make windows easier to resize by increasing border size.

### ISSUE THREAD

**Issue by bruno-robert** [vinceliuice/WhiteSur-gtk-theme#100]
So apparently according to [this](https://forum.xfce.org/viewtopic.php?pid=40740#p40740) and [this](https://unix.stackexchange.com/questions/156435/how-can-i-make-windows-easier-to-resize-in-xfce), the theme is what defines how easy it is to grab a window border.

I'm wondering if there is a way to make the window edges easier to grab and resize without affecting the aesthetic of the theme?
Currently, it's always a pain to resize a window without using the keyboard.

Great theme btw, thank you so much!

**Comment by vinceliuice** [comment]
This requires xfwm to improve grab and resize support

**Comment by Coeur-Noir** [comment]
Obviously.

But as seen here https://unix.stackexchange.com/a/364531 : 
⋅ The width of the grab area is controlled by the theme
⋅ something to change in the theme definition (…) `~/.gtkrc-2.0`

Those bits look old ( 2016~2017 ) so things may have changed since…
