### ISSUE TITLE
Firefox 121 broken context menu

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#1001]
It's the menu you get when right clicking an empty area.

On 120:
![Screenshot from 2023-12-22 12-16-38](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/399c2bd1-1b81-487a-a7eb-32e90ccbc46f)

On 121:
![Screenshot from 2023-12-22 12-23-12](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/048fcba7-db65-43e5-a9a9-326d5af9c8d8)

**Comment by SVTA-OP** [comment]
Yeah, same issue. The icons are still visible yet tiny. 
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/126323835/7648d5f0-b5d5-482a-b598-d810efb93572)
