### ISSUE TITLE
Changing the top panel font size

### ISSUE THREAD

**Issue by jkemp814** [vinceliuice/WhiteSur-gtk-theme#1003]
Hello Everyone,

How do I change the top panel font size? On a HiDPI monitor, the fonts are way too small. I have found all the posts stating to use 

```
stage {
    font-family: SF Pro Display Medium;
    font-size: 16px;
}

```
But that does not change anything.

If I create my on theme and import this theme, it works, but breaks a lot of pop-up windows.

```
@import url("resource:///org/gnome/theme/gnome-shell.css");
stage {
    font-family: SF Pro Display Medium;
    font-size: 16px;
}

```
It would be nice to have a section already built into the theme, so it could be edited.

What do you suggest I enter into the gnome-shell.css of this theme?

**Comment by bredigian** [comment]
I've same problem. Do you have any solution?

**Comment by bredigian** [comment]
Look at this: https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/525
It's worked for me.

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If so, please respond, if not, please close your issue! thanks 😉
