### ISSUE TITLE
Switch to Default Shell Text When Using GDM Theme

### ISSUE THREAD

**Issue by nkiswardy** [vinceliuice/WhiteSur-gtk-theme#1009]
I love the GDM theme, but when I install it using `sudo ./tweaks.sh -g` it changes the default font in the top status bar. Can you please add an option to either use the GDM theme font, or the default Gnome font? Is there a way to do this currently? Thanks!

**Comment by bloodnighttw** [comment]
I am also facing same issue!

**Comment by scottyphillips** [comment]
Yes I would like this too, the GDM theme from Whitesur is the best, but it seems to mess a little with Adwaita in particular once its installed.

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If so, please respond, if not, please close your issue! thanks 😉

**Comment by nkiswardy** [comment]
The text appears to be fixed. Thank you @vinceliuice
