### ISSUE TITLE
[BUG] Firefox: Popup windows have a weird black opaque shadow

### ISSUE THREAD

**Issue by geraltofrivia** [vinceliuice/WhiteSur-gtk-theme#101]
Description:
Anytime a new window is popped up (not manually opened), but as a popup like clicking "Help -> About Firefox" or using something like [this](https://www.quackit.com/html/codes/html_popup_window_code.cfm), the window has a weird black opaque shadow. 

Illustrative Screenshot: 
![Screenshot from 2021-01-05 11-51-56](https://user-images.githubusercontent.com/7823009/103638146-c8ce3c80-4f4c-11eb-8066-b4c94bdf12b7.png)

Details:
- OS: Elementary OS 5.1.7 Hera
- Firefox Version: 84.0 (64-bit)
- GTK Theme: WhiteSur-light
- Firefox userChrome.css: this repo's

How to replicate bug:
Simply Help > About Firefox to open a "popup window" and it should have a similar issue. 

This only seem to be happening with Firefox windows, not in Chrome, and not in any other part of the OS.

**Comment by vinceliuice** [comment]
Is this issue only appear when using this theme?

**Comment by geraltofrivia** [comment]
Good question! Turns out, no! Its a firefox issue with Elementary's GTK Stylesheet. I'm closing this issue down since it doesn't relate to this theme. My bad.

[src1](https://www.bountysource.com/issues/93449886-firefox-big-black-shadow-around-pop-up), [src2](https://bugzilla.mozilla.org/show_bug.cgi?id=1666839), [src3](https://bugzilla.mozilla.org/show_bug.cgi?id=1682377)

Btw, I love the work you've done here. Using pretty much all aspects of this theme everywhere.
