### ISSUE TITLE
Top bar shadow

### ISSUE THREAD

**Issue by alisson3000br** [vinceliuice/WhiteSur-gtk-theme#1010]
Hello everyone, first thank you for this amazing theme 

I wanna ask about how to add shadow to the top panel/top bar, i did tried to change gnome shell css searched all the possibilities there but no success, for sure there is a way to do it but i cant find it anywhere even on google

thanks

**Comment by kernelb00t** [comment]
I don't think this would be a very great design choice, because of wanted behaviour:
The panel is in the highest layer of the view, meaning that if you put a shadow rule on it, the shadow will go over your maximized apps and make the UI very very bad looking.

If you still want to, please reply and I'll get you on how to do it.

**Comment by alisson3000br** [comment]
Hello thanks for reply, i still want to know how to add the shadow, i added shadow to the wallpaper in photoshop but everytime i change wallpaper i have to go to photoshop hahaha

**Comment by alisson3000br** [comment]
![Screenshot from 2024-05-21 17-00-49](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/148722558/50a0a937-6491-4672-bd42-ec1e02b5e9c6)

**Comment by alisson3000br** [comment]
dash to dock i added shadow to the wallpaper too

**Comment by alisson3000br** [comment]
i wish i could add shadows straight to the panel and the dock so i dont have to photoshop wallpapers

**Comment by alisson3000br** [comment]
I use dash to dock

**Comment by alisson3000br** [comment]
i searched on google but there is nothing that works which is weird

**Comment by washburn24** [comment]
I don't exactly know what you mean by shadow, but the Blur My Shell theme has some panel and dock options.

**Comment by vinceliuice** [comment]
#panel {
  box-shadow: 0 3px 8px rgba(0, 0, 0, 0.15);
}
