### ISSUE TITLE
How to remove this line?

### ISSUE THREAD

**Issue by minhdevs** [vinceliuice/WhiteSur-gtk-theme#1011]
### How to remove this line ?

![Sans titre](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/104881854/4d656fd8-b87e-4b06-9eee-8054b8e0d0ff)

**Comment by AnuraagaNath** [comment]
I do not think that you can remove it. Cause it is default and comes with Google Chrome.

**Comment by stoneC0der** [comment]
@minhdevs Which version of chrome are using?
Mine is on the right side

![Screenshot from 2024-02-22 11-33-52](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/11365636/012cf27f-e214-47e6-8a2b-1d8cb3a967eb)

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If so, please respond, if not, please close your issue! thanks 😉 @minhdevs
