### ISSUE TITLE
No border-radius on WorkspaceView workspaces thumbnails

### ISSUE THREAD

**Issue by kernelb00t** [vinceliuice/WhiteSur-gtk-theme#1012]
![Screenshot from 2024-01-17 08-44-31](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/68474172/c22609cc-2269-46dd-a6dd-6f46a69139a7)
![Screenshot from 2024-01-17 08-44-13](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/68474172/44dff241-1546-4d62-b2a0-457d4837ffc8)
Border radius is not applied on workspace thumbnails when on Application overview, but does exist when on Workspaces overview.
I'm thinking of 2 solutions:
If percentage-based border-radius is used, the same rule can be reused for the tiles.
If pixel-based border radius, we have to find a way to transform the pixel into percentage to be more portable.

**Comment by vinceliuice** [comment]
Gnome-shell do not support set border-radius on workspace thumbnails when workspaces < 4

**Comment by kernelb00t** [comment]
Really? That's shameful. Has an upstream patch been reported? Or is it a technical limitation?

**Comment by vinceliuice** [comment]
Gnome team did not set any class for this thumbnails, so we can not make any style to it

**Comment by vinceliuice** [comment]
![Screenshot from 2024-01-18 16-32-44](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/f9ae8bf3-8e60-42d3-90a8-73d86e1c69f3)

**Comment by kernelb00t** [comment]
Ok, closing issue.
