### ISSUE TITLE
Firefox Monterey theme not working properly

### ISSUE THREAD

**Issue by Zorro-no** [vinceliuice/WhiteSur-gtk-theme#1013]
Arch Linux, GNOME 45.3, Wayland
Updated just now
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/108409246/e952dfa1-1d86-4f81-973b-e9096428c94a)

**Comment by vinceliuice** [comment]
What's your firefox version ?

**Comment by Zorro-no** [comment]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/108409246/30bf560a-a245-4db4-ac44-4aaadf39611c)

**Comment by SVTA-OP** [comment]
If I'm not wrong, I think you can change the button alignment by running `./tweaks.sh -f -e`. Or just install `gnome-tweaks` and check it there.

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If so, please respond, if not, please close your issue! thanks 😉 @Zorro-no

**Comment by Zorro-no** [comment]
sorry i forgot
