### ISSUE TITLE
Steam icon is light on light panel in Linux Mint 21.3.

### ISSUE THREAD

**Issue by junglized** [vinceliuice/WhiteSur-gtk-theme#1016]
Steam icon remains light despite light theme being chosen. Because of that the icon is barely indistiguishable form panel.

My system info:
OS: Linux Mint 21.3 Virginia
Arch: x86_64
Kernel: 6.5.0-15-generic
Desktop: X-Cinnamon
Display Server: x11

Screenshot: 
![Screenshot from 2024-01-28 21-26-30](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/26525585/89df6b18-7358-4f2e-a787-e99b03046fd9)

Theme settings:
![Screenshot from 2024-01-28 21-30-31](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/26525585/0b3a4de1-fe35-4385-bce5-45b7b6e502f7)

**Comment by kernelb00t** [comment]
Does this issue appears with the stock light theme? If so, please report issue to Steam. If not, please provide a screenshot :wink:

**Comment by junglized** [comment]
> Does this issue appears with the stock light theme? If so, please report issue to Steam. If not, please provide a screenshot 😉

Thanks for a reply.

Stock icon themes (Mint-X, Mint-Y and Mint-L) don't have light versions of themeselves and display the icon wrong way. On the other hand Numix-light, Papirus-light and Qogir-light display the icon properly. Basically every "-light" theme I have installed, apart from WhiteSur-light, have it right.

**Comment by kernelb00t** [comment]
Hmm, it's strange actually. BTW, I think this is a Steam problem, as the icon doesn't change when I deactivate the icon and shell theme. Try without any themes, by uninstalling(!) the theme first (see the README), then GNOME Tweaks -> Appearance -> Set all options to defaults. Log out/log in, then launch Steam. 
If the problem persists, file an issue at Steam and post the link here so we can close the issue and track if there's any needs. If you have any questions, DO NOT create another issue, just respond to this issue and reopen it if there is a proof that WhiteSur is the cause.

**Comment by junglized** [comment]
Wait a sec...🫷I've just realised I should post this in [White Sur icon theme repo](https://github.com/vinceliuice/WhiteSur-icon-theme), not here in GTK theme repo... We actually might be talking about two different things? 🤨

**Comment by kernelb00t** [comment]
Oh yes, that is indeed a WhiteSur icon theme problem, if the other themes get it right. Look at other white theme Git sources that get the Steam icon right (you can use GitHub's search) and check if there's any differences/if they use a steam icon that WhiteSur doesn't use.

@vinceliuice We need info about this, and I want to add that I tried on Gnome (WhiteSur light) and there's the same problem.

**Comment by junglized** [comment]
I'll open issue in appropriate repo. Thanks.

**Comment by junglized** [comment]
Thanks, I've just opened another issue in appriopriate repo.
