### ISSUE TITLE
Option to remove Border lines on shell icons (like fluent gtk theme)

### ISSUE THREAD

**Issue by KyberNull** [vinceliuice/WhiteSur-gtk-theme#1017]
Request to add an option which lets the user to enable/disable the border lines on Shell UI elements such as the panel

![Screenshot from 2024-01-29 19-52-13](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/50045306/44b13c89-1a75-4282-9221-01788b52ee64)

**Comment by kernelb00t** [comment]
For those kinds of issues and feature requests, I can only encourage you to get familiar with this project, try to implement this, and submit a Merge Request :wink: We would be more than happy to review your code.

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If so, please respond, if not, please close your issue! thanks 😉
