### ISSUE TITLE
Apple logo stuck in corner even after changing themes back to Yaru

### ISSUE THREAD

**Issue by ap801** [vinceliuice/WhiteSur-gtk-theme#1018]
I have changed my theme in gnome tweaks back to Yaru.  However, the apple logo from the white sur theme is still stuck in the corner even after restarting computer several times.  Any way I could fix this issue???  I am currently using Ubuntu 22.04.3 LTS.
![Screenshot from 2024-02-01 17-28-10](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/158530809/a8f5c1d0-643d-4aed-90c3-5c4df6fe919f)

**Comment by ap801** [comment]
Nevermind I have figured it out thanks

**Comment by openfellas** [comment]
Hello @ap801 what did you do to solve it, having the same issue

**Comment by ap801** [comment]
@openfellas you need to uninstall GDM theme sudo ./tweaks.sh -g -r
