### ISSUE TITLE
Window control icons not changed for couple of apps

### ISSUE THREAD

**Issue by tnayhsud** [vinceliuice/WhiteSur-gtk-theme#1019]
# System Details Report
---
## Report details
- **Date generated:**                          2024-02-05 23:18:27

## Hardware Information:
- **Hardware Model:**                        Hewlett-Packard HP 245 G7 Notebook PC
- **Memory:**                                       8.0 GiB
- **Processor:**                                    AMD Athlon Silver 3050U with Radeon™ Graphics × 2
- **Graphics:**                                      AMD Radeon™ Graphics
- **Disk Capacity:**                              256.1 GB

## Software Information:
- **Firmware Version:**                      F.55
- **OS Name:**                                     Ubuntu 23.10
- **OS Build:**                                       (null)
- **OS Type:**                                        64-bit
- **GNOME Version:**                          45.2
- **Windowing System:**                     Wayland
- **Kernel Version:**                             Linux 6.5.0-15-generic

For App center, Dynamic wallpaper and may be couple of more apps, window control icons neither shifted to left nor look like MAC window controls. 

Commands executed: 
./install.sh -m -t all -l -c Dark -N stable  --normal --round -i ubuntu
sudo ./tweaks.sh -g
sudo ./tweaks.sh -f

![Screenshot from 2024-02-05 23-22-53](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/38681502/65083d56-8bdc-4c9f-af56-8718ad2cf5ed)
![Screenshot from 2024-02-05 23-22-26](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/38681502/7e750ce8-4590-487b-8bc7-05d86e219bac)

**Comment by nicolas-oliveira** [comment]
Since you've applied the theme to flatpak and tried tweaks several times, it seems to be a problem with the application itself and Wayland. Have you tried switching to Xorg and seeing if the application has the theme applied correctly?

**Comment by kernelb00t** [comment]
@tnayhsud :eyes:
