### ISSUE TITLE
Firefox title bar

### ISSUE THREAD

**Issue by edwardstjohn** [vinceliuice/WhiteSur-gtk-theme#102]
Not sure if I've done something wrong, but for me the title bar looks like below rather than what is in the preview (where the title bar is in line with the address bar etc.) - is this meant to happen or is there something I need to edit?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54864187/103759616-edd5b480-500b-11eb-98e3-5ea7e9a6e6e2.png">

Love the theme by the way, looks awesome!

**Comment by vinceliuice** [comment]
Are you using Budgie desktop?

**Comment by edwardstjohn** [comment]
Nope, just regular Firefox on MacOS Big Sur (M1)

**Comment by vinceliuice** [comment]
OK! then I don’t know how to do it, after all this theme is designed for linux desktop.

**Comment by edwardstjohn** [comment]
Ah no worries then! Theme still looks great
