### ISSUE TITLE
Firefox in last version glich the tabs

### ISSUE THREAD

**Issue by nicolas-oliveira** [vinceliuice/WhiteSur-gtk-theme#1020]
# Hardware info
```
CPU: 12-core (4-mt/8-st) 12th Gen Intel Core i5-12500H (-MST AMCP-)
speed/min/max: 2938/400/4500:3300 MHz Kernel: 6.2.0-26-generic x86_64 Up: 23m
Mem: 4302.5/7617.0 MiB (56.5%) Storage: 238.47 GiB (70.7% used) Procs: 424
Shell: fish inxi: 3.3.13
```
# Graphics:
```
  Device-1: Intel Alder Lake-P Integrated Graphics driver: i915 v: kernel
  Device-2: NVIDIA GA107BM [GeForce RTX 3050 Mobile] driver: nvidia
    v: 550.40.07
  Device-3: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 resolution: 1: 1920x1080~60Hz
    2: 1600x900~120Hz
  OpenGL: renderer: Mesa Intel Graphics (ADL GT2)
    v: 4.6 Mesa 23.1.1 - kisak-mesa PPA
```
![Captura de tela de 2024-02-06 17-23-04](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/45501748/be544d3d-ab27-4b66-8269-022f1f2c3a7f)

If I rollback the [version](https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/ca620d17c481c5a21d0535a679b2a94d8c402fab) to [this version](https://github.com/vinceliuice/WhiteSur-gtk-theme/releases/tag/2023-10-13) the behaviour seems to be gone. This happens with Xorg and Wayland
The firefox is the 122.0 version

**Comment by nicolas-oliveira** [comment]
The issue seems to be in this commit https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/bbcfcca27e71d7ea47bf4b9318c2dc349bb9b3f7

**Comment by l3ifk** [comment]
I still experience the same bug unfortunately. Despite using the latest release of White Sur gtk theme which includes the fix.. 
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/100339546/7d675a1b-4793-4e04-b741-68987b2e70fd)
Only occurs when using the snap version of firefox. Flatpak firefox does not have this issue, but at the same time the theme does not work either for it.
