### ISSUE TITLE
the text and bluetooth headset icons are not properly aligned in quick settings 

### ISSUE THREAD

**Issue by houssemko** [vinceliuice/WhiteSur-gtk-theme#1022]
As you can see
![Screenshot from 2024-02-08 18-20-58](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/41808005/5fa14c81-11cd-47df-85e0-07556d763a96)

**Comment by kernelb00t** [comment]
Does this issue still occurs? Please provide more infos about your setup, search other issues for what to include.

**Comment by kernelb00t** [comment]
FYI, can't repro on Gnome 45.5 Arch Linux Rolling, with 5a52172d2f27437555cc58c7dad15d06af74553d :
`./install.sh -l -o normal -c Dark -N mojave --darker -s 280 -P smaller -i arch`

**Comment by kernelb00t** [comment]
Does this issue happens on the two monitors, or on the smallest/biggest one ? Can you try to get the command you used to install the theme? 
Try to reinstall the theme with the command I used, then with `./install.sh -l -c Dark`. After the command, don't forget to reapply the theme in `GNOME Tweaks` app, then log out/log in.

**Comment by houssemko** [comment]
Yes the issue happens on two monitors , the laptop screen and the external monitor .
I tried to reinstall the theme with the command you used and no the issue is still there .

**Comment by kernelb00t** [comment]
1. Can you try with the latest WhiteSur GTK theme and the latest WhiteSur icon theme? Log out/log in after applying everything. Use default commands (`./install.sh`)
2. Try with no theme applied, everything set to Adwaita, or None, disable extensions, and reboot

**Comment by houssemko** [comment]
okay i found a fix , it was the because of the interface font i was using .

**Comment by kernelb00t** [comment]
Great! If your issue is resolved, you can close this issue.

**Comment by houssemko** [comment]
Yes.
