### ISSUE TITLE
Make searchbox bigger please in application menu

### ISSUE THREAD

**Issue by kristof-linux** [vinceliuice/WhiteSur-gtk-theme#1024]
Hello,
Can somebody help me to get the searchbox bigger in the application menu if i make my fonts bigger...now i have this font settings and it doesn't fit.
Thanks a lot!

![afbeelding](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/58733661/6edb2da2-5958-455f-a1ef-ed22191ec7cd)
![Schermafdruk van 2024-02-15 14-27-20](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/58733661/a1abbbaa-c23e-44bd-89ac-920a5736552f)
![Schermafdruk van 2024-02-15 14-27-20](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/58733661/c3ef46bc-316c-4e83-8f75-79c492bba3f6)

**Comment by kernelb00t** [comment]
Wow, are you sure you are using Gnome? As I can see, this is KDE, not GNOME. If you have any questions related to KDE and/or you are using the WhiteSur KDE theme (that has not been updated in a while), please make an issue on its GitHub repo : <https://github.com/vinceliuice/WhiteSur-kde>. I'm not very knowledgeable on KDE, so I will not be very useful.
