### ISSUE TITLE
Change accent colors not working

### ISSUE THREAD

**Issue by abelncm** [vinceliuice/WhiteSur-gtk-theme#103]
I am using Ubuntu 20.10 and i'm getting this message:

cp: cannot stat 'WhiteSur-gtk-theme/src/assets/gtk-3.0/thumbnail-light.png': No such file or directory

I've tried renaming the file from /thumbnail-light.png.bak to /thumbnail-light.png but it still shows the same error.

What can i do?

**Comment by vinceliuice** [comment]
Download the last version on github and try again!

**Comment by abelncm** [comment]
@vinceliuice that's the latest version i was using. i have tried that also.

**Comment by vinceliuice** [comment]
Tell me what you run at terminal, I'll test it on my desktop and fix it

**Comment by coder8080** [comment]
I have the same problem. Here is the copy of my terminal session:

┌──[ coder8080@linux ] [ 16:15:31 ]
├── ~/Загрузки
└> cd ./WhiteSur-gtk-theme-master/
┌──[ coder8080@linux ] [ 16:15:35 ]
├── ~/Загрузки/WhiteSur-gtk-theme-master
└> ./install.sh -t green
Rendering thumbnail-light.png
Gtk-Message: 16:15:43.969: Failed to load module "xapp-gtk3-module"

** (inkscape:8695): WARNING **: 16:15:43.980: Invalid option --export-filename=thumbnail-light.png
Rendering thumbnail-dark.png
Gtk-Message: 16:15:44.027: Failed to load module "xapp-gtk3-module"

** (inkscape:8706): WARNING **: 16:15:44.040: Invalid option --export-filename=thumbnail-dark.png

Rendering assets/checkbox-checked.png
Gtk-Message: 16:15:44.098: Failed to load module "xapp-gtk3-module"

** (inkscape:8721): WARNING **: 16:15:44.110: Invalid option --export-filename=assets/checkbox-checked.png

Rendering assets/checkbox-checked@2.png
Gtk-Message: 16:15:44.145: Failed to load module "xapp-gtk3-module"

** (inkscape:8730): WARNING **: 16:15:44.156: Invalid option --export-filename=assets/checkbox-checked@2.png

Rendering assets/checkbox-checked-insensitive.png
Gtk-Message: 16:15:44.193: Failed to load module "xapp-gtk3-module"

...A few minutes later...

** (inkscape:11993): WARNING **: 16:16:03.242: Invalid option --export-filename=thumbnail-dark.png
  Change theme color ... 
==> Generating the gtk-light.css...
==> Generating the cinnamon-light.css...
==> Generating the gtk-light-solid.css...
==> Generating the cinnamon-light-solid.css...
==> Generating the gtk-dark.css...
==> Generating the cinnamon-dark.css...
==> Generating the gtk-dark-solid.css...
==> Generating the cinnamon-dark-solid.css...
==> Generating the gnome-shell-light.css...
==> Generating the gnome-shell-light-alt.css...
==> Generating the gnome-shell-light-solid.css...
==> Generating the gnome-shell-light-solid-alt.css...
==> Generating the gdm3-light.css...
==> Generating the gnome-shell-dark.css...
==> Generating the gnome-shell-dark-alt.css...
==> Generating the gnome-shell-dark-solid.css...
==> Generating the gnome-shell-dark-solid-alt.css...
==> Generating the gdm3-dark.css...
==> Generating dash-to-dock stylesheet.css...
==> Generating dash-to-dock stylesheet-dark.css...
  Installing '/home/coder8080/.themes/WhiteSur-light'... 
cp: не удалось выполнить stat для '/home/coder8080/Загрузки/WhiteSur-gtk-theme-master/src/assets/gtk-3.0/thumbnail-light.png': Нет такого файла или каталога

sorry for my english, I am from Russia.

**Comment by vinceliuice** [comment]
I'll check this

**Comment by vinceliuice** [comment]
Fixed!
