### ISSUE TITLE
Gnome 46 weird bug

### ISSUE THREAD

**Issue by ryzendew** [vinceliuice/WhiteSur-gtk-theme#1030]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/84041391/158d010b-6304-4cfb-af71-8a31fc6e6d37)
Gnome 46 has this weird white outline 

Arch linux 
Gnome 46 beta
Nvidia 4070 and RX 5700XTX

**Comment by Ravi-Kishor** [comment]
same bug here too arch linux gnome 46 beta

**Comment by pedroliberaldev** [comment]
Same here! Fedora Workstation 39 and Fedora Workstation 40 Pre-release

**Comment by kernelb00t** [comment]
You mentioned beta version, does it still happens on release version?

**Comment by grav3m1nd-byte** [comment]
> You mentioned beta version, does it still happens on release version?

I migrated to Gnome 46 last night, release version, and I can confirm this is still happening.

**Comment by vinceliuice** [comment]
Fixed now
