### ISSUE TITLE
How to release all stuffs to February version? All reinstall or make-release.sh?

### ISSUE THREAD

**Issue by leonevilred** [vinceliuice/WhiteSur-gtk-theme#1034]
如何更新到2月呢？全部重装一遍还是make-release.sh会更新?

**Comment by kernelb00t** [comment]
Can you please ask your question at least in English? Even if some here can, this is not the most talked one. Please provide an English translation of what you want to say for non-Chinese contributors (yes, there is Google Translate, but it isn't perfect and I couldn't understand your question with it).

**Comment by vinceliuice** [comment]
直接运行./install.sh安装，release文件我有时候会忘记运行

**Comment by leonevilred** [comment]
> 直接运行./install.sh安装，release文件我有时候会忘记运行

谢谢，已./install.sh重装一遍

**Comment by kernelb00t** [comment]
Please mind to close your issue if it is solved, thanks! 😉
