### ISSUE TITLE
 Manjaro gnome45.4 The themes of some applications (setting ,nautilus, etc.) will become default theme  after reboot or logout 

### ISSUE THREAD

**Issue by linzeennnn** [vinceliuice/WhiteSur-gtk-theme#1037]
my installtion command  `./install -c Dark -t pink -l    ./tweak -c Dark -t pink -F`
terminal and some application display currectly
chrome and nautilus works fine when first installed, but after reboot will revert to the default theme.
![Screenshot from 2024-03-28 07-30-39](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/152974252/1c19d465-dee0-4228-8f63-5a8cc1366247)
![Screenshot from 2024-03-28 07-28-46](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/152974252/63f8b9bc-2c81-4f3d-bc41-d22e9bf5b779)
![Screenshot from 2024-03-28 07-28-17](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/152974252/b84c44f2-4865-43d1-9d5c-9f0081ad133a)
And the theme in the legacy applicon in the tweak will become unselected, and i need to reselect the theme.
![Screenshot from 2024-03-28 07-30-21](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/152974252/a4dbde8b-ab65-49fc-9a45-96f2c660de10)
This does not happen with other themes

**Comment by kernelb00t** [comment]
Please add more infos about your setup. Go check other issues for what to add. This seems like an external software is wanting to get rid of those settings.

**Comment by linzeennnn** [comment]
> Please add more infos about your setup. Go check other issues for what to add. This seems like an external software is wanting to get rid of those settings.
![Screenshot from 2024-03-29 10-29-51](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/152974252/f7673332-609c-41ae-9633-2c10deee90af)

actually i didnt setup anything else . the first setup after i install this version manjaro image is install WhiteSur-gtk-theme but it not work fine
