### ISSUE TITLE
File upload box not in dark mode and calendar events no scrooll

### ISSUE THREAD

**Issue by dantonbertuol** [vinceliuice/WhiteSur-gtk-theme#104]
The file upload box in slack is not in dark mode.

The events scroll bar on the calendar does not work, when there are many events it gets stuck and cuts off a part of the events (below the calendar in the top panel)

**Comment by dantonbertuol** [comment]
![upload_slack](https://user-images.githubusercontent.com/32557284/104207263-09c3c680-540f-11eb-8932-308b3babedfd.png)

**Comment by vinceliuice** [comment]
What system and gnome version are you using?

**Comment by dantonbertuol** [comment]
Ubuntu 20.10
Gnome 3.38.1

Another problem is with the icons to maximize, minimize and close the windows, some are not with the MacOs layout, example Visual Studio Code, Sublime Text, Rambox.

![exit_rambox](https://user-images.githubusercontent.com/32557284/104953197-b28c9b80-59a4-11eb-9199-a6a1afe4c8db.png)
![exit_sublime](https://user-images.githubusercontent.com/32557284/104953198-b4565f00-59a4-11eb-86be-40773e02c1d9.png)
![exit_vscode](https://user-images.githubusercontent.com/32557284/104953200-b5878c00-59a4-11eb-87ea-6844163dbcdd.png)

**Comment by rivanfebrian123** [comment]
Hi @dantonbertuol! Do you install those app from Snap?
