### ISSUE TITLE
Error installling

### ISSUE THREAD

**Issue by rohanthapa123** [vinceliuice/WhiteSur-gtk-theme#1040]

**Comment by 0-yochanan-0** [comment]
I am trying to install WhiteSur-gtk-theme on GhostBSD. However I am facing to the error message:

  Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> ./shell/lib-core.sh: line 202: setterm: command not found
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> setterm -cursor off
  TRACE  :
    >>> signal_error
    >>> start_animation
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ghostbsd;24.01.1
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2024-04-19T10:28:28+0200

I have util-linux installed, but setterm command is still not found. 
Could you please help me with this?
Thanks

**Comment by kernelb00t** [comment]
Please mind to close your issue if it is solved, thanks! 😉
