### ISSUE TITLE
Black Font on Panel not Working

### ISSUE THREAD

**Issue by abdasis** [vinceliuice/WhiteSur-gtk-theme#1043]
I've tried to run the command with parameters

`./install --black, --blackfont`

However, the font that appears still white

**Comment by vinceliuice** [comment]
Just run: `./install --black` the use the light gnome-shell theme

**Comment by abdasis** [comment]
Oh black font just work on light theme?

**Comment by vinceliuice** [comment]
Yes, because default light theme is white font color, and dark theme have black background for panel
