### ISSUE TITLE
screen-sharing and do-not-disturb icon in  the status bar is too big

### ISSUE THREAD

**Issue by yuhldr** [vinceliuice/WhiteSur-gtk-theme#1044]
archlinux

When using `gnome remote desktop 46.1-1`, the status bar prompts desktop sharing when being remotely accessed, but these two icons are abnormal(**screen-sharing and do-not-disturb icon in  the status bar is too big**)

![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/25719023/6d28b6de-6173-4187-95a5-35330d84deee)

theme is installed by

```bash
cd WhiteSur-gtk-theme && ./install.sh -m -l -c Dark -t green -N mojave

cd icons/WhiteSur-icon-theme && ./install.sh -t green -a -b
```
and using [extension:user-themes](https://extensions.gnome.org/extension/19/user-themes/) and [do-not-disturb-while-screen-sharing-or-recording](https://extensions.gnome.org/extension/5985/do-not-disturb-while-screen-sharing-or-recording/)

![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/25719023/84aaa364-aa35-4dc8-969a-cd181e52265d)

**Comment by vinceliuice** [comment]
你桌面版本，桌面分辨率和scaling是多少阿，我自己的桌面上没这个问题
![Screenshot from 2024-04-18 14-58-02](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/8393e91e-4e96-4811-8482-e0694be855aa)

**Comment by yuhldr** [comment]
还执行了这一句，电脑重启以后出现了这个问题:
```bash
cd WhiteSur-gtk-theme && sudo ./tweaks.sh -g -t green -c Dark -o solid -i arch
```

**Comment by vinceliuice** [comment]
应该修复了

**Comment by yuhldr** [comment]
> 应该修复了

没问题了，感谢！

**Comment by yuhldr** [comment]
> 应该修复了

还有个问题，执行下面以后，共享屏幕的警示颜色消失

```bash
sudo ./tweaks.sh -g -t green -c Dark -o solid -i arch
```

前后差别如图，这个不应该变成白色，橙色作为警告

![截图 2024-04-19 09-55-23](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/25719023/9c20f914-3ed8-4a65-b423-6c29c3c985be)
![截图 2024-04-19 09-56-23](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/25719023/2e00b4ef-97cd-41e7-9451-79fb040140a3)

**Comment by vinceliuice** [comment]
现在修复了
