### ISSUE TITLE
Issue to install on GhostBSD

### ISSUE THREAD

**Issue by 0-yochanan-0** [vinceliuice/WhiteSur-gtk-theme#1047]
I am trying to install WhiteSur-gtk-theme on GhostBSD. However I am facing to the error message:

I have util-linux installed, but setterm command is still not found.
Could you please help me with this?
Thanks

**Comment by vinceliuice** [comment]
Sorry about this I never used a BSD system, so I also have no idea about this
But you can use those release files: https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/release

**Comment by 0-yochanan-0** [comment]
Thank you for quick reply :)

**Comment by 0-yochanan-0** [comment]
Thank you for quick reply :)
