### ISSUE TITLE
Fedora 40 unexpected white outline

### ISSUE THREAD

**Issue by XsPDevKX** [vinceliuice/WhiteSur-gtk-theme#1050]
Just upgraded to Fedora 40 and almost everything works perfectly, except for box outlines which for now i've only seen in the option's menu.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/96445862/09e687cd-2208-4b1f-bf81-ea75d688825c)

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/96445862/9e3b8f29-c0fe-4a42-87de-67e083594849)

**Comment by vinceliuice** [comment]
Download the last version on github and try agagin

**Comment by luca-martino** [comment]
> Download the last version on github and try agagin


Same issue also with commit b6587fe 

OS: Fedora Linux 40 (Workstation Edition) x86_64
DE: GNOME 46.1
Theme: WhiteSur-Dark [GTK2/3]

**Comment by luca-martino** [comment]
> Just upgraded to Fedora 40 and almost everything works perfectly, except for box outlines which for now i've only seen in the option's menu.
> 
try ./install.sh -l

**Comment by kernelb00t** [comment]
Please mind to close your issue if it is solved, thanks! 😉

**Comment by XsPDevKX** [comment]
A simple reinstilation fixed the issue, I couldnt find out what caused the issue but it seems like it was an error isolated to that niche situation.
