### ISSUE TITLE
Change panel font color in Overview (Show all apps)

### ISSUE THREAD

**Issue by alisson3000br** [vinceliuice/WhiteSur-gtk-theme#1051]
![Screenshot from 2024-04-25 17-08-47](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/148722558/1b8280d0-9630-4d78-a5a5-599d9e46354e)

**Comment by alisson3000br** [comment]
i done --black, --blackfont and it is black but only in overview it is white, i tried css file but couldnt find the correct line
somebody help? thanks

**Comment by alisson3000br** [comment]
![Screenshot from 2024-04-25 17-16-19](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/148722558/6dc6a28e-1fe0-46df-8df9-06db6c6fb757)

btw, only the apple it is black but the text is white in overview

**Comment by washburn24** [comment]
If you just want the text and icons to be black and you're cool with modifying the .css...

#panel .panel-button {
  color: black; }

You can find where that is or make your own.  It will also control the text color of extension menus like Applications and Places.

**Comment by alisson3000br** [comment]
i tried already at the css but i hit my limitation on this, i dont know how to do it

**Comment by kernelb00t** [comment]
Please mind to close your issue if it is solved, thanks! 😉
