### ISSUE TITLE
Window control buttons are not over ridden

### ISSUE THREAD

**Issue by asifrahaman13** [vinceliuice/WhiteSur-gtk-theme#1056]
Hey in gnome 46 not all the applications are having the correct control buttons on the top. While for some applications it looks fine but for others it is showing the default one only.

For some applicationns it is looking like this:

![Screenshot from 2024-04-29 12-39-56](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97652031/8e50a25b-4e27-44fc-91d8-fc3829d3112b)

Some of the applications where it is not proper are settings, files, firefox etc.

Note that before gnome 46 it wasnt the problem except for the firefix.

The top three icons should look something like this(red, yellow, green colored).

![Screenshot from 2024-04-29 12-41-15](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97652031/559ea917-2bbf-4daf-8eee-e5ea67e0be8b)

Also firefox does not have the feature since long time. Can we fix that too.

My system details is as follows:

![Screenshot from 2024-04-29 12-44-01](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97652031/dbd8a42f-83b4-41a5-85d1-26ee80c59059)

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by asifrahaman13** [comment]
Thanks it worked now.,
