### ISSUE TITLE
apple logo

### ISSUE THREAD

**Issue by jihad-islam** [vinceliuice/WhiteSur-gtk-theme#1064]
after uninstalled the whitesur theme yet the apple logo appears in the top bar. how i can remove the logo completely? i am using ubuntu 24.04.
![Screenshot from 2024-05-09 11-54-29](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/110405190/dcb8366b-0891-4b07-9570-87d480a5989f)

**Comment by vinceliuice** [comment]
Run: `sudo ./install.sh -r -g`

**Comment by vinceliuice** [comment]
You need uninstall gdm theme

**Comment by kernelb00t** [comment]
Please close this issue if your issue is resolved, thanks! 😉
