### ISSUE TITLE
Calendar days on Light-Nord version are not visible

### ISSUE THREAD

**Issue by d4nicoder** [vinceliuice/WhiteSur-gtk-theme#1065]
## Info
- Distro: Arch Linux x64
- DE: Gnome 46
- GTK Theme: WhiteSur-Light-nord
- Shell Theme: Whitesur-Light-nord
- Theme version: [Release 2024-05-01](https://github.com/vinceliuice/WhiteSur-gtk-theme/releases/tag/2024-05-01)

## Problem
I'm using the Light nord version of the theme and the top calendar days have very bad visibility. Maybe they should have a transparent background by default and other color for the :hover.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/3621392/9a2d9061-7850-47c0-982f-c65223d633d4)

**Comment by vinceliuice** [comment]
It should be fixed, run this and try again:  `git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1`

**Comment by d4nicoder** [comment]
Solved! thank you ;)
