### ISSUE TITLE
Visual Glitch for Containerised Firefox Tabs

### ISSUE THREAD

**Issue by Binero** [vinceliuice/WhiteSur-gtk-theme#1072]
Running Arch Linux on GNOME 46 and Firefox 127.0 through Flatpak. When opening a Firefox tab inside a container, the colour of the container does not appear in the correct place. The title of the tab also shows incorrectly. In the screenshot, the container colour appears as a red dot in the "New Tab" tab. 

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/6867251/33498706-ab5a-4c9c-a5f5-b5b26066d28e)

**Comment by arigit** [comment]
I use firefox containers a lot and the visual glitch is quite bad,

![image](https://github.com/user-attachments/assets/ee78a16a-e7ed-4b8d-86fb-d1af5bf04adc)


This is the mozilla-provided container extension.

@vinceliuice  any chance to have this sorted out? otherwise, your firefox integration is really outstanding, looking forward to using it - thank you for releasing it

**Comment by arigit** [comment]
I hacked a tempoerary fix for this that makes the WhiteSur GTK theme usable in Firefox

Hopefully the dev will add an option to do this properly

![image](https://github.com/user-attachments/assets/45dbb287-a84a-4227-8c0d-ad2159f99730)



- **Firefox Multi-Container indicator fix procedure:**
	- In the file: `~/.var/app/org.mozilla.firefox/.mozilla/firefox/firefox-themes/WhiteSur/parts/tabsbar.css`
	- Add the top line for Firefox Containers back:
		- Search for: `Active Tab`
			- Inside: `.tab-background:is([selected]) {`
			- Comment-out: `/*border: none !important;*/`
		- Search for: `.tab-context-line`
	        - Below the stance, add:
		        - ```css
			      .tabbrowser-tab[class*="identity-color-"] .tab-background {
				             border-top: solid 2px var(--identity-icon-color) !important;
				             opacity: 0.6;
				             transition: all .15s ease-in-out !important;
				        }   
		          ```
	- Remove weird container-indicator dot:
		- Search for: `new container tab`
		- Comment-out *the entire stance*:
		  - ```css
		    .tabbrowser-tab[class*="identity-color-"]-.tab-content:: before {
		      ...
		    ```

**Comment by vinceliuice** [comment]
What extension is this, Firefox Multi-Account Containers ?

**Comment by arigit** [comment]
Yes @vinceliuice , and thanks a bunch for the fix. 

As a touchup, I added some opacity to the line to make it similar to the "new content dot" opacity ( that shows underneath,
In:
```.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {```
I added
```opacity: 0.6```
