### ISSUE TITLE
Hot edge is not working : my dock doesn't appear

### ISSUE THREAD

**Issue by nprime496** [vinceliuice/WhiteSur-gtk-theme#1079]
Hi,

I'd like to say that this a wonderful job already, I am mostly satisfied with the new look in just one command.

However, I have a rather inconvenient behavior, my dock doesn't appear by default. I have to click the "Window" key or "Activities" for it to show.
Also, the hot edge, doesn't work : dragging my mouse to the bottom of my screen doesn't make it appear.

Is it an expected behavior ? (I doubt  so)
How can I solve it ?

Note:
My dock doesn't appear at all by default, I have to click the "Window" key or "Activities" for it to show.

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by vinceliuice** [comment]
Did you enabled gnome-shell extensions

**Comment by vinceliuice** [comment]
Try this https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by nprime496** [comment]
I enabled it. It breaks everything on the dock.
Here are the screenshots:

Before:

I get the expected result but hardly accessbible.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54849528/1bb90ff1-dcd8-4e2a-aa29-725cb9de6b35)

Extension:

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54849528/ef53a993-3905-4e0a-8dfe-0b29b76495b9)

After:

![Screenshot from 2024-06-21 18-57-19](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54849528/253fdad7-8799-46ce-bb41-d36452aeb98d)

**Comment by nprime496** [comment]
It is working now after reinstalling dash-to-dock from the ground up : my dock appear constantly on screen.

**Comment by nprime496** [comment]
The dock is visible thank you!

 But the hot edge is still not working : when I drag my mouse to the bottom of the screen (for example with a full screen app), the dock doesn't appear.

**Comment by nprime496** [comment]
I managed to get it working by configuring dash-to-dock. It's one of these settings (or the combination) :

`~/$ gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false`
`~/$ gsettings set org.gnome.shell.extensions.dash-to-dock autohide true`

Thanks for your quick answer.

Ressources:
https://askubuntu.com/questions/1005470/how-do-i-auto-hide-the-ubuntu-dock-using-gsettings-on-ubuntu-17-10-and-later
https://askubuntu.com/questions/1199638/disable-hot-edge-to-fire-auto-hide-ubuntu-dock
https://discourse.ubuntu.com/t/ubuntu-dock-add-true-autohide-option-to-default-session/11200/4
