### ISSUE TITLE
Wrong position of window buttons in the Preferences window

### ISSUE THREAD

**Issue by User991** [vinceliuice/WhiteSur-gtk-theme#108]
Hi, i noticed that when the title bar buttons (Close, minimize and resize) are set on the left of the window (through the Tweaks tool), they are in the wrong position in the Preferences window
![Schermata da 2021-01-13 22-31-02](https://user-images.githubusercontent.com/17948689/104512808-0d15a880-55ef-11eb-9b75-eaaa66d6abd2.png)
.

**Comment by vinceliuice** [comment]
Only this theme have this issue?

**Comment by Gictorbit** [comment]
But it's fine on arch Linux, I think this happens only on Ubuntu
![image](https://user-images.githubusercontent.com/34630603/104697320-d17cfa80-5724-11eb-8016-42806cd2cb43.png)
