### ISSUE TITLE
Inconsistent title bar heights

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#1080]
![Screenshot from 2024-07-05 15-30-32](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/eb159f2a-e8ee-4212-8211-f31fb1c235ff)

From left to right: Firefox title bar is the largest, GTK 4 title bar is almost half of firefox, and GTK 3 title bar is even smaller.

**Comment by vinceliuice** [comment]
1, Firefox can not set the button size smaller,
2, CSD headerbar(buttons and title are all in the topbar) are different with titlebar(only have titles on topbar), so they have different size

**Comment by FelixFourcolor** [comment]
I see, thanks for the explanation. Feel free to close the issue if there's nothing you could do about it.
