### ISSUE TITLE
Firefox Monterey theme: address bar mislocated in Firefox 128

### ISSUE THREAD

**Issue by yiwenlu66** [vinceliuice/WhiteSur-gtk-theme#1082]
On Arch Linux. The Firefox Monterey theme results in the address bar being mislocated when not focused, after upgrading to Firefox 128.

Correct when focused:
![image](https://github.com/user-attachments/assets/bad05e6e-a952-4c32-8831-47a5ea0ff161)

Breaks when not focused:
![image](https://github.com/user-attachments/assets/6c6238dd-270e-4752-8f03-2d091a0c4d3a)

**Comment by mitakvd** [comment]
On Ubuntu 22.04 it's even worse

![Screenshot from 2024-07-12 12-22-45](https://github.com/user-attachments/assets/e681ae8d-4c44-4514-bea4-961bea14213d)

**Comment by nicolas-oliveira** [comment]
![image](https://github.com/user-attachments/assets/e970b4ef-0027-4624-8697-b7011851b976)
Same here, ubuntu 22.04 with alt style

it seems that in addition to the address bar losing its color, the "hover" property of the tabs has a bizarre animation.
the same when changing with "alt-tab"

**Comment by nicolas-oliveira** [comment]
Inspecting and looking for inconsistencies I found that id "#searchbar" doesn't exists anymore:
![image](https://github.com/user-attachments/assets/ef06dfdc-9270-4bf2-9715-6b136a2d4271)
 Look for this rule:
 
 https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/other/firefox/Monterey/parts/headerbar-urlbar.css#L124

**Comment by nicolas-oliveira** [comment]
Guys, I tried to make some corrections to the "alt" style, it's in this pull request: https://github.com/vinceliuice/WhiteSur-gtk-theme/pull/1083
