### ISSUE TITLE
Option to use default gnome 46 icon for top left activities icon

### ISSUE THREAD

**Issue by kugelvlitz** [vinceliuice/WhiteSur-gtk-theme#1086]
At this moment the available icon options are `[apple|simple|gnome|ubuntu|tux|arch|manjaro|fedora|debian|void|opensuse|popos|mxlinux|zorin|budgie|gentoo]`. There's no option to leave or set the default icon, as it always overwrites it.

Said icon: ![Screenshot from 2024-07-16 10-03-26](https://github.com/user-attachments/assets/a3210259-6dcb-46eb-bae2-bdf068ae044b)

**Comment by vinceliuice** [comment]
You mearn the apple icon ? just run: `./install.sh -i apple`

**Comment by kugelvlitz** [comment]
> You mearn the apple icon ? just run: `./install.sh -i apple`

No, I'm referring to the icon that comes with stock gnome 46. See picture above for reference.

**Comment by vinceliuice** [comment]
Just run `./install.sh` the default theme do not overwrite the icon

**Comment by vinceliuice** [comment]
![Screenshot from 2024-07-18 14-37-42](https://github.com/user-attachments/assets/5687f072-46f5-4c98-9b27-38729984922e)

**Comment by vinceliuice** [comment]
Run `git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1` and try again

**Comment by kugelvlitz** [comment]
> Run `git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1` and try again

I uninstalled the theme and did a reboot, where I was able to see the default Icon. Cloned the repo and ran `./install.sh`. At first it seemed to do the trick but after a second reboot the icon was missing

![Screenshot from 2024-07-21 22-09-50](https://github.com/user-attachments/assets/6b5f92b3-ea1a-47e9-aaa1-ade0f06918fb)

**Comment by vinceliuice** [comment]
Try again

**Comment by kugelvlitz** [comment]
It works, thank you very much!

**Comment by vinceliuice** [comment]
You are welcome !
