### ISSUE TITLE
Close and minimize icons for some applications do not work

### ISSUE THREAD

**Issue by Guilhermedlv** [vinceliuice/WhiteSur-gtk-theme#1087]
Why do the close and maximum icons of some applications not match the Theme icon, for example Chrome?

Chrome
![image](https://github.com/user-attachments/assets/74601483-274d-4647-9f53-75ef83cd0bce)
Firefox
![image](https://github.com/user-attachments/assets/ba58281c-d2e9-41c1-973d-24b5d7ca7651)
Telegram
![image](https://github.com/user-attachments/assets/c7c87362-eeca-4aa5-9d69-e3955ad751c3)

System - Ubuntu 24.04

**Comment by vinceliuice** [comment]
What's your desktop ?

**Comment by Guilhermedlv** [comment]
Hello, I use Ubuntu 24.04 with gnome 46

**Comment by vinceliuice** [comment]
How did you install this theme ?

**Comment by Guilhermedlv** [comment]
Okay, I did it like this -

Run git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1

Run ./install.sh to install the default WhiteSur GTK theme pack.

Right away

Run this command to install WhiteSur into gtk-4.0 configuration folder ($HOME/.config/gtk-4.0)

.themes

![image](https://github.com/user-attachments/assets/c5d2418f-edc8-4cdc-8264-5f2a54af55ad)

.gtk-4.0

![image](https://github.com/user-attachments/assets/f19b6b0f-b61c-4a1f-8821-f78e1b348e1a)

**Comment by vinceliuice** [comment]
Did you installed plasma desktop ?

**Comment by Guilhermedlv** [comment]
I didn't install it

**Comment by vinceliuice** [comment]
About the chrome, make sure appearance setting is using GTK style

**Comment by vinceliuice** [comment]
And firefox you need to use the system theme not the matte one

**Comment by vinceliuice** [comment]
telegram is not a gtk app, do not use gtk themes

**Comment by Guilhermedlv** [comment]
> Sobre o Chrome, você precisa alterar a configuração de aparência para o estilo GTK

Show I got it

> E no Firefox você precisa usar o tema do sistema, não `matte/light/dark`aquele

Do you say you use the Fox theme that comes with WhiteSur-gtk-theme?

> telegram não é um aplicativo gtk, não use temas gtk

ok, I got it

**Comment by vinceliuice** [comment]
You are welcome

**Comment by yayangkasep** [comment]
> About the chrome, you need change appearance setting to GTK style

where do I usually edit appearance for chrome? reply plz..

**Comment by Guilhermedlv** [comment]
> > Sobre o cromo, você precisa alterar a configuração de aparência para o estilo GTK
> 
> onde costumo editar a aparência do Chrome? responda por favor..

You just need to leave the gtk theme enabled, it will take the system theme.

![image](https://github.com/user-attachments/assets/d21d0bdb-48c2-494b-a79f-b6e15909cb14)

**Comment by yayangkasep** [comment]
> > > Sobre o cromo, você precisa alterar a configuração de aparência para o estilo GTK
> > 
> > 
> > onde costumo editar a aparência do Chrome? responda por favor..
> 
> You just need to leave the gtk theme enabled, it will take the system theme.
> 
> ![image](https://private-user-images.githubusercontent.com/84813395/360709449-d21d0bdb-48c2-494b-a79f-b6e15909cb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTM0MzgsIm5iZiI6MTcyNDM5MzEzOCwicGF0aCI6Ii84NDgxMzM5NS8zNjA3MDk0NDktZDIxZDBiZGItNDhjMi00OTRiLWE3OWYtYjZlMTU5MDljYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2MDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYTU4MDBlMmQyODc0YmI3NGNiNWZiOGZmNDdkYjIwNmYzOWQ4Yjc0ZDgxOGE5Yjk3MTk4ZmU3MTM0MDk4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RxOfL4--WNHnHoWHeCimWovlSIz5T3HrHVcENOsAsrs)

Where is it from? From Ubuntu settings or from tweaks?

**Comment by kauanmocelin** [comment]
@yayangkasep Google Chrome > Settings > Appearance

**Comment by vinceliuice** [comment]
I think is from GTK theme
