### ISSUE TITLE
[Nautilus] right-clicking files and folders causes them to appear selected untill you leave the folder or do an area selection

### ISSUE THREAD

**Issue by rasber-3** [vinceliuice/WhiteSur-gtk-theme#1093]
As the title says, whenever I right-click a file or a folder, it will keep indicating that the file is selected, even though it isn't. I can keep right-clicking files, making more of them appear selected, but if I perform any command like cut or copy, only the latest selection is affected. The only way I've found to get rid of this bug is to either leave and re-enter the folder or do an area selection. I assume it's some problem with the theme because I've googled it and haven't found any mention of anyone else having this problem before.

Video example:
https://github.com/user-attachments/assets/d8177dc2-9549-40c0-93aa-545e67ed8db1

Linux/gnome versions:
- Fedora 40 6.9.11-200
- Gnome shell 46.3.1
- GNOME nautilus 46.2

What i've tried:
- Reinstalling the theme
- Reinstalling Nautilus
- Finding any relevant information using "journalctl -xe | grep nautilus" while triggering the bug with no success

I'd be happy to provide more information if necessary if you just tell me how.

**Comment by FengZhongShaoNian** [comment]
I installed the latest version of the WhiteSur-gtk theme through the github master branch today and I had the same problem.
 When using the default theme Adwaita, in Nautilus, when you right-click a file and then click another file with the left mouse button, the highlight of the file originally selected by the right mouse button remains (but the color becomes lighter), but the original file should not be selected at this time, so it should not have any highlight color. This seems to be a bug in Nautilus.

When using the dark theme of WhiteSur-gtk, the color of the file originally selected by the right click is the same as the highlight color of the file selected by the left click of the mouse, so it is impossible to distinguish which file is the currently selected one.

What I expect most is that after selecting a file with the right mouse button, if you click other files with the left mouse button, you can cancel the highlighting of the item that was previously selected with the right mouse button, as if you had not used the right mouse button at all before.

I really like this beautiful theme WhiteSur-gtk, and I would be grateful if WhiteSur-gtk theme can do this.

**Comment by FengZhongShaoNian** [comment]
Here is what Nautilus looks like when using the default Adwaita theme:

https://github.com/user-attachments/assets/4f71eb4a-3eca-4789-bce9-79ea9da5683b

Here’s what Nautilus looks like when using the WhiteSur-Dark-solid theme:

https://github.com/user-attachments/assets/04a70ced-5238-477e-b071-8748fa32c42b

My system information:
-  OS: Arch Linux x86_64
- Display (U2790B): 3840x2160 @ 60 Hz (a]
- DE: GNOME 46.3.1
- WM: Mutter (Wayland)

**Comment by vinceliuice** [comment]
@FengZhongShaoNian What aboult now ?

**Comment by FengZhongShaoNian** [comment]
> @FengZhongShaoNian What about now ?

It's working great now! Thank you very much for your work!
