### ISSUE TITLE
Window Control Buttons blurry in Brave Browser PWA's

### ISSUE THREAD

**Issue by Arche151** [vinceliuice/WhiteSur-gtk-theme#1096]
First of all, thank you for developing and maintanining this amazing project!

I'm very happy with the result of the theme, but unfortunately PWA's that I created via Brave Browser have blurry window control buttons. 

Normal Brave windows don't have this issue, only PWA's.

Brave PWA's

![image](https://github.com/user-attachments/assets/9eb2a88e-3350-404d-8faf-3080a79631be)

Normal Brave Windows

![image](https://github.com/user-attachments/assets/b65f0795-6555-4377-a180-ac02a3ba4b1b)

I'm on Ubuntu 22.04. 

Would be very grateful for a fix :)

**Comment by vinceliuice** [comment]
This is a app scaling issue, all chromiue based Browser have this issue

**Comment by Arche151** [comment]
> This is a app scaling issue, all chromiue based Browser have this issue

Ah damn, so there's no fix?
