### ISSUE TITLE
Scaling of back and forth buttons in Nautilus is off

### ISSUE THREAD

**Issue by Arche151** [vinceliuice/WhiteSur-gtk-theme#1097]
![image](https://github.com/user-attachments/assets/47b75224-38cb-49fa-9537-9050202baba1)

The back and forth buttons are stretched and distorted I can't figure out how to make them look normal like in Firefox for instance.

My Nautilus version is 42.6

Edit:

Here a comparison with the correctly scaled back and forth buttons on Firefox at the bottom and the ones in Nautilus at the top.

![image](https://github.com/user-attachments/assets/a815c642-b049-4691-8736-b1c7290b30bb)

**Comment by vinceliuice** [comment]
Because gtk app use your customize icon theme, but firefox theme use buildin icons, change your icon theme to WhiteSur-icon-theme, it'll be the same icon as firefox theme

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-icon-theme

**Comment by Arche151** [comment]
@vinceliuice That fixed the issue with the arrows in Nautilus, thank you!! 

But unfortunately I have a new issue now: The app icons aren't consistent in style and size:

![image](https://github.com/user-attachments/assets/eee31645-a02e-4f06-8dce-523479c66108)

Is there a way to keep the Nautilus arrows but switch my app icons back to how they were before?

PS: Thank you for your hard work :)
