### ISSUE TITLE
I can't see the botton in DeaDBeeF player with dark theme.

### ISSUE THREAD

**Issue by laichiaheng** [vinceliuice/WhiteSur-gtk-theme#11]
![2020-07-20 01-40-11 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/87881170-13eda500-ca2a-11ea-9f6f-588e9080c98b.png)

**Comment by MahdiBaghbani** [comment]
not only  this program, many programs (for example Jetbrain IDEs) bottom corners aren't rounded too.

**Comment by laichiaheng** [comment]
Pamac 的 icon 也看不見

**Comment by vinceliuice** [comment]
Change the icon theme to the dark one

**Comment by laichiaheng** [comment]
> Change the icon theme to the dark one

Thanks.
