### ISSUE TITLE
Installing Whitesur GTK in Onlyoffice

### ISSUE THREAD

**Issue by juanchopi37** [vinceliuice/WhiteSur-gtk-theme#1105]
I had had problems getting whitesur to be applied in the OnlyOffice suite and I wanted to share the solution for people who have not been able to solve it. The first solution can be found in this link: https://helpcenter.onlyoffice.com/installation/desktop-flags.aspx 

However, in my case the file was not found, so I had to create a script and a .desktop file (this would create two accesses for OnlyOffice) to do this follow these steps in case you have not found the solution in the link:

1. First, let's create a script that launches OnlyOffice with the desired flag:

```
nano ~/.local/bin/onlyoffice-custom.sh
```

In this file, add the following lines:

```
#!/bin/bash
flatpak run org.onlyoffice.desktopeditors --system-title-bar "$@"
```

Save and close the file.

Make the script executable:

```
chmod +x ~/.local/bin/onlyoffice-custom.sh
```

Now, let's create a custom .desktop file:

```
nano ~/.local/share/applications/onlyoffice-custom.desktop
```

Add the following content:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=ONLYOFFICE Desktop Editors (Custom)
Exec=/home/USERNAME/.local/bin/onlyoffice-custom.sh %F
Icon=org.onlyoffice.desktopeditors
Categories=Office;
```
Replace USERNAME with your actual username.

Make the .desktop file executable:
```
chmod +x ~/.local/share/applications/onlyoffice-custom.desktop
```
Update the applications database:
```
update-desktop-database ~/.local/share/applications
```

**Comment by vinceliuice** [comment]
Onlyoffice is not gtk app, can not use gtk themes

**Comment by juanchopi37** [comment]
That's what I thought, basically what I did was create another .desktop file that could use the Whitesur theme header, that's just it.

![image](https://github.com/user-attachments/assets/2b8b9923-cd1e-4e20-b029-3a7f7f12d318)

with gtk: 

![image](https://github.com/user-attachments/assets/4fb162e1-9c7a-468e-a663-9d943e261ede)

This is only to create a compatible header and is only a solution to only office, it is not for all apps or only for some

**Comment by threeyeies** [comment]
I look that you can replace the original Exec line in original .desktop by the line you commented 

flatpak run org.onlyoffice.desktopeditors --system-title-bar "$@" 

...and works it.

```
[Desktop Entry]
Version=1.0
Name=ONLYOFFICE
GenericName=Document Editor
GenericName[ru]=Редактор документов
Comment=Edit office documents
Comment[ru]=Редактировать офисные документы
Type=Application
Exec=flatpak run org.onlyoffice.desktopeditors --system-title-bar "$@"
Terminal=false
Icon=org.onlyoffice.desktopeditors
Keywords=Text;Document;OpenDocument Text;Microsoft Word;Microsoft Works;odt;doc;docx;rtf;
Categories=Office;WordProcessor;Spreadsheet;Presentation;
```
