### ISSUE TITLE
Ubuntu 24.04 Nautilus and move window buttons (close, max, min) to the left side

### ISSUE THREAD

**Issue by deusexec** [vinceliuice/WhiteSur-gtk-theme#1107]
Hi! Thank you so much for a such beautiful theme!

**I have two question:**

1. How to customize Nautilus window like Files. Because it is still looks like default.
2. How to move window buttons to the left side? Buttons like close, min, max.

**OS Ubuntu 24.04.**

**Comment by deusexec** [comment]
The second question is already resolved by the following command:

`gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'`

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by deusexec** [comment]
@vinceliuice Thank you! It works.
