### ISSUE TITLE
How to clean Obsidian title bar?

### ISSUE THREAD

**Issue by Arche151** [vinceliuice/WhiteSur-gtk-theme#1108]
I'm using WhiteSur on Ubuntu with Obsidian (Flatpak version). 

Currently, the title bar shows the name of my Obsidian vault, the name of the currently opened note current note, as well as the Obsidian version.

![image](https://github.com/user-attachments/assets/386b2634-d061-4a87-aae7-e9fdcc21f3e4)

I would prefer if the title bar would display nothing or only "Obsidian". Does anyone know how to achieve this? Using custom CSS inside Obsidian didn't work, unfortunately.

Thanks for any help!

**Comment by vinceliuice** [comment]
This is a not a theme thing, you need modify the source code and recompile it

**Comment by Arche151** [comment]
@vinceliuice Ah ok, I see.
