### ISSUE TITLE
False display on standard opacity themes

### ISSUE THREAD

**Issue by Sciroccogti** [vinceliuice/WhiteSur-gtk-theme#111]
I installed the awesome theme from source, however there is a error:

![image](https://user-images.githubusercontent.com/32357397/104810539-3709dd80-5830-11eb-86d9-b5c8cdfca559.png)

![image](https://user-images.githubusercontent.com/32357397/104810548-45f09000-5830-11eb-9246-8fc8a848afd1.png)

**Comment by vinceliuice** [comment]
用solid版本，如果你使用的是nvidia显卡就会有这种问题，显卡驱动的渲染问题，有滞留

**Comment by Sciroccogti** [comment]
明白了，感谢

**Comment by Sciroccogti** [comment]
Seems to be fixed by 3401130 or `nvidia-driver-465`.
