### ISSUE TITLE
Is this black line from the theme or a configuration

### ISSUE THREAD

**Issue by alisson3000br** [vinceliuice/WhiteSur-gtk-theme#1110]
the line is only on the left side of the window

this is ubuntu 24  is libadwaita

thanks in advance

![Screenshot from 2024-08-20 12-23-01](https://github.com/user-attachments/assets/dd633de7-4b73-4e55-8e9f-19fb5796d263)

**Comment by vinceliuice** [comment]
Did you installed any rounded window extensions ?

**Comment by alisson3000br** [comment]
Just found in Round Windows corners the solution, in Padding settings only the left side was 0.0 and instead of 1.0 that is the default setting now there is no line anymore, thanks your reply helped !!!

i'll close the issue
