### ISSUE TITLE
firefox-dev 130 monterey address bar overlap with tab

### ISSUE THREAD

**Issue by dongdigua** [vinceliuice/WhiteSur-gtk-theme#1113]
Firefox Version: Firefox Developer Edition 130.0b8

![图片](https://github.com/user-attachments/assets/aa654922-4a08-4d9a-95ea-5eedb7addc66)

**Comment by vinceliuice** [comment]
Check readme file

Tips about monterey options (Fix the urlbar attached tabs issue)

    Remove all space separators on left of urlbar
    Make sure how many buttons you put on side of urlbar an then run ./tweaks.sh -f monterey -e

/*--------------Configure your Monterey theme--------------
 * ONLY for Monterey theme
 * Enable one of these options and disable the other ones.
 */

/* How many buttons on left headerbar */
@import "Monterey/left_header_button_3.css"; /**/
/*@import "Monterey/left_header_button_4.css"; /**/
/*@import "Monterey/left_header_button_5.css"; /**/

/* How many buttons on right headerbar */
@import "Monterey/right_header_button_3.css"; /**/
/*@import "Monterey/right_header_button_4.css"; /**/
/*@import "Monterey/right_header_button_5.css"; /**/

    Choose the right buttons number config then remove /* to enable it and add /* to disable the default one

**Comment by dongdigua** [comment]
Sorry I didn't notice it. It works!
