### ISSUE TITLE
Flatpak install (tweaks.sh -F) gives an error

### ISSUE THREAD

**Issue by NBA2K1** [vinceliuice/WhiteSur-gtk-theme#1114]
Oops! Operation failed...

  =========== ERROR LOG ===========
  
>>>>>>> No error log found <<<<<<
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-flatpak.sh
    >>> lib-install.sh
    >>> tweaks.sh
  SNIPPET:
    >>> cp -a "$theme_path/gtk-3.0/"* "$build_dir/files"
  TRACE  :
    >>> signal_error
    >>> pakitheme_gtk3
    >>> connect_flatpak
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO  : ubuntu debian;linuxmint;21.3
  SUDO    : no
  DESKTOP : cinnamon
  REPO    : 2024-08-25T04:18:09+0200

![image](https://github.com/user-attachments/assets/69c0a304-7d58-426f-af6d-2fafc4948065)

**Comment by NBA2K1** [comment]
OK, I had to execute it with sudo. Doesn't say anywhere.
But then I get this error: 
  Connecting 'WhiteSur' themes to your Flatpak... 

  Could not locate theme... install theme first!
  
  I have installed the theme to the standard location with the provided install.sh script like so:
`./install.sh -d ~/.themes -c Light -c Dark -t red -t default -o solid`

**Comment by NBA2K1** [comment]
Found a comment that claimed to fixed it but it didn't help me
https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/551#issuecomment-1195415690

**Comment by vinceliuice** [comment]
I fixed it now run: `tweaks.sh -F -c Light -c Dark -t red -t default -o solid` to install it
