### ISSUE TITLE
Support for GTK.Notebook?

### ISSUE THREAD

**Issue by TomJansen** [vinceliuice/WhiteSur-gtk-theme#1115]
Thank you for this theme! I have an issue however with LibreOffice. In LibreOffice, the tab bar (GTK.Notebook) looks not so pretty with WhiteSur:
![image](https://github.com/user-attachments/assets/4384c05b-2176-4bd1-9ee0-149f5ca09ae2)

Maybe we can take inspiration from the GTK.Notebook style from Adwaita? I made a small mockup using GTK_DEBUG=interactive:
![image](https://github.com/user-attachments/assets/ce1de409-9965-4902-9a76-7b80df54c060)

This image is with the WhiteSur-Light-solid and with these CSS styles on top:
```
headerbar {
    border: 0px;
}

button:checked {
   background-color: #e9e9e9;
   border: 0px;
}

notebook > header.top {
    box-shadow: inset 0 0px #dcdfe3;
    background-color: white;
    border: 0px
}

notebook > header > tabs > tab {
    padding: 2px 10px;
    min-width: 20px;
    min-height: 26px;
    outline-offset: -4px;
    border: 0px solid transparent;
    border: none;
    border-radius: 0px 0px 0 0;
}

notebook > header > tabs > tab:hover:not(:checked) {
    border-bottom: 3px solid;
    border-color: #eeeeee;
}

notebook > header > tabs > tab:selected {
    border-bottom: 3px solid;
    border-color: #0860f2;
}
```

Note also the lighter button colors

**Comment by vinceliuice** [comment]
That will change all gtk app style

**Comment by TomJansen** [comment]
Looks super good!
