### ISSUE TITLE
Let Firefox control color theme in WhiteSur monterey?

### ISSUE THREAD

**Issue by Rojoloter** [vinceliuice/WhiteSur-gtk-theme#1116]
Ive found this fork of the repo (https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS9) that gives the color theme control to firefox. This makes it possible to use the Adaptive Tab Bar Color extension, that blends the toolbar colors whit the page contents. Is there a way to do this in WhiteSur monterey? Thanks in advance

**Comment by vinceliuice** [comment]
Run `./tweaks.sh -f adaptive` or `./tweaks.sh -f monterey adaptive` or `./tweaks.sh -f alt adaptive`
to install adaptive theme
