### ISSUE TITLE
Firefox wrong icon color

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#1117]
bf71497

before
![Screenshot from 2024-08-31 16-40-23](https://github.com/user-attachments/assets/5208a8ef-38ae-4131-8afa-1e6596995f02)

after
![Screenshot from 2024-08-31 16-40-51](https://github.com/user-attachments/assets/4d9387ea-2fdc-4b84-a37d-54ef7c6dfb3b)

**Comment by vinceliuice** [comment]
What's your firefox version ?

**Comment by vinceliuice** [comment]
Try the last update again

**Comment by FelixFourcolor** [comment]
Firefox 129 (arch). The last update didn't help.

**Comment by vinceliuice** [comment]
Which theme version did you installed ?

**Comment by FelixFourcolor** [comment]
I normally use `./tweaks.sh -f`. But I just tried the other 3 alternatives, they all have the same issue (black icons).

**Comment by FelixFourcolor** [comment]
Anyway, I hope someone else can chime in if they have the same issue. If it's only me, I don't mind just reverting that commit for myself. 🙂

**Comment by vinceliuice** [comment]
![Screenshot from 2024-09-02 04-36-28](https://github.com/user-attachments/assets/953b0f8a-605e-4a6d-b870-fb94d7f466a3)

**Comment by vinceliuice** [comment]
It works all well on my desktop, I don't know what happen

**Comment by adriancalavie** [comment]
It happens on my side too (version 129.0.2)

**Comment by BrenoAV** [comment]
Same here! Firefox version 129.0.2 (pop-os 22.04)

Command used:

`./tweaks.sh -f`

**Comment by FelixFourcolor** [comment]
> Edit: solved by setting in `about:config`
> 
>     * `svg.context-properties.content.enabled` equals `true`
It works, thank you!

**Comment by FelixFourcolor** [comment]
I found another problem. The "Close tab" button is not showing,
![Screenshot from 2024-09-02 18-53-58](https://github.com/user-attachments/assets/145f132e-3844-4851-bdfb-dbc3ef683704)

**Comment by vinceliuice** [comment]
After you `svg.context-properties.content.enabled` equals `true`, still not showing ?

**Comment by vinceliuice** [comment]
Now it's ok
