### ISSUE TITLE
How to apply the shell customization options ?

### ISSUE THREAD

**Issue by houssemko** [vinceliuice/WhiteSur-gtk-theme#1118]
`WARNING: Ambigous '-o' option. We'll show a chooser dialog when possible
  WARNING: '-o' variant of '75' isn't recognized. We'll show a chooser dialog when possible
  WARNING: '-h' variant of 'smaller' isn't recognized. We'll show a chooser dialog when possible
  Removing the old 'WhiteSur' themes...`

i get those warnings when applying with this : `./install.sh -d /home/houssem/.local/share/themes -o normal -c Dark --shell -o 75 -h smaller -n -s --darker `

**Comment by vinceliuice** [comment]
Now run this: `./install.sh -o normal -d $HOME/.local/share/themes -c Dark --shell -p 75 -h smaller -g -s --darker`

**Comment by vinceliuice** [comment]
It's weird, you and I use the same gnome-shell version, but it works all good on my desktop, just I using fedora
