### ISSUE TITLE
Permission to store theme in other repo

### ISSUE THREAD

**Issue by techcoder20** [vinceliuice/WhiteSur-gtk-theme#112]
Hi @vinceliuice I am the creator of [MacOSBigSurThemeConverter](https://github.com/techcoder20/MacOSBigSurThemeConverter) I make use of your theme in my script and have credited you at every point possible. Currently in my script I clone your script and run the install script. Will it be fine with you if I store the theme in my repo ? The reason I prefer storing the themes in my repo is that it will reduce the number of dependencies and reduce the time of installation. So I would really like it if you could give me permission to store the themes in my repo :)

**Comment by vinceliuice** [comment]
No problem!

**Comment by techcoder20** [comment]
Thanks :)
