### ISSUE TITLE
Gnome 47 

### ISSUE THREAD

**Issue by ryzendew** [vinceliuice/WhiteSur-gtk-theme#1123]
So Gnome 47 added accent colors and the area where you apply that looks like this 
![image](https://github.com/user-attachments/assets/0d100094-0a3f-4046-98ea-0d45126b13ae)

Also the accent colors apply in some places with your theme 1% but the rest is still just default blue 

![image](https://github.com/user-attachments/assets/ff60bbb3-b346-4db2-96af-ae8d67ea4507)
![image](https://github.com/user-attachments/assets/87abe19d-7ef0-491b-bfdd-621b4ac5909f)
![image](https://github.com/user-attachments/assets/9c1c8547-34ee-451d-9d0f-e53422ea9464)

**Comment by ryzendew** [comment]
not to bug you but any update on gnome 47 support?

**Comment by diorcula** [comment]
I wonder about this too, does gnome 47 allow such themeing?

**Comment by ryzendew** [comment]
> I wonder about this too, does gnome 47 allow such theming?

yes

**Comment by diorcula** [comment]
> > I wonder about this too, does gnome 47 allow such theming?
> 
> yes

I can remember there were difficulties with GTK3 and GTK4, how is this handled now then?
I am not too proficient with themeing and haven't used this theme in about a year now
