### ISSUE TITLE
Nautilus Sidebar and Accent colors set to yellow even though theme is set to default colors

### ISSUE THREAD

**Issue by cinnamonbunbuns** [vinceliuice/WhiteSur-gtk-theme#1128]
I am not sure how I managed to do this or what I did to cause this.

I ran the fix under tweaks.sh for Flatpaks and afterwards my highlight color in some areas is yellow but in some areas it is blue. Additionally the sidebar icons in Nautilus are yellow when they should be blue. I have also tried uninstalling and reinstalling the theme three times now and it not fixed the issue.

![image](https://github.com/user-attachments/assets/662b305e-2dda-4e2a-be31-b375d0601afc)

![image](https://github.com/user-attachments/assets/8373197d-c092-4ccd-808f-8fbd2e905f0a)

![image](https://github.com/user-attachments/assets/588b0a88-aaa4-4f5b-a4e7-e453d4a831da)

![image](https://github.com/user-attachments/assets/c8294fb4-2dea-40e1-9736-e97ade39b5d9)

**Comment by vinceliuice** [comment]
Run  ./install.sh -l -r

**Comment by cinnamonbunbuns** [comment]
That did the trick! Was able to reinstall to default colors. Thank you for the quick response and have an amazing day!
