### ISSUE TITLE
[Query] How do I change the default big sur wallpaper in GDM theme?

### ISSUE THREAD

**Issue by bluefangs** [vinceliuice/WhiteSur-gtk-theme#113]
I've installed the GDM theme via `sudo ./install -g`. I see that the login screen has changed as mentioned in the readme.md.
However, I'd like to change the default Big Sur wallpaper that is being displayed as the login screen background. What do I need to do to change that specific wallpaper?

Thx

**Comment by vinceliuice** [comment]
Replace this picture:  `../src/assets/gnome-shell/common-assets/background.jpg`
Then reinstall it
