### ISSUE TITLE
Adding Firefox darker theme broke the adaptive theme's tabsbar

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#1138]
This commit 3589f39ea7a6c65463f036059041f145eeed3e53 broke the adaptive theme's tabsbar.

Before, there was a color difference to indicate the active tab.
[Screencast From 2024-09-30 11-00-03.webm](https://github.com/user-attachments/assets/2a623e2c-4e94-41c0-9d6b-12156cf8d631)

After, all tabs look the same.
[Screencast From 2024-09-30 11-02-13.webm](https://github.com/user-attachments/assets/70abc550-dd93-4a0c-9c82-f8e35242e335)

-----------------------------------------
AFAIK this only affects the "normal" adaptive theme (`./tweaks.sh -f adaptive`). Non-adaptive themes are not affected, and the `monterey adaptive` and `flat adaptive` themes are not affected.

**Comment by fernandesafp** [comment]
Fixed with #1140. Thanks.
