### ISSUE TITLE
Graphic bug after Suspend.

### ISSUE THREAD

**Issue by Mimich-FR** [vinceliuice/WhiteSur-gtk-theme#114]
Hey i need some help.

I use all GTK WhiteSur suite (Wallpaper, gdm, browser theme, icon, main theme, Dash to dock theme) on archlinux with:
- linux-lts(kernel)
- nvidia-lts(graphics card driver)
- GNOME
- GDM
- GRUB

OK so, this problems pop just after a long suspend time, with a short time the same problem persists but is automatically fix in a second.

![Login screen corner](https://user-images.githubusercontent.com/65086532/104852928-b31e2700-58fd-11eb-8d85-b5b544455b74.jpg)
![Login screen](https://user-images.githubusercontent.com/65086532/104852932-baddcb80-58fd-11eb-85c3-d6c013925e10.jpg)
After login
![Corner ](https://user-images.githubusercontent.com/65086532/104852950-e82a7980-58fd-11eb-9877-e7ba00a02524.jpg)
![Dash to dock ](https://user-images.githubusercontent.com/65086532/104852941-ce893200-58fd-11eb-80b1-6809821ed260.jpg)

Thank you in advance.

**Comment by vinceliuice** [comment]
Is it only this theme have this issue? it looks like a graphic driver bug not a theme issue

**Comment by Mimich-FR** [comment]
Is just after a installation of a WhiteSur gdm theme with a installation scripts.

**Comment by vinceliuice** [comment]
Maybe there is something issue with this gdm theme, I suggest you remove gdm theme if this happen again

**Comment by vinceliuice** [comment]
Maybe there is something issue with this gdm theme, I suggest you remove gdm theme if this happen again

**Comment by Mimich-FR** [comment]
Yea after uninstall GDM theme. Bug is fixed thanks for your support.

**Comment by Gynshu** [comment]
How to remove only gdm theme?

**Comment by vinceliuice** [comment]
./install.sh -g -r

**Comment by LukeyAlvin** [comment]
I have the same problem, It will be like that after I suspend my ubuntu, How can i solve it ?
