### ISSUE TITLE
GTK 4.0 theme not being applied after latest update

### ISSUE THREAD

**Issue by umangg2226** [vinceliuice/WhiteSur-gtk-theme#1148]
![image](https://github.com/user-attachments/assets/ad596298-0b4e-4ef4-a875-5483c65f3c4a)
![image](https://github.com/user-attachments/assets/811b2991-3b29-4119-a96e-6a0d9904472c)

Hello, GTK 4.0 theme not being applied on system apps like files, uploader etc.. while third party apps like slack, chrome and vscode working.

have installed with this command: `./install.sh -n umang -o solid -c dark -a alt -s nord --libadwaita --darker && sudo ./tweaks.sh -c dark -g`

thank you.

**Comment by luca-martino** [comment]
... same on fedora 40 and i have another issue with "tweaks.sh"

![immagine](https://github.com/user-attachments/assets/82cc9558-c94e-4a02-8ae3-1ebe97afe1ca)

**Comment by umangg2226** [comment]
@vinceliuice theme isn't darker but it works. thank you very much.
![image](https://github.com/user-attachments/assets/778cd9ca-74b2-4587-8d73-bac28b9d7917)

**Comment by vinceliuice** [comment]
Darker background color is #1f1f1f, default background color is #242424

**Comment by umangg2226** [comment]
![image](https://github.com/user-attachments/assets/0ae0ed6b-95a8-4613-a36b-e57c245dab7b)
![image](https://github.com/user-attachments/assets/f95f1922-d916-44f8-8d7f-cfcdbae532be)
@vinceliuice sorry but bg color of titlebar & icons is different accross gtk4 and chrome. it was used to be same like chrome.

**Comment by vinceliuice** [comment]
Chrome use gtk3 theme colors, not libadwaita(gtk4)

**Comment by umangg2226** [comment]
@vinceliuice i think the nord color scheme is not getting applied in gtk 4

**Comment by umangg2226** [comment]
![image](https://github.com/user-attachments/assets/f5eb5a49-e506-4d09-b05e-36953c5917ad)
@vinceliuice

**Comment by vinceliuice** [comment]
Now it's fixed

**Comment by umangg2226** [comment]
seems perfect now, thanks a lot @vinceliuice
