### ISSUE TITLE
variable boundaries are not set

### ISSUE THREAD

**Issue by coder8080** [vinceliuice/WhiteSur-gtk-theme#115]
my terminal session:

`
┌──[ coder8080@linux ] [ 15:46:23 ]
├── ~/Загрузки
└> git clone https://github.com/vinceliuice/WhiteSur-gtk-theme 
Клонирование в «WhiteSur-gtk-theme»…
remote: Enumerating objects: 1206, done.
remote: Counting objects: 100% (1206/1206), done.
remote: Compressing objects: 100% (606/606), done.
remote: Total 4852 (delta 665), reused 1103 (delta 600), pack-reused 3646
Получение объектов: 100% (4852/4852), 7.98 MiB | 1.91 MiB/s, готово.
Определение изменений: 100% (2554/2554), готово.
┌──[ coder8080@linux ] [ 15:46:33 ]
├── ~/Загрузки
└> cd ./WhiteSur-gtk-theme
┌──[ coder8080@linux ] [ 15:46:39 ]
├── ~/Загрузки/WhiteSur-gtk-theme
└> ./install.sh --size 280
./install.sh: строка 533: theme_color: не заданы границы переменной
`

sorry for Russian localization

**Comment by coder8080** [comment]
here is normal format of terminal session:
┌──[ coder8080@linux ] [ 15:46:23 ]
├── ~/Загрузки
└> git clone https://github.com/vinceliuice/WhiteSur-gtk-theme
Клонирование в «WhiteSur-gtk-theme»…
remote: Enumerating objects: 1206, done.
remote: Counting objects: 100% (1206/1206), done.
remote: Compressing objects: 100% (606/606), done.
remote: Total 4852 (delta 665), reused 1103 (delta 600), pack-reused 3646
Получение объектов: 100% (4852/4852), 7.98 MiB | 1.91 MiB/s, готово.
Определение изменений: 100% (2554/2554), готово.
┌──[ coder8080@linux ] [ 15:46:33 ]
├── ~/Загрузки
└> cd ./WhiteSur-gtk-theme
┌──[ coder8080@linux ] [ 15:46:39 ]
├── ~/Загрузки/WhiteSur-gtk-theme
└> ./install.sh --size 280 ./install.sh: строка 533: theme_color: не заданы границы переменной

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed
