### ISSUE TITLE
Flatpak Firefox

### ISSUE THREAD

**Issue by alisson3000br** [vinceliuice/WhiteSur-gtk-theme#1150]
![Screenshot from 2024-10-15 16-09-37](https://github.com/user-attachments/assets/d9b9a15b-4d9a-42d6-9f49-0d2cd1dc6186)

i need help fixing this buttons padding too close to the border, and btw the firefox theme is only for snap?

**Comment by vinceliuice** [comment]
Does it not work on faltpak ?

**Comment by alisson3000br** [comment]
You mean tweaks.sh -f? That only works for snap Firefox, flatpak Firefox gets the gtk which makes those buttons too close to the border

**Comment by vinceliuice** [comment]
What's your flatpak firefox version ?

**Comment by alisson3000br** [comment]
it is 131.0.3

**Comment by alisson3000br** [comment]
flatseal solved on ubuntu, on fedora it works without it
