### ISSUE TITLE
I can't update the theme

### ISSUE THREAD

**Issue by houssemko** [vinceliuice/WhiteSur-gtk-theme#1151]
./install.sh -d /home/houssem/.local/share/themes -o normal -c Dark -t purple --shell -p 75 -h smaller  -g -s --darker

  ERROR: '-s' can't be empty 

scheme and small shell are conflicting

**Comment by vinceliuice** [comment]
scheme options are standard and nord

**Comment by vinceliuice** [comment]
If you want install nord version you should run: `./install.sh -d /home/houssem/.local/share/themes -o normal -c Dark -t purple --shell -p 75 -h smaller -g -s nord --darker`

**Comment by vinceliuice** [comment]
./install.sh -d /home/houssem/.local/share/themes -o normal -c Dark -t purple --shell -p 75 -h smaller -s nord --darker
