### ISSUE TITLE
Window design is not the same

### ISSUE THREAD

**Issue by juanchopi37** [vinceliuice/WhiteSur-gtk-theme#1157]
Today I installed the theme again, but apparently only some have it by default, the system windows appear with the default theme. How can this be solved?

![Captura desde 2024-10-25 20-17-02](https://github.com/user-attachments/assets/f76937f5-3481-4a8f-b931-acf3bca739cf)

**Comment by vinceliuice** [comment]
`./install.sh -c dark -l`

**Comment by juanchopi37** [comment]
Thank you very much, I really appreciate your work :D
