### ISSUE TITLE
Doubt in the nord theme after the recent update

### ISSUE THREAD

**Issue by aniruth6k** [vinceliuice/WhiteSur-gtk-theme#1163]
Warm welcome to vinceliuice. I am huge fan of your repo due to the beautiful themes in it. I really appreciate your work.
until a month back when i used this in linux mint 22 cinnamon flavor after cloning this repo i used to execute the command ./install.sh --nord and this makes the cinnamon look so pretty it literally changes everything to the beautiful nord theme. But after the recent update i am completely lost and unable to bring that back i have tried different releases like:
./install.sh -n Whitesur-Dark-nord
./install.sh -n Whitesur-Dark-solid-nord
but neither of these brings the original nord palette which i was using earlier. It is bringing just a black theme. I really miss the old one. Can you help me out? I actually follow a youtube video which i have linked below for your reference so you can view the nord theme which i am requesting about:
https://www.youtube.com/watch?v=h1yIY1BwetQ

In 3.30 timestamp in the video he downloads using the command:
./install.sh --nord 
in 7.00 timestamp he uses the dconf command and it looks really pretty. Do help me with it.

**Comment by vinceliuice** [comment]
Command changed run: ./install.sh -s nord

**Comment by aniruth6k** [comment]
![Screenshot from 2024-11-01 23-57-19](https://github.com/user-attachments/assets/3322bcfe-f538-4d7a-b1bb-1f7aeaa17fbd)
Thank you vinceliuice for your quick reply. The nord colors have come but the window borders aren't looking like how it used it to be. Last time i tried the window borders and the buttons looked exactly like the macos too. I have added a screenshot for your reference.

**Comment by vinceliuice** [comment]
Change your wm theme

**Comment by aniruth6k** [comment]
Thank you vinceliuice. It is back to normal and looking good once again.

**Comment by aniruth6k** [comment]
Thank you vinceliuice. It is back to normal and looking good once again.
