### ISSUE TITLE
Change the font size of buttons

### ISSUE THREAD

**Issue by rashadgasimli** [vinceliuice/WhiteSur-gtk-theme#1165]
Hi, after updating to Fedora 41 (GNOME 47), the font size of buttons are smaller than default one. Here is the photos about the differences:
1. WhiteSur-gtk-theme:
![Screenshot From 2024-11-04 21-43-01](https://github.com/user-attachments/assets/bacc6002-048e-4290-aa59-8ba3ded0a946)
2. Adwaita:
![Screenshot From 2024-11-04 21-50-03](https://github.com/user-attachments/assets/c11ea135-b37c-42f3-9d34-070f08665ad1)

**Comment by nehubuser** [comment]
I think you can change the font size from Gnome Tweaks.

**Comment by rashadgasimli** [comment]
I can't, there are no settings about changing the buttons' font size
