### ISSUE TITLE
Do Not Disturb toggle is squared instead of rounded. 

### ISSUE THREAD

**Issue by nehubuser** [vinceliuice/WhiteSur-gtk-theme#1167]
OS: Arch
DE: Gnome

Bug: Toggle for Do Not Disturb is squared. I think it should be rounded like the rest of the toggles. 
![image](https://github.com/user-attachments/assets/3ecd8e9d-d28d-4144-8076-4869788836d7)

**Comment by vinceliuice** [comment]
What's your gnome version ?

**Comment by vinceliuice** [comment]
Try install this theme from github

**Comment by nehubuser** [comment]
47.  I installed it from github with git clone.

**Comment by vinceliuice** [comment]
Try again, I update it

**Comment by nehubuser** [comment]
Tried it after uninstalling the previous one. 
Same result. 

But please don't waste your time on this unless you get similar reports from other users as well. 
Perhaps it is only happening on my system.

**Comment by vinceliuice** [comment]
If you install GDM theme you need reinstall it again: `sudo ./tweaks.sh -g`

**Comment by nehubuser** [comment]
That worked! Now the buttons are good!  

But it seems to have cropped the calendar /weather section on the notification menu. 

I tested it again after removing the theme (both gnome and gdm) and installing it again just to make sure. The cropped/cutout part remains. 😅 

 
![Screenshot From 2024-11-07 22-10-10](https://github.com/user-attachments/assets/738dff7c-1c0f-4ea3-9407-50a647a36680)

**Comment by vinceliuice** [comment]
What about now ?
