### ISSUE TITLE
[Firefox] No separator space between the Address Bar and the First Tab under Monterey theme

### ISSUE THREAD

**Issue by kiyospace** [vinceliuice/WhiteSur-gtk-theme#1169]
1. Download WhiteSur-gtk-theme-**2024.09.02**.tar.gz and untar it
2. Run `./tweaks.sh -f monterey`
3. Start firefox and there is **no separator space between the Address Bar and the First Tab** (See the red block area in the attached picture)

![no-separator](https://github.com/user-attachments/assets/7f5a0649-e803-49dd-b389-3351bc28f7e8)

**Comment by vinceliuice** [comment]
What's your firfox version?

**Comment by kiyospace** [comment]
I am using Firefox **128.4.0esr (64-bit)** on Linux Mint (cinnamon desktop).

**Comment by kiyospace** [comment]
Also another small issue under this monterey theme from WhiteSur-gtk-theme-**2024.09.02**.tar.gz I'd like to mention is that, the shadow (grey area) when hovering on the "**backward button <**" behaves differently than that on the **forward button >** or the **stop X button**.

Please see the attached picture for details. Thanks.

![small-issue-on-backward](https://github.com/user-attachments/assets/2542b9ba-0eba-4dd2-8c62-a57693f9a2c6)

**Comment by vinceliuice** [comment]
Download this and try again: https://github.com/vinceliuice/WhiteSur-gtk-theme/releases/tag/2024-11-18

**Comment by kiyospace** [comment]
Thanks! The WhiteSur-gtk-theme-**2024-11-18**.tar.gz release solved the problem mentioned in the title as well as the problem about the backward button mentioned in the comment. Closing.
