### ISSUE TITLE
GDM theme not working at all

### ISSUE THREAD

**Issue by Yuri6037** [vinceliuice/WhiteSur-gtk-theme#117]
Running `sudo ./install.sh -g -c light` does not have any effect under PopOS 20.10

**Comment by Yuri6037** [comment]
This is absolutely terrible nightmare: I tried to force overwrite gdm3-theme.gresource but this broke the entire system no more boot! I'm prompted with a nice white screen with unrecoverable error. I'll have to burn an arch iso just to chroot inside the system

**Comment by Yuri6037** [comment]
![Uploading IMG_20210121_231208.jpg…]()

Here is a picture of the problem taken from my phone.

**Comment by Yuri6037** [comment]
Even better I figured why it fails, but there is an error in your theme:

```
Jan 21 23:50:25 X gnome-shell[8272]: Execution of main.js threw exception: Script <main> threw an exception
Jan 21 23:50:25 X gnome-shell[8272]: JS ERROR: Error: No valid stylesheet found for 'gdm3.css'
                                            loadTheme@resource:///org/gnome/shell/ui/main.js:449:15
                                            _loadDefaultStylesheet@resource:///org/gnome/shell/ui/main.js:394:5
                                            _initializeUI@resource:///org/gnome/shell/ui/main.js:188:5
                                            start@resource:///org/gnome/shell/ui/main.js:159:5
                                            @<main>:1:47
```

**Comment by vinceliuice** [comment]
Not support pop os, I'll fix that, pop os and ubuntu have changed gdm theme dir and folder

**Comment by Yuri6037** [comment]
Thanks a lot.

I wonder if your code will keep working after system upgrade... Could you allow the use of update-alternatives? Modifying theme files directly isn't great when this risks to be partially reverted by an apt upgrade.

**Comment by vinceliuice** [comment]
Honestly, it is still not recommended to use third-party gdm themes, because there will be some unexpected issues that can make it impossible to enter the desktop

**Comment by fpiem** [comment]
@Yuri6037 Were you able to restore your PopOS boot? I ran into the same issue.
