### ISSUE TITLE
Some system dialog buttons are not readable (white text on white background)

### ISSUE THREAD

**Issue by mauriziopinotti** [vinceliuice/WhiteSur-gtk-theme#1170]
Some system dialog buttons are not readable (white text on white background).

For example Logout, Reboot and Poweroff dialogs:

![IMG_20241117_150756437_HDR](https://github.com/user-attachments/assets/94b3b4cb-66cf-4171-af2b-254625404eea)

Another example is the Install Extension confirmation popup (go to https://extensions.gnome.org and try to install an extension).

**OS details**
Ubuntu 24.10
Gnome 47
Wayland
WhiteSur-light theme

**Comment by vinceliuice** [comment]
Download the last update from github and try again

**Comment by vinceliuice** [comment]
What about now ?

**Comment by mauriziopinotti** [comment]
> What about now ?

Thanks, now it's ok! 👍🏻
