### ISSUE TITLE
Latest Git version Installation failed

### ISSUE THREAD

**Issue by aloksrk** [vinceliuice/WhiteSur-gtk-theme#1171]
ops! Operation failed...

  =========== ERROR LOG ===========
  >>> Error: Undefined variable: "$gnome-version".
  >>>         on line 111:9 of src/sass/gtk/_common-4.0.scss
  >>>         from line 6:9 of src/main/gtk-4.0/gtk-Dark.scss
  >>> >>     @if $gnome_version == 'old' {
  >>> 
  >>>    --------^
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> sassc ${SASSC_OPT} "${THEME_SRC_DIR}/main/gtk-4.0/gtk${color}.scss" "${TMP_DIR_F}/gtk.css"
  TRACE  :
    >>> signal_error
    >>> install_theemy
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO  : rolling;arch
  SUDO    : no
                           ••••    DESKTOP : GNOME Shell 47.1
  REPO    : 2024-11-18T08:03:21+0530

  HINT: You can google or report to us the info above 

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

**Comment by vinceliuice** [comment]
Is this file exist in your theme source folder ? `~/WhiteSur-gtk-theme/src/sass/_gtk-base-temp.scss`

**Comment by aloksrk** [comment]
Yes
