### ISSUE TITLE
Themes not applying to GTK applications

### ISSUE THREAD

**Issue by ImSreyas** [vinceliuice/WhiteSur-gtk-theme#1172]
Distro: fedora 41 (kernel v 6.11.7) wayland
gnome version: 47

The theme was working perfectly on my system before the upgrade from Fedora 40 to Fedora 41. However, after the upgrade, the theme stopped applying to most GTK applications. It still works for some apps, such as GNOME Terminal, Firefox, and Document Viewer.

How can I resolve this issue?

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by ImSreyas** [comment]
> Run: `./install.sh -l`

Thanks, it worked :)
