### ISSUE TITLE
Error on install in Fedora

### ISSUE THREAD

**Issue by evandrodevbr** [vinceliuice/WhiteSur-gtk-theme#1173]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> Error: Unable to locate package dialog
  >>> Error: Unable to locate package dialog
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> apt install -y dialog
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_dialog_deps
    >>> show_needed_dialogs
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO  : workstation;platform:f41;fedora;41
  SUDO    : yes
  DESKTOP : GNOME Shell 47.0
  REPO    : 2024-11-17T13:52:58-0300

=========================================================
GPU: RTX 3070 8GB
CPU: R7 5700G
RAM: 64GB 4X16GB
SSD: M2 NVME

**Comment by vinceliuice** [comment]
Apt on fedora ?
