### ISSUE TITLE
Brave browser close buttons doesn't get effected by the macos style buttons

### ISSUE THREAD

**Issue by githlacker** [vinceliuice/WhiteSur-gtk-theme#1175]
![image](https://github.com/user-attachments/assets/a6dd223a-2289-4383-9026-ae8f47a0c6d4)

**Comment by nehubuser** [comment]
It is a chromium based browser and it has it's own decoration system in the browser's setting. 
Pic related is a decoration setting in chromium.  

There must be a similar setting in "brave" (malware) where you can change the button decoration. 

![image](https://github.com/user-attachments/assets/8e896b13-9586-4195-935f-5f321fb943fe)

**Comment by githlacker** [comment]
Ye should have looked more sorry for the bother

**Comment by sourcelocation** [comment]
@nehubuser Why do you say it's malware lmao
