### ISSUE TITLE
GNOME Accent Colors overwrites WhiteSur Accent Colors

### ISSUE THREAD

**Issue by Keqwerty** [vinceliuice/WhiteSur-gtk-theme#1176]
GNOME 47 accent colors overwrites whitesur accent colors (i liked old blue, but GNOME overwrites it with own blue that i dont like)

# System Details Report
---

## Report details
- **Date generated:**                              2024-11-22 00:05:59

## Hardware Information:
- **Hardware Model:**                              Gigabyte Technology Co., Ltd. B650 AORUS ELITE AX
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 7700 × 16
- **Graphics:**                                    NVIDIA GeForce RTX™ 3060
- **Disk Capacity:**                               2.5 TB

## Software Information:
- **Firmware Version:**                            FA5f
- **OS Name:**                                     Arch Linux

- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.11.6-arch1-1

GNOME Accent Color
![Screenshot From 2024-11-22 00-08-39](https://github.com/user-attachments/assets/e6078ccb-4c07-42bf-a316-d33c94f1a94f)

Old WhiteSur Accent Color
![Screenshot From 2024-11-22 00-09-12](https://github.com/user-attachments/assets/47147907-676e-43b2-849a-f771bef8eab7)

**Comment by Keqwerty** [comment]
fixed with parameter -t default in install.sh

**Comment by vinceliuice** [comment]
Now you can run `./install.sh -f` for the fixed accent color version
