### ISSUE TITLE
window button deosnt follow tweaks

### ISSUE THREAD

**Issue by holiq** [vinceliuice/WhiteSur-gtk-theme#1183]
I have tweaks my window button into left on gnome tweaks, all apps are worked and before update firefox its works too, but since update into latest i got like this
I have pull the latest commit on this repo
![image](https://github.com/user-attachments/assets/902aff54-308d-4ca0-a7db-bbf6a0c291a7)

**Comment by vinceliuice** [comment]
Fixed now
