### ISSUE TITLE
Firefox search bar won't work in place when focused

### ISSUE THREAD

**Issue by anggyferdiawan** [vinceliuice/WhiteSur-gtk-theme#1186]
I'm using ubuntu 24.04 and installed GTK Theme. The problem is when the firefox search bar is clicked, it can't display fully like when idle. 

I've attached a photo of it idle and when clicked.

![Screenshot from 2024-12-05 12-43-07](https://github.com/user-attachments/assets/7efb6103-b9a8-4c89-a19d-0c8f43d6df6a)
![Screenshot from 2024-12-05 12-43-13](https://github.com/user-attachments/assets/7febf0da-89a3-4b58-8a4c-1768801eaaf9)

**Comment by luca-martino** [comment]
.. it's the same on my Fedora 41 - Gnome 47 - Firefox 131.0.2 

> I'm using ubuntu 24.04 and installed GTK Theme. The problem is when the firefox search bar is clicked, it can't display fully like when idle.
> 
> I've attached a photo of it idle and when clicked.
> 
> ![Screenshot from 2024-12-05 12-43-07](https://private-user-images.githubusercontent.com/67379808/392670747-7efb6103-b9a8-4c89-a19d-0c8f43d6df6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODgwODMsIm5iZiI6MTczMzM4Nzc4MywicGF0aCI6Ii82NzM3OTgwOC8zOTI2NzA3NDctN2VmYjYxMDMtYjlhOC00Yzg5LWExOWQtMGM4ZjQzZDZkZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNWE3ODRkOWY2YjQzMjI5NjlhNjcwMTE4ZTA5Y2Y4NzNhYjI0NjAyMjhlNWI4YWJhZjcxMzk3YjYxNWNjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._P3JNUXgOo-uBQOzxsxpZwwku2HHUy_T48lCe4sEbnk) ![Screenshot from 2024-12-05 12-43-13](https://private-user-images.githubusercontent.com/67379808/392670782-7febf0da-89a3-4b58-8a4c-1768801eaaf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODgwODMsIm5iZiI6MTczMzM4Nzc4MywicGF0aCI6Ii82NzM3OTgwOC8zOTI2NzA3ODItN2ZlYmYwZGEtODlhMy00YjU4LThhNGMtMTc2ODgwMWVhYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA4MzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhODlmNzM0MGIzMWYxNmYyNDZkZjgzZjNkZDlhNDhkNDcyZjc1OTA4Zjg3NGVhMDk2ODA4ZjcxZTU5NmI2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vUwEXSBJcKHSXDt8sLO-nVfyeotkCqK503dG0rOO_oo)

**Comment by vinceliuice** [comment]
Last update just works for firefox >= 133.0, you can update your firefox version, or use old whitesur version

**Comment by anggyferdiawan** [comment]
> Last update just works for firefox >= 133.0, you can update your firefox version, or use old whitesur version

Good, it works as expected. Thanks
![Screenshot from 2024-12-05 19-24-16](https://github.com/user-attachments/assets/62e639f2-1334-4d5d-81b4-7e7a4b1f36a0)
