### ISSUE TITLE
how to fix title button not work for all windows ?

### ISSUE THREAD

**Issue by isnuka** [vinceliuice/WhiteSur-gtk-theme#1187]
![Screenshot From 2024-12-05 19-25-02](https://github.com/user-attachments/assets/6afdfcb2-1db8-49a1-a5ed-473df93cd7f7)
why title bar button doesn't work in all applications how to fix it so that everything works in all applications

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by isnuka** [comment]
thanks verry much its work but firefox n chrome not work , sorry how to fix ? 
![Screenshot From 2024-12-05 20-54-17](https://github.com/user-attachments/assets/0efa2400-ed5f-4b67-b40d-3aeb85ed77f1)

**Comment by vinceliuice** [comment]
Run: `./tweaks.sh -f` to use whitesur firefox theme,
and change your chrome appearance setting to GTK

**Comment by isnuka** [comment]
Ok thanks , success for you 🙏🏻
