### ISSUE TITLE
Upper-bar icons are not changed

### ISSUE THREAD

**Issue by KaizOffical** [vinceliuice/WhiteSur-gtk-theme#1191]
The first is the problem with start menu icon. I've ran this command and re-login, but the start menu is still unchanged.
```bash
./install.sh --shell -i apple
```
Apple/ubuntu/any icon is still not working.

In addition, some other icons (like keyboard input) are unchanged even I've tried to re-login, reboot but nothing worked.

My upper bar when using this theme.
![image](https://github.com/user-attachments/assets/2b99ea04-0205-4bcd-a35e-67fb36d81616)

**Comment by b-risk** [comment]
Same problem in Fedora, rebooting does not fix.

**Comment by KaizOffical** [comment]
> After run this, reset your gnome-shell theme or restart your desktop

Oh, it worked now, thanks
