### ISSUE TITLE
The Titlebar of Gnome Tweak is invisible.

### ISSUE THREAD

**Issue by laichiaheng** [vinceliuice/WhiteSur-gtk-theme#12]
![2020-07-20 08-18-20 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/87888848-acebe280-ca61-11ea-8ae8-19df57368ce7.png)

**Comment by MLDamazigh** [comment]
This is a gnome 3.36 issue.

**Comment by zeparu** [comment]
that has been an issue in gnome for along time, only happens when you have leftsided window controls

**Comment by edwinvandeven** [comment]
You can make the window a little bit wider and the top bar should appear again.

**Comment by laichiaheng** [comment]
@edwinvandeven I've found out that I just need to hover my mouse on "X — 口 <", and it will appear.
