### ISSUE TITLE
Apps like Synaptic do not recognize newer/differently named theme

### ISSUE THREAD

**Issue by TPO100Cofficial** [vinceliuice/WhiteSur-gtk-theme#121]
Couldn't upload directly, used Discord links inestead.
As stated in title, apps like Synaptic Package manager don't recognize newer versions of the theme. (Or, maybe it's the theme being named differently. Either way, it's a problem.)

Notes: In screenshots, "BigSur" is newer installation of theme, "WhiteSur" is older.

https://cdn.discordapp.com/attachments/796148574811455510/803085379841294346/unknown.png
https://cdn.discordapp.com/attachments/796148574811455510/803085462927048714/unknown.png

**Comment by vinceliuice** [comment]
Did you run this with sudo?

**Comment by TPO100Cofficial** [comment]
That might be it. I'll test later installing with sudo.

**Comment by TPO100Cofficial** [comment]
I got caught up in a lot of things outside the internet, but finally got back today and yep, I just needed to run it both with and without Sudo.
