### ISSUE TITLE
Wrong title bar and buttons in ubuntu software

### ISSUE THREAD

**Issue by MichaelP89** [vinceliuice/WhiteSur-gtk-theme#124]
In the ubuntu software applications there is the wrong titlebar and buttons.
I use the solid theme:
![Bildschirmfoto vom 2021-01-30 09-55-35](https://user-images.githubusercontent.com/48978558/106352232-81379800-62e1-11eb-9197-1051d5e0a8f7.png)

**Comment by asif-hoda** [comment]
I think you need to snap connect the snap store because snap store is installed as a snap package and snaps donot follow gtk themes. Thats why just ```sudo snap install whitesur-gtk-theme``` in your terminal and then run ```for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i whitesur-gtk-theme:gtk-3-themes; done
```. Then restart.

**Comment by MichaelP89** [comment]
Thank you, works like a charm! :-)
