### ISSUE TITLE
snap icon theme and gtk theme not working for all apps except snap store

### ISSUE THREAD

**Issue by asif-hoda** [vinceliuice/WhiteSur-gtk-theme#126]
I installed the snap theme for my snap apps so that i can integrate my ubuntu into one theme. But after i connected the gtk3 theme and icon theme to all apps using the command given in the readme. But its only working for the snap store, apps like gimp are not accepting the theme.
Steps to reproduce:
1. sudo snap install whitesur gtk theme
2. then connect the theme to all apps
3. Will not work for any apps except snap store.

![Screenshot from 2021-01-30 19-49-59](https://user-images.githubusercontent.com/47708014/106358902-07c99500-6335-11eb-9681-99fef7e2ed49.png)

As in the screenshot, the gimp icon did not update to the icon theme's icon. I did restart.

![Screenshot from 2021-01-30 19-50-25](https://user-images.githubusercontent.com/47708014/106358967-55de9880-6335-11eb-803f-065c57e43632.png)

In this screenshot the gimp system theme was supposed to change but it looks just like the default system theme. Please adress this issue.

**Comment by rivanfebrian123** [comment]
Already fixed here: https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip. Run `./tweaks.sh -s` to connect your WhiteSur theme to your Snap apps

**Comment by iononi** [comment]
> Already fixed here: https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip. Run `./tweaks.sh -s` to connect your WhiteSur theme to your Snap apps

Hello, I ran the `./tweaks.sh -s` command in Ubuntu 22.04 LTS and I got the following error message:

![image](https://user-images.githubusercontent.com/90079777/225813413-697ab290-1d5e-457a-8ec9-c3a9c2d43c5c.png)
