### ISSUE TITLE
It's hard to read the text on top bar with light theme.

### ISSUE THREAD

**Issue by laichiaheng** [vinceliuice/WhiteSur-gtk-theme#13]
The texts blend with the background.
![2020-07-20 11-52-17 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/87898067-c8fe7c80-ca7f-11ea-9ce5-e244fe802895.png)

**Comment by christianbearslyclark** [comment]
try the alternative version. It's better  :)

**Comment by vinceliuice** [comment]
Now. it's ok, I added a black font color version
