### ISSUE TITLE
Add a blur to the DaskToDock dock

### ISSUE THREAD

**Issue by shreyas-jadhav** [vinceliuice/WhiteSur-gtk-theme#132]
Is it anyway possible to add blur or make the background color more darker after hovering on the dock? When I hover over the dock with an application open, it is too hard to distinguish between dock and the application. I would love to change the color of the dock on hover or add a shadow around it or make the application background blur so I can see the dock clearly.

**Normal dock:**
![image](https://user-images.githubusercontent.com/73429007/106993194-34036c80-67a0-11eb-8520-abe6eeb92dea.png)

**Dock while using an application:**   Can hardly see the border and the background text around the icons make it too messy
![image](https://user-images.githubusercontent.com/73429007/106993181-2817aa80-67a0-11eb-86e0-d1f96b01692a.png)

**Comment by kerrongordon** [comment]
You can try out this extension [blur-my-shell](https://extensions.gnome.org/extension/3193/blur-my-shell/)

**Comment by MinghuiZou** [comment]
You can change **line 128** of **~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css**
**for example:**
```css
#dashtodockContainer.dashtodock #dash {
  background: rgba(0, 0, 0, 0.5);
}
```

**Comment by snydox** [comment]
@MinghuiZou would this add blur to the dash to dock? I'm running GNOME 40 and when I enable Blur my shell the Dock looks squarish rather than rounded.

**Comment by vinceliuice** [comment]
Nope, blur my shell does not support any rouned dash style
