### ISSUE TITLE
GTK4 support

### ISSUE THREAD

**Issue by LeapofAzzam-backup** [vinceliuice/WhiteSur-gtk-theme#133]
The new GTK4 has been released. It was made for the new GNOME 4. Ubuntu also made it's Yaru theme supported by GTK4. Can we have a GTK4 theme, so we can use it on GNOME 4?

**Comment by vinceliuice** [comment]
I'll update it to gtk 4.0

**Comment by d0vi** [comment]
I guess this can be closed now @vinceliuice 🏆

**Comment by vinceliuice** [comment]
Yes, full support for gtk 4 now
