### ISSUE TITLE
--icon should change Dash icon as well.

### ISSUE THREAD

**Issue by renantmagalhaes** [vinceliuice/WhiteSur-gtk-theme#134]
Hi,

I believe the option --icon should also change the "Show applications" icon

[How its looks like](https://i.imgur.com/6h5oPYN.png)

I currently make the installation of this extensions using the following args

`sudo ~/WhiteSur-gtk-theme/install.sh -i void -o standard -t blue -g`

I`m trying to change the icon in the dash without success, there`s an extra arg to make this happen ?

**Comment by vinceliuice** [comment]
This can only change the icon on panel

**Comment by renantmagalhaes** [comment]
@vinceliuice There`s a way to also change the "Show applications" ? I think the GDM theme is replacing some default icons, and I cannot modify this.

**Comment by renantmagalhaes** [comment]
Just find the file, it is:
`/WhiteSur-gtk-theme/src/assets/gnome-shell/common-assets/view-app-grid.svg`
