### ISSUE TITLE
Background Color of the sidebar and items

### ISSUE THREAD

**Issue by Tuxman2** [vinceliuice/WhiteSur-gtk-theme#135]
Hello,

for now the sidebar in nautilus looks like that (for the colors):

![whitesurSidebar1](https://user-images.githubusercontent.com/23556606/108215133-e506f100-7128-11eb-91fe-df0dd114fd66.png)

I would like to see it looks like that (the picture come from another bigsur gtk theme):

![bigsur](https://user-images.githubusercontent.com/23556606/108215248-05cf4680-7129-11eb-9ac3-5741908075e3.png)

What lines I must modify in the .css file ?

I also want the background box color be less light and a little more dark. Where to modify it in the .css file ?

![WhiteSurBackground](https://user-images.githubusercontent.com/23556606/108215699-855d1580-7129-11eb-9693-a9a4d636acc4.png)

Thanks.

Regards.

**Comment by vinceliuice** [comment]
I use png pictures as the selected background image src/assets/gtk-3.0/common-assets/sidebar-assets.svg

**Comment by Tuxman2** [comment]
> I use png pictures as the selected background image src/assets/gtk-3.0/common-assets/sidebar-assets.svg

Ok, thanks for your reply. ;-) 

What Gnome extensions do you use with your theme ? I found two Gnome extensions to have: big-sur-menu (https://extensions.gnome.org/extension/3703/big-sur-menu/) and big-sur-status-area (https://extensions.gnome.org/extension/3708/big-sur-status-area/). The first one works very well with Gnome 3.38 (see my comment in the link). On the other side, the second works under Gnome 3.36 but not yet under Gnome 3.38. The guy who make the two extensions doesn't have update the second extension for Gnome 3.38, and so there is an issue (look here: https://github.com/Fausto-Korpsvart/Big-Sur-StatusArea/issues/1). It's too bad.

Regards.

**Comment by Tuxman2** [comment]
Hi,

I'm come back to you.

I searched in the source code of your gtk theme but I don't find the way to change the sidebar background color and the color of the items of the sidebar (home, documents, ....). I would that the sidebar looks like that:
https://user-images.githubusercontent.com/23556606/108215248-05cf4680-7129-11eb-9ac3-5741908075e3.png

I used the --nautilus-use-colors options to have the last style for the titlebar. The titlebar is white and I want to have the titlebar color like that:

![nautilustitlebar](https://user-images.githubusercontent.com/23556606/109159832-fecdb700-776c-11eb-9a03-dd84c14a35b4.png)

Can you help me to change these elements in your source code by myself ?

Thanks.

Note: Where to change the color background and the text color of the buttons when you have logged out of the session (cancel restart buttons, cancel shutdown buttons, ...) (it depends of the gnome shell theme) ?

Regards.

**Comment by Tuxman2** [comment]
You can close the subject, I switched to your Mojave gtk theme.
