### ISSUE TITLE
Icons error

### ISSUE THREAD

**Issue by FaisalAhmed123** [vinceliuice/WhiteSur-gtk-theme#136]
Whilst trying to use some of the icons, I get this error
`┌──(faisal071㉿hp-2540p-kali)-[~/Downloads/WhiteSur-gtk-theme-master]
└─$ ./install.sh -i Apple                                                   1 ⨯
   ERROR: Unrecognized icon variant 'Apple'. 
   Try './install.sh --help' for more information. 
                                                      `
![image](https://user-images.githubusercontent.com/59764708/108386401-84e57d00-7204-11eb-8560-58d4f013d5b3.png)

**Comment by vinceliuice** [comment]
Apple icon is the default one, there is no need to add this option when you run it
