### ISSUE TITLE
HDPI, XHDPI variants for xfwm4

### ISSUE THREAD

**Issue by shawnanastasio** [vinceliuice/WhiteSur-gtk-theme#137]
It would be nice to have a way to generate HDPI and XHDPI variants of the xfwm4 theme so the theme is usable on devices with a DPI higher than ~90. Xfce includes 3 variants of their own xfwm4 theme, but it's up to third-party themes to provide their own versions for HIDPI support.

**Comment by vinceliuice** [comment]
No problem!

**Comment by wuhanhui** [comment]
4k and 2K resolution are quite common now. Is that works now?

**Comment by zhouhaibing089** [comment]
Nice work!

I wonder whether it is a good idea to generate hdpi theme for gnome-shell (and gtk-3.0, maybe gtk-2.0?) as well (not just xfwm variants)? If that sounds good, I'm happy to contribute with some pointers.
