### ISSUE TITLE
"Activities" icon not working

### ISSUE THREAD

**Issue by applemonkey496** [vinceliuice/WhiteSur-gtk-theme#138]
I set `-i ubuntu` on installation, but even after <kbd>Alt</kbd><kbd>F2</kbd>, <kbd>r</kbd> and a full reboot, I don't see anything.

## Images
![image](https://user-images.githubusercontent.com/55333787/108446179-946bc280-7212-11eb-9afd-40b6a07d2a02.png)
___
**On hover:**

![image](https://user-images.githubusercontent.com/55333787/108448319-583a6100-7216-11eb-9168-5c96868a2ca9.png)

**Comment by vinceliuice** [comment]
What's you system version?

**Comment by applemonkey496** [comment]
I'm on Ubuntu 20.04. I am also using the most up-to-date version of the theme; I ran `git pull` and everything was up to date.

**Comment by vinceliuice** [comment]
I update it, Maybe you can download from github and try again!

**Comment by applemonkey496** [comment]
I updated it. Unfortunately no change. I am able to confirm, however, that hovering over where it would be gives the space a light fill and that clicking on it still works. Just no icon.

**Comment by vinceliuice** [comment]
Check this dir: `src/assets/gnome-shell/activities` if there are svg pictures here, and check the installed folder: `~/.themes/WhiteSur-light/gnome-shell/assets` if there is a `activities.svg` exist

**Comment by vinceliuice** [comment]
If this file missed then there must be something wrong when you install it

**Comment by applemonkey496** [comment]
In `src/assets/gnome-shell/activities` all the svg files are there and they look as intended. Also in `/usr/share/themes/Whitesur-light-solid-blue/gnome-shell/assets` there is an `activities.svg` file and it is indeed the Ubuntu logo. (There is also an `activities-white.svg` in that folder which is a white-themed Ubuntu logo.)

**Comment by applemonkey496** [comment]
I managed to find this message repeated several times in my `/var/log/syslog`:
```
Feb 20 00:41:00 desktop gnome-shell[1730]: Failed to load resource:///org/gnome/shell/theme/Yaru/assets/background.jpg: The resource at “/org/gnome/shell/theme/Yaru/assets/background.jpg” does not exist
```

**Comment by vinceliuice** [comment]
I‘ll fix this

**Comment by applemonkey496** [comment]
Ok thanks, that would be great! Do you know what's causing the issue?

**Comment by vinceliuice** [comment]
Need to correct the icon path in the Yaru/gnome-shell.css

**Comment by vinceliuice** [comment]
I updated the install.sh file you can try it again

**Comment by applemonkey496** [comment]
@vinceliuice almost forgot about this. Now, the theme only installs with the Apple logo, even if I pass `-i ubuntu` or something else. I tried uninstalling and reinstalling the GDM theme, but unfortunately that did not solve the problem.

**Comment by rivanfebrian123** [comment]
I'm working on this :+1:  Trying to fix it

**Comment by lfcutillas** [comment]
> @vinceliuice almost forgot about this. Now, the theme only installs with the Apple logo, even if I pass `-i ubuntu` or something else. I tried uninstalling and reinstalling the GDM theme, but unfortunately that did not solve the problem.
> (To clarify, I did AltFnF2+r to refresh after uninstall and reinstall.)

Same happens to me

**Comment by rivanfebrian123** [comment]
> > @vinceliuice almost forgot about this. Now, the theme only installs with the Apple logo, even if I pass `-i ubuntu` or something else. I tried uninstalling and reinstalling the GDM theme, but unfortunately that did not solve the problem.
> > (To clarify, I did AltFnF2+r to refresh after uninstall and reinstall.)
> 
> Same happens to me

Oh yeah, almost forget about this. Can anyone try this?: https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6183055/WhiteSur-gtk-theme-tested.zip

**Comment by rivanfebrian123** [comment]
Update: https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip
