### ISSUE TITLE
The text color of "Cap Lock is on" is not white in some cases

### ISSUE THREAD

**Issue by Brookg** [vinceliuice/WhiteSur-gtk-theme#139]
First of all, thanks for your work. It's great!

System version: `Ubuntu 20.04.2 LTS x64`
Gnome version: `3.36.8`
Window system: `X11`

When I log in for the first time after starting Ubuntu, the tip "Cap Lock is on"（“大写锁定已开启”） is like this:
![2021-02-20_14-25](https://user-images.githubusercontent.com/22161469/108586761-678eeb00-738b-11eb-92e9-a536f7449aae.png)

When I log in again after locking the screen , the style of tip "Cap Lock is on"（“大写锁定已开启”） is shown below:
![2021-02-20_14-27](https://user-images.githubusercontent.com/22161469/108587003-614d3e80-738c-11eb-879d-85c209fc5ab0.png)
The text color of "Cap Lock is on"（“大写锁定已开启”） is not white and looks not beautiful.

By the way, the text color of "Cap Lock is on"（“大写锁定已开启”） is not white on `authentication` dialog either:
![2021-02-20_14-44](https://user-images.githubusercontent.com/22161469/108587304-e38a3280-738d-11eb-924f-d497e835db07.png)

**Comment by vinceliuice** [comment]
好的，我会修复这个的
