### ISSUE TITLE
Black Border around Windows is problematic in fullscreen

### ISSUE THREAD

**Issue by zeparu** [vinceliuice/WhiteSur-gtk-theme#14]
![grafik](https://user-images.githubusercontent.com/21054889/88173330-abb5e380-cc22-11ea-8fa3-9e088e712cd5.png)
here is a screenshot of 2 windows maximized side by side, you can see where the black borders end / where the corners would be rounded

![grafik](https://user-images.githubusercontent.com/21054889/88173389-c9834880-cc22-11ea-839b-fd1fed386aeb.png)
issue is there too for just a single window, the black outline stops just short of the edge of the screen

**Comment by vinceliuice** [comment]
CSD have sharp corners

See upstream bug.
Wayland fix:

    Go to the about:config page
    Search for the layers.acceleration.force-enabled preference and set it to true.
    Now restart Firefox, and it should look good!

X11 fix:

    Go to the about:config page
    Type mozilla.widget.use-argb-visuals
    Set it as a boolean and click on the add button
    Now restart Firefox, and it should look good!
