### ISSUE TITLE
GDM login screen broken UI 

### ISSUE THREAD

**Issue by hotrungnhan** [vinceliuice/WhiteSur-gtk-theme#140]
power off button broken ui only in loginscreen , But after login in , it work well .
Isnt that isue come from your Themes ?
I was in ubuntu 20.04 
with whitesur gdm themes, whitesur cursor, Grub whitesur.
![IMG_20210220_205353](https://user-images.githubusercontent.com/40029631/108597910-fae11400-73bd-11eb-989c-d79325a6cd00.jpg)

**Comment by vinceliuice** [comment]
Reinstall it again, I test on my ubuntu but I don't have this issue, if this issue still exist you can run sudo ./install.sh -g -r to remove it

**Comment by hotrungnhan** [comment]
> Reinstall it again, I test on my ubuntu but I don't have this issue, if this issue still exist you can run sudo ./install.sh -g -r to remove it

i was did, default gdm is perfectly fine , but white sur was not . 
I use the master ver , instead of 15.1 ver 
could the isuee come from here ?

**Comment by rivanfebrian123** [comment]
Hi there, can you try https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip and see if it works? Installation command: `./tweaks.sh -g`

**Comment by fd6130** [comment]
> Hi there, can you try https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip and see if it works? Installation command: `./tweaks.sh -g`

The UI layout is broken when you apply system avatar or custom avatar to user account.

**Comment by rivanfebrian123** [comment]
> > Hi there, can you try https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip and see if it works? Installation command: `./tweaks.sh -g`
> 
> The UI layout is broken when you apply system avatar or custom avatar to user account.


Forwarding your image from https://github.com/vinceliuice/WhiteSur-gtk-theme/pull/168

![image](https://user-images.githubusercontent.com/6300910/114643254-85c7f600-9cff-11eb-8356-7c998531beb0.png)

It's GNOME Shell theme problem but it's related to GDM

Could you please try the "New framework" commit https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/65ebe753a16a420f2f924ab25de8dd91083a5d4f? If it fails, can you please try the "update" commit (a commit before "New framework") https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/0b25ab18d1f3be06802edf024bcb8e968563c303?

**Comment by rivanfebrian123** [comment]
But, the GDM theme itself is now okay, right?

**Comment by fd6130** [comment]
> But, the GDM theme itself is now okay, right?

Tried and still the same. Mostly is due to the GNOME Shell version problem. Perhaps you can try the GDM with GNOME version greater than 3.30 to see whether this problem will occurs or not?

**Comment by fd6130** [comment]
> > > Hi there, can you try https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip and see if it works? Installation command: `./tweaks.sh -g`
> > 
> > 
> > The UI layout is broken when you apply system avatar or custom avatar to user account.
> 
> Forwarding your image from #168
> 
> ![image](https://user-images.githubusercontent.com/6300910/114643254-85c7f600-9cff-11eb-8356-7c998531beb0.png)
> 
> It's GNOME Shell theme problem but it's related to GDM
> 
> Could you please try the "New framework" commit https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/65ebe753a16a420f2f924ab25de8dd91083a5d4f? If it fails, can you please try the "update" commit (a commit before "New framework") https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/0b25ab18d1f3be06802edf024bcb8e968563c303?

Tried and still the same. Mostly is due to the GNOME Shell version problem. Perhaps you can try the GDM at GNOME version greater than 3.30 to see whether this problem will occurs or not?

**Comment by fd6130** [comment]
> But, the GDM theme itself is now okay, right?

Yeah, the GDM did fix some of the issue except the Layout UI.
