### ISSUE TITLE
Text is over out/bad truncate the dialog box in Zorin OS 15.3 Core

### ISSUE THREAD

**Issue by fd6130** [vinceliuice/WhiteSur-gtk-theme#145]
![Screenshot from 2021-03-05 10-33-24](https://user-images.githubusercontent.com/11419744/110066302-18de4980-7dac-11eb-90e3-ed45666ae1f3.png)
![Screenshot from 2021-03-05 10-33-54](https://user-images.githubusercontent.com/11419744/110066307-1aa80d00-7dac-11eb-90fa-e593fdf1df37.png)

**Comment by fd6130** [comment]
#140 For the GDM, so far so good but just the avatar and username they both stick together made it looks weird.

**Comment by fd6130** [comment]
I think it is because of the fixed size dialog in this theme so the text go out of the dialog instead of go to the new line.

**Comment by rivanfebrian123** [comment]
![Screenshot from 2021-03-06 11-59-28](https://user-images.githubusercontent.com/6300910/110195925-7ee1d400-7e73-11eb-9293-e45cf7e8fda0.png)
Looks just normal here.


Distro: Manjaro, Theme: WhiteSur Light

**Comment by vinceliuice** [comment]
Earlier version of gnome-shell will have this issue

**Comment by fd6130** [comment]
> Earlier version of gnome-shell will have this issue

Ok... my gnome is 3.30.2 and the only option is to change to ubuntu 20.04 base?
