### ISSUE TITLE
The `--remove` command doesn't work

### ISSUE THREAD

**Issue by ghost** [vinceliuice/WhiteSur-gtk-theme#146]
So I'm new to this theme and I loved it very much and also this amazing. I always wanted to have Mac OS but I can't afford to it and buy the os also I don't have a PC that atleast runs GNOME. SO Im stuck with XFCE. But when I installed it it was good and tried 3 colors and wanted to have red. When I used `sudo ./install.sh -r -t green -g` it says `DONE!` but the theme is still visible in the manager and I can change to it. I tried to close the settings manager and open the themes menu again, it was still there and working. So now how do I remove the theme.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by rivanfebrian123** [comment]
> So I'm new to this theme and I loved it very much and also this amazing. I always wanted to have Mac OS but I can't afford to it and buy the os also I don't have a PC that atleast runs GNOME. SO Im stuck with XFCE. But when I installed it it was good and tried 3 colors and wanted to have red. When I used `sudo ./install.sh -r -t green -g` it says `DONE!` but the theme is still visible in the manager and I can change to it. I tried to close the settings manager and open the themes menu again, it was still there and working. So now how do I remove the theme.

Hi! Can you provide your distro version? I have tested the GDM theme removal (revert) on Manjaro and Ubuntu, and it worked just fine. Anyways, you can try `sudo ./install.sh -r -g` without `-t green` and see if it works

**Comment by thatkevin07** [comment]
> > So I'm new to this theme and I loved it very much and also this amazing. I always wanted to have Mac OS but I can't afford to it and buy the os also I don't have a PC that atleast runs GNOME. SO Im stuck with XFCE. But when I installed it it was good and tried 3 colors and wanted to have red. When I used `sudo ./install.sh -r -t green -g` it says `DONE!` but the theme is still visible in the manager and I can change to it. I tried to close the settings manager and open the themes menu again, it was still there and working. So now how do I remove the theme.
> 
> Hi! Can you provide your distro version? I have tested the GDM theme removal (revert) on Manjaro and Ubuntu, and it worked just fine. Anyways, you can try `sudo ./install.sh -r -g` without `-t green` and see if it works

I'm using Zorin 15. Lite Edition, I use lightdm. I thought the remove command will remove themes. I tried it by installing GDM too. Then found it didn't work with GDM also

2 problems now: Remove command doesn't work & GDM theme doesn't work upon installing.

BTW the best theme I have ever seen...

**Comment by rivanfebrian123** [comment]
Oh I see. So you just wanna delete the GTK theme only, right? Then run `sudo ./install.sh -r` and `./install.sh -r` to remove both system and user themes

**Comment by thatkevin07** [comment]
But I just manually deleted the theme, now my problem is that GDM theme
isn't working

First I installed them and then GDM

**Comment by rivanfebrian123** [comment]
The current version of WhiteSur installer doesn't actually support ZorinOS. See #145 

Anyways, in the mean time, you can try `sudo ./tweaks.sh -g -r` in my local repo here:
[WhiteSur-gtk-theme-Firefox-prep-Mar-19.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6170193/WhiteSur-gtk-theme-Firefox-prep-Mar-19.zip)

It's not ready to push to my Github repo since it will make tons of frustating merge conflicts. I would rather commit it **only** when it's ready

**Comment by thatkevin07** [comment]
Actually I said Qogir as the best theme, I removed whitsur and sat with
Qogir. That's nice. Anyways, I will check this out when it gets some better
support..

Thanks

**Comment by rivanfebrian123** [comment]
Don't forget to tell me if my installer works :D
Need your feedback

**Comment by thatkevin07** [comment]
Sure 😃
