### ISSUE TITLE
Gnome weather bottom corners (fix included)

### ISSUE THREAD

**Issue by edwinvandeven** [vinceliuice/WhiteSur-gtk-theme#15]
There seems to be some overflow in Gnome weather. Adding the css below to gtk-dark.css fixed it for the light theme.

```
#weather-page,
#weekly-forecast-frame {
	border-bottom-right-radius: 14px;
}

#weather-page-content-view {
	border-bottom-right-radius: 14px;	
	border-bottom-left-radius: 14px;
}
```

Before 
![Screenshot from 2020-07-22 22-19-25](https://user-images.githubusercontent.com/7576685/88224667-9f08ae00-cc69-11ea-80de-7b03c05686dd.png)

After
![Screenshot from 2020-07-22 22-19-53](https://user-images.githubusercontent.com/7576685/88224672-a039db00-cc69-11ea-817d-27db23cde9e2.png)

**Comment by vinceliuice** [comment]
Thanks!
