### ISSUE TITLE
This bar in trash folder looks broken (Gnome Files)

### ISSUE THREAD

**Issue by sowrensen** [vinceliuice/WhiteSur-gtk-theme#152]
Pretty self explanatory, I've added an screenshot which explains better. Also the contrast for the disabled **Restore** button should be improved.

![image12](https://user-images.githubusercontent.com/13097375/111189582-6e063080-85e0-11eb-9b36-b01454929ec8.png)

Thanks for your works anyway, I like most of your themes, both Plasma and Gnome. 👌

**Comment by rivanfebrian123** [comment]
Already fixed here: [WhiteSur-gtk-theme-backup-Apr-4.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip)

It'll be ready to merge tomorrow, insha Allah, after passing some tests
