### ISSUE TITLE
The title buttons in firefox donot work like title buttons of other applications

### ISSUE THREAD

**Issue by asif-hoda** [vinceliuice/WhiteSur-gtk-theme#153]
Well, according to the rest of your theme, only the particular title button that i will hover upon should get highlighted. But, in firefox(I am using the whitesur firefox theme), if i hover on any one one titlebutton, all the buttons get highlighted at once. This happens only in firefox. I have title bar off.

I am going to attach an image, so that its more clear.
Please fix this.
I have one more question - I had a friend that uses chrome. Is there a version of this firefox theme that works for chrome as well?
![IMg](https://user-images.githubusercontent.com/47708014/111312716-95fb9f80-8685-11eb-8362-2bf9e15fc2df.jpg)

**Comment by asif-hoda** [comment]
I think the title buttons are working like a single button performing different actions depending where it is pressed upon. I guess that is why all of the buttons are being highlighted if i bring my mouse close to them. They are not working like the title buttons do. I guess this is the reason why the title buttons look low res than title buttons and why they look bigger and seem to have more space between them. Please atleast fix the 'title buttons not working like title buttons of other applications' issue.

**Comment by asif-hoda** [comment]
I FIXED IT!! I just had to fix some mistakes in chrome/WhiteSur/parts/titlebutton-dark.css and had to change some names in chrome/WhiteSur/titlebuttons

**Comment by YasirRWebDesigner** [comment]
> I FIXED IT!! I just had to fix some mistakes in chrome/WhiteSur/parts/titlebutton-dark.css and had to change some names in chrome/WhiteSur/titlebuttons

If you could, please tell us as well what did you change?
