### ISSUE TITLE
nautilus sidebar

### ISSUE THREAD

**Issue by nmrcardoso** [vinceliuice/WhiteSur-gtk-theme#156]
Please can you add the sidebar of nautilus to be sizeable and color of sidebar be the same as we increase the area of the sidebar?
Now the theme looks odd for the sidebar

**Comment by rivanfebrian123** [comment]
Hi man! Are you ready to try this? https://github.com/rivanfebrian123/WhiteSur-gtk-theme

**Comment by nmrcardoso** [comment]
Thanks a lot @rivanfebrian123. 
That's amazing now :)
