### ISSUE TITLE
Customize the GDM screen with your WhiteSur-gtk-theme

### ISSUE THREAD

**Issue by Tuxman2** [vinceliuice/WhiteSur-gtk-theme#157]
Hello,

I would like to change some parts of the GDM screen with your WhiteSur-gtk-theme.

First, I want to get rid of the white color box when the user is selected by default. I made some search on the net, and it seems it depends on these lines:

.login-dialog-user-list:expand . login-dialog-user-list-item: selected { background-color: xxxx}
.login-dialog-user-list-item: loggin-in { solid numbercolor}.

I guess I must also disable the parts for 'hover' and the 'active' items ?

Second, I want to change the color of the buttons when I want to shutdown the system with the GDM screen. The cancel button is in grey and the shutdown button is in blue. I want the cancel button in green and when it is hover, it is highlight.

I modified your gdm3.css file but I don't see anything of my  changes when the gdm login screen is displayed. 

Can you help me ?

Thanks a lot.

**Comment by vinceliuice** [comment]
Modify this file gnome-shell-dark.scss(or gnome-shell.scss)

**Comment by Tuxman2** [comment]
> Modify this file gnome-shell-dark.scss(or gnome-shell.scss)

Ok, but I would like to change the color for the 'Cancel' button in the dialog box when we want to shutdown or restart the system in the GDM login screen. What is the part for this in the .css source code ? 
Another thing. The show-apps button (view-app-grid button) is highlight when it is pressed in the WhiteSur-gtk-theme, but it is not the case with the Mojave-gtk-theme. I don't want that the view-app-grid-button is highlight when it is pressed in the WhiteSur-gtk-theme. Where can I modify it ?

Thanks for your help.

Regards.

**Comment by Tuxman2** [comment]
Up !!!

I found a solution for the show-apps buttons. So it is solved. But I don't find the solution to change the color of the 'Cancel' button in the dialog box in the GDM login screen (who appears when restart or shutdown is selected).

Does it depends of the: '.login-dialog .modal-dialog-button:hover, .login-dialog .modal-dialog-button:focus' line or other line ?

Please, I really need your help to find a solution.

Thank you very much.

**Comment by vinceliuice** [comment]
.modal-dialog-linked-button:first-child

**Comment by Tuxman2** [comment]
Hi vinceliuice,

I had found a way to change the Gdm screen as I wanted before you posted your answer. But thanks for your answer.

I had to extract the gnome-shell-theme.gresource file,. change the gnome-shell.css file and then recompile it.

Now the Gdm screen looks like I want. ;-)

One last thing. I want to change the color of the text who say that the battery is full charged when I click on the battery icon on the taskbar. Do you know where I can modify the color line for that in your gnome-shell.css file ?

After that, you will can close this subject.

Thanks.

**Comment by vinceliuice** [comment]
That'll change all panel button color, battery icon can not be set separately

**Comment by Tuxman2** [comment]
> That'll change all panel button color, battery icon can not be set separately

Ok. I close this subject. ;-)
