### ISSUE TITLE
openSUSE Icon

### ISSUE THREAD

**Issue by in-famous-raccoon** [vinceliuice/WhiteSur-gtk-theme#159]
Hi Vince,

first of all, thank you for the really nice theme, i use both variants and i love it!
I am running openSUSE and it has zero problems except the nautilus sidebar, but i fixed this with ./install.sh -s 280.

Would it be possible to add an openSUSE icon for the gnome-shell activities icon?

Thank you and stay safe. :smiley:

**Comment by vinceliuice** [comment]
No problem!
