### ISSUE TITLE
Titlebar buttons dont work in some apps

### ISSUE THREAD

**Issue by tejasag** [vinceliuice/WhiteSur-gtk-theme#161]
HI, i am using this theme in Ubuntu and it is working perfectly except for the fact that some apps are not getting the expected title bar buttons.

Like discord & Spotify:
![image](https://user-images.githubusercontent.com/67542663/112715133-b557bf80-8f04-11eb-93dd-f2e3d5339b48.png)

**Comment by rivanfebrian123** [comment]
It that Snap app or native app?
