### ISSUE TITLE
dash-to-dock error "stylesheet.css does not exist"

### ISSUE THREAD

**Issue by kidney-bean** [vinceliuice/WhiteSur-gtk-theme#164]
I am trying to install the dash to dock but i get the error "stylesheet.css does not exist". I have checked and the file exists and has stuff in it. What am I doing wrong?

**Comment by rivanfebrian123** [comment]
Can you try this?
[WhiteSur-gtk-theme-backup-Mar-30.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6225220/WhiteSur-gtk-theme-backup-Mar-30.zip)


Use `./tweaks.sh -d` to install Dash to Dock theme


It'll be ready to merge in a week. Insha Allah

**Comment by irvadesigner** [comment]
I tried this way and it works,

1. cd ~/.local/share/gnome-shell/extensions/
2. mkdir dash-to-dock@micxgx.gmail.com
3. cp /path/to/css/ ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com
4. Run install.sh script inside dash-to-dock folder

Hope it help!

**Comment by rivanfebrian123** [comment]
> I tried this way and it works,
> 
>     1. cd ~/.local/share/gnome-shell/extensions/
> 
>     2. mkdir [dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)
> 
>     3. cp /path/to/css/ ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com
> 
>     4. Run install.sh script inside dash-to-dock folder
> 
> 
> Hope it help!

Jadi gini, kan installer yang sekarang di master masih belum bisa ngedeteksi ini si `stylesheet.css` ini ditaroh di mana. Apa di home atau root (sistem). Nah, kalo caranya Mas udah bagus, cuman itu cuma bekerja kalo Dash to Docknya nginstall sendiri (gak pake root). Kalo Dash to Docknya bawaan kek Manjaro beda lagi ceritanya.

BTW, banyak juga ya orang Indo pake nih tema :)

**Comment by irvadesigner** [comment]
Iya mas, saya suka theme nya krn clean jadi enak bgt pas buka laptop mata jadi seger. Salam kenal mas Rivan, semoga sukses selalu :)

**Comment by rivanfebrian123** [comment]
Hehe... salam kenal juga

> semoga sukses selalu :)

Aamiin...

**Comment by rivanfebrian123** [comment]
Mas, maaf, masnya sibuk gak nih?

**Comment by irvadesigner** [comment]
Iya mas, ada apa? Belum terlalu sibuk sih mas. Mas mau nanya apa?

**Comment by rivanfebrian123** [comment]
Mas mau software tester gitu ngga? Jadi mas bantu kita ngetes fitur2 WhiteSur ke berbagai macam distro, tapi santai aja kok, ga usah buru2 amat

**Comment by irvadesigner** [comment]
Boleh mas, kasi aja list distro yang jadi main target selain Ubuntu apa
aja. ;)

**Comment by rivanfebrian123** [comment]
Wah, makasih mas. Kita mulai seminggu lagi sih... ngerjainnya tiap weekend aja :D Btw, masnya ada discord ngga? Kapan2 kita ngobrol bareng sama temen aku @Musshal

**Comment by irvadesigner** [comment]
Sama² mas, senang bisa membantu. Saya ga ada discord mas, yg ada slack,
telegram, WA, zoom (kadang² aja). Kalo minggu depan saya belum bisa mas,
karena hari raya di Bali, 2 minggu lagi boleh mas?

**Comment by ReneSpies** [comment]
I have the same issue as @kidney-bean. Moving the `stylesheet.css` into the new directory does not work and neither does the `March-backup`. Also, please keep your conversations in English so people like me can fix the error in threads like these.

**Comment by irvadesigner** [comment]
> I have the same issue as @kidney-bean. Moving the `stylesheet.css` into the new directory does not work and neither does the `March-backup`. Also, please keep your conversations in English so people like me can fix the error in threads like these.

My apologize for not using English. To fix your problem please follow this steps:

1. Go to https://extensions.gnome.org/extension/307/dash-to-dock/ with your firefox web browser
2. Right underneath the web menu you will find "Click here to install browser extension" click this link and follow installation instruction to install Firefox extension
3. Once you done installing you will see button like images below, then switch the button to on. 
![Screenshot from 2021-04-07 02-47-24](https://user-images.githubusercontent.com/44344728/113762938-b0d4a780-974b-11eb-994d-4acbedaa4787.png)
4. Open terminal and run install.sh inside dash-to-dock folder which is located under WhiteSur-gtk-theme > src > other by typing this command ./install.sh, reboot your machine once done

PS: if you want to personalize dash to dock appearance you can install Gnome Tweak app, simply run this command: sudo apt update && sudo apt install gnome-tweaks. You can find setting for dash to dock right inside Extensions menu and to personalize it appearance you can click on Gear Icon.

Hope this help

**Comment by rivanfebrian123** [comment]
@ReneSpies 

> Moving the `stylesheet.css` into the new directory does not work and neither does the `March-backup`
Could you please describe your distro and DE, sir?

> Also, please keep your conversations in English so people like me can fix the error in threads like these.
Hehe... I'm sorry :)
