### ISSUE TITLE
[bug] Unmount button is in wrong place // sidebar width size doesnt change all setting

### ISSUE THREAD

**Issue by danieltomasz** [vinceliuice/WhiteSur-gtk-theme#165]
I tried to change the Nautilus sidebar width size, now the unmount button is displayed in the wrong place
I am on PopOS 20.10, Gnome 3.38.3 with PopShell plugin, I am using Ultrawide monitor
![image](https://user-images.githubusercontent.com/7980381/112909527-ea753500-90f1-11eb-8f74-78805c09a5b5.png)

The unmount button is tied to the body of the file manager, not the sidebar - manipulating the width of the body moves the button to the right place, but this is unexpected behaviour for me.

![image](https://user-images.githubusercontent.com/7980381/112910307-64f28480-90f3-11eb-8bea-961c21d9e4c1.png)

**Comment by rivanfebrian123** [comment]
Can you try this?
[WhiteSur-gtk-theme-backup-Mar-30.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6225220/WhiteSur-gtk-theme-backup-Mar-30.zip)

It'll be ready to merge in a week. Insha Allah

**Comment by danieltomasz** [comment]
Thanks! I  was able to  force sidebar to look good
You probably know that using  when Installing GDM theme it gives an error
```
`  ERROR: Unrecognized installation option '-g'.
```

**Comment by rivanfebrian123** [comment]
Oh, forgot about that :D


GDM installation is now seperated from `install.sh`. Use` ./tweaks.sh -g` instead. You can also change your background, make it darker, and make it blur or not. Run` ./tweaks.sh -h` to explore more features!
