### ISSUE TITLE
Linux Mint 20 Panel Modals transparency issue

### ISSUE THREAD

**Issue by reynaldoa76** [vinceliuice/WhiteSur-gtk-theme#17]
When clicking on the Menu or calendar everything is 100% transparent.
![panel_modal_issue](https://user-images.githubusercontent.com/67919838/88343565-abdfdd00-cd0f-11ea-9cf4-5f99998f2b28.png)

Is there a way to fix this? I installed all the dependencies.

**Comment by vinceliuice** [comment]
I'll fix this!
