### ISSUE TITLE
Error: The selector"%osd_panel" was not found.

### ISSUE THREAD

**Issue by fd6130** [vinceliuice/WhiteSur-gtk-theme#173]
This issue occur when i pull the latest branch and execute `./install.sh` in Zorin OS. I think mostly is because of incompatible gnome version?

```
Installing 'WhiteSur' themes in '/home/fd6130/.themes'...
  --->>> GTK | GNOME Shell | Cinnamon | Metacity | XFWM | Plank <<<---
  Color variants   : dark;light
  Theme variants   : default
  Opacity variants : normal;solid
  Alt variants     : normal
  Icon variant     : standard
  Nautilus variant : default

                             ••••     Error: ".resize-popup" failed to @extend "%osd_panel".
       The selector "%osd_panel" was not found.
       Use "@extend %osd_panel !optional" if the extend should be able to fail.
        on line 58 of src/sass/gnome-shell/common/_osd.scss
>>   @extend %osd_panel;
   ----------^
Error: ".resize-popup" failed to @extend "%osd_panel".
       The selector "%osd_panel" was not found.
       Use "@extend %osd_panel !optional" if the extend should be able to fail.
        on line 58 of src/sass/gnome-shell/common/_osd.scss
>>   @extend %osd_panel;
   ----------^
                         ••••         Error: ".resize-popup" failed to @extend "%osd_panel".
       The selector "%osd_panel" was not found.
       Use "@extend %osd_panel !optional" if the extend should be able to fail.
        on line 58 of src/sass/gnome-shell/common/_osd.scss
>>   @extend %osd_panel;
   ----------^
Error: ".resize-popup" failed to @extend "%osd_panel".
       The selector "%osd_panel" was not found.
       Use "@extend %osd_panel !optional" if the extend should be able to fail.
        on line 58 of src/sass/gnome-shell/common/_osd.scss
>>   @extend %osd_panel;
   ----------^
                             ••••     
  Done!

  Run './install.sh --help' to explore more customization features!
```

**Comment by rivanfebrian123** [comment]
In which version? Can you please mention it? Check https://github.com/vinceliuice/WhiteSur-gtk-theme/commits/master

@vinceliuice I think we need to create a branch for every feature development (probably every month), for example, WhiteSur-4-21, where 4 stands for April and 21 stands for 2021, instead of delivering sudden changes to the users by directly commit to the master branch

**Comment by fd6130** [comment]
> In which version (commit)? Can you please mention it? Please check https://github.com/vinceliuice/WhiteSur-gtk-theme/commits/master :)
> 
> @vinceliuice I think we need to create a branch for every feature development (probably every month), for example, WhiteSur-4-21, where 4 stands for April and 21 stands for 2021, instead of delivering sudden changes to the users by directly commit to the master branch

f1ab2ebb434e00b48b2bcfe6b2b06f41dd9e4e6d

**Comment by vinceliuice** [comment]
Try the last update again, I updated it, it runs all right on my fedora gnome 40

**Comment by fd6130** [comment]
> Try the last update again, I updated it, it runs all right on my fedora gnome 40

Ok, the issue has been solved.
