### ISSUE TITLE
Corners of window are not rounded when window is maximized

### ISSUE THREAD

**Issue by xidddekate** [vinceliuice/WhiteSur-gtk-theme#174]
Hope you fix it !
Overall theme is fantastic

**Comment by vinceliuice** [comment]
Just run `./install.sh --round`

**Comment by xidddekate** [comment]
Thanks man...
But --round option works only for file explorer on ubuntu. All other apps are still facing rounded corners issue

**Comment by xidddekate** [comment]
only inbuilt system apps has rounded corners. The existing apps on my system like vs code, pycharm,etc  dont have rounded corners

**Comment by vinceliuice** [comment]
Only CSD app can have bottom rounded coners, those app are not GTK app don't use default CSD window, gnome does not support  that, I just can't do anything about this

**Comment by xidddekate** [comment]
Ohk got it !
Once again I appreciate your sincere efforts.

Cheers

**Comment by vinceliuice** [comment]
Thank you!
