### ISSUE TITLE
Blur popups even when -o solid chosen.

### ISSUE THREAD

**Issue by Jazzhoo** [vinceliuice/WhiteSur-gtk-theme#175]
Hi, I realized that some pop-ups like Libreoffice "save" / "close without saving" / "cancel" or cinnamon's "restart/shutdown/sleep" are semi transparent even with -o solid chosen.

Cinnamon 4.8.6
Libreoffice 7.1.1

**Comment by rivanfebrian123** [comment]
![Screenshot from 2021-04-09 16-26-34](https://user-images.githubusercontent.com/6300910/114159812-6708de80-9950-11eb-9f24-14ea67b46a4c.png)


```
  Removing the old 'WhiteSur' themes...

  Installing 'WhiteSur' themes in '/home/rivanfebrian123/.themes'...
  --->>> GTK | GNOME Shell | Cinnamon | Metacity | XFWM | Plank <<<---
  Color variants   : dark;light
  Theme variants   : default
  Opacity variants : solid
  Alt variants     : normal
  Icon variant     : standard
  Nautilus variant : default

                         ••••         
  Done!

  Run './install.sh --help' to explore more customization features!
```

No, it's no a "me too". I'm just giving a more info for other developers

**Comment by vinceliuice** [comment]
I'll fix this!
