### ISSUE TITLE
Nautilus top left corner is transparent

### ISSUE THREAD

**Issue by lucanello** [vinceliuice/WhiteSur-gtk-theme#177]
After updating the whitesur-gtk-theme package on my Ubuntu Budgie Desktop, Nautilus top left corner became transparent.

```
$ sudo apt-cache showpkg whitesur-gtk-theme 
Package: whitesur-gtk-theme
Versions: 
20210408-0ubuntu1~focal (/var/lib/apt/lists/ppa.launchpad.net_ubuntubudgie_backports_ubuntu_dists_focal_main_binary-amd64_Packages) (/var/lib/apt/lists/ppa.launchpad.net_ubuntubudgie_backports_ubuntu_dists_focal_main_binary-i386_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ppa.launchpad.net_ubuntubudgie_backports_ubuntu_dists_focal_main_binary-amd64_Packages
                  MD5: b841ae1d0db931cd9c7b9c7ed39079e5
 Description Language: en
                 File: /var/lib/apt/lists/ppa.launchpad.net_ubuntubudgie_backports_ubuntu_dists_focal_main_i18n_Translation-en
                  MD5: b841ae1d0db931cd9c7b9c7ed39079e5


Reverse Depends: 
Dependencies: 
20210408-0ubuntu1~focal - gtk2-engines-murrine (0 (null)) gtk2-engines-pixbuf (0 (null)) 
Provides: 
20210408-0ubuntu1~focal - 
Reverse Provides:
```

![image](https://user-images.githubusercontent.com/1607904/114269862-7861f180-9a09-11eb-8b4c-926d2d54f222.png)

**Comment by vinceliuice** [comment]
Please install frome github, already fixed this issue

**Comment by lucanello** [comment]
> Please install frome github, already fixed this issue

Thanks for your fast response. Even if I remove the apt-package and install the latest version from GitHub, this issue appears. How can I fix it?

**Comment by vinceliuice** [comment]
Wha

**Comment by vinceliuice** [comment]
You need to download from master https://github.com/vinceliuice/WhiteSur-gtk-theme/archive/refs/heads/master.zip

**Comment by vinceliuice** [comment]
Not last release

**Comment by vinceliuice** [comment]
Then run ./install.sh

**Comment by lucanello** [comment]
> What's your system and gnome version?

```
$ uname -a
Linux luca-desktop 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>8</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version>
```

**Comment by vinceliuice** [comment]
gnome 3.36?

**Comment by vinceliuice** [comment]
OK! I'll download this system and test it

**Comment by lucanello** [comment]
> gnome 3.36?

Yeah seems so. Should the bug be fixed as soon as I execute the install script? Or do I need to refresh the window provider? Even after installing with the latest master from Git, it didn't change.

**Comment by lucanello** [comment]
Something is really wrong, I feel like any changes I do with the script doesn't change the appearance.

**Comment by vinceliuice** [comment]
After relogin your desktop if it still have this issue, then there must be something wrong, anyway I'll test this theme on that system

**Comment by lucanello** [comment]
I think I fixed it. I installed the theme to `/usr/share/themes` and switched it in the Ubuntu Budgie Desktop settings so it is reloaded. Not sure if the system-wide installation is required or if the switching did its thing, but it works now. Thank you!
One problem, which I believe was also already fixed, is still there though: the sidebar in Nautilus doesn't properly resize when changing the width.

**Comment by vinceliuice** [comment]
You can try './install.sh -N default' to install the alt version this can resize, or './install.sh -N mojave' to install mojave style nautilus version

**Comment by canadrian72** [comment]
Hi there, I'm facing the same exact issue. I tried downloading from the master branch @vinceliuice linked and reinstalling but no luck there. @lucanello how exactly did you install it into `/usr/share/themes`? Did you just set this as your destination for the installer?

**Comment by fossfreedom** [comment]
> Please install frome github, already fixed this issue

I am going to try to update the ubuntu budgie package to the latest version.  Unfortunately the install routines that have changed in the latest version is breaking the debian package build.  I am going to have to unpick the changes to find out why.

**Comment by vinceliuice** [comment]
@fossfreedom Install.sh file have changed a lot to get better Installation performance

**Comment by canadrian72** [comment]
So no current fix for the blank left corner? I am also getting overlapping buttons on the top right of nautilus as follows.

![image](https://user-images.githubusercontent.com/47571939/116785302-e62c9680-aa66-11eb-9882-f8752d4cac7d.png)

**Comment by rivanfebrian123** [comment]
@canadrian72 Can you provide your installation info, please. I mean, where did you install it from? Debian/Ubuntu package? Our "stable" (Pling) release? Or, this repo (`./install.sh`)?

**Comment by canadrian72** [comment]
Yes of course, sorry. I am on Ubuntu 20.10. I have tried installing WhiteSur from the snap store, from the master branch, and from [the zip linked above](https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/177#issuecomment-817153818). Beyond this, neofetch below for general system specs. Only weird thing I see here is that WM theme isn't WhiteSur, but I'm not sure if this is expected behavior.

![image](https://user-images.githubusercontent.com/47571939/116787098-30fedc00-aa70-11eb-8da1-a0dbde4ac5d2.png)

**Comment by vinceliuice** [comment]
I'll test on ubuntu 20.10

**Comment by canadrian72** [comment]
Just to follow up, I experience this issue on WhiteSur Dark only. WhiteSur dark-solid, WhitSur light, and WhiteSur light-solid do not have this issue. So for now, I am okay with using WhiteSur dark-solid as it looks amazing and fixes that small nautilus bug; I am okay if this is not fixed. Thank you for this amazing theme and for all the hard work you do! Cheers.
