### ISSUE TITLE
Linked firefox theme does not exist

### ISSUE THREAD

**Issue by TheExistingOne** [vinceliuice/WhiteSur-gtk-theme#18]
In the README you link a firefox theme that seems to not currently be in the repository. 
![image](https://user-images.githubusercontent.com/49994945/88337450-9c4e9d00-cceb-11ea-8bf2-5298bcc14740.png)
![image](https://user-images.githubusercontent.com/49994945/88337584-cd2ed200-cceb-11ea-8f62-ee403e32e381.png)

**Comment by vinceliuice** [comment]
Now! it's ok! firefox theme is finished!
