### ISSUE TITLE
Gnome Shell 3.38 font size increased in last couple days?

### ISSUE THREAD

**Issue by zeparu** [vinceliuice/WhiteSur-gtk-theme#182]
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/062b643627e6f42f10aa9b7607eabb2855f0d9a4/src/sass/_variables.scss#L16

this was added in a commit about 3 days ago, and recently it feels like the font size in she shell has been a little bigger than it used to be?

was that intentional or maybe just a mistake, right now the font of the shell is visibly bigger than the font on my normal programs

**Comment by vinceliuice** [comment]
I change it back

**Comment by zeparu** [comment]
the update that u did didnt really fix it for me

**however**, installing the GDM theme changes the font in the panel, and the font size too.

Is the Shell theme not overwriting some font, and it will fallback to the GDM-theme's font?

this is all happening in 3.38 gnome shell by the way

**Comment by vinceliuice** [comment]
Did you installed some 3rd Gdm theme already? then that would the reason, because theme code have different priority

**Comment by zeparu** [comment]
no, was using vanilla gnome-shell gdm-theme

**Comment by zeparu** [comment]
with default GDM theme
![image](https://user-images.githubusercontent.com/21054889/114703311-65ab2d80-9d25-11eb-9917-2fd15b4215dd.png)

with whitesur GDM theme
![image](https://user-images.githubusercontent.com/21054889/114703386-82dffc00-9d25-11eb-8a76-1622a302167b.png)

even some icons are different here

**Comment by vinceliuice** [comment]
Notifications icon is in Gdm theme, gnome-shell theme can not change that

**Comment by zeparu** [comment]
good to know

but the font sizes are still different too, especially looking at "No Events" and "Do Not Disturb", you can easily see the difference

**Comment by vinceliuice** [comment]
I can try to add some code to reset, but in some places, the Gdm theme still has a higher priority than the gnome-shell theme
