### ISSUE TITLE
Size of close button in Overview

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#183]
After the recent release, I noticed that the size of the close button in Overview has got scaled up too much. It looks so wrong and out of place as well. I would like to know if that's something by design or a bug.

![Close button size](https://user-images.githubusercontent.com/38633812/114314621-dc251100-9b14-11eb-8790-93a593b66da0.png)

**Comment by vinceliuice** [comment]
What's your gnome-shell version？

**Comment by saaditory** [comment]
> What's your gnome-shell version？

I'm using GNOME 3.36.8 on Ubuntu 20.04.2 LTS.

**Comment by vinceliuice** [comment]
I think this is fixed

**Comment by saaditory** [comment]
Yes, it is fixed now. Thanks for your great work!

![image](https://user-images.githubusercontent.com/38633812/115066852-88963700-9f09-11eb-9cb1-5290f2bd3951.png)
