### ISSUE TITLE
关于“显示桌面”按钮的背景色

### ISSUE THREAD

**Issue by xpume** [vinceliuice/WhiteSur-gtk-theme#184]
有一个问题想请教：
我用的是`Fedora`发行版，`MATE`桌面，使用`WightSur-light`作为控件，发现`显示桌面`按钮的背景色是白色，与面板的背景色不同，比如：当面板设置为半透明时，`显示桌面`按钮的背景色还是白色，请问要怎么改一下，才能使面板背景色与`显示桌面`按钮的背景色始终保持统一呢？非常感谢！
![WhiteSure-light_Menta](https://user-images.githubusercontent.com/22957642/114489811-5bfec880-9c46-11eb-99dd-aba02600165f.gif)
我的`显示桌面`按钮在上图GIF的右下角。
![show-desktop](https://user-images.githubusercontent.com/22957642/114490581-b0ef0e80-9c47-11eb-92db-5fbccc2a4e2a.jpeg)

**Comment by stepbystep2** [comment]
我的`显示桌面`按钮在上图GIF的右下角。

**Comment by kernelb00t** [comment]
Please speak English here, not all contributors speak Chinese :wink: (and Google Translate/traduction services aren't very useful to understand specific issues).
