### ISSUE TITLE
Wifi & Sign out Menu Always BOLD

### ISSUE THREAD

**Issue by xpec-rojas** [vinceliuice/WhiteSur-gtk-theme#185]
Hello,

I have this issue, the theme seems to be font weight light, but this area and the notifications are always showing as bold:

![image](https://user-images.githubusercontent.com/30267047/114500817-74db8f80-9bee-11eb-879d-c0a5bf63315e.png)

This happened once I installed the GDM theme.

Also I want to know which var I need to modify to separate the dock from the maximized border-bottom windows and have the same margin-bottom to the margin-top:

![image](https://user-images.githubusercontent.com/30267047/114500944-a5bbc480-9bee-11eb-9194-e96938e27ccc.png)

THanks

**Comment by xpec-rojas** [comment]
![image](https://user-images.githubusercontent.com/30267047/114501011-c2f09300-9bee-11eb-88d5-49c018d939e1.png)

It seems is displaying everywhere as bold.

**Comment by vinceliuice** [comment]
Could you tell me your Gnome-shell version?

**Comment by xpec-rojas** [comment]
GNOME Shell 3.36.7

**Comment by xpec-rojas** [comment]
Any updates about this? What do I need to do with my system to make it work or do i need to wait for an update by your side? Thanks

**Comment by vinceliuice** [comment]
You can try the last update

**Comment by xpec-rojas** [comment]
![image](https://user-images.githubusercontent.com/30267047/114809346-9ca63100-9d6f-11eb-88d2-580b4d7acb17.png)

Working fine. Thanks.

What about the Dock? How can i increase the margin? To make the margin-top equal to the margin-bottom? (That is separated from the border bottom of the screen, so it will be equally separated from the border bottom of the screen AND border bottom of the maximized apps)

**Comment by vinceliuice** [comment]
Still testing!
