### ISSUE TITLE
Chinsese Pinyin is not visible during typing in WhiteSur-dark or WhiteSur-dark-solid

### ISSUE THREAD

**Issue by fd6130** [vinceliuice/WhiteSur-gtk-theme#186]
Sorry my english rip 100% so i will type two language to describe my issue..

字体黑色导致中文输入法输入的时候 (选字) 会看不见任何字。

The character from pinyin is not visible because of the black color character.

**Comment by vinceliuice** [comment]
我是中国人，你可以直接打汉字

**Comment by vinceliuice** [comment]
我需要知道你的gnome-shell版本或者系统版本，有截图的话更好

**Comment by vinceliuice** [comment]
我知道问题所在了，很快就能修复

**Comment by fd6130** [comment]
> 我知道问题所在了，很快就能修复

好的 感谢你。 现在打字都靠猜选的 哈哈哈。

**Comment by vinceliuice** [comment]
修复了
