### ISSUE TITLE
dash to dock launchpad icons not displayed properly with latest of Whitesur

### ISSUE THREAD

**Issue by kimlulz** [vinceliuice/WhiteSur-gtk-theme#188]
![스크린샷, 2021-04-14 14-22-58](https://user-images.githubusercontent.com/42508318/114658687-3e585e80-9d2d-11eb-8b9f-bc185648e5d0.png)

after update latest of Whitesur, icons in launchpad (Dash to dock) Not displayed properly..

**Comment by rivanfebrian123** [comment]
It's the same issue as #187 and it's already fixed in the latest commit. Can you install the latest update, please, and tell us if that work?

**Comment by vinceliuice** [comment]
I've fixed this

**Comment by kimlulz** [comment]
Solved. Thanks!
