### ISSUE TITLE
Activities closing animation breaks

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#189]
Activities closing animation breaks while the opening animation works fine.

*With GDM+Shell Theme*

https://user-images.githubusercontent.com/38633812/114853700-7fb83f00-9dfd-11eb-8451-673b379a70fc.mp4

*Without GDM+Shell Theme*

https://user-images.githubusercontent.com/38633812/114853718-82b32f80-9dfd-11eb-9ded-5da291b46f7b.mp4

I'm running GNOME 3.36.8.

**Comment by chasebros** [comment]
Same issue here, and its messed some other things up as well.  How would one go about fully uninstalling? Not just the icons and theme but the system changes as well. Removing everything, thanks!

**Comment by chasebros** [comment]
Is this resolved? Thanks @vinceliuice :)

**Comment by vinceliuice** [comment]
I add some transitions and test on my ubuntu20.04 on vm, it's ok now, but I did not test on a real pc

**Comment by chasebros** [comment]
I'll test it tomorrow and get back! Your the man @vinceliuice love the theme!!

**Comment by vinceliuice** [comment]
OK!👌

**Comment by saaditory** [comment]
Hey @vinceliuice, It's not fixed for me yet and still behaves the same.

**Comment by noobmyq** [comment]
Exactly the same issue on gnome 3.36, ubuntu 20.04 lts
