### ISSUE TITLE
 When the mouse passes over the left column of nautilus, the background does not refresh

### ISSUE THREAD

**Issue by Hoking007** [vinceliuice/WhiteSur-gtk-theme#19]
![image](https://user-images.githubusercontent.com/55968385/88354904-1424d200-cd95-11ea-8922-aa14a6eac77b.png)

Problem: When the mouse passes over the left column of nautilus, the background does not refresh
I have two computers with Ubuntu 20.04 installed, Gnome version is 3.36.3, but one computer is normal, and the other has problems as above

**Comment by HugoLiconV** [comment]
![Screenshot from 2020-07-29 08-34-46](https://user-images.githubusercontent.com/22970186/88813734-8707c180-d176-11ea-9f62-5de6077a84c6.png)

I don't know if it's the same bug, but the left column keeps the items highlighted when I pass the mouse over.

**Comment by Hoking007** [comment]
> ![Screenshot from 2020-07-29 08-34-46](https://user-images.githubusercontent.com/22970186/88813734-8707c180-d176-11ea-9f62-5de6077a84c6.png)
> 
> I don't know if it's the same bug, but the left column keeps the items highlighted when I pass the mouse over.

Yes we have the same problem.

**Comment by juxuanu** [comment]
This bug is still happening with Gnome 3.36.4-1

**Comment by tortoise10h** [comment]
The bug is still happening to me when I download 16-8-2020 version

**Comment by vinceliuice** [comment]
I fixed it at solid version, transparency sidebar version still can not be fixed, this is a issue about Nvidia drivers
