### ISSUE TITLE
Dash to dock install is broken

### ISSUE THREAD

**Issue by carlosala** [vinceliuice/WhiteSur-gtk-theme#190]
Hi!
I have all the requiered and optional dependencies installed in Debian, and when I try to run `./tweaks.sh -d` or `./tweaks.sh -d -c dark` appears the error message `Oops! Operation has been canceled or failed...`.
There are no logs, so I cannot paste here.
Does anyone know any solution?

**Comment by rivanfebrian123** [comment]
Can you please try the earlier version to see if it work? https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/65ebe753a16a420f2f924ab25de8dd91083a5d4f

**Comment by carlosala** [comment]
No, it doesn't work for me.

**Comment by vinceliuice** [comment]
Tell me you gnome-shell version and your dash-to-dock version, and last tell me the way you installed dash-to-dock

**Comment by rivanfebrian123** [comment]
Is it the newly installed Debian? I think there's a problem with your `sudo`. Probably you forgot to configure it. Anyway, can you please try another command like `sudo ls`?

**Comment by carlosala** [comment]
No, there is no problem with sudo. I tried also to run `./tweaks.sh -d` as sudo, and the same error. I also tried to run a command before as sudo, to prevent `./tweaks.sh -d` to ask for the password.
Gnome Shell: `3.38.4`
Dash to dock `69`

**Comment by carlosala** [comment]
I think that it install the theme although the script finishes with an error. I tried to install the dark one and after the light one and it changes, but it's very anoying to have this error message. Maybe you should revise the script after the installation.

**Comment by rivanfebrian123** [comment]
Thanks for your bug report. Would be appreciated if you can help us to hunt more bugs and do some quality check :)

**Comment by carlosala** [comment]
For sure, thanks for your work!
