### ISSUE TITLE
XFCE Notification button very barely readable.

### ISSUE THREAD

**Issue by el3ctr0lyte** [vinceliuice/WhiteSur-gtk-theme#192]
On xfce, when i get a notification with a button, the button is barely visible. Especially in normal indoors daylight. This is only the light theme and it affects the latest version. The button can be seen when you hover over it, but it doesn't help if you don't notice that there is a button to begin with. Strangely enough, on the dark theme, the button text color and the notification text color seems to be the same.

Here is an example:
![light-button-label](https://user-images.githubusercontent.com/69082962/115161905-87e3d900-a0a0-11eb-959d-f3d378a806dc.png)

It would be greatly appreciated if you can improve the contrast of the button a bit. Maybe by making the text darker? Or making the actual button a bit darker?

Other than that i think you did a fantastic job with this theme! I love it very much!

**Comment by codic12** [comment]
Also, when hovering over icons in xfce4-panel, at least in the dark version, it leaves a lingering effect where the item hovered over stays hovered over but dimmed for a while.

**Comment by codic12** [comment]
(at least ni the dark theme).

**Comment by codic12** [comment]
sorry, it seems to be gone after a restart of the xfce4-panel.

**Comment by rivanfebrian123** [comment]
> On xfce, when i get a notification with a button, the button is barely visible. Especially in normal indoors daylight. This is only the light theme and it affects the latest version. The button can be seen when you hover over it, but it doesn't help if you don't notice that there is a button to begin with. Strangely enough, on the dark theme, the button text color and the notification text color seems to be the same.
> 
> Here is an example:
> ![light-button-label](https://user-images.githubusercontent.com/69082962/115161905-87e3d900-a0a0-11eb-959d-f3d378a806dc.png)
> 
> It would be greatly appreciated if you can improve the contrast of the button a bit. Maybe by making the text darker? Or making the actual button a bit darker?
> 
> Other than that i think you did a fantastic job with this theme! I love it very much!

Hey, your panel looks so opaque! Are you using an Arch-based distro?

**Comment by rivanfebrian123** [comment]
> sorry, it seems to be gone after a restart of the xfce4-panel.

Sorry, I ask again. What is your distro?

**Comment by codic12** [comment]
Arch linux. I think there was a conflict between the old and new theme.

**Comment by el3ctr0lyte** [comment]
I am using linux mint 20.

**Comment by rivanfebrian123** [comment]
@codic12 Is that fixed after a logout or restart?

I think you two have different issues here. @el3ctr0lyte talks about his notification balloon while @codic12 talks about his panel

**Comment by codic12** [comment]
Yes, I said my issue was fixed. Yeah, I just hijacked an issue because it had the xfce name on it. Sorry!

**Comment by rivanfebrian123** [comment]
> Yes, I said my issue was fixed. Yeah, I just hijacked an issue because it had the xfce name on it. Sorry!

No worries
