### ISSUE TITLE
[Firefox] WhiteSur theme only applied when toolkit.legacyUserProfileCustomizations.stylesheets in about:config is enabled

### ISSUE THREAD

**Issue by ankolaver** [vinceliuice/WhiteSur-gtk-theme#193]
Hello, 

Just wanted to highlight an issue I faced when trying to enable the Firefox Theme using `./tweaks.sh -f` after cloning the repository.

Even though the theme is installed successfully after running the aforementioned command, when Firefox is restarted, the WhiteSur theme still does not apply. I also double checked the local installation and it seemed to be successfully installed in the `~/.mozilla/firefox/firefox-themes` folder. Additionally, I wanted to check if it was applied to Firefox profiles by going to `about:profiles` in firefox ==> and then launching the folder ==> and going to the chrome directory shows that it indeed links correctly to the Firefox themes folder where the WhiteSur theme is installed.

**Solution:** After some searching, I managed to resolve the issue by going to `about:config` and changing the value of `toolkit.legacyUserProfileCustomizations.stylesheets` to True. 

My hypothesis is that since Firefox 69, loading of userChrome/userContent css is disabled ==> https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/

I am sorry if this issue is mentioned before and brought up again, but I brought it up here in case others face the same issue (I didn't manage to find info about it). Thank you! Appreciate this theme done by the developers very much :)

_I faced this issue on Fedora 34 Beta, Firefox 87 64bit_

**Comment by rivanfebrian123** [comment]
Hmm... that's weird. Did you install it when your Firefox is running?

**Comment by ankolaver** [comment]
Yup, the first time I installed it, I didn't close my Firefox. But subsequently after closing Firefox, I re-ran the command and it stated that the installation was successful.

**Comment by rivanfebrian123** [comment]
> Yup, the first time I installed it, I didn't close my Firefox. But subsequently after closing Firefox, I re-ran the command and it stated that the installation was successful.

You can download the latest commit and try again to see if that work :)
