### ISSUE TITLE
GDM installation error

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#196]
Recently I tried to install gdm theme and I got this error: 

![Error](https://user-images.githubusercontent.com/38633812/115383004-bf609b80-a1ee-11eb-9cd2-45b8a59bbac9.png)

It seemed like it was just a warning or something, so I ignored. But when I restarted my system, gdm was crashed and there was just black screen.

I used `chroot` and fixed by removing the gdm theme.

**Comment by vinceliuice** [comment]
What's your system?

**Comment by vinceliuice** [comment]
Glib2 should be installed if you are using mainstream linux distributions

**Comment by saaditory** [comment]
> What's your system?

I'm using `Ubuntu 20.04.2 LTS x86_64`

**Comment by vinceliuice** [comment]
Did you run ./install.sh before?

**Comment by vinceliuice** [comment]
You need install `libglib2.0-dev-bin`

**Comment by saaditory** [comment]
> Did you run ./install.sh before?

No I didn't.

**Comment by saaditory** [comment]
> Did you run ./install.sh before?

I restored my system using Timeshift and it removed gdm theme. So I just tried to reinstall gdm theme.

**Comment by saaditory** [comment]
> You need install `libglib2.0-dev-bin`

Thanks! Installing it fixed the issue.
