### ISSUE TITLE
Tilix bottom radius still not fixed

### ISSUE THREAD

**Issue by maxodoble** [vinceliuice/WhiteSur-gtk-theme#197]
Tilix on Gnome 40 still (latest master of today: cf0c21612f86866fb7) doesn't show correct bottom window roundings, the shell area overlaps the roundings on the bottom:

![white_sur](https://user-images.githubusercontent.com/7969171/115434154-a82ea780-a208-11eb-8c0f-339730f15416.png)

**Comment by maxodoble** [comment]
Thanks, this is partially fixed now:
fixed when using light theme
not fixed when using dark theme variant ?

**Comment by vinceliuice** [comment]
Dark version not fixed on your desktop？

**Comment by maxodoble** [comment]
No, it's not fixed for me when using dark theme for tilix.
