### ISSUE TITLE
Gnome shell theme doesn't honor app grid icon from configured icon theme

### ISSUE THREAD

**Issue by rstrube** [vinceliuice/WhiteSur-gtk-theme#198]
When using the Gnome shell theme, the app grid icon appears to be hard coded to a specific icon.  I use the Papirus icon theme, so this feels out of place.

![image](https://user-images.githubusercontent.com/4212764/115445276-e27d5200-a1d2-11eb-8035-dba6d0399975.png)

Ideally the app grid icon would use the app grid icon from the icon theme that's selected.

![image](https://user-images.githubusercontent.com/4212764/115445378-00e34d80-a1d3-11eb-88b9-70d5a135ce19.png)

![image](https://user-images.githubusercontent.com/4212764/115445580-44d65280-a1d3-11eb-83be-0ddb929fedb1.png)

**Comment by vinceliuice** [comment]
I'll give this a option!

**Comment by vinceliuice** [comment]
You can run `./install.sh --normal` to install normal show apps button version now!

**Comment by rstrube** [comment]
Thank you! Worked like a charm.  I really appreciate your efforts!
