### ISSUE TITLE
Wrong Fonts Gnome shell 3.36 4K Arch

### ISSUE THREAD

**Issue by JartX** [vinceliuice/WhiteSur-gtk-theme#20]
![Captura de pantalla de 2020-07-24 19-37-04](https://user-images.githubusercontent.com/8399211/88419782-0cd9e480-cde6-11ea-88c8-ee0c654e9089.png)

**Comment by zeparu** [comment]
try installing `ttf-dejavu`

**Comment by pixix4** [comment]
I have the same problem.

Installed fonts:

- noto-fonts
- adobe-source-code-pro-fonts
- cantarell-fonts
- nerd-fonts-complete
- nerd-fonts-fira-mono
- ttf-dejavu
- ttf-fira-code
- ttf-fira-mono
- ttf-fira-sans
- ttf-liberation
- ttf-material-design-icons
- ttf-ms-win10
- ttf-opensans
- ttf-roboto
- ttf-ubuntu-font-family
