### ISSUE TITLE
Gnome Shell Theme: Regardless of selected wallpaper, Activities Overview always uses specific blurred background

### ISSUE THREAD

**Issue by rstrube** [vinceliuice/WhiteSur-gtk-theme#201]
Currently when viewing the Activities Overview, the blurred background is always the same (the blurred default wallpaper: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/assets/gnome-shell/common-assets/background-blur.png).

Ideally the background that's blurred would be whatever wallpaper the user has currently selected.

If that's not an option, perhaps provide an option for users to define the background wallpaper when installing the GTK and Gnome Shell themes.

**Comment by vinceliuice** [comment]
No problem! I'll give this a option

**Comment by vinceliuice** [comment]
Now it's OK!

**Comment by vinceliuice** [comment]
Now you can put a image at source root dir  then run: `./install.sh -b [your image name] `
for example: `./install.sh -b background.jpg`  (rename your image file to background.jpg)

**Comment by rstrube** [comment]
Thank you, that's fantastic news!
