### ISSUE TITLE
Firefox is messed up!

### ISSUE THREAD

**Issue by Ryan-da-ghost** [vinceliuice/WhiteSur-gtk-theme#202]
The reason being ofc firefox decided OH we need a MAJOR new update, lets update our UI! 
![Capture](https://user-images.githubusercontent.com/78041469/115578115-3cb50a80-a2da-11eb-9dab-77841f3db93d.PNG)

Could anyone help ?

**Comment by Ryan-da-ghost** [comment]
After Removing
 @import "parts/csd.css"; 
It works but with VERY bad UI

**Comment by rivanfebrian123** [comment]
What's you OS?

**Comment by Ryan-da-ghost** [comment]
> 
> 
> What's your OS?

Windows

**Comment by rivanfebrian123** [comment]
WhiteSur doesn't officially support Windows, but you can do some manual theme installation for your Firefox and GTK (on MSYS2 or MINGW). You might find [this article](https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/) useful. The WhiteSur theme files for Firefox is located [here](https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/src/other/firefox)
