### ISSUE TITLE
[Feature Request] Option for GNOME 40 defaults

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#205]
Hey, 
As this theme tries to match the macOS style on the GNOME DE to improve its looks, the latest update to gnome i.e. GNOME 40 has already improved on many areas that look stunning. So I want to make some suggestions here. Kindly take a look at the screenshots below:

*Default Shell Theme:*
![Screenshot from 2021-04-25 15-25-42](https://user-images.githubusercontent.com/38633812/115990075-c74b8180-a5da-11eb-8ec3-62cbd0a43b7f.png)

*WhiteSur Shell Theme:*
![Screenshot from 2021-04-25 15-26-08](https://user-images.githubusercontent.com/38633812/115990079-cc103580-a5da-11eb-8273-c997de132cb6.png)

First of all, I love the default pill style of gnome 40 and the fact that it remains visible when we are in overview, as it indicates the current state/position. But in the current WhiteSur theme it disappears. So, I would love to see if this theme gets an option for default GNOME 40 pill style for shell and also that if it remains visible in overview.

My main request here is that, if we closely look at the spacing **[1]** and corner radius of the dock, they both look different. As the default GNOME 40 dock style matches the above workspace design, it looks more integrated with it. So, can we have an option for the default dock style?

One more thing, it will also be great if we could use the `view-app-grid.svg` with the other shell themes as well. Like if the WhiteSur icon theme is selected then there should be the the WhiteSur icon of `Show Application` for any shell theme.

**Edit:
[1] Spacing between icons**

**Comment by saaditory** [comment]
Also, I'll mention [this issue](https://github.com/vinceliuice/WhiteSur-icon-theme/issues/30) here that, this theme should slowly improve instead of blindly following macOS style because the GNOME DE can look more stunning than macOS style, .

**Comment by vinceliuice** [comment]
Run `./install.sh --normal` or `./install.sh  --normalshowapps` then you can get what you want!

**Comment by vinceliuice** [comment]
Maybe I should add this in README file

**Comment by saaditory** [comment]
> Maybe I should add this in README file

Yes, you definitely should.

But my case is different than #198. In #198, he wanted to use *Papirus icon + WhiteSur Shell theme* but in my case it's *WhiteSur icon + Default Shell theme*. So I want the `Show Applications` button to also follow WhiteSur icon theme and not the default one (if that's possible). 

Any manual tweak to replace `Show Applications` icon is also accepted.

**Comment by vinceliuice** [comment]
I'll try this, add this icon to icon theme

**Comment by saaditory** [comment]
Great @vinceliuice! What do you say about other suggestions?

**Comment by vinceliuice** [comment]
I get this, you are right! default gnome theme dock radius looks more perfect, I'll update this!

**Comment by vinceliuice** [comment]
Dock radius is updated, aboult the show app icons, if you don't set a background image in shell theme, then it will only show the symbolic icon `view-app-grid-symbolic.svg` and recolor it with dash panel text color, so if I add a non-symbolic icon as `view-app-grid-symbolic.svg` it'll show just a white color block, so unfortunately, your second idea cannot be realized at present!

**Comment by saaditory** [comment]
1. Thanks for the dock, it looks awesome now.
2. Yes, You are right. I tried it as well, the `show app` icon appears as white color block with default shell theme.
![Screenshot from 2021-04-29 11-22-46](https://user-images.githubusercontent.com/38633812/116512987-56f67600-a8e2-11eb-988b-f48b5f9b7ffd.png)

**Comment by saaditory** [comment]
3. I had another suggestion to highlight/add-background to the activities icon in overview (just like the default behavior) as well (if you want to consider). BTW, I should have numbered the requests, sorry.

**Comment by vinceliuice** [comment]
If you have good suggestions just tell me, I'll test it!
