### ISSUE TITLE
Nautilus search button looks wrong

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#206]
The title explains the issue.

![image](https://user-images.githubusercontent.com/38633812/115991614-c585bc00-a5e2-11eb-9de6-4273284f2afd.png)

**Comment by rivanfebrian123** [comment]
@vinceliuice You agree to make it centered like this?
![Screenshot from 2021-04-29 17-01-50](https://user-images.githubusercontent.com/6300910/116534435-b5d0e500-a90c-11eb-8fa8-971ed4b4ac38.png)

![Screenshot from 2021-04-29 17-02-05](https://user-images.githubusercontent.com/6300910/116534429-b49fb800-a90c-11eb-94a1-da136f39aa4c.png)

**Comment by vinceliuice** [comment]
I'll set it to right side:
![2021-04-29 19-30-09 的屏幕截图](https://user-images.githubusercontent.com/7604295/116544188-621cc680-a921-11eb-9282-0d420cc7beaf.png)
