### ISSUE TITLE
Firefox tab names not staying centered

### ISSUE THREAD

**Issue by behren** [vinceliuice/WhiteSur-gtk-theme#207]
Hello, the tab names won't stay centered for longer than a millisecond on my system. Sometimes they don't even center at all.
I am running Mint 20.1.

![image](https://user-images.githubusercontent.com/75254846/115999683-f79c1b80-a5ec-11eb-949b-fad6c9c35825.png)

![image](https://user-images.githubusercontent.com/75254846/115999738-2b774100-a5ed-11eb-8517-7f8b8559d846.png)

**Comment by vinceliuice** [comment]
What's your firefox version, I'll test it

**Comment by behren** [comment]
88.0 (64-bit)

**Comment by vinceliuice** [comment]
Ok, I'll fix this!

**Comment by vinceliuice** [comment]
Fixed!

**Comment by behren** [comment]
It works most of the time. It doesn't work on a new window though. The home page always has its tab name centered more to the right: 

![image](https://user-images.githubusercontent.com/75254846/116518988-3e319480-a8d1-11eb-96d0-74c1416709e4.png)

**Comment by vinceliuice** [comment]
I'll test this
