### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by memesforlife1** [vinceliuice/WhiteSur-gtk-theme#209]
Hello! I'd like to know what fonts you used for the fonts in the pictures of the whitesur gtk themes

**Comment by rivanfebrian123** [comment]
It's "Inter". But, in the GDM previews, it's the default Ubuntu font. Because, I didn't know how to change it when taking those screenshots :D

**Comment by memesforlife1** [comment]
Thanks! :)

**Comment by rivanfebrian123** [comment]
Your welcome!
