### ISSUE TITLE
glib-compile-resources: command not found: Linux Mint (Ubuntu)

### ISSUE THREAD

**Issue by sinnrrr** [vinceliuice/WhiteSur-gtk-theme#21]
Fix: Add to _README.md_ following dependency for **Ubuntu**-based distributions:
`libglib2.0-dev`

**Comment by 74V0C** [comment]
had the same issue on ubuntu 20.04, can attest that installing the above package resolves the issue. Create a pull request?

**Comment by 74V0C** [comment]
whoops, my bad, looks like the fix has already been integrated. Close the issue
