### ISSUE TITLE
Firefox Private Window is laggy

### ISSUE THREAD

**Issue by Ftamino** [vinceliuice/WhiteSur-gtk-theme#210]
Firefox Private Window is laggy
Icant see any suggestions
![Bildschirmfoto von 2021-04-28 09-30-26](https://user-images.githubusercontent.com/83065176/116364635-b41bfa00-a804-11eb-8970-afd04e8da5f9.png)

**Comment by rivanfebrian123** [comment]
Can't really help with this cuz it's Firefox's bug. It also happens to other theme like this boy: https://github.com/EliverLara/firefox-sweet-theme, anyway. 


![Screenshot_2021-04-28_16-36-42](https://user-images.githubusercontent.com/6300910/116383436-07ac3900-a841-11eb-9d8e-08c63bedf196.png)
In the mean time, you can remove your WhiteSur Firefox theme by running `./tweaks.sh -f -r`

**Comment by Ftamino** [comment]
No I dont really need the ingknito mode i was only wondering if this is a bug

**Comment by rivanfebrian123** [comment]
Yeah, it's Firefox bug. You can report this issue at https://bugzilla.mozilla.org/home

**Comment by vinceliuice** [comment]
I think this is fixed now
