### ISSUE TITLE
Glassy Nautilus headerbar isn't transparent anymore

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#213]
![Screenshot from 2021-04-29 07-51-42](https://user-images.githubusercontent.com/6300910/116489782-f7876e80-a8bf-11eb-8288-44b1aa0ea529.png)

Install command: `./install.sh -N glassy`
OS: `Manjaro GNOME`
GNOME version: `40.0.0`
Nautilus version: `40.0`

**Comment by rivanfebrian123** [comment]
It works now! Thanks

**Comment by vinceliuice** [comment]
You are welcome!
