### ISSUE TITLE
Found a Youtube channel to learn from

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#214]
In the old days, I used to learn about macOS design from the screenshots on Google, but now, I found this [Youtube channel](https://www.youtube.com/c/zollotech/videos) to learn and get inspiration from. It also has some videos with dark mode display there, so we can make our dark theme more authentic

**Comment by vinceliuice** [comment]
OK！Let me see if we can get some useful information from those videos
