### ISSUE TITLE
Nautilus window control button overlapped

### ISSUE THREAD

**Issue by Jikol** [vinceliuice/WhiteSur-gtk-theme#216]
Hello.
FIrst of all I would like to thank you for  your good theme, it looks nice.
I'm just have an issue with Nautilus control buttons positioning when i install this theme with script. I doesn't appear when I use the gnome looks version (but it's default and i want rounded fullscreen window)
![Screenshot from 2021-05-01 21-45-34](https://user-images.githubusercontent.com/32988071/116793364-b01eff00-aac6-11eb-8bc2-b476c312919a.png)

I tried all the alternatives variant but none worked.

**Comment by raillen** [comment]
Same problem here.

**Comment by vinceliuice** [comment]
What's you system version?

**Comment by vinceliuice** [comment]
Download the last update and run `./install.sh -R`

**Comment by vikas-0** [comment]
> Download the last update and run `./install.sh -R`

Didn't work. 
Files : 3.36.3-stable
Gnome: 3.36
OS: Ubuntu 20.04.1
Running on X11

**Comment by Jikol** [comment]
I tried laast update and it works like a charm, good job.
![Screenshot-20210502124316-912x621](https://user-images.githubusercontent.com/32988071/116810459-30d01080-ab44-11eb-8147-edfade185394.png)
Nautilus: 3.36.3-0ubuntu1
Gnome: 3.36.8
Ubuntu: 20.04.2
Windows system: X11

**Comment by raillen** [comment]
> What's you system version?
> Download the last update and run ./install.sh -R

I'm using PopOS 20.10, Nautilus 3.36. I've tried did it, but doesn't work.
