### ISSUE TITLE
Overlap on Applications drawer search

### ISSUE THREAD

**Issue by surajghuwalewala** [vinceliuice/WhiteSur-gtk-theme#217]
I am getting an overlap of menus when I try to search in the Application drawer. See the below image.

![Screenshot from 2021-05-02 03-38-38](https://user-images.githubusercontent.com/31948966/116796164-1d975380-aaf8-11eb-8816-d44eaaccaf24.png)

Any suggestions?

PS: I am new to this.

**Comment by vinceliuice** [comment]
What's your desktop version？

**Comment by surajghuwalewala** [comment]
![Screenshot from 2021-05-02 13-27-15](https://user-images.githubusercontent.com/31948966/116806466-ccfd1600-ab4a-11eb-8449-2537fecf3f22.png)

Could it be because of Gnome 3.28?

**Comment by rivanfebrian123** [comment]
You right. Honestly, we have a long standing old GNOME (especially on Ubuntu 18.x) compatibility problem since then, but fortunately, now we already have the GNOME version detection so I think we can solve those compatibility issues easier
