### ISSUE TITLE
Installer breaks Font sizing

### ISSUE THREAD

**Issue by janaSunrise** [vinceliuice/WhiteSur-gtk-theme#219]
After installing this, My font size all over PC has become weird, crooked and unbearable. Checked the settings, Nothing has changed, but the font's totally different. Please help.

![Screenshot from 2021-05-03 13-51-40](https://user-images.githubusercontent.com/56873669/116862405-52072e80-ac22-11eb-9f1f-24f0d4cb73be.png)
![Screenshot from 2021-05-03 14-02-40](https://user-images.githubusercontent.com/56873669/116862409-53d0f200-ac22-11eb-8169-b45ebd0bde63.png)
![Screenshot from 2021-05-03 14-16-58](https://user-images.githubusercontent.com/56873669/116862412-54698880-ac22-11eb-8e4a-2b47a970abed.png)

**Comment by rivanfebrian123** [comment]
>  My font size all over PC has become weird, crooked and unbearable

Your text/font looks just good. You mean it's something like #20 or #51?

**Comment by janaSunrise** [comment]
Not really, But mine's a lot large than it used to be.

**Comment by vinceliuice** [comment]
Why not set your font size smaller like 10？

**Comment by janaSunrise** [comment]
Tried that already, Seems like It doesn't modify the size of the top bar though

**Comment by rivanfebrian123** [comment]
Can't see your top bar tho

**Comment by janaSunrise** [comment]
I showed just my notifications. Everything has changed, so I just showed the notifs.

**Comment by rivanfebrian123** [comment]
Nah, I thought by "top bar", you mean titlebar (headerbar / window decoration), panel, or something

Why don't you just show us your whole screen so we can understand your problem correctly?

**Comment by janaSunrise** [comment]
![Screenshot from 2021-05-05 16-32-05](https://user-images.githubusercontent.com/56873669/117131744-764c4200-adbf-11eb-91e3-db8c1cd356b8.png)

I've been using it, and The sections in the top has a large font size now, Almost large by 4 or 5 pixels. No idea why it's happening after installing the theme.

**Comment by rivanfebrian123** [comment]
Your font is totally fine tho. My laptop has the same screen resolution with that image so I can see your screen image in pixel-perfect (fullscreen).

> I've been using it, and The sections in the top has a large font size now, Almost large by 4 or 5 pixels. No idea why it's happening after installing the theme.

Let's be honest. I feel the same too. I think that's because of the GNOME upgrade. When I set my font size to x.5 in size, it's rendered as a narrow font for some unknown reason

**Comment by hematenergi** [comment]
> Tried that already, Seems like It doesn't modify the size of the top bar though

i have same issues with u. and i stuck how to revert back to original top bar font size. :(

**Comment by rivanfebrian123** [comment]
@vinceliuice you have any idea?

**Comment by vinceliuice** [comment]
I’ll set the panel font weight to normal!
