### ISSUE TITLE
Cinnamon's volume indicators are a bit hard to see with WhiteSur-light

### ISSUE THREAD

**Issue by Janne-d-Arc** [vinceliuice/WhiteSur-gtk-theme#220]
I love this theme although I have noticed that the Cinnamon volume indicators (the pop-ups that appear when changing the volume with the multimedia keys) are a bit hard to see since they are displayed as a white icon on a nearly white background:

![light](https://user-images.githubusercontent.com/13596575/116948343-bdfa8e80-ac44-11eb-9a1f-48044690af55.jpg)

These indicators are clearly visible using WhiteSur-light-solid and WhiteSur-dark:

![solid](https://user-images.githubusercontent.com/13596575/116948376-d074c800-ac44-11eb-8ddc-f32e5af656ac.jpg)
![dark](https://user-images.githubusercontent.com/13596575/116948401-db2f5d00-ac44-11eb-914f-85ffc9cad58c.jpg)

Is this intended?

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by Janne-d-Arc** [comment]
> I'll fix this

Thank you. :)
