### ISSUE TITLE
GDM 40 login screen background always remain black.

### ISSUE THREAD

**Issue by aloksrk** [vinceliuice/WhiteSur-gtk-theme#222]
I install many times but GDM 40 login screen background always remain black, no wallpaper.

**Comment by rivanfebrian123** [comment]
@vinceliuice Is this why you add `--background` in `install.sh`?

**Comment by vinceliuice** [comment]
I did not check this, but it's ok to set to default

**Comment by rivanfebrian123** [comment]
Okay
