### ISSUE TITLE
can't revert panel transparency

### ISSUE THREAD

**Issue by Fancy2209** [vinceliuice/WhiteSur-gtk-theme#223]
I was testing the theme tweaks but when I was reverting the panel transparency it doesn't let me
![Captura de ecrã de 2021-05-05 19-14-54](https://user-images.githubusercontent.com/64917206/117196710-5a07cf80-add6-11eb-9a3b-aea8d23a4000.png)

**Comment by rivanfebrian123** [comment]
It's a parameter of GDM installation. So to "revert" your panel transparency, you can just run `sudo ./tweaks.sh -g --some-customization-parameter`
