### ISSUE TITLE
theme break original font size and style on top bar ubuntu 20

### ISSUE THREAD

**Issue by hematenergi** [vinceliuice/WhiteSur-gtk-theme#224]
after i pull up the repo for theme update then i do sudo ./tweaks.sh -g and suddenly top bar change to bold and got bigger. alt+f2 r didnt fix this issue
![image](https://user-images.githubusercontent.com/47767846/117317860-17b4c000-aeb4-11eb-84b9-e24bdc0f009e.png)

**Comment by rivanfebrian123** [comment]
I think you have a similar issue with #185. Anyways, what's your OS and the font you use?

**Comment by hematenergi** [comment]
> I think you have a similar issue with #185. Anyways, what's your OS and the font you use?

ubuntu lts 20.04. i use original ubuntu font and never change the font

**Comment by hematenergi** [comment]
> I think you have a similar issue with #185. Anyways, what's your OS and the font you use?

its little different with #185 issue. it only happen on top bar

**Comment by rivanfebrian123** [comment]
Thanks for clarifying. We're working on it

**Comment by hematenergi** [comment]
> Thanks for clarifying. We're working on it

i hope it will be fix soon. fyi, it happen with default and other theme but normal with shell theme Yaru-dark.
this is in yaru-dark
![image](https://user-images.githubusercontent.com/47767846/117326362-c7d9f700-aebb-11eb-8df5-5d27d8f49e48.png)

**Comment by hematenergi** [comment]
![image](https://user-images.githubusercontent.com/47767846/117332764-6c5f3780-aec2-11eb-9b93-55168efcf497.png)

everything is fine now. thank you so much!

**Comment by vinceliuice** [comment]
You are welcome!
