### ISSUE TITLE
GDM tweak with custom background and --no-blur defaults to default background instead of custom

### ISSUE THREAD

**Issue by imdaveho** [vinceliuice/WhiteSur-gtk-theme#226]
I ran `sudo ./tweak.sh -g -n -b ~/Pictures/custom_image.jpg` as per the instructions in the readme and the login defaults to the default BigSur background. However, if I run `sudo ./tweak.sh -g -b ~/Pictures/custom_image.jpg` (without the `-n`) -- this sets the custom image just fine.

I tried inspecting the bash scripts, but couldn't really follow the setup process...

edit: workaround this by replacing background-default.png in `src>assets>gnome-shell>common-assests` with the image I wanted...but obviously still an issue with the script in question

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by rivanfebrian123** [comment]
@vinceliuice Just tell me if you need some help :)

**Comment by vinceliuice** [comment]
@rivanfebrian123  OK! no problem

**Comment by vinceliuice** [comment]
Fixed!
