### ISSUE TITLE
Firefox theme issue - tab titles are not centered after Firefox update 

### ISSUE THREAD

**Issue by qurczax** [vinceliuice/WhiteSur-gtk-theme#227]
After Firefox update tabs titles are not centered, they are aligned to the left - version 88.0
![obraz](https://user-images.githubusercontent.com/11503879/117576937-00f6af00-b0e8-11eb-94d8-6b90bcae3bb7.png)

**Comment by vinceliuice** [comment]
Install the last version on github, this is fixed a few days ago
