### ISSUE TITLE
[VISUAL GLITCH] Strange size issue on the calendar/clock.

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#230]
Hi,

I'm having this issue right here with the calendar:

![07-06-07 on terça 11, maio 2021](https://user-images.githubusercontent.com/69485578/117890769-27554f80-b28c-11eb-9319-82b577a4c525.png)

I don't know if it's a _GNOME_ issue, a extension issue, or if it is because I'm using two monitors...but, I'm finding this kind of annoying as i can't see my to-do list and agenda with this glitch.
The calendar is VERY thin, some buttons are off the screen and is generally unusable.
Removing the theme and using the stock _Ubuntu_ theme fixes it, but after I apply the theme again and restart _Gnome Shell_, this glitch comes back.
I hope this is fixable, and _sorry if I'm being annoying_.

**Comment by rivanfebrian123** [comment]
What's extension you use? Is it "Unite"?

> sorry if I'm being annoying.

No, you ain't :)

**Comment by CyberAzure** [comment]
> What extension you use? Is it "Unite"?

Alot of extensions actually, but not _Unite_.
I don't know how to paste an _entire_ list of all the extensions that are on my system too.

**Comment by rivanfebrian123** [comment]
You can take some screenshot of them then. And, what's your Ubuntu version?

**Comment by CyberAzure** [comment]
> You can take some screenshot of them then.

Allllllrighty, here's all of the extensions on my system:

![1](https://user-images.githubusercontent.com/69485578/117897362-06dfc200-b299-11eb-90b9-1b59f46be8e4.png)
![2](https://user-images.githubusercontent.com/69485578/117897376-0a734900-b299-11eb-921e-f568dd10eff3.png)
![3](https://user-images.githubusercontent.com/69485578/117897379-0e06d000-b299-11eb-90c3-2b57841b0cef.png)

Alot of extensions I know, but the result is gorgeous:

![desktop](https://user-images.githubusercontent.com/69485578/117897550-7655b180-b299-11eb-9bc9-7332d853c516.png)

> And, what's your Ubuntu version?

Ubuntu 20.04, I will update to GNOME 40 once it is on LTS.

**Comment by rivanfebrian123** [comment]
Wow! That's insane! I'm trying to install them too to find the bug

**Comment by CyberAzure** [comment]
For whom may concern, I use the Mkos icon theme too, and the theme changes according to the time(and the icon theme too).
I was thinking about posting this setup on the reddit board r/unixporn because it looks exactly as macOS, but i need to fix this calendar issue first.

**Comment by insanitywanted** [comment]
> > You can take some screenshot of them then.
> 
> Allllllrighty, here's all of the extensions on my system:
> 
> ![1](https://user-images.githubusercontent.com/69485578/117897362-06dfc200-b299-11eb-90b9-1b59f46be8e4.png)
> ![2](https://user-images.githubusercontent.com/69485578/117897376-0a734900-b299-11eb-921e-f568dd10eff3.png)
> ![3](https://user-images.githubusercontent.com/69485578/117897379-0e06d000-b299-11eb-90c3-2b57841b0cef.png)
> 
> Alot of extensions I know, but the result is gorgeous:
> 
> ![desktop](https://user-images.githubusercontent.com/69485578/117897550-7655b180-b299-11eb-9bc9-7332d853c516.png)
> 
> > And, what's your Ubuntu version?
> 
> Ubuntu 20.04, I will update to GNOME 40 once it is on LTS.

How did you get those (file, edit, view, go option on the top bar)?

**Comment by CyberAzure** [comment]
> How did you get those (file, edit, view, go option) on the top bar?

Download [this](https://extensions.gnome.org/extension/4111/mock-universal-menu/) extension, it's only for aesthetic purposes and it doesn't really do something when clicked.

**Comment by CyberAzure** [comment]
I _think_ I've found the cause...

**Putting your laptop screen on vertical orientation.**

I use my laptop as a second screen on my left, **totally** vertical, in that screen I usually put chatting apps, music player w/ bar visualizers, and other things as well.
My main screen on center, is just a normal monitor on horizontal, nothing special there.

Seems like _GNOME Shell_ on _Ubuntu 20.04_ doesn't like this, and makes some elements _(not only the calendar, notifications are a bit glitched too)_ **out of place, stretched out, totally vertical, or a combination of the three**.

_Temporary fix?_
**Don't use your laptop screen vertically.**
_Absolute fix?_
I don't think there's a permanent fix to this other than maybe _GNOME 40_, but I don't know if this glitch is present there as I can't test that.

Just warning again. **_I THINK_** that's the cause, because the glitch is **NOT** present when I set it _(laptop screen)_ to horizontal and restart _GNOME Shell_.

If needed, I'll open the issue again, but I think I've fixed it.

**Comment by CyberAzure** [comment]
I won't reopen it _(unless someone wants to)_, but the issue persists on horizontal monitors too **SOMETIMES**.
Don't know if this is a _GNOME_ problem, a theme problem or an extension problem.
But it's getting to my nerves a _lil'_ bit.
