### ISSUE TITLE
Brightness and Touchpad icons are blurry in GNOME 3.36

### ISSUE THREAD

**Issue by divyanshu0x16** [vinceliuice/WhiteSur-gtk-theme#231]
I don't know much about development so I don't have any idea where the issue is coming from, but the brightness and touchpad icons are blurry in GNOME 3.36. I have attached screenshots for the same. 
![Screenshot from 2021-05-12 17-42-29](https://user-images.githubusercontent.com/62815174/117973427-02bfad00-b34a-11eb-8b82-4cda03ade818.png)
![Screenshot from 2021-05-12 17-42-34](https://user-images.githubusercontent.com/62815174/117973441-07846100-b34a-11eb-8ccb-57bc9f227b30.png)
![Screenshot from 2021-05-12 17-42-36](https://user-images.githubusercontent.com/62815174/117973452-0b17e800-b34a-11eb-9055-84795de24711.png)

**Comment by vinceliuice** [comment]
What icon theme you are using?

**Comment by divyanshu0x16** [comment]
I'm really sorry, it looks like I accidentally opened an issue in the wrong repo.
