### ISSUE TITLE
Small glitch Nautilus

### ISSUE THREAD

**Issue by mfauvain** [vinceliuice/WhiteSur-gtk-theme#232]
![Screenshot 20210512_102526](https://user-images.githubusercontent.com/14844435/118002803-98891700-b30d-11eb-93d0-f63b2d9ac4e0.jpg)

the 'rectangle' around the selected item is too wide for some reason.
Can you indicate where is this 'keyboard selected' rectangle setting? I can't find it and would like to make it transparent actually.

**Comment by vinceliuice** [comment]
What's your nautilus version？

**Comment by mfauvain** [comment]
40.1
Can you help with where I can find the color/attributes of this rectangle in the scss files?

**Comment by vinceliuice** [comment]
I'll remove this

**Comment by mfauvain** [comment]
Thx. but my question is more general, I would like to hide the selection rectangle on every instance of it appearing. Is there a single setting/color somewhere?

**Comment by vinceliuice** [comment]
You need modify the source scss file

**Comment by mfauvain** [comment]
thx, seen.
