### ISSUE TITLE
Question: Where do I go to change list item border padding?

### ISSUE THREAD

**Issue by SaucySauce** [vinceliuice/WhiteSur-gtk-theme#235]
(mock up)
<img width="1920" alt="GNOME Stuff, eh" src="https://user-images.githubusercontent.com/38703177/118133360-44a32e80-b3f0-11eb-93f6-a471d91b1cbb.png">
I want to set the sidebars to the same size and style on my theme; your theme has the margin padding for the items but I can't find the code on your theme. I'm sorry I'm making a post that's not about your creation but I can't find other places with the information.

**Comment by vinceliuice** [comment]
On nautilus it's `placessidebar.sidebar` you can add a `padding: 6px;` to the `placessidebar.sidebar` or add a `margin: 3px 6px;` to the `placessidebar.sidebar row.sidebar-row`

**Comment by vinceliuice** [comment]
If you want all sidebar have the same style, then don't set style for nautilus， just set to `.sidebar` and `.sidebar row`

**Comment by vinceliuice** [comment]
If you don't know what css node works for the part you want to change, you can use this tool: https://blog.gtk.org/2017/04/05/the-gtk-inspector/

**Comment by SaucySauce** [comment]
Thank you so much.

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by SaucySauce** [comment]
Thank you once again. I'm closing the issue.
