### ISSUE TITLE
Dash To Dock installation error

### ISSUE THREAD

**Issue by Froggy232** [vinceliuice/WhiteSur-gtk-theme#237]
Hi,
First, thanks you for your incredible work!
I have a problem with the installation of the Dash-To-Dock theme, it doesn't work, the installer tell me : 

 Oops! An error is detected...

  ERROR LOG:
Error: File to import not found or unreadable: gtk-base-temp.
        on line 7:1 of src/sass/_colors.scss
        from line 7:1 of src/other/dash-to-dock/stylesheet-dark.scss
 @import gtk-base-temp;

   ^

  TIP: you can google or report to us the error log above

I have tried with the latest version of the theme on gnome 40 and the latest fork of dash-to-dock for gnome 40.
It seems to be a problem with the theme itself and not dash to dock, which I find very weird.
I don't have any gtk-base-temp file in the directory, the problem is probably that?

Anyway, the dash to dock theme is not installed, the dock is opaque black and not transparent.
Does someone have an idea, or the same problem?

Thanks!

**Comment by vinceliuice** [comment]
I'll fix this, by the way if you are using gnome40 then don't install dash to dock theme, because this is for <= 3.38 version

**Comment by vinceliuice** [comment]
Just go to `Dash to dock setting` > `Appearance` > turn off `Use built-in theme`

**Comment by rivanfebrian123** [comment]
> Just go to `Dash to dock setting` > `Appearance` > turn off `Use built-in theme`

Why?

**Comment by Froggy232** [comment]
Thanks, so it probably came from the gnome 40 version of dash to dock right?
If so, I will just wait for the update, when it will be done.
For the moment, I have turn off the built-in theme and made my own settings, it's not perfect but it's not that bad.

Thanks for your amazing work anyway!

**Comment by vinceliuice** [comment]
Gnome 40 dash to dock theme I've built in gnome-shell theme! check this:
![Screenshot from 2021-05-14 18-34-29](https://user-images.githubusercontent.com/7604295/118258955-14888800-b4e3-11eb-93b8-fff17c6c30c2.png)
![Screenshot from 2021-05-14 18-34-32](https://user-images.githubusercontent.com/7604295/118258970-194d3c00-b4e3-11eb-88f5-0186d8516467.png)

**Comment by rivanfebrian123** [comment]
> Gnome 40 dash to dock theme I've built in gnome-shell theme! check this:

Cool!



> Just go to `Dash to dock setting` > `Appearance` > turn off `Use built-in theme`

And, what about this?

**Comment by vinceliuice** [comment]
When gnome-shell version <= 3.38, if I add the dash to dock theme code into gnome-shell theme, it will not show the margin to the bottom edge and bottom radius, so I have to make the theme built in dash to dock itself to show this style, but on Gnome 40 The original gnome-shell theme style is like this, so there is no need to install dash to dock built in now!

**Comment by vinceliuice** [comment]
@rivanfebrian123  Just make sure don't use the dash-to-dock built-in theme, because this option is on, dash-to-dock will not show the style in gnome-shell theme

**Comment by vinceliuice** [comment]
By the way, I installed dash to dock (40 version) from here: https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40

**Comment by rivanfebrian123** [comment]
Oh... I see. Everything is now so different. Sorry for being out-to-date :)

**Comment by Froggy232** [comment]
Thanks you a lot!

**Comment by vinceliuice** [comment]
You are welcome!
