### ISSUE TITLE
[Visual Glitch] Corners are not smoothly rounded on Totem & Celluloid video player

### ISSUE THREAD

**Issue by insanitywanted** [vinceliuice/WhiteSur-gtk-theme#238]
Hi Devs!
I am having an issue with the video players like totem and celluloid. Corners are not appearing smoothly rounded, other themes do not have this issue. 

![issue1](https://user-images.githubusercontent.com/47140829/118264505-69250680-b4d5-11eb-8620-b37af30c55fb.png)
![issue2](https://user-images.githubusercontent.com/47140829/118264509-6b876080-b4d5-11eb-86ab-6335f6e878ac.png)

Thank you so much for creating this beautiful theme.

**Comment by CyberAzure** [comment]
This can be an app problem, a render problem, a GNOME problem or a theme problem.
Try pressing `Alt + R` and then typing `R` again and `Enter`, this may solve the problem in some cases.

**Comment by insanitywanted** [comment]
Hey.
`ALT + R` does nothing for me.

**Comment by rivanfebrian123** [comment]
This also happens on another theme (Adwaita). The transparency there is gone for some reason

**Comment by CyberAzure** [comment]
Strange...
Maybe Vinceliuice can look onto this, but I think this may be an app problem.

**Comment by rivanfebrian123** [comment]
Some part of the Popover has transparancy, while the other part, that is on top of BaconVideoWidget, loses its transparancy. You can fill a new issue here at https://gitlab.gnome.org/GNOME/totem/-/issues if you want to

**Comment by insanitywanted** [comment]
Same issue is happening with celluloid player.
