### ISSUE TITLE
[Issue] Gedit visibilty issue

### ISSUE THREAD

**Issue by insanitywanted** [vinceliuice/WhiteSur-gtk-theme#240]
Hi Devs!

Gedit has some visibility issue. Text color and line highlighter has white color which makes text unreadable.

![issue4](https://user-images.githubusercontent.com/47140829/118266443-3b8d8c80-b4d8-11eb-8091-926cb64408ab.png)

Thanks

**Comment by vinceliuice** [comment]
Just change the gedit colorscheme

**Comment by vinceliuice** [comment]
This is not contol by the gtk theme

**Comment by insanitywanted** [comment]
If anybody else is finding the fix. Just uncheck "Highlight current line" in preference.

![Screenshot from 2021-05-14 18-45-32](https://user-images.githubusercontent.com/47140829/118276034-ceccbf00-b4e4-11eb-85e6-19d2c7f4f469.png)

Thank you @vinceliuice for the wonderful theme.
