### ISSUE TITLE
Text size of top panel

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#242]
![image](https://user-images.githubusercontent.com/38633812/118341306-ff8a1400-b537-11eb-9db4-96f39a05683d.png)

Don't you think that the text size of the top panel is too small and thin?

**Comment by vinceliuice** [comment]
Try the last update and run `./install.sh -HD`

**Comment by saaditory** [comment]
Nice! looks good now.
It'd be better if `Application Menu` & `Clock Menu` text would be bold.
Thanks anyways.

**Comment by saaditory** [comment]
> It'd be better if `Application Menu` & `Clock Menu` text would be bold.

This is because the icons in the top panel are bold/filled.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Updated!
