### ISSUE TITLE
Activities pill in overview?

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#243]
*Desktop:*
![Screenshot from 2021-05-15 06-46-59](https://user-images.githubusercontent.com/38633812/118344754-724fbb00-b549-11eb-8407-f6260c90d2e2.png)
*Overview:*
![Screenshot from 2021-05-15 06-47-27](https://user-images.githubusercontent.com/38633812/118344755-7380e800-b549-11eb-92ae-20339a72fb57.png)

In GNOME 40, the default pill remains visible in overview as well because it show that the `Activities` are visible, but in this theme this is not the case. Is it a design choice or it needs design?

**Comment by vinceliuice** [comment]
I'll add a hover background in overview

**Comment by saaditory** [comment]
> I'll add a hover background in overview

Yeah, that's good at least.

**Comment by saaditory** [comment]
Would you not mind to tell me how to add still background in overview?

**Comment by vinceliuice** [comment]
#panel:overview #panelActivities.panel-button {}

**Comment by saaditory** [comment]
Thanks @vinceliuice!
