### ISSUE TITLE
Can't remove the Firefox theme

### ISSUE THREAD

**Issue by adamzugone** [vinceliuice/WhiteSur-gtk-theme#247]
(This is most likely mainly just because I'm new to Linux and do stupid things)
So, after I realized that this WhiteSur theme isn't for my computer (I had some graphical glitches that I think are either because of my incompetence or the age of my laptop). I ran the command to remove the theme, not too sure if I used -r or -u, but all I know is that the Firefox theme remained. I don't think there was a specific command to just remove the Firefox theme so I thought maybe uninstalling and re-installing Firefox itself would work, but it didn't.
I mean, everyone's gotta start somewhere. Could someone help me figure out how to get rid of the theme? *_*

**Comment by rivanfebrian123** [comment]
To uninstall Firefox, you can just run `./tweaks.sh -f -r`

**Comment by adamzugone** [comment]
Ah lol, that makes a lot of sense. I had the right idea, just didn't use the correct command. Thank you!

**Comment by rivanfebrian123** [comment]
Your welcome :)
