### ISSUE TITLE
lock screen broken. after install gdm theme 

### ISSUE THREAD

**Issue by anishkumar127** [vinceliuice/WhiteSur-gtk-theme#248]
ubuntu 21.04 wayland gnome 3.38 . there also broken login screen lock screen total broken. showing only black and bigger icon in black color. and my mostly system broken. after install. gdm   sudo ./tweaks.sh -g -D   
-_- what should i do now ?
i think i have to format my laptop or install new os -_- can u help me ?

**Comment by jithinlal** [comment]
I do have the same issue

**Comment by jithinlalpr** [comment]
Seems like this is an issue with the wallpaper, i gave blank as an option, and atleast i could login to the system, even though the lock screen completely is broken

**Comment by vinceliuice** [comment]
Put `ctrl + alt + f3` run `startx` or just cd to whitesur theme source folder then `run sudo ./tweaks.sh -g -r`

**Comment by alexboutros** [comment]
Just had this problem. Couldn't even get into virtual console with ctrl + alt + #. Had to edit grub to enable booting into text mode, then run `run sudo ./tweaks.sh -g -r`. 
Kernel: 5.13.19-2-MANJARO
GNOME 40.5
