### ISSUE TITLE
GDM font can't be changed to Ubuntu

### ISSUE THREAD

**Issue by mfauvain** [vinceliuice/WhiteSur-gtk-theme#249]
Not an issue specific to this theme, but wondering if someone else had the issue.
GDM won't use the defined theme font, and when forcing it in _common.scss like so
```
// Stage
stage {
  @include font(body);
  @include fontsize($base_font_size);
  color: $fg_color;
  font-family: Ubuntu;
```
it gives squares in GDM login screen

![Screenshot 20210516_182415](https://user-images.githubusercontent.com/14844435/118416177-0158f200-b674-11eb-92e9-b394628356df.jpg)

Anyone with the issue?

**Comment by CyberAzure** [comment]
Try posting this issue on Stack Exchange or other forums, as this is not a issue relating to the theme(because I experienced the same issue using other GDM themes in the past).
