### ISSUE TITLE
[Pop!_OS & Ubuntu] Default image viewer is dark-themed 

### ISSUE THREAD

**Issue by airvue** [vinceliuice/WhiteSur-gtk-theme#25]
![github-issue](https://user-images.githubusercontent.com/53982860/88757559-32832880-d11b-11ea-9686-9fa54b7133f4.png)

**Comment by zeparu** [comment]
that is normal for any theme, if it provides a dark theme

the default video player does the same too

**Comment by MahdiBaghbani** [comment]
Can you explain it more to me? How does it work? Automatically applies dark
theme to Reader and video?
It will be better if you show me code snippets because I can’t find such
things in source code.

**Comment by zeparu** [comment]
not here, the themes is 0% responsible here, the default image viewer and video player will use the current theme's dark mode, no matter the theme

**Comment by MahdiBaghbani** [comment]
Is there a way to force these programs to use the defined color theme? Like
defining css properties targeting Reader colors.
If you have documentation links, can you please share it with me? I’m
working on creating my own theme based on this theme and I appreciate your
help.

>

**Comment by mBilG** [comment]
you can use gtkinspector to check the style classes..
my previous attempts to change them were not so successful..

**Comment by mBilG** [comment]
1 way to overcome it is to use 2 themes separately for dark and light.
as @zeparu mentioned: from the light theme, rename the gtk-dark.css to something else.
when you open the apps they will appear with the light theme

**Comment by airvue** [comment]
@zeparu @mBilG  Thanks !
