### ISSUE TITLE
No outline

### ISSUE THREAD

**Issue by mfauvain** [vinceliuice/WhiteSur-gtk-theme#250]
I would like to remove the outline when selecting a button/path bar/entry box/icon etc
like so :
![20210516_183835](https://user-images.githubusercontent.com/14844435/118416736-b12f5f00-b676-11eb-88d5-cf4f239a6b42.jpg)
to be like
![20210516_183858](https://user-images.githubusercontent.com/14844435/118416737-b2f92280-b676-11eb-952b-3f0f928702c1.jpg)

Or 

![Screenshot 20210516_183948](https://user-images.githubusercontent.com/14844435/118416772-e045d080-b676-11eb-827d-2ba26eb3e379.jpg)

to be like
![Screenshot 20210516_183959](https://user-images.githubusercontent.com/14844435/118416750-c73d1f80-b676-11eb-8e4b-f13efe6f47a5.jpg)

Can someone help pls?

**Comment by CyberAzure** [comment]
That is actually a pretty cool idea, as a real Mac doesn't have those outlines.
But it would need to be replaced with something else, like, darkening the background of the text box for example(as some apps doesn't do this for some reason).

> Can someone help pls?

I think maybe modifying some values on the theme files?
It would take some time to find the right value, but yeah...

**Comment by rivanfebrian123** [comment]
Sorry guys, we're freezing this repo for a week for a maintainance

**Comment by mfauvain** [comment]
ok, I guess freezing = no more update but issues can still be reported.
To get rid of outlines I've tried changing all `&:focus { @include entry(focus);` to `&:focus { @include entry(normal);`
and it seems to be 'remove' the outline. however not quite the desired behaviour. but I can't find where the entry function is defined.

**Comment by vinceliuice** [comment]
Buttons and notifications outline I can remove at future updates, but entries outline I will keep it
