### ISSUE TITLE
[NAUTILUS VISUAL GLITCH] Bottom left corner not rounded after last update.

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#251]
### Hi,
Pretty self-explanatory by the title, but here's a pic to demonstrate it _better_:

![04-22-00 on segunda 17, maio 2021](https://user-images.githubusercontent.com/69485578/118447841-9fc27300-b6c7-11eb-9f2c-5ed53980698d.png)

As you can probably notice, the bottom left corner is squared and **not** rounded, for some strange reason.
This was _not happening after the last update_.
_Maybe_ relating to my last issue on #230?

**Comment by vinceliuice** [comment]
What's your nautilsu version?

**Comment by vinceliuice** [comment]
May be you are using some extension like `Blur me`?

**Comment by insanitywanted** [comment]
I can also confirm this bug. This glitch is only on solid version not in regular version.

**Comment by CyberAzure** [comment]
> What's your nautilsu version?

3.36.3-stable, comes with _Ubuntu 20.04_ by default.


> May be you are using some extension like `Blur me`?

I don't use any blur extensions, I think they're kind of bad on _GNOME_ so I don't use them.


> I can also confirm this bug. This glitch is only on solid version not in regular version.

In fact this does not happen on the normal version, only on Solid for some reason.

**Comment by vinceliuice** [comment]
Ok I'll check this

**Comment by CyberAzure** [comment]
Looks like it's fixed with the last update, somehow?
I won't close the issue because I need to know if someone else is still having this issue, but seems fixed to me.

**Comment by rivanfebrian123** [comment]
Glad to hear that! It seems like the `gtk_base` calls collide each other before, but now it was refactored (and fixed). Anyways, what about #230? Is it still there?
