### ISSUE TITLE
Root apps are not themed

### ISSUE THREAD

**Issue by insanitywanted** [vinceliuice/WhiteSur-gtk-theme#252]
When I run synaptic package manager using root permission, it isn't themed.

**Without Root (sudo)**

![synapissue1](https://user-images.githubusercontent.com/47140829/118477563-6ec85980-b72c-11eb-895a-59aa7fc1469d.png)

**With Root (sudo)**

![synapissue2](https://user-images.githubusercontent.com/47140829/118477569-70921d00-b72c-11eb-9661-84e81a07cbb4.png)

**Comment by vinceliuice** [comment]
You need install this theme with sudo

**Comment by insanitywanted** [comment]
How can I install it with sudo? I am using gnome-look version (placed the files in .themes folder). I also installed snap package for whitesur.

**Comment by vinceliuice** [comment]
Download from github then run sudo ./install.sh
