### ISSUE TITLE
Dash to Dock has another black transparent background

### ISSUE THREAD

**Issue by YusufMavzer** [vinceliuice/WhiteSur-gtk-theme#253]
![image](https://user-images.githubusercontent.com/28507059/118504666-ffeb0080-b72b-11eb-9cf9-0fe342be44ba.png)

**Comment by rivanfebrian123** [comment]
Using another extensions like "Blur My Shell" may cause this issue

**Comment by insanitywanted** [comment]
If you are using `floating dock` and `dash to dock` extension at the same time. Please try disabling the dash to dock.

**Comment by CyberAzure** [comment]
1 → Blur extensions. ↴
**Personally**, I don't have any luck with them, and they cause delay/lag on _GNOME Shell_, and thus, doesn't look as good as on _KDE_.
Disable them, remove them, or test all blur extensions until one of them finally works flawlessly.
The best extensions for blur on _GNOME_ so far is [Blur Me](https://extensions.gnome.org/extension/4236/blur-me/), [Blur My Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/)(Very glitchy on my PC), & [Blyr](https://extensions.gnome.org/extension/1251/blyr/)


2 → Dock. ↴
I recommend using _Plank_ if you want the "real" _macOS_ experience ([there's even an extension that integrates Plank with Ubuntu Dock!](https://extensions.gnome.org/extension/4198/dash-to-plank/)), but if you prefer using the Docky-Dash, try using just _Floating Dock_ and disabling all other dock extensions that you might have

**NOTE: DON'T USE PLANK WITH "BLUR ME", IT MIGHT CRASH PLANK!**
