### ISSUE TITLE
Gnome40 - Nautilus a lot of left spacing 

### ISSUE THREAD

**Issue by YusufMavzer** [vinceliuice/WhiteSur-gtk-theme#254]
![image](https://user-images.githubusercontent.com/28507059/118505097-653ef180-b72c-11eb-908a-e9bf6ffa44ed.png)

![image](https://user-images.githubusercontent.com/28507059/118505130-6cfe9600-b72c-11eb-936b-0482cde17709.png)

**Comment by rivanfebrian123** [comment]
You can resize the panel to fix this (the grip is hidden)

**Comment by insanitywanted** [comment]
I don't think this is a theme issue. You can go to list view, there is a hidden grip (just try dragging the whitespace before the "name" title to the left).

**Comment by CyberAzure** [comment]
Exactly what _@rivanfebrian123_ and _@insanitywanted_ said, i'll just make suggestions so this never happens again to new users;

The grip could be visible for everyone, or make resizing the _"invisible panel"_ impossible to do so, but that would need an separate extension or a fork of _Nautilus_ maybe.

**Comment by YusufMavzer** [comment]
Thanks 😄, it appear to be an invisible panel indeed
