### ISSUE TITLE
"gtk-base" make multi-processing not possible

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#257]
Since `color` in `for color in "${colors[@]}"; do` requires `gtk-base`, it's not possible to install them parallelly, which means, it's gonna slow down the installation process. Is that okay to make the installation process serial?

**EDIT:** but it's better for installation stability

**Comment by vinceliuice** [comment]
No problem, as long as keep the source code concise and efficient, You can choose the best way you think for installation!
