### ISSUE TITLE
[UN-RELATED] How to install icon-themes on root?

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#260]
### Hi,

I want to apply my icon theme on _root_, so when I do _`sudo nautilus`_, the icons don't change to ugly monochrome folders.
Is this possible?
I already managed to install _WhiteSur GTK Theme_ on _root_, but what about icons?

Thanks in advance.

**Comment by vinceliuice** [comment]
Just install the icon theme with sudo

**Comment by CyberAzure** [comment]
That worked with WhiteSur icon theme, thanks!
But in case someone else uses another icon theme, paste the icon theme to `usr/share/icons`.
