### ISSUE TITLE
Unable to share screen in google.meet

### ISSUE THREAD

**Issue by FieryCod** [vinceliuice/WhiteSur-gtk-theme#261]
After installing the firefox theme I'm unable to share the screen on google meet. I have tried uninstalling the theme and screen sharing now works. I have also tried this theme: https://github.com/vinceliuice/Mojave-gtk-theme and the effects are the same.

**Comment by rivanfebrian123** [comment]
What's your distro?

**Comment by FieryCod** [comment]
@rivanfebrian123  I had the same effect on both manjaro and popos

**Comment by vinceliuice** [comment]
There is a button on popover, you need choose what you want to share
![Screenshot from 2021-05-24 20-43-25](https://user-images.githubusercontent.com/7604295/119352841-c0e12000-bcd4-11eb-8ee0-d0c41da1d43e.png)

**Comment by vinceliuice** [comment]
![Screenshot from 2021-05-24 20-49-35](https://user-images.githubusercontent.com/7604295/119352874-cb031e80-bcd4-11eb-8841-0744fbc37447.png)

**Comment by FieryCod** [comment]
@vinceliuice @rivanfebrian123 Hmm. I'm trying to accept permissions, but nothing is shown.

![image](https://user-images.githubusercontent.com/14275210/119358325-c9bbfc80-bca8-11eb-9ecf-1e2b02776415.png)

This is what I have received from `journalctl`
![image](https://user-images.githubusercontent.com/14275210/119358469-f243f680-bca8-11eb-832b-1787dde7464c.png)

**Comment by vinceliuice** [comment]
'select window or screen' see that？ just click it and choose the last option then click allow

**Comment by vinceliuice** [comment]
'select window or screen' is a combobox button but lost the style, I fixed it now, download the last update and it'll show as a button now!

**Comment by FieryCod** [comment]
@vinceliuice Confirmed. After updating to the newest change I can see properly styled `select window or screen`. Before I just did not know that it's a button.

Thank you so much for your work! This theme rocks!

**Comment by vinceliuice** [comment]
You are welcome!
