### ISSUE TITLE
Tab titles for sites without favicon are not centred in Firefox theme

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#262]
[Example](https://joulev-test.netlify.app)

```html
<!DOCTYPE html>
<head><title>Test</title></head>
<body>Hello world</body>
```

![image](https://user-images.githubusercontent.com/44609036/119470219-541c6300-bd72-11eb-8aec-cb24e81be6c2.png)

**Comment by vinceliuice** [comment]
what's your firefox version？

**Comment by rivanfebrian123** [comment]
Me too
![Screenshot from 2021-05-25 16-22-17](https://user-images.githubusercontent.com/6300910/119473576-7fed1800-bd75-11eb-9a50-3af7208b04f4.png)
![Screenshot from 2021-05-25 16-22-22](https://user-images.githubusercontent.com/6300910/119473589-83809f00-bd75-11eb-96ec-cd95a1a1f90a.png)
![Screenshot from 2021-05-25 16-22-32](https://user-images.githubusercontent.com/6300910/119473598-85e2f900-bd75-11eb-9eba-02841540a5f9.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by rivanfebrian123** [comment]
Thanks!

**Comment by AdamXweb** [comment]
I've got a [fix](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commit/5d0f09a9072f65041f8f44b71bd41a519d1ae007) on my ported MacOS & Windows theme:
`/* Fix website with no favicon centred text */
.tabbrowser-tab:not([image]) .tab-icon-overlay:not([pinned], [sharing], [crashed]) .tab-icon-stack {
	margin-left: 0 !important
}
.tabbrowser-tab:not([image]) .tab-icon-stack {
	margin-left: 0 !important
}`

**Comment by joulev** [comment]
@AdamXweb It works. Thanks a lot :)

**Comment by rivanfebrian123** [comment]
> I've got a [fix](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commit/5d0f09a9072f65041f8f44b71bd41a519d1ae007) on my ported MacOS & Windows theme:
> `/* Fix website with no favicon centred text */ .tabbrowser-tab:not([image]) .tab-icon-overlay:not([pinned], [sharing], [crashed]) .tab-icon-stack { margin-left: 0 !important } .tabbrowser-tab:not([image]) .tab-icon-stack { margin-left: 0 !important }`

That's awesome! You can just open a PR then

**Comment by AdamXweb** [comment]
#277

**Comment by rivanfebrian123** [comment]
Thanks for your effort fixing this issue

**Comment by vinceliuice** [comment]
Thanks, It's fixed now!

**Comment by AdamXweb** [comment]
Glad to help!
