### ISSUE TITLE
Can't install FireFox Theme

### ISSUE THREAD

**Issue by dmytro-udovychenko** [vinceliuice/WhiteSur-gtk-theme#264]
ERROR LOG:
cp: target '/home/biz/.mozilla/firefox/firefox-themes' is not a directory

There is no firefox-themes directory yet. Manually creation is not help.

FireFox version: 88.0.1 (64-bit)

**Comment by dmytro-udovychenko** [comment]
[Here](http://kb.mozillazine.org/Profile_folder_-_Firefox) is described URLs for FireFox in Ubuntu.

**Comment by rivanfebrian123** [comment]
What is your distro?

**Comment by dmytro-udovychenko** [comment]
Ubuntu 21.04
Gnome version: Ubuntu 21.04

**Comment by dmytro-udovychenko** [comment]
Maybe you have some other maual installation ways?

**Comment by rivanfebrian123** [comment]
This boy: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/9e81febd09197278e047213f9bd5ab552aac18fc/src/other/firefox/README.md

Anyways, I'm downloading Ubuntu 21.04 now

**Comment by dmytro-udovychenko** [comment]
Thanks, [this](https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/9e81febd09197278e047213f9bd5ab552aac18fc/src/other/firefox/README.md) is very helpful for me.
