### ISSUE TITLE
Dark-solid shell themes no bold texts in top bar

### ISSUE THREAD

**Issue by Roknauta** [vinceliuice/WhiteSur-gtk-theme#268]
When i select a dark-solid option in Shell Themes the text of top bar not render with bold effect.

![Screenshot from 2021-05-27 14-22-35](https://user-images.githubusercontent.com/7780234/119870093-5b20ae00-bef7-11eb-858c-f2cb8c13e3df.png)

**Comment by vinceliuice** [comment]
Only HD version is bold

**Comment by vinceliuice** [comment]
Run `./install.sh -HD`
