### ISSUE TITLE
How to clean uninstall the theme pack.

### ISSUE THREAD

**Issue by vinaykumar7686** [vinceliuice/WhiteSur-gtk-theme#269]
Texts and Pictures are overlapping. Unable to perform daily tasks after installing. 
I am not able to completely remove the theme, some traces of it are left at some places. Please help me!!

**Comment by rivanfebrian123** [comment]
Please provide as much info as possible, even just a screenshot, so we can help you out

**Comment by vinaykumar7686** [comment]
Everything has become misaligned after installing. Please help me in finding the solution.

One such screenshot attached. 
![Screenshot from 2021-05-28 17-27-23](https://user-images.githubusercontent.com/49321180/119980587-1f124980-bfda-11eb-82cd-ba6c95cb1aad.png)

**Comment by rivanfebrian123** [comment]
On old Ubuntu versions, you also need to install the GDM theme to make it work perfectly with GNOME Shell

**Comment by vinceliuice** [comment]
If you want to uninstall this theme you can run: `./install.sh -r`

**Comment by vinaykumar7686** [comment]
> On old Ubuntu versions, you also need to install the GDM theme to make it work perfectly with GNOME Shell

I am on the latest stable version of Zorin OS. I guess that might not be the problem.

**Comment by vinaykumar7686** [comment]
> If you want to uninstall this theme you can run: `./install.sh -r`

Thanks a lot!!

**Comment by rivanfebrian123** [comment]
> > On old Ubuntu versions, you also need to install the GDM theme to make it work perfectly with GNOME Shell
> 
> I am on the latest stable version of Zorin OS. I guess that might not be the problem.

Hmm...
