### ISSUE TITLE
Color of Bookmarks in FireFox

### ISSUE THREAD

**Issue by dmytro-udovychenko** [vinceliuice/WhiteSur-gtk-theme#270]
![Screenshot-20210528115453-166x73](https://user-images.githubusercontent.com/81159289/119958250-895fc580-bfab-11eb-9265-d182f443514a.png)

How to change color of Bookmark folders and single Bookmarks to white or grey?

**Comment by rivanfebrian123** [comment]
![Screenshot from 2021-05-28 16-01-34](https://user-images.githubusercontent.com/6300910/119959220-fdab6080-bfcd-11eb-8d51-b6ee1141ff4c.png)
It's already white

**Comment by dmytro-udovychenko** [comment]
Oh, see that the white theme was enabled. After switching to black firefox theme Bookmark colors changed to white.

**Comment by rivanfebrian123** [comment]
Awesome!
