### ISSUE TITLE
Nautilus visual glitch

### ISSUE THREAD

**Issue by dmytro-udovychenko** [vinceliuice/WhiteSur-gtk-theme#271]
I've enable WhiteSur-Dark (not solid) and have some visual glitches in Nautilus.
This happened when mouse focused on the top bar navigation
![Screenshot-20210528122016-380x75](https://user-images.githubusercontent.com/81159289/119961773-17897b00-bfaf-11eb-939f-9e2cbfbfccc1.png)
And this when I click on the Home button:
![Screenshot-20210528122052-412x304](https://user-images.githubusercontent.com/81159289/119961914-3a1b9400-bfaf-11eb-9d68-8ce6907572f6.png)

Also I use Nvidia latest driver
![Screenshot-20210528122251-784x677](https://user-images.githubusercontent.com/81159289/119962161-6e8f5000-bfaf-11eb-9beb-5b1a35aae14c.png)

System:
![Screenshot-20210528122339-613x442](https://user-images.githubusercontent.com/81159289/119962296-8ff03c00-bfaf-11eb-9201-4567034b0ac5.png)

**Comment by vinceliuice** [comment]
Nvidia driver will have this issue, Cannot be repaired at this time
