### ISSUE TITLE
Any idea for this?

### ISSUE THREAD

**Issue by theycallmecharlie** [vinceliuice/WhiteSur-gtk-theme#272]
How can i fix this 
~ Deb Buster
![SearchOverview](https://user-images.githubusercontent.com/38168227/120064849-ad231a00-c044-11eb-97db-07947453976a.png)

**Comment by vinceliuice** [comment]
Update your gnome-shell, not support for older version <= 3.36

**Comment by theycallmecharlie** [comment]
I didn't pay attention to my version of the gnome... Unfortunately, i'll have to wait for a stable version of gnome-shell for deb buster XD. The gnome version 38, only on Deb bullseye for now. 

Thx vince

**Comment by rivanfebrian123** [comment]
![Screenshot from 2021-05-31 08-22-46](https://user-images.githubusercontent.com/6300910/120127367-6884b380-c1e9-11eb-8efa-31ffc704574a.png)
Note that GNOME Shell and GDM are different eventho they're collaborating each other

**Comment by rivanfebrian123** [comment]
> I didn't pay attention to my version of the gnome... Unfortunately, i'll have to wait for a stable version of gnome-shell for deb buster XD. The gnome version 38, only on Deb bullseye for now.
> 
> Thx vince

Wait, how did you upgrade your GNOME to 38.x? 
![Screenshot from 2021-05-31 08-39-13](https://user-images.githubusercontent.com/6300910/120128244-c74b2c80-c1eb-11eb-991e-095d5edc1d60.png)

**Comment by theycallmecharlie** [comment]
> > I didn't pay attention to my version of the gnome... Unfortunately, i'll have to wait for a stable version of gnome-shell for deb buster XD. The gnome version 38, only on Deb bullseye for now.
> > 
> > Thx vince
> 
> Wait, how did you upgrade your GNOME to 38.x? 
> ![Screenshot from 2021-05-31 08-39-13](https://user-images.githubusercontent.com/6300910/120128244-c74b2c80-c1eb-11eb-991e-095d5edc1d60.png)
> 

Deb Buster doesn't support Gnome 38, well, at least I haven't found it... But what you can try to do is use Deb Bullseye (still in testing) and it comes with Gnome 3.38.4

**Comment by theycallmecharlie** [comment]
> > > I didn't pay attention to my version of the gnome... Unfortunately, i'll have to wait for a stable version of gnome-shell for deb buster XD. The gnome version 38, only on Deb bullseye for now.
> > > Thx vince
> > 
> > 
> > Wait, how did you upgrade your GNOME to 38.x?
> > ![Screenshot from 2021-05-31 08-39-13](https://user-images.githubusercontent.com/6300910/120128244-c74b2c80-c1eb-11eb-991e-095d5edc1d60.png)
> 
> Deb Buster doesn't support Gnome 38, well, at least I haven't found it... But what you can try to do is use Deb Bullseye (still in testing) and it comes with Gnome 3.38.4

![image](https://user-images.githubusercontent.com/38168227/120306204-0048d700-c2a8-11eb-8155-82d7cddc233a.png)
