### ISSUE TITLE
Please help me revert the settings of ./tweaks.sh (I don't know exactly that it is done by that) on my default shell of gnome 40 !!!!!!

### ISSUE THREAD

**Issue by Anshum-Bhargav** [vinceliuice/WhiteSur-gtk-theme#278]
![Screenshot from 2021-05-30 20-53-12](https://user-images.githubusercontent.com/70581590/120109990-6e4aac80-c189-11eb-8527-211a69dd3dac.png)
as you can see, I am not using whitesur theme but still somehow my default theme is just overwrite by I don't know ./tweaks.sh I think. pls help me! I have just started to use linux (I think like a week or something). 

BTW I am using fedora 34 with gnome 40.

**Comment by vinceliuice** [comment]
run sudo ./tweaks.sh -g -r

**Comment by Anshum-Bhargav** [comment]
Thank you sir !!! 

You are a life saver !
