### ISSUE TITLE
[Request] Flatpak support

### ISSUE THREAD

**Issue by anthonyajumelles** [vinceliuice/WhiteSur-gtk-theme#28]
Preferably via Flathub, so all applications can access the theme easily.

**Comment by thenexus7** [comment]
That'd be awesome to have ! :+1:

**Comment by maydayv7** [comment]
Flatpak apps can be made to access '.themes` in /home, so it is not necessary to make it available on flathub

**Comment by charlesngeru** [comment]
> Flatpak apps can be made to access `.themes` in /home, so it is not necessary to make it available on Flathub

How can one do that??

**Comment by anthonyajumelles** [comment]
> > Flatpak apps can be made to access `.themes` in /home, so it is not necessary to make it available on Flathub
> 
> How can one do that??

Install FlatSeal on Flathub. Once you have it open, you can set what folders apps have access to. 

Enable access to ~.themes

**Comment by charlesngeru** [comment]
> > > Flatpak apps can be made to access `.themes` in /home, so it is not necessary to make it available on Flathub
> > 
> > 
> > How can one do that??
> 
> Install the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) app. It allows you to set permissions for Flatpak apps that they wouldn't have by default on installation.
> 
> Once you have it open, you can enable access to the ~.themes folder.
> 
> After that, you can open a Flatpak app and they'll use the theme your system is set to if it's one you downloaded outside of a Flatpak database.

So, At the **'Filesystem'** section, add _~/.themes_ as 'Other **files'** ??

**Comment by anthonyajumelles** [comment]
Bingo!

**Comment by charlesngeru** [comment]
Awesome! It works. 

Thank you for taking the time to assist me! Much appreciated.

**Comment by charlesngeru** [comment]
> Bingo!
> […](#)
> On August 25, 2021 12:41:15 PM EDT, Charles Ngeru ***@***.***> wrote: > > > Flatpak apps can be made to access `.themes` in /home, so it is not necessary to make it available on Flathub > > > > > > How can one do that?? > > Install the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) app. It allows you to set permissions for Flatpak apps that they wouldn't have by default on installation. > > Once you have it open, you can enable access to the ~.themes folder. > > After that, you can open a Flatpak app and they'll use the theme your system is set to if it's one you downloaded outside of a Flatpak database. So, At the **'Filesystem'** section, add _~/.themes_ as 'Other **files'** ?? -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#28 (comment)](https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/28#issuecomment-905697259)

Awesome! It works. 

Thank you for taking the time to assist me! Much appreciated.

**Comment by fr3nchalp4a** [comment]
@vinceliuice please close as it is resolved 😉
