### ISSUE TITLE
Search Suggestions Scrolling Broken

### ISSUE THREAD

**Issue by hackingguy** [vinceliuice/WhiteSur-gtk-theme#284]
While clicking screenshot it auto corrects, so using mobile camera
OS: Manjaro 21 (Gnome)
![photo_2021-06-02_14-45-44](https://user-images.githubusercontent.com/28388650/120454302-62d9ca00-c3b1-11eb-928a-52683abe6bd8.jpg)

**Comment by vinceliuice** [comment]
Fixed!

**Comment by hackingguy** [comment]
Sorry, can u confirm, its still broken!

**Comment by vinceliuice** [comment]
![截图_2021-06-02_20-41-51](https://user-images.githubusercontent.com/7604295/120481806-11e2c980-c3e3-11eb-8039-ee8854f094d8.png)

**Comment by vinceliuice** [comment]
I tested on manjaro 21, it's fixed!

**Comment by CyberAzure** [comment]
Also happens to me, Ubuntu 20.04.
But, this is a GPU problem as it seems to happen even without the theme, and thus, happens on other Distros I've used too!
This has something to do with Vertical Sync probably.
