### ISSUE TITLE
The firefox theme not in Sync with the latest version of firefox(firefox 89)

### ISSUE THREAD

**Issue by asif-hoda** [vinceliuice/WhiteSur-gtk-theme#286]
The firefox theme just got messed up due to the new changes in the latest update. The tabs are not synced, buttons are wierd, etc. Please fix this.

**Comment by rivanfebrian123** [comment]
Yeah, Firefox has revamped their UI. Here's the current workaroud: https://geekermag.com/how-to-enable-new-proton-firefox-ui/. Anyway, I saw @AdamXweb is working on WhiteSur Proton theme in his repo branch

**Comment by vinceliuice** [comment]
I'll fix it!
