### ISSUE TITLE
New Firefox update (FF 89.0) broke some design in URL bar and tab bar

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#289]
Yesterday I updated FF to FF 89.0. It comes with new design in a lot of components, but it is causing some problems when applying custom themes. Some of them has been fixed but these are still outstanding:

The newly-added "PLAYING" made the tab look quite bad. <strike>Also the new design of site information part ("Extension (Tabliss)" box) fits badly to the theme.</strike>

![image](https://user-images.githubusercontent.com/44609036/120730598-06d78880-c50c-11eb-9673-c8aaf5a886ff.png)

The contrast in the URL dropdown is not good either.

![image](https://user-images.githubusercontent.com/44609036/120730999-e1974a00-c50c-11eb-9547-4eb2f4bb48ba.png)

EDIT
* Site information part fixed in https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/05f705b474b814618be2bd8de3b3f212542f60ec

**Comment by Shawn-sudo** [comment]
I think there are several things that we can do currently
1. Wait for the change of this theme: Might take a long time
2. Downgrade firefox: Since the update is not about new features but mainly about UI, I personally think that it would be okay to downgrade it.
It is well shown at [here](https://support.mozilla.org/en-US/kb/install-older-version-firefox)
4. Just don't use this firefox theme
I personally think that this firefox UI looks great, so you can just give it a try by setting "toolkit.legacyUserProfileCustomizations.stylesheets" as false.

**Comment by joulev** [comment]
@Shawn-sudo Thanks for your comment. Here are my thoughts:

> I think there are several things that we can do currently
> 
> 1. Wait for the change of this theme: Might take a long time

To wait for a release, yes. But to wait for the commit that fixes this, it probably won't be long. Once the fix is commited I can just clone this repo, copy the Firefox subdirectory to my `chrome` and use the updated theme.
> 
> 2. Downgrade firefox: Since the update is not about new features but mainly about UI, I personally think that it would be okay to downgrade it.
>    It is well shown at [here](https://support.mozilla.org/en-US/kb/install-older-version-firefox)

I am quite hesitant to use another profile &ndash; Firefox says I have to make a new user profile if I downgrade. There are definitely ways to work around this but, well, for a person who always update whenever new releases are available like me, downgrading just doesn't feel right.
> 
> 3. Just don't use this firefox theme
>    I personally think that this firefox UI looks great, so you can just give it a try by setting "toolkit.legacyUserProfileCustomizations.stylesheets" as false.

It looks great to me too, but I still prefer this Safari-inspired Firefox theme with tab spanning over the full width and clean design and etc etc. To listen to Spotify I also have the desktop app installed too, so to me the mentioned design problems don't matter much and I can live with it for now (just report here as I do whenever I find a bug).

**Comment by joulev** [comment]
A new Monterey theme has been made, so closing this ticket.
