### ISSUE TITLE
Read view and private window icons need a correction 

### ISSUE THREAD

**Issue by IDOHAVENOT** [vinceliuice/WhiteSur-gtk-theme#29]
![Screenshot from 2020-08-03 12-45-51](https://user-images.githubusercontent.com/64141145/89179455-a001df80-d587-11ea-9b24-ccec573a71c8.png)
![Screenshot from 2020-08-03 12-47-12](https://user-images.githubusercontent.com/64141145/89179475-a8f2b100-d587-11ea-9cff-1fd698f5fc99.png)
Read view and private window icons need

**Comment by mBilG** [comment]
For the private icon: you can change it under parts > headerbar-private-urlbar.css
I personally change: height to 32px and top to 8
you may have other preferences.
![Screenshot from 2020-08-04 21-48-46](https://user-images.githubusercontent.com/63431684/89301629-78506b80-d69c-11ea-8fba-4a452ed600b8.png)

**Comment by vinceliuice** [comment]
Thanks @mBilG
