### ISSUE TITLE
Changing Activities icon not working Ubuntu 20 Gnome 40

### ISSUE THREAD

**Issue by mech243** [vinceliuice/WhiteSur-gtk-theme#290]
Nothing changes when I use the command `./install.sh -i ubuntu
`

I get the output of:
![Screenshot from 2021-06-05 23-09-07](https://user-images.githubusercontent.com/38262690/120906648-16adb480-c653-11eb-80c0-4da5949ffd81.png)

but the icon is still an Apple logo while I want it to be the Ubuntu logo. Not sure what I'm doing wrong here, any help would be appreciated

**Comment by vinceliuice** [comment]
![2021-06-06 08-19-03 的屏幕截图](https://user-images.githubusercontent.com/7604295/120908731-e3dddd80-c69f-11eb-86b1-0f4065ea80c4.png)
I tested on my gnome 40, but all works well!

**Comment by vinceliuice** [comment]
Could you show me your desktop screenshot?

**Comment by mech243** [comment]
![image](https://user-images.githubusercontent.com/38262690/120908938-65654980-c667-11eb-881b-e9b228742f4e.png)
Here you go
And thanks for the help

**Comment by vinceliuice** [comment]
Did you try relogin your desktop?

**Comment by vinceliuice** [comment]
Or are you using Arcmenu?

**Comment by mech243** [comment]
I restarted and it's working fine now, sorry for the trouble
