### ISSUE TITLE
Button color problem

### ISSUE THREAD

**Issue by Shawn-sudo** [vinceliuice/WhiteSur-gtk-theme#291]
I found this when I was uninstalling an app through Software. When I was doing this, it showed me to authenticate my self. Before pressing the "authenticate" button, the button is red. However, when I press the red "authenticate" button after typing my password, it turns to blue.

*Before pressing the button
![Screenshot from 2021-06-06 00-08-57](https://user-images.githubusercontent.com/60294318/120912240-9049a080-c65b-11eb-9ae1-908966eaa975.png)

*After pressing the button
![Screenshot from 2021-06-06 00-09-00](https://user-images.githubusercontent.com/60294318/120912244-993a7200-c65b-11eb-9cb3-e1530fd303f0.png)

**Comment by vinceliuice** [comment]
I'll fix this!
