### ISSUE TITLE
Clear Linux Support

### ISSUE THREAD

**Issue by kelvinmarshall** [vinceliuice/WhiteSur-gtk-theme#292]
Thanks for the great theme. I have been using it in clear Linux but after GNome 40 upgrade it doesn't work anymore.

**Logs**

Oops! Operation has been aborted or failed...

  =========== ERROR LOG ===========
  >>> Unable to detect release version (use '--releasever' to specify release version)
  >>> Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-install.sh at 65
    >>> tweaks.sh
  SNIPPET:
    >>> dnf install -y glib2-devel libxml2 sassc
  TRACE  :
    >>> operation_aborted
    >>> rootify
    >>> install_gdm_deps
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : clear-linux-os;clear-linux-os;34700;34700
  SUDO   : yes
  GNOME  : new
  REPO   : 2021-06-06T18:12:43+0300

**Comment by rivanfebrian123** [comment]
Thanks for reporting. I'm testing it!

![Screenshot from 2021-06-07 06-36-48](https://user-images.githubusercontent.com/6300910/120943708-d46f9a80-c75a-11eb-8c16-e74e441f238a.png)

**Comment by kelvinmarshall** [comment]
@rivanfebrian123 Thanks. Let me know of any adjustments or tweaks I need to do to the install scripts.

**Comment by rivanfebrian123** [comment]
Oh yeah, you guys use `dnf` for installing software?
