### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#293]
Would you mind relicensing this project to MIT? You know, GPL 3 is way too strict and some people doesn't really follow it. Take some example:

- https://github.com/FirefoxCSSThemers/WhiteSur-Tweaked
- https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS
- https://github.com/Raayib/WhiteSur-Light-ulauncher

MIT is actually good for project like this:

- https://github.com/yxqsnz/mac-os-transformation-script-for-linux/issues/1

That's it. Thanks

**Comment by vinceliuice** [comment]
I don’t know about these Licenses, if you think mit is better, then we can change to mit.

**Comment by rivanfebrian123** [comment]
Okay, I'm editing it
