### ISSUE TITLE
Unable to install snap theme

### ISSUE THREAD

**Issue by domiden** [vinceliuice/WhiteSur-gtk-theme#295]
First, many thanks for your hard work!

During the installation process of the snap theme, an error occurred, preventing the process from being completed.

```bash
gtk-3-themes whitesur-gtk-theme:gtk-3-themes
  TRACE  :
    >>> operation_aborted
    >>> rootify
    >>> connect_snap
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;"21.04"
  SUDO   : yes
  GNOME  : old
  REPO   : 2021-06-06T17:12:43+0200
```

Last pull: commit a862249442833edba73d7857a17f2a3f6836a9bc

If you need additional infos, just let me know.

**Comment by rivanfebrian123** [comment]
No error log?

**Comment by domiden** [comment]
Wired, I've just got that terminal output:

![Screenshot from 2021-06-07 11-32-25](https://user-images.githubusercontent.com/24540355/120993796-2e388a80-c784-11eb-99bd-4cef095fdccb.png)

No, I don't have any issues with the internet connection.

**Comment by rivanfebrian123** [comment]
I think you need to upgrade your system. You know, it supposed to be like this:

![Screenshot from 2021-06-07 16-46-04](https://user-images.githubusercontent.com/6300910/120995725-df084f00-c7af-11eb-9898-6a5e7e5bc7da.png)

**Comment by domiden** [comment]
Strange. Last week it worked perfectly fine. I'll check the system logs and come back if I won't have been able to solve it by myself. Thanks for your quick response!

**Comment by rivanfebrian123** [comment]
Your welcome. Anyway, can you run `journalctl -p 3 > /path/to/file.txt` and send the result here?
