### ISSUE TITLE
File Explorer (Nautilus) style broken

### ISSUE THREAD

**Issue by delucca** [vinceliuice/WhiteSur-gtk-theme#297]
Hi everyone.

Congrats on the lib! It is pretty impressive the quality and how easy it is to install. I've been ricing my workstations for a long time and I've never seen something so well developed and easy to install!

Anyway, I've been facing a minor issue with my file explorer. While hovering the sidebar, for some reason it breaks the style of the items. I've recorded a video showing that [in this link](https://drive.google.com/file/d/1soPeR9GqhscQsFIQz8n41x0uvXDFQaRJ/view?usp=sharing)

Does anyone know how to fix it?

**Comment by rivanfebrian123** [comment]
Your welcome!

> Anyway, I've been facing a minor issue with my file explorer. While hovering the sidebar, for some reason it breaks the style of the items. I've recorded a video showing that in this link

We're sorry. We can't really do anything with that. It's either NVIDIA or GTK problem. Here's the upstream bug report: https://forums.developer.nvidia.com/t/issues-with-icons-gtk-theme-and-other-graphical-components-prior-to-installation-of-nvidia-drivers/38618

**Comment by delucca** [comment]
> Your welcome!
> 
> > Anyway, I've been facing a minor issue with my file explorer. While hovering the sidebar, for some reason it breaks the style of the items. I've recorded a video showing that in this link
> 
> We're sorry. We can't really do anything with that. It's either NVIDIA or GTK problem. Here's the upstream bug report: https://forums.developer.nvidia.com/t/issues-with-icons-gtk-theme-and-other-graphical-components-prior-to-installation-of-nvidia-drivers/38618

Thanks for the quick response!

Damn! This bug is open since 2015 😮 

Do you have any idea what I could do as a workaround for that? Do you know if that same issue is happening with open source drivers? Or only Nvidia proprietary drivers?

**Comment by rivanfebrian123** [comment]
Open source drivers like MESA etc. doesn't have any glitches like this so far

**Comment by delucca** [comment]
Thanks. I'll try switching to open-source driver!

It is sad that Nvidia does not give a damn for Linux users :/

Anyway, thanks for your quick responses! Again, congrats on the theme :)

**Comment by delucca** [comment]
Thanks @rivanfebrian123 I've just switched to `video-linux` open-source driver and now it is fixed!

Closing it :)

**Comment by rivanfebrian123** [comment]
> It is sad that Nvidia does not give a damn for Linux users :/
Yeah, proprietary software make it harder for other developers outside the team to debug and looking for their vulnerabilities and even to collaborate with

> Thanks @rivanfebrian123 I've just switched to video-linux open-source driver and now it is fixed!
Your welcome and glad to hear that!
