### ISSUE TITLE
Issue with Navigation Bar in WhiteSur-light-solid theme

### ISSUE THREAD

**Issue by hemanthsavasere** [vinceliuice/WhiteSur-gtk-theme#299]
Hi,

First of all, it's an amazing library and the look and feel is awesome. I'm in love with it and I hope this project would reach greater heights. 

I'm facing the issue with WhiteSur-light-solid theme, while hovering and clicking on the he forward and backward buttons on the sidebar, for some reason it breaks the style of the items. I've attached the video link for the same.

[WhiteSur Sidebar Navigation Issue](https://drive.google.com/file/d/1o66raWEKIN6G0Zwjj4Ewx-6DeuZgvjGL/view?usp=sharing)

**Comment by anilms** [comment]
Confirming another issue with the sidebar with WhiteSur-light-solid.
When you drag the sidebar to expand width, the sidebar border moves forward. but the sidebar color does not expand. It seems to be fixed width.

Also, thanks for the amazing work.

![Screenshot from 2021-06-08 15-33-52](https://user-images.githubusercontent.com/2180008/121266376-433e1800-c86f-11eb-8f0a-ff0edd23361f.png)

**Comment by rivanfebrian123** [comment]
> First of all, it's an amazing library and the look and feel is awesome. I'm in love with it and I hope this project would reach greater heights.

> Also, thanks for the amazing work.

Thank you guys! And Alhamdulillah

> I'm facing the issue with WhiteSur-light-solid theme, while hovering and clicking on the he forward and backward buttons on the sidebar, for some reason it breaks the style of the items. I've attached the video link for the same.

Doesn't happen here. Probably NVIDIA issue

> Confirming another issue with the sidebar with WhiteSur-light-solid.

Well, this is actually intended. Use `-N normal` to fix this (default is `stable`)

**Comment by anilms** [comment]
Thanks for the reply. It worked.

For --nautilus-style, i saw three options,
```
  -N, --nautilus-style [default|stable|mojave|glassy]
 Set Nautilus style. Default is BigSur-like style
```

Both mojave and glassy worked. Sidebar color extended when it was dragged.

**Comment by rivanfebrian123** [comment]
Youre welcome!

**Comment by hemanthsavasere** [comment]
Hi, 
Yes, I checked it and this issue is happening due to NVIDIA drivers. I think we can close the ticket .
