### ISSUE TITLE
Ubuntu Software center is totally transparent and not usable

### ISSUE THREAD

**Issue by AliAbdelaal** [vinceliuice/WhiteSur-gtk-theme#30]
After enabling the theme i ended up with ubuntu software center totally transparent and cannot use it
![gnome-shell-screenshot-5RMRO0](https://user-images.githubusercontent.com/22421898/89397499-37923a00-d710-11ea-8b6d-244938b1c344.png)

**Comment by mBilG** [comment]
Are you using the correct theme?

**Comment by AliAbdelaal** [comment]
> Are you using the correct theme?

Yes, downloaded it via gnomelooks https://www.gnome-look.org/p/1403328/

**Comment by mBilG** [comment]
It seems something else is causing this.. Maybe graphics?
the close,maximize,minimize buttons have not changed.. you may have to look into that

**Comment by AliAbdelaal** [comment]
> It seems something else is causing this.. Maybe graphics?
> the close,maximize,minimize buttons have not changed.. you may have to look into that

When i use the Yaru theme it works fine, but i am using Nvidia driver as GPU, do you suggest it has something to do with that ?

**Comment by mBilG** [comment]
To be completely honest i'm not a pro when it comes to troubleshooting linux.
Maybe you can try to run on a different graphics if you can.
or try to create a new user and test
Or try with a VM or a live disk
Or let's wait for someone with more knowledge to help us.

**Comment by fossfreedom** [comment]
This is a snap issue .... nothing to do with this theme. Any gtk theme that is not in the common-themes snap will have this problem.

The snap in question should default to adwaita but doesn't. 


Theming support is still being worked on for snaps.

**Comment by AliAbdelaal** [comment]
> This is a snap issue .... nothing to do with this theme. Any gtk theme that is not in the common-themes snap will have this problem.
> 
> The snap in question should default to adwaita but doesn't.
> 
> Theming support is still being worked on for snaps.

Yes exactly, the issue was that the store was a snap package, i removed it and downloaded the deb one, and now it works great, do you know how to add the theme to the common-themes so that it could be recognized on snap applications ?

**Comment by fossfreedom** [comment]
They are not accepting new themes into common-themes.

When theme handling is released then this theme will need to be packaged as a snap.

Any snaps such as ubuntu-software that requires a theme will look for the equivalent snap and autoinstall it.

**Comment by spider623** [comment]
the issue is that the theme is not available as a snap yet, you can create a custom gtk3 config and point it to mojave dark or light that are snap available themes, you will need to install and connect the themes first

**Comment by sanjaygeeky** [comment]
Hello This seems to be annoying as the transparent does not allow you to do anything

**Comment by vinceliuice** [comment]
You can install the theme from the Snap Store оr by running:

sudo snap install whitesur-gtk-theme

To connect the theme to an app run:

sudo snap connect [other snap]:gtk-3-themes whitesur-gtk-theme:gtk-3-themes
