### ISSUE TITLE
[QUESTION] Now with the "release" of macOS Monterey, will the theme be updated?

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#300]
Like, changing the name, the _Firefox_ theme & etc.
For me, just by changing the name and the _Firefox_ theme will be a great step.

If you don't know what I'm talking about: https://www.apple.com/macos/monterey-preview

**Comment by vinceliuice** [comment]
Firefox do not support to move the tabsbar on titlebar, so I can't make a theme like Monterey safari for firefox!

**Comment by rivanfebrian123** [comment]
@vinceliuice Could you please recreate those Apple wallpapers? :)

**Comment by CyberAzure** [comment]
> Firefox do not support to move the tabsbar on titlebar, so I can't make a theme like Monterey safari for firefox!

Aw man... I hope someone creates a new browser that resembles this new Safari look.

> @vinceliuice Could you please recreate those Apple wallpapers? :)

I sure do want those too ;].

**Comment by SwapnilNair** [comment]
> Firefox do not support to move the tabsbar on titlebar, so I can't make a theme like Monterey safari for firefox!

Hey vince,not entirely true.I do have a theme that moves the tabs next to the address bar.The buttons are a little jankily positioned though,but everything works fine.
![Screenshot from 2021-06-11 18-59-45](https://user-images.githubusercontent.com/61003297/121815504-724ff180-cc94-11eb-8bda-955c21293c0d.png)

**Comment by SwapnilNair** [comment]
> @vinceliuice Could you please recreate those Apple wallpapers? :)

Hey @CyberAzure ,https://512pixels.net/projects/default-mac-wallpapers-in-5k/ should be the wallpaper you were looking for.I personally like the dark one.Do note that its a 22mb file though.

**Comment by rivanfebrian123** [comment]
> > Firefox do not support to move the tabsbar on titlebar, so I can't make a theme like Monterey safari for firefox!
> 
> Hey @vinceliuice ,not entirely true.I do have a theme that moves the tabs next to the address bar.The buttons are a little jankily positioned though,but everything works fine.
> ![Screenshot from 2021-06-11 18-59-45](https://user-images.githubusercontent.com/61003297/121815504-724ff180-cc94-11eb-8bda-955c21293c0d.png)
> PS: the buttons,hamburger menu and that >> thing are completely removable,I just use them a lot.

That's a good news. You know where the source code is?

**Comment by vinceliuice** [comment]
@SwapnilNair Could you tell me where I can get this firefox theme？

**Comment by SwapnilNair** [comment]
https://github.com/SwapnilNair/SafariFox
I've put it up on my Github .

**Comment by vinceliuice** [comment]
Thanks! I will check this theme, as long as it looks like this, designing the latest safari theme will not be a problem

**Comment by SwapnilNair** [comment]
Great!Looking forward to it.

**Comment by rivanfebrian123** [comment]
Keep going guys!

**Comment by vinceliuice** [comment]
Added here: https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/src/other/firefox/Monterey
![2021-06-16 20-04-59屏幕截图](https://user-images.githubusercontent.com/7604295/122215745-298b7900-cede-11eb-82e2-4e4d7e0c8f80.png)

**Comment by vinceliuice** [comment]
Run `./tweaks.sh -f -e`
change :
```
@import "WhiteSur/theme.css"; /**/
/*@import "Monterey/theme.css"; /**/
```
to :
```
/*@import "WhiteSur/theme.css"; /**/
@import "Monterey/theme.css"; /**/
```

**Comment by rivanfebrian123** [comment]
Nice work! Waiting for a fix for this:

![Screenshot from 2021-06-16 19-58-24](https://user-images.githubusercontent.com/6300910/122223377-4d01f400-cedd-11eb-9be7-ca9e01deb4fb.png)

**Comment by vinceliuice** [comment]
This is not easy to fix, because the current way to achieve this appearance is to move the `tabs bar` to the top, so automatic adjustment cannot work according to the button on the headerbar. I can only set a specific left offset pixel value, so you need to remove the sidebar button and home button on the left to make it display properly!

**Comment by vinceliuice** [comment]
![Screenshot_20210616_215316](https://user-images.githubusercontent.com/7604295/122231814-52673a80-ceed-11eb-975a-1276510e1425.png)
-------------------
I added some options for buttons number on headerbar
```
/* buttons on left headerbar */
@import "left_header_button_3.css";
/*@import "left_header_button_4.css";*/
/*@import "left_header_button_5.css";*/

/* buttons on right headerbar */
@import "right_header_button_3.css";
/*@import "right_header_button_4.css";*/
/*@import "right_header_button_5.css";*/
```

**Comment by vinceliuice** [comment]
You have 5 buttons on left then use `@import "left_header_button_5.css`

**Comment by vinceliuice** [comment]
And don't forget to remove the spaces on left side!

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by CyberAzure** [comment]
### Thank you all!

Now I just feel like this repo having the name "_WhiteSur_" is unfitting, but I _think_ it's impossible to change it without creating a entirely new repo.
Maybe _WhiteRey_?
Well, "_Monte_" means Mountain in Portuguese, so I think "_WhiteMountain_" would be cooler.
Anyways, I can use `-n` on the installation and change de name of the theme to _Monterey_ without any issues.
**Thank you** so much @SwapnilNair, @rivanfebrian123 & @vinceliuice!
