### ISSUE TITLE
Rounded corners visual bug with new Firefox 89.

### ISSUE THREAD

**Issue by nvt194** [vinceliuice/WhiteSur-gtk-theme#301]
I'm recently upgraded to firefox 89 and rounded corner on firefox looks like a mixture of rounded and straigh edges. I'm using pop os 20.10 but I think Ubuntu would have the same issues. Could you take a look at this. Thanks.
![1](https://user-images.githubusercontent.com/66350350/121796356-edb79180-cc07-11eb-8f84-c655174fed70.png)
![2](https://user-images.githubusercontent.com/66350350/121796359-f27c4580-cc07-11eb-8b4e-bd11e5195af4.png)

**Comment by rama-2402** [comment]
I have the same issue with dark theme in nautilus and settings panel. 
![DeepinScreenshot_select-area_20210613114124](https://user-images.githubusercontent.com/68183781/121797198-57ea2980-cc3c-11eb-90e5-1aa2d7e07021.png)

**Comment by SwapnilNair** [comment]
Unfortunately I think its got something to do with the way the system renders the bottom edges themselves(at least on Ubuntu and EOS). Maybe try tweaking the corner radius till it looks acceptable to you.

**Comment by CyberAzure** [comment]
> I'm recently upgraded to firefox 89 and rounded corner on firefox looks like a mixture of rounded and straigh edges. I'm using pop os 20.10 but I think Ubuntu would have the same issues. Could you take a look at this. Thanks.
> ![1](https://user-images.githubusercontent.com/66350350/121796356-edb79180-cc07-11eb-8f84-c655174fed70.png)
> ![2](https://user-images.githubusercontent.com/66350350/121796359-f27c4580-cc07-11eb-8b4e-bd11e5195af4.png)

This is a well know error, as [this](https://www.omgubuntu.co.uk/2020/04/fix-firefox-rounded-corners-gnome) states and issue #154 too.

> I have the same issue with dark theme in nautilus and settings panel.
> ![DeepinScreenshot_select-area_20210613114124](https://user-images.githubusercontent.com/68183781/121797198-57ea2980-cc3c-11eb-90e5-1aa2d7e07021.png)

Try using the normal theme(not the solid one) to see if this still happens, and also test with the light theme.

**Comment by rama-2402** [comment]
> > I'm recently upgraded to firefox 89 and rounded corner on firefox looks like a mixture of rounded and straigh edges. I'm using pop os 20.10 but I think Ubuntu would have the same issues. Could you take a look at this. Thanks.
> > ![1](https://user-images.githubusercontent.com/66350350/121796356-edb79180-cc07-11eb-8f84-c655174fed70.png)
> > ![2](https://user-images.githubusercontent.com/66350350/121796359-f27c4580-cc07-11eb-8b4e-bd11e5195af4.png)
> 
> This is a well know error, as [this](https://www.omgubuntu.co.uk/2020/04/fix-firefox-rounded-corners-gnome) states and issue #154 too.
> EDIT: I've noticed that you aren't using the Firefox theme included with the theme, maybe that's the issue?
> And also, I remember that custom color schemes/themes on Firefox itself can cause this too, try using the default theme on Firefox.
> 
> > I have the same issue with dark theme in nautilus and settings panel.
> > ![DeepinScreenshot_select-area_20210613114124](https://user-images.githubusercontent.com/68183781/121797198-57ea2980-cc3c-11eb-90e5-1aa2d7e07021.png)
> 
> Try using the normal theme(not the solid one) to see if this still happens, and also test with the light theme.

Thanks for the reply! Normal theme works fine with the rounded corners. The problem is with the solid theme for both Dark and Light theme.

**Comment by KonstantMan** [comment]
I can confirm the issue remains on Arch gnome 40.2 regardless of the whitesur 
theme variant i'm using or the firefox themes 
![Screenshot from 2021-06-16 20-17-51](https://user-images.githubusercontent.com/56481040/122264266-e245be00-cec6-11eb-8acb-28755fdd86b8.png)
![Screenshot from 2021-06-16 20-17-41](https://user-images.githubusercontent.com/56481040/122264271-e2de5480-cec6-11eb-8379-9b13a4a07eb9.png)
![Screenshot from 2021-06-16 20-17-23](https://user-images.githubusercontent.com/56481040/122264274-e376eb00-cec6-11eb-966c-fe74c7adae37.png)

**Comment by vinceliuice** [comment]
See upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1408360.
Wayland fix:

    Go to the about:config page
    Search for the layers.acceleration.force-enabled preference and set it to true.
    Now restart Firefox, and it should look good!

X11 fix:

    Go to the about:config page
    Type mozilla.widget.use-argb-visuals
    Set it as a boolean and click on the add button
    Now restart Firefox, and it should look good!

**Comment by KonstantMan** [comment]
The problem remains 
![Screenshot from 2021-06-17 17-33-14](https://user-images.githubusercontent.com/56481040/122417218-dd414700-cf78-11eb-9baf-811a21a57fa8.png)

**Comment by vinceliuice** [comment]
Then I don't know how to fix this, only gnome desktop have this issue, kde is ok, and this is not a theme issue
