### ISSUE TITLE
Where to run ./install.sh

### ISSUE THREAD

**Issue by VelvetThunder1** [vinceliuice/WhiteSur-gtk-theme#302]
I'm not sure where to run the ./install.sh or ./tweaks.sh command, the whitesur theme folder, or in the /usr/share/themes folder. This is my first time trying something like this, I apologize if this is a dumb question.

**Comment by rivanfebrian123** [comment]
First time using Linux? Well, here is the tutorial:

![Screenshot from 2021-06-13 18-07-05](https://user-images.githubusercontent.com/6300910/121804807-605d5700-cc72-11eb-8dd1-6e9a5c775b41.png)
![Screenshot from 2021-06-13 18-07-30](https://user-images.githubusercontent.com/6300910/121804809-62271a80-cc72-11eb-87c5-e2082734e1d9.png)
![Screenshot from 2021-06-13 18-07-38](https://user-images.githubusercontent.com/6300910/121804811-63584780-cc72-11eb-8c78-e165bb3447f8.png)
![Screenshot from 2021-06-13 18-08-12](https://user-images.githubusercontent.com/6300910/121804814-64897480-cc72-11eb-9030-351156ebb9ac.png)

**Comment by VelvetThunder1** [comment]
oh i see, yes its my first time using linux, thank you very much for your help

**Comment by rivanfebrian123** [comment]
Your welcome :)
