### ISSUE TITLE
Bug css in login screen

### ISSUE THREAD

**Issue by m134m4a1** [vinceliuice/WhiteSur-gtk-theme#306]
ubuntu-18-04
Css error in screen login
![Screenshot from 2021-06-17 10-02-37](https://user-images.githubusercontent.com/46261472/122325037-0ef3e700-cf54-11eb-9222-75444df34c59.png)
![Screenshot from 2021-06-17 10-08-58](https://user-images.githubusercontent.com/46261472/122325052-14e9c800-cf54-11eb-90b1-2dea718d7660.png)

**Comment by rivanfebrian123** [comment]
Old Ubuntu versions require the GDM theme to be installed too

**Comment by fd6130** [comment]
> Old Ubuntu versions require the GDM theme to be installed too

Well i think this is because of Gnome version at Ubuntu 18.04. Mine still like that even though i have GDM theme installed.

**Comment by m134m4a1** [comment]
I don't think so

**Comment by vinceliuice** [comment]
Do not support gnome version < 3.36

**Comment by rivanfebrian123** [comment]
> Well i think this is because of Gnome version at Ubuntu 18.04. I'm facing the same issue even though i have GDM theme installed.

Disabling "User Themes" extension should do the trick. The latest installer has an instruction for that

**Comment by m134m4a1** [comment]
Can I solve problem on ubuntu 20.04

**Comment by vinceliuice** [comment]
20.04 is supported!

**Comment by m134m4a1** [comment]
Thank you happy coding

**Comment by m134m4a1** [comment]
![Uploading Screenshot from 2021-07-01 19-11-47.png…]()

**Comment by m134m4a1** [comment]
i have gnome version > 3.36

**Comment by m134m4a1** [comment]
![Uploading Screenshot from 2021-07-01 19-11-47.png…]()

**Comment by joulev** [comment]
@m134m4a1 You should wait a bit for the image to be uploaded before sending the message.

**Comment by m134m4a1** [comment]
![Screenshot from 2021-07-01 19-11-47](https://user-images.githubusercontent.com/46261472/124153630-d2c99600-dabe-11eb-9553-066c8433acf2.png)

**Comment by vinceliuice** [comment]
run `gnome-shell --version` to get your gnome-shell version

**Comment by rivanfebrian123** [comment]
@m134m4a1 You disabled the "User Themes" extension? If so, then install the GDM theme

**Comment by m134m4a1** [comment]
![Screenshot from 2021-07-02 06-39-26](https://user-images.githubusercontent.com/46261472/124200790-67081d00-db00-11eb-9f06-302c4ba9f881.png)

**Comment by vinceliuice** [comment]
Your gnome version is 3.28 < 3.36 , not supported
