### ISSUE TITLE
Firefox window corner is still rounded when maximised (Monterey theme)

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#307]
Thanks for the new Monterey Firefox theme, I installed it just now and it looks amazing!

However, the Firefox window corner is rounded even when the window is maximised, which (as I understand) is not the desired behaviour of this theme).

![image](https://user-images.githubusercontent.com/44609036/122325559-06e87700-cf55-11eb-9180-e03e68426ba1.png)

**Comment by rivanfebrian123** [comment]
Me too :D

**Comment by vinceliuice** [comment]
I'll fix this!
