### ISSUE TITLE
Moving tabs in new Firefox Monterey theme is not smooth

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#308]
In the old Firefox WhiteSur theme, tabs can be moved very smoothly.

However, in the new Monterey theme, only tab movement between different windows is smooth. Tab movement in the same window is not as good.

![screencast](https://user-images.githubusercontent.com/44609036/122409950-bd784600-cfad-11eb-8765-34fc29f4849d.gif)

**Comment by vinceliuice** [comment]
I'll try fix this!

**Comment by joulev** [comment]
> I'll try fix this!

Thanks!

**Comment by joulev** [comment]
Thanks, it works perfectly!
