### ISSUE TITLE
Make "Show Application" icon a little bit transparent

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#309]
The "Show Application" icon in some screenshots in the internet looks a little bit transparent. Even this video literally shows that the icon does look like that: https://youtu.be/kPUgUElLxGo. Could you redesign it? :)

**Comment by vinceliuice** [comment]
No problem!

**Comment by rivanfebrian123** [comment]
It has changed. Thanks!
