### ISSUE TITLE
Simplify Firefox Monterey theme

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#310]
Thank you for the theme, but I still have some problem with the "list all tabs" button and the "Extension ..." label. They take spaces so much and the "list all tabs" button is even unclickable. I think it is okay to collapse it as we can just scroll through tab buttons. What do you think?

Here's my layout config:
![Screenshot from 2021-06-18 06-34-22](https://user-images.githubusercontent.com/6300910/122485158-71a2bc80-d000-11eb-99ac-6ffbb855b818.png)

This is how it looks without `customChrome.css`:
![Screenshot from 2021-06-18 06-37-04](https://user-images.githubusercontent.com/6300910/122485164-736c8000-d000-11eb-9751-25f69d1f4c9b.png)

This is how it looks with `customChrome.css`:
![Screenshot from 2021-06-18 06-37-46](https://user-images.githubusercontent.com/6300910/122485166-74051680-d000-11eb-97a9-1d883e87ca75.png)

And here is my `customChrome.css`:
```
/* Add your own custom styles here */

#identity-box.extensionPage #identity-icon-label {
  visibility: collapse !important;
}

#tabbrowser-tabs ~ #alltabs-button {
  visibility: collapse !important;
}
```

**Comment by vinceliuice** [comment]
That's looks good, I'll add this!

**Comment by rivanfebrian123** [comment]
Thanks. Closing now

**Comment by vinceliuice** [comment]
Looks great! added
