### ISSUE TITLE
New tab button is not aligned in Firefox Monterey theme

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#311]
When I installed the Firefox theme last night after https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/a224cfe004400a2099498d4fe9f4fce7275fde49, the new tab button is perfectly aligned.

![image](https://user-images.githubusercontent.com/44609036/122499902-efc08c80-d01b-11eb-858c-769dfdcc8720.png)

However when I installed it this morning after https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/1571fa9d05d8bcbb85dad30460d4d7a0173fc9c7, the button is shifted to the top. It's no longer centered.

![image](https://user-images.githubusercontent.com/44609036/122499889-e9caab80-d01b-11eb-92ca-b688c7405c9a.png)

**Comment by vinceliuice** [comment]
I'll fix this!
