### ISSUE TITLE
Is there any way to port the Firefox theme to Windows?

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#318]
I just tried to install the Firefox theme to Firefox on Windows but it didn't work: the browser window is not even usable. But surely there is a way around this? I know this theme is built for Linux, but I think the Firefox theme in particular can also be used in Windows, after some tweaks to its source.

**Comment by joulev** [comment]
There is a modification for Windows and macOS [here](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS) but it is for WhiteSur only (currently)...

**Comment by vinceliuice** [comment]
Sorry about that I don't know how to use it on windows and macos

**Comment by joulev** [comment]
Oh I see, I will look at the source code of https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS and see if I can do something myself then. Thanks!
