### ISSUE TITLE
The left corner is not rounded

### ISSUE THREAD

**Issue by kinggx9** [vinceliuice/WhiteSur-gtk-theme#32]
App: gnome-disk-utility
Error:  gtk-3.0 (gtk-***.css)
![Ảnh chụp màn hình_2020-08-08_13-47-26](https://user-images.githubusercontent.com/56580423/89704508-69a8d380-d97e-11ea-94b6-11c79ea5ac2c.png)
![Ảnh chụp màn hình_2020-08-08_20-19-58](https://user-images.githubusercontent.com/56580423/89711453-95df4700-d9b4-11ea-877c-03473eef6ae6.png)

**Comment by kinggx9** [comment]
Fix: gtk-3.0.css
`@import url("resource:///org/gnome/theme/gtk.css");


/*(((((((((((((((( TOOLBAR )))))))))))))))))))*/

toolbar{

  -GtkWidget-window-dragging: true;
 padding: 2px;
  background-color: #515151;
  border-bottom: 1px solid rgba(0,0,0,1)}

toolbar separator{

  background: none; }

toolbar.horizontal separator{

  margin: 0 6px;}

toolbar.vertical separator{

 margin: 6px 0;}/*6*/

toolbar:not(.inline-toolbar) button,
toolbar:not(.inline-toolbar) spinbutton,
toolbar:not(.inline-toolbar) entry,
toolbar:not(.inline-toolbar) scale,
toolbar:not(.inline-toolbar) switch{

  margin-right: 1px;
  margin-bottom: 1px; }

toolbar:not(.inline-toolbar) .linked > button,
.inline-toolbar:not(.inline-toolbar) .linked > button,
toolbar:not(.inline-toolbar) .linked > entry,
.inline-toolbar:not(.inline-toolbar) .linked > entry {

  margin-right: 0; }

toolbar.osd{

  padding: 7px;
  border: 1px solid rgba(0, 0, 0, 0.5);
  border-radius: 5px;
  background-color: #37373a; }

toolbar.osd.bottom,
toolbar.osd.top,
toolbar.osd.right,
toolbar.osd.left{

  border-radius: 0; }

toolbar.osd.top{

  border-width: 0 0 1px 0; }

toolbar.osd.bottom{

  border-width: 1px 0 0 0; }

toolbar.osd.left{

  border-width: 0 1px 0 0; }

toolbar.osd.right{

  border-width: 0 0 0 1px; }

.osd toolbar{

  background-color: transparent; }

toolbar.secondary-toolbar{

  padding: 3px;
  border-bottom: 1px solid rgba(0,0,0,1); }

toolbar.secondary-toolbar button{

  padding: 0 3px 0 3px; }

toolbar.bottom-toolbar{

  padding: 4px;
  border-width: 1px 0 0 0;
  border-style: solid;
  border-color: rgba(0,0,0,1);
  background-color: rgba(64,64,64,1);  }

.bottom-toolbar.inline-toolbar {

  padding: 4px;
  border-width: 1px 0 0 0;
  border-style: solid;
  border-color: rgba(0,0,0,1);
  background-color: rgba(64,64,64,1);  }

toolbar.bottom-toolbar button{

  padding: 2px 3px 2px 3px; }

.bottom-toolbar.inline-toolbar button {

  padding: 2px 3px 2px 3px; }






/*********************************************************************/
/*            FILECHOOSER                                            */
/*********************************************************************/


filechooser placessidebar.sidebar separator{

  background-color: #505050;/*transparent;*/ }

filechooser.maximized placessidebar.sidebar{

  background-color: transparent;}
  
filechooser placessidebar.sidebar scrollbar{

  border-color: rgba(222, 227, 240, 0.85); }

.nautilus-window placessidebar.sidebar scrollbar {

   border-color: rgba(222, 227, 240, 0.85); }

filechooser placessidebar.sidebar scrollbar.overlay-indicator:not(.dragging):not(.hovering) slider{

  background-color: #767676;
  border: 1px solid rgba(0, 0, 0, 0.3); }

filechooser placessidebar.sidebar scrollbar slider{

  background-color: rgba(118, 118, 118, 0.7); }

filechooser placessidebar.sidebar scrollbar slider:hover{

   background-color: #838383; }

filechooser placessidebar.sidebar scrollbar slider:hover:active{

  background-color: #3273c4; }

filechooser placessidebar.sidebar scrollbar slider:disabled{

  background-color: transparent; } 
 
filechooser placessidebar.sidebar scrollbar trough{

  background-color: rgba(222, 227, 240, 0.85); }

/******************* FILECHOOSER .CSD ***************/

filechooser.csd.background{

  background-color: transparent; }

/********************************************************/

filechooser paned > separator {

  background-image: image(#505050); }



/***********************************************************************/
/*-------------------------- HEADERBAR---------------------------------*/
/***********************************************************************/

headerbar:only-child,
headerbar{
  
  min-height: 35px;
  padding: 1px 8px 2px 10px;
  border-width: 0px 0px 0.5px;
  border-style: solid;
  border-color: black;
  color: rgba(188,188,188, 0.8);
  background-color: transparent;
  background-image:  linear-gradient(to top, #343437, #3f4043);}

.maximized headerbar{

  border-radius: 1px; }

headerbar .title{

  text-shadow:  /*0 -1px alpha(#ffffff, 0.04),*/
				 -1px  0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.3),
				  0px  2px alpha(#202020, 0.05);
  padding-left: 12px;
  padding-right: 12px; }

headerbar .subtitle{

  text-shadow: /* 0 -1px alpha(#ffffff, 0.04),*/
				 -1px  0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.3),
				  0px  2px alpha(#202020, 0.05);
  opacity: 0.75;
  font-size: smaller;
  padding-left: 12px;
  padding-right: 12px; }

headerbar.selection-mode{

  color: #ffffff;
  text-shadow:  0px -1px alpha(#202020, 0.02),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.15),
				  0px  2px alpha(#202020, 0.05);
  background-color: #3273c4;
  border-color: #285d9f;
  /*box-shadow: 0 1px 0 rgba(0, 0, 0, 0.08);*/ }

.maximized headerbar.selection-mode{

  background-color: #3273c4; }

/*headerbar.selection-mode:backdrop{

  color: rgba(255, 255, 255, 0.6);
  text-shadow:  0px -1px alpha(#202020, 0.02),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.15),
				  0px  2px alpha(#202020, 0.05);
  background-color: #3273c4;
  border-color: #8c8c8c;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.08); }*/

headerbar.selection-mode .selection-menu{

  box-shadow: none;
  padding-left: 10px;
  padding-right: 10px; }

headerbar.selection-mode .selection-menu GtkArrow{

  -GtkArrow-arrow-scaling: 1; }

headerbar.selection-mode .selection-menu .arrow{

 -gtk-icon-source: -gtk-icontheme("pan-down-symbolic"); }

headerbar.selection-mode .subtitle:link{

  color: #dceaf9; }

headerbar.default-decoration,
.csd headerbar.default-decoration,
 headerbar.default-decoration:backdrop,
.csd headerbar.default-decoration:backdrop,
.default-decoration.titlebar:not(headerbar),
.csd .default-decoration.titlebar:not(headerbar),
.default-decoration.titlebar:backdrop:not(headerbar),
.csd .default-decoration.titlebar:backdrop:not(headerbar) {

  min-height: 26px;
  border-width:0 0 0;
  background-color: transparent;
  background-image: linear-gradient(to bottom, #3f4043, #3a3b3e);}

.maximized headerbar.default-decoration,
.maximized.csd headerbar.default-decoration,
.maximized headerbar.default-decoration:backdrop,
.maximized.csd headerbar.default-decoration:backdrop,
.maximized.default-decoration.titlebar:not(headerbar),
.maximized.csd .default-decoration.titlebar:not(headerbar),
.maximized.default-decoration.titlebar:backdrop:not(headerbar),
.maximized.csd .default-decoration.titlebar:backdrop:not(headerbar) {

  border-radius: 1px;
  background-color: transparent;
  background-image: linear-gradient(to bottom, #3f4043, #3a3b3e);} 

headerbar separator {
  
  padding-left: 6px;
  padding-right: 6px;
  padding-top: 3px;
  padding-bottom: 3px;
  margin-top: 7px;
  margin-bottom: 4px; }


.maximized headerbar:first-child{

  border-radius: 0; }

headerbar:first-child:backdrop {

  border-top-left-radius: 5px; }
 


.maximized headerbar:last-child{

  border-radius: 0; }

headerbar:last-child:backdrop {

  border-top-right-radius: 5px; }

.maximized headerbar:last-child:backdrop{

  border-radius: 0; }
 
headerbar:only-child{

  border-top-left-radius: 5px;
  border-top-right-radius: 5px;}

headerbar separator.titlebutton{

  min-width: 0px;
  min-height: 0px;
  background: none;
  border-width: 0 0px; }

headerbar separator.titlebutton:backdrop{

   }

headerbar.selection-mode button{

  border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button.flat{

  border-color: transparent;
  background-color: #3273c4;
  background-image: none;
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button.sidebar-button {

  border-color: transparent;
  background-color: #3273c4;
  background-image: none;
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar switch:backdrop {

  opacity: 0.75; }

headerbar progressbar trough {

  background-color: rgba(105, 105, 105, 0.15); }

headerbar progressbar:backdrop {

  opacity: 0.75; }

headerbar scale:backdrop {

  opacity: 0.75; }

headerbar scale slider {

  background-color: #3e3e3e; /* inside slider-button color*/
  border-color: #323232; }

headerbar scale slider:hover {

  background-color:#535353;/* inside slider-btton hover color*/
  border-color: #323232; }
  
headerbar scale slider:active {

 background-color:#3369a4;/* inside slider-btton active color*/
  border-color: #323232; }

headerbar scale slider:disabled {

   background-color: #3e3e3e; /* inside slider-button color*/
  border-color: #323232; }

headerbar scale trough {

   border-radius: 3px; 
  background-color: rgba(0,0,0,0.4); 
  border: 1px solid;
  border-color: #323232;}

headerbar scale trough:disabled {

   background-color: #404040; }

headerbar.selection-mode button:hover{

  border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button:disabled{

  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
 
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);
  color: rgba(255, 255, 255, 0.4); }

headerbar.selection-mode button:disabled label{

  color: rgba(255, 255, 255, 0.4); }

headerbar.selection-mode button:active{
border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button:checked{

  border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}
    
headerbar.selection-mode button:hover:active{

  border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button:hover:checked{

  border-color: #1c59b5;
  background-color: #3273c4;
  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
  color: #ffffff;
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);}

headerbar.selection-mode button:disabled:active{

  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
 
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);
  color: rgba(255, 255, 255, 0.4); }


headerbar.selection-mode button:disabled:checked{

  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
 
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);
  color: rgba(255, 255, 255, 0.4); }


headerbar.selection-mode button:disabled:checked{

  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
 
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);
  color: rgba(255, 255, 255, 0.4); }

headerbar.selection-mode button:disabled:active{

  background-image: linear-gradient(to bottom,#3273c4,#1c59b5);
 
  text-shadow:  0px -1px alpha(#ffffff, 0.04),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.4),
				  0px  2px alpha(#202020, 0.05);
  color: rgba(255, 255, 255, 0.4); }


/********HEADERBAR NAUTILUS CANVAS **************************/

headerbar .nautilus-canvas-item.subtitle{

  color: #8d8d8d; }

headerbar .nautilus-canvas-item.subtitle:selected{

  color: #d2e1f7;}
   
headerbar .nautilus-canvas-item.subtitle:selected:focus{

  color: #d2e1f7;}


/*********************************************************************/
/*           .TITLEBAR                                               */
/*********************************************************************/
window > .titlebar:not(headerbar),
window > .titlebar:not(headerbar):backdrop{

  /*padding: 0;
  background: none;
  border: none;
  box-shadow: none;*/ }

.titlebar {

  border-radius: 6px 6px 0 0; }

.titlebar:not(headerbar) {

  /*min-height: 38px;
  padding: 0 7px;
  border-width: 0px 0px 0.4px;
  border-style: solid;
  border-color: #c5c3c6;
  color: rgba(41, 33, 33, 0.8);
  text-shadow: 0 1px alpha(#ffffff, 0.35);
  background-color: transparent;
  background-image: linear-gradient(to bottom, #e4e9ef, #c7cbd0);*/}

.maximized .titlebar:not(headerbar) {

  border-radius: 1px; }

.maximized .titlebar:backdrop:not(headerbar) {

  border-radius: 1px; }

.titlebar:backdrop:not(headerbar) {

  /*transition: 200ms ease-out;*/ }

.titlebar:not(headerbar) .title {

  text-shadow:  /*0 -1px alpha(#ffffff, 0.04),*/
				 -1px  0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.3),
				  0px  2px alpha(#202020, 0.05);
  padding-left: 12px;
  padding-right: 12px; }

.titlebar:not(headerbar) .subtitle {

  text-shadow:  /*0 -1px alpha(#ffffff, 0.04),*/
				 -1px  0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.3),
				  0px  2px alpha(#202020, 0.05);
  opacity: 0.75; 
  font-size: smaller;
  padding-left: 12px;
  padding-right: 12px; }

.titlebar:not(headerbar) > separator {
  min-width: 1px;
  background-image: image(rgba(50,50,50,1));
  background-color:transparent;/*image(rgba(188,188,188,0.1));*/}
 
.titlebar:not(headerbar) separator.titlebutton {

  min-width: 0px;
  min-height: 0px;
  background: none;
  margin: -1px;
  border-width: 0 1px; }

.titlebar:not(headerbar) separator.titlebutton:backdrop {

   }

/********TITLEBAR NAUTILUS CANVAS *************************/

.titlebar:not(headerbar) .nautilus-canvas-item.subtitle{

  color: #8d8d8d; }

.titlebar:not(headerbar) .nautilus-canvas-item.subtitle:selected{

  color: #d2e1f7;}

.titlebar:not(headerbar) .nautilus-canvas-item.subtitle:selected:focus{

  color: #d2e1f7;}

/******** SELECTION MODE TITLEBAR  *********************/

.selection-mode.titlebar:not(headerbar) {

  color: #ffffff;
  text-shadow:  0px -1px alpha(#202020, 0.02),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.15),
				  0px  2px alpha(#202020, 0.05);
  background-color: rgba(32, 106, 217, 0.95);
  /*border-color: #8c8c8c;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.08); */}


.selection-mode.titlebar:backdrop:not(headerbar) {

  color: rgba(255, 255, 255, 0.6);
  text-shadow:  0px -1px alpha(#202020, 0.02),
				 -1px 0px alpha(#202020, 0.05),
				  1px  0px alpha(#202020, 0.05),
				  0px  1px alpha(#202020, 0.15),
				  0px  2px alpha(#202020, 0.05);
  background-color: rgba(32, 106, 217, 0.95);
/*  border-color: #8c8c8c;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.08);*/ }

.selection-mode.titlebar:not(headerbar) .selection-menu {

  box-shadow: none;
  padding-left: 10px;
  padding-right: 10px; }

.selection-mode.titlebar:not(headerbar) .selection-menu GtkArrow {

  -GtkArrow-arrow-scaling: 1; }

.selection-mode.titlebar:not(headerbar) .selection-menu .arrow {

  -gtk-icon-source: -gtk-icontheme("pan-down-symbolic"); }

.maximized .selection-mode.titlebar:not(headerbar) {

  background-color: #3273c4; }

.selection-mode.titlebar:not(headerbar) .subtitle:link{

  color: #dceaf9; }
`

**Comment by vinceliuice** [comment]
Thanks, I'll fix this!
