### ISSUE TITLE
Monterey wallpaper has annoying lines on the left

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#320]
OS: Void Linux
Size: 1080p
Installed with `wallpapers/install-wallpapers.sh`
(click to zoom in)

![Screenshot from 2021-06-23 08-33-53](https://user-images.githubusercontent.com/6300910/123065165-74d1ea00-d3fe-11eb-8463-093c94c3b1a4.png)

![Screenshot from 2021-06-23 08-33-58](https://user-images.githubusercontent.com/6300910/123065184-78fe0780-d3fe-11eb-86f2-2b01a4cadd33.png)

**Comment by vinceliuice** [comment]
I'll check this!

**Comment by rivanfebrian123** [comment]
Thanks! Here is my display settings:

![Screenshot from 2021-06-23 08-56-14](https://user-images.githubusercontent.com/6300910/123067947-f9256c80-d400-11eb-80ef-27dedac8fd2c.png)

**Comment by vinceliuice** [comment]
Fixed!
