### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by doglinhaskkk** [vinceliuice/WhiteSur-gtk-theme#326]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.skype.com/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
  >>> E: The repository 'http://ppa.launchpad.net/librecad-dev/librecad-stable/ubuntu focal Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  >>> E: The repository 'http://ppa.launchpad.net/tista/adapta/ubuntu focal Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;20.04
  SUDO   : no
  GNOME  : old
  REPO   : 2021-06-24T11:23:49-0300

  HINT: You can google or report to us the info above

**Comment by vinceliuice** [comment]
You meed update all your apps

**Comment by doglinhaskkk** [comment]
I've updated all apps and the error remains.

**Comment by rivanfebrian123** [comment]
Maybe these tutorials can help:

- https://itsfoss.com/repository-does-not-have-release-file-error-ubuntu/
- https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file

**Comment by vinceliuice** [comment]
You need remove those 3 not available PPAs

**Comment by doglinhaskkk** [comment]
Ok, it worked, thank you!

**Comment by rivanfebrian123** [comment]
Your welcome!
