### ISSUE TITLE
Display issue of Files sidebar

### ISSUE THREAD

**Issue by lomirus** [vinceliuice/WhiteSur-gtk-theme#327]
Just as the video below shows:

https://user-images.githubusercontent.com/21173956/123363025-4857d280-d5a4-11eb-82e0-a6beed52a0e8.mp4

And my system info:
> OS: Manjaro Linux x86_64 
Host: 82B6 Lenovo Legion R7000 2020 
Kernel: 5.10.42-1-MANJARO 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 3.38.4 
WM: Mutter 
WM Theme: WhiteSur-light 
Theme: WhiteSur-dark [GTK2/3] 
Icons: BigSur [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
Memory: 2140MiB / 15872MiB

**Comment by vinceliuice** [comment]
Nvidia driver issue, just use the solid version, this issue can not be fixed at normal version for now
