### ISSUE TITLE
Firefox WhiteSur theme doesn't work on Solus MATE

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#329]
Distro: Solus
DE: MATE

![Screenshot at 2021-06-25 18-48-41](https://user-images.githubusercontent.com/6300910/123421629-4b27e700-d5e7-11eb-9172-998c87f467bf.png)

It only happens with WhiteSur theme tho, the Monterey theme works just fine

![Screenshot at 2021-06-25 18-49-53](https://user-images.githubusercontent.com/6300910/123421621-47946000-d5e7-11eb-9dd0-78b676dffc6c.png)

**Comment by vinceliuice** [comment]
Try the last update, you did not disable "Monterey/left_header_button_3.css" and "Monterey/right_header_button_3.css"

**Comment by vinceliuice** [comment]
I fixed it

**Comment by rivanfebrian123** [comment]
Oh yeah... I forgot :D
