### ISSUE TITLE
Decrease the corner radius

### ISSUE THREAD

**Issue by LeandroPelegrini** [vinceliuice/WhiteSur-gtk-theme#33]
Hey, I've been trying to decrease a little the corner radius, changed the sass file and parsing, but nothing change.
Can someone please tell me the variable name to change it?

![Border radius](https://i.ibb.co/bFvk4rx/image.png)

6px vs 14px comparison.
Thanks.

**Comment by vinceliuice** [comment]
Change the `$wm_radius: 14px;` in `src/sass/_variables.sass`

**Comment by LeandroPelegrini** [comment]
Thanks, just to add an info. I parsed the sass but forgot to re-install, now its working, thanks for the reply.
