### ISSUE TITLE
Button icons fail to appear correctly with the Monterey theme in firefox. 

### ISSUE THREAD

**Issue by linusrg1** [vinceliuice/WhiteSur-gtk-theme#332]
Arch
Kde Plasma 5.22.2
Firefox 89.0.2 (with dark reader and ublock installed)
![Screenshot_20210625_150352](https://user-images.githubusercontent.com/67347319/123445570-89ada980-d5c7-11eb-8cc3-da0f51a50413.png)

**Comment by linusrg1** [comment]
> Disable the titlebar

very dumb question. But they moved everything around in the latest firefox release. Do you know where they moved the top bar configurator to?

**Comment by linusrg1** [comment]
> Disable the titlebar

well I did that but I have the same issue. Should I try resetting firefox?

**Comment by CyberAzure** [comment]
I experience this same issue, Ubuntu Studio 20.04 with GNOME 3.36.

**Comment by vinceliuice** [comment]
![2021-06-30 20-24-41 的屏幕截图](https://user-images.githubusercontent.com/7604295/123959929-4e551580-d9e1-11eb-9886-4db1df4187ec.png)

**Comment by vinceliuice** [comment]
See the `Title Bar` check box at bottom? turn it off!

**Comment by linusrg1** [comment]
> See the `Title Bar` check box at bottom? turn it off!

I did. And now that I think about it the global kde theme has buggy icons too. So maybe there is some type of conflict with the latest version of KDE?

**Comment by vinceliuice** [comment]
I have plasma 5.22 on my manjaro, but everything works well

**Comment by linusrg1** [comment]
> I have plasma 5.22 on my manjaro, but everything works well

Then idk why it is being so buggy for me.
