### ISSUE TITLE
Activities icon incorrect

### ISSUE THREAD

**Issue by Matt-Elliot** [vinceliuice/WhiteSur-gtk-theme#333]
After installing this theme and choosing the ubuntu activities icon, the activities icon change to an ugly square with 9 coloured squared in it. 

![Screenshot-20210627113837-176x119](https://user-images.githubusercontent.com/80140208/123552553-4d4f8a00-d73c-11eb-9cc5-ec6bf6b6cfc8.png)

First time I installed I used sudo install. (I don't know if this caused a problem).

Uninstalling the theme and reinstalling doesn't work (I tried all icons). I tried with sudo and without sudo install.

**Comment by Matt-Elliot** [comment]
Sorry, it seems like there are two things. I was getting confused between them. 
![Screenshot-20210627134703-651x976](https://user-images.githubusercontent.com/80140208/123555944-5d706500-d74e-11eb-8f15-b0c75b4e050a.png)
The one on the left is the applications button. The correct looking one is activities button. If I customize the icon for applications button with dash to Panel, it looks like this :

![Screenshot-20210627134752-639x989](https://user-images.githubusercontent.com/80140208/123555996-9c9eb600-d74e-11eb-8ae6-38c9b9b7a65c.png)

That icon for show applications didn't look like that before I installed this theme. I prefer the applications button as it has a more useful right click context menu. For now I'll just disable it and right click on the panel itself...

**Comment by CuriousxOctopus** [comment]
This problem has returned in Gnome42 Ubuntu 22.04. Not sure if it's caused by theme or dash to panel.
Thank you
