### ISSUE TITLE
Error Log: Error: Unable to find a match: sassc AND Account or password is expired

### ISSUE THREAD

**Issue by tv-nieri** [vinceliuice/WhiteSur-gtk-theme#335]
Hello!
Congrats for the amazing job, this theme looks super cool!
I am trying to install it but i keep getting this error if i try with sudo privileges, but my password is not expired:

> 
        Oops! Operation failed...
      
        =========== ERROR LOG ===========
        >>> sudo: Account or password is expired, reset your password and try again
        >>> sudo: unable to change expired password: Authentication token manipulation error

And if i try with no sudo privileges:
> 

        Oops! Operation failed...
      
        =========== ERROR LOG ===========
        >>> Error: Unable to find a match: sassc
        
        =========== ERROR INFO ==========
        FOUND  :
          >>> install.sh
          >>> lib-core.sh
          >>> lib-install.sh at 168
        SNIPPET:
          >>> dnf install -y sassc glib2-devel libxml2
        TRACE  :
          >>> signal_error
          >>> install_theme_deps
          >>> install_themes
          >>> main
        
        =========== SYSTEM INFO =========
        DISTRO : rhel;platform:el8;fedora;8.4
        SUDO   : no
        GNOME  : old
        REPO   : 2021-06-27T22:52:08-0300
      
        HINT: You can google or report to us the info above
      
        https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

However, i do have a sassc version running on my system:

>
      ➜  WhiteSur-gtk-theme-master sassc --version
      sassc 0.12.3 (sass/libsass 3.4.3)
      ➜  WhiteSur-gtk-theme-master

Have you ever seen something like this?
Thanks and congrats again!

**Comment by vinceliuice** [comment]
glib2-devel

**Comment by vinceliuice** [comment]
This is also needed

**Comment by tv-nieri** [comment]
After some research i found an strange workaround for an issue about some cloud stuff. I added this entry to my /etc/environment:
`SASS_LIBSASS_PATH="/usr/local/lib/libsass"`

After that, the issue was solved but i found another one. At least in my system, sassc does not have an option -M, it has -m.
I changed it in the script "lib-core.sh", like this:

> 
      ➜  WhiteSur-gtk-theme-master cat lib-core.sh | grep -i sassc
      SASSC_OPT="-m -t expanded"
      ➜  WhiteSur-gtk-theme-master

It fixed the issues for me and now i have the themes installed.
Thanks team!

**Comment by rivanfebrian123** [comment]
> Have you ever seen something like this?

Honestly, yeah. Those logs are alien things for me.


> `    DISTRO : rhel;platform:el8;fedora;8.4`

I never use RHEL before :D I think it's made for servers, and not for home users


>  \>\>\> sudo: Account or password is expired, reset your password and try again
>  \>\>\> sudo: unable to change expired password: Authentication token manipulation error

Maybe you can try these tutorials:

- https://www.tecmint.com/fix-passwd-authentication-token-manipulation-error-in-linux/
- https://forums.centos.org/viewtopic.php?t=74118


> `    >>> Error: Unable to find a match: sassc`

Wait, RHEL doesn't have `sassc`? Then how do you manage to have it installed in your system?

Anyway, I can't give RHEL full support cause I don't have any RHEL the installation yet

**Comment by tv-nieri** [comment]
Actually RHEL does have sassc, the problem is that the script was not finding it, not sure why.
Ah yeah, RH has Redhat Enterprise Linux Server, and Redhat Enterprite Linux (workstation). Almost no diference like Ubuntu Linux and Ubuntu Linux Server.

I manage to workaround the issue with the steps i mentioned in my previous post.
Great job with the theme, i am already using it, icons and everything!
