### ISSUE TITLE
i cant able to install this why

### ISSUE THREAD

**Issue by jagan20-u** [vinceliuice/WhiteSur-gtk-theme#338]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: The repository 'cdrom://Linux Mint 20.1 _Ulyssa_ - Release amd64 20210103 focal Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;linuxmint;20.1
  SUDO   : no
  GNOME  : old
  REPO   : 2021-07-01T07:04:30+0530

  HINT: You can google or report to us the info above

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

jagan@jagan-K43SD:~/Downloads/WhiteSur-gtk-theme$

**Comment by vinceliuice** [comment]
Disabled this repository 'cdrom://Linux Mint 20.1 Ulyssa - Release amd64 20210103 focal Release'

**Comment by vinceliuice** [comment]
Update you system before you install this theme

**Comment by rivanfebrian123** [comment]
- https://itsfoss.com/repository-does-not-have-release-file-error-ubuntu/
- https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file

**Comment by jagan20-u** [comment]
again i recive some error 
  

  Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/main/binary-i386/by-hash/SHA256/7b27bf688d8a6b2762fbefdfe8d2f353cfc880fc82b0d0aafebbe229f108229a  Hash Sum mismatch
  >>>    Hashes of expected file:
  >>>     - Filesize:499760 [weak]
  >>>     - SHA256:7b27bf688d8a6b2762fbefdfe8d2f353cfc880fc82b0d0aafebbe229f108229a
  >>>     - SHA1:2dbf3a4a49dcbfe5d172760b408c279cc68771b0 [weak]
  >>>     - MD5Sum:91c4d90dd741f0a9841a9d961ee8da0c [weak]
  >>>    Hashes of received file:
  >>>     - SHA256:834f6edc54dd297154abeeb66cb933e9f9d352a678c8f74ee78868be37b66d7f
  >>>     - SHA1:a4678f9f82466bba24f826697a658d40432af7ea [weak]
  >>>     - MD5Sum:4ded4612c3dcd56f2871df1c1df1dbcc [weak]
  >>>     - Filesize:499760 [weak]
  >>>    Last modification reported: Thu, 01 Jul 2021 07:26:26 +0000
  >>>    Release file created at: Thu, 01 Jul 2021 07:26:03 +0000
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-amd64/by-hash/SHA256/aa7d47b1609ef9fd166ce0f6a44d6246f4c9b2ed97b96a91c08ade6577abfde2  
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-i386/by-hash/SHA256/7471e11df798a53d07817f214c80cbd4d829830ccf2f09ad173a6fd892b8ea35  
  >>> E: Some index files failed to download. They have been ignored, or old ones used instead.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;linuxmint;20.1
  SUDO   : no
  GNOME  : old
  REPO   : 2021-07-01T07:04:30+0530

  HINT: You can google or report to us the info above

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues
