### ISSUE TITLE
again i recived this error during installation of whitesur gtk theme

### ISSUE THREAD

**Issue by jagan20-u** [vinceliuice/WhiteSur-gtk-theme#339]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/main/binary-i386/by-hash/SHA256/7b27bf688d8a6b2762fbefdfe8d2f353cfc880fc82b0d0aafebbe229f108229a  Hash Sum mismatch
  >>>    Hashes of expected file:
  >>>     - Filesize:499760 [weak]
  >>>     - SHA256:7b27bf688d8a6b2762fbefdfe8d2f353cfc880fc82b0d0aafebbe229f108229a
  >>>     - SHA1:2dbf3a4a49dcbfe5d172760b408c279cc68771b0 [weak]
  >>>     - MD5Sum:91c4d90dd741f0a9841a9d961ee8da0c [weak]
  >>>    Hashes of received file:
  >>>     - SHA256:834f6edc54dd297154abeeb66cb933e9f9d352a678c8f74ee78868be37b66d7f
  >>>     - SHA1:a4678f9f82466bba24f826697a658d40432af7ea [weak]
  >>>     - MD5Sum:4ded4612c3dcd56f2871df1c1df1dbcc [weak]
  >>>     - Filesize:499760 [weak]
  >>>    Last modification reported: Thu, 01 Jul 2021 07:26:26 +0000
  >>>    Release file created at: Thu, 01 Jul 2021 07:26:03 +0000
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-amd64/by-hash/SHA256/aa7d47b1609ef9fd166ce0f6a44d6246f4c9b2ed97b96a91c08ade6577abfde2  
  >>> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-i386/by-hash/SHA256/7471e11df798a53d07817f214c80cbd4d829830ccf2f09ad173a6fd892b8ea35  
  >>> E: Some index files failed to download. They have been ignored, or old ones used instead.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;linuxmint;20.1
  SUDO   : no
  GNOME  : old
  REPO   : 2021-07-01T07:04:30+0530

  HINT: You can google or report to us the info above

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

**Comment by rivanfebrian123** [comment]
Could you please try this solution: https://askubuntu.com/questions/1215577/failed-to-fetch-url-hash-sum-mismatch-ubuntu-18-04-lts? Please tell us if that work
