### ISSUE TITLE
Bug - Rename edit mode in (Nemo) file manager has black and white overlapped, offset, text

### ISSUE THREAD

**Issue by dhunter** [vinceliuice/WhiteSur-gtk-theme#34]
Using Cinnamon DE on Linux Mint, (with Nemo, its default file manager).  If I use WhiteSur-light for the Controls part of my theme, and try to rename a file by right-clicking it, click "Rename" then click on the file name, it looks like it overlaps one version of the file name with black text, (as it looks before being selected) with another version of the file name with white text, (as it looks when being selected) on top of each other, but slightly offset, so that it's very hard to actually read the filename any more.  

Tried doing a regular screenshot of, but afraid screenshotting knocks me out of the rename edit mode, so had to try to taking a picture of with my phone, so the quality of the screenshot is poor, but hopefully good enough that you can see what I'm talking about.  

![IMG_0273](https://user-images.githubusercontent.com/9156/90343764-93e33c80-dfe1-11ea-8311-74967a57850c.JPG)

Note: The issue definitely seems to be localized to just this theme as, if I switch the Controls portion of the theme back to Orchis-light, (which I was using before this) there is no problem with the rename text, but when you click "Rename" with Orchis-light, the text of the filename to be renamed definitely does shift to the left as soon as "Rename" is clicked, and the text stays to the left after being clicked to edit.  It's perfectly readable, but it definitely moves slightly to the left when I right-click>Rename with Orchis-light, while it moves slightly to the right when I right-click>Rename with WhiteSur-light, (and part of the first letter of the filename - in this case, the vertical line of the lower-case "b" seems to double up horizontally.

(Edit: In case you're curious, the filename you're trying to read above is "bug_fixes_and_improvements.txt").

**Comment by vinceliuice** [comment]
I get it, I'll fix this!

**Comment by vinceliuice** [comment]
Fixed!
