### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by seyedmm** [vinceliuice/WhiteSur-gtk-theme#341]
How should I fix this error?

**Comment by rivanfebrian123** [comment]
What the error is?

**Comment by seyedmm** [comment]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: Failed to fetch http://ir.archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-amd64/by-hash/SHA256/f88f1f2679de5792aa5aaec9c4ddce6d9f5b90e8b87b77e44d02e56752df631e  Hash Sum mismatch
  >>>    Hashes of expected file:
  >>>     - Filesize:827576 [weak]
  >>>     - SHA256:f88f1f2679de5792aa5aaec9c4ddce6d9f5b90e8b87b77e44d02e56752df631e
  >>>     - SHA1:997043c921365362ae63c401cc86e8bf643399c1 [weak]
  >>>     - MD5Sum:f9c684024ceb8d9f510b52f7c9ec7ea4 [weak]
  >>>    Hashes of received file:
  >>>     - SHA256:f547e19667f417767e53f5546bbd452976eda35741b3dc32ac71128250b2c44b
  >>>     - SHA1:ca41acfa9a7053662f7e1cb8d2181acc4b9adac6 [weak]
  >>>     - MD5Sum:53f74bb0b52d4c0f45352dd1e27d6e09 [weak]
  >>>     - Filesize:827576 [weak]
  >>>    Last modification reported: Wed, 30 Jun 2021 19:41:10 +0000
  >>>    Release file created at: Wed, 30 Jun 2021 23:25:55 +0000
  >>> E: Failed to fetch http://ir.archive.ubuntu.com/ubuntu/dists/focal-updates/universe/binary-i386/by-hash/SHA256/e7dfc8266c2bda2a8c36d8f50b54f4a57aea80f97e92ba4f32f1e901b8a0a08f  
  >>> E: Some index files failed to download. They have been ignored, or old ones used instead.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;20.04
  SUDO   : yes
  GNOME  : old
  REPO   : 2021-07-01T06:04:30+0430

**Comment by vinceliuice** [comment]
Network error! check your DNS setting

**Comment by seyedmm** [comment]
I changed the DNS to 1.1.1.1 but the error did not resolve

**Comment by rivanfebrian123** [comment]
It's the similar issue as #339. Could you please run `sudo apt update -y; echo RESULT: $?` and copy the log to here?

**Comment by seyedmm** [comment]
The log:

```Hit:1 http://ir.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 http://ir.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:4 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu focal InRelease      
Hit:5 http://deb.fdmpkg.org bionic InRelease                                   
Hit:6 http://packages.microsoft.com/repos/code stable InRelease                
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease    
Hit:8 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:9 http://ppa.launchpad.net/numix/ppa/ubuntu focal InRelease
Hit:10 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal InRelease
Hit:11 http://ppa.launchpad.net/persepolis/ppa/ubuntu focal InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
20 packages can be upgraded. Run 'apt list --upgradable' to see them.
RESULT: 0
```

**Comment by rivanfebrian123** [comment]
I think everything is ok now. They already fixed their hash problems
