### ISSUE TITLE
--normal or --normalshowapps doesn't work

### ISSUE THREAD

**Issue by andreluisos** [vinceliuice/WhiteSur-gtk-theme#342]
The --normal option is supposed to keep the default gnome "Show apps" icons, Right? The options doesn't work, however.

**Comment by vinceliuice** [comment]
![2021-07-02 08-33-18 的屏幕截图](https://user-images.githubusercontent.com/7604295/124203834-2d3f1280-db10-11eb-9740-da448a1e6a63.png)

**Comment by vinceliuice** [comment]
Download the last update on master and try it again!

**Comment by andreluisos** [comment]
I've tried but it's still there.
I'll do some more tests tomorrow. Kinda rushy today.

**Comment by vinceliuice** [comment]
Did you run ./install.sh --normal successfully？

**Comment by andreluisos** [comment]
Yup. It worked.

**Comment by vinceliuice** [comment]
Did you installed th GDM theme？

**Comment by andreluisos** [comment]
Yes. Apparently, everything is working as expected now.

I can't stress enough to say thank you for the hard work, mate. You're very talented.

**Comment by vinceliuice** [comment]
You are welcome!
