### ISSUE TITLE
Application Menu Background Issue on Pop!_ OS 21.04

### ISSUE THREAD

**Issue by sconetto** [vinceliuice/WhiteSur-gtk-theme#343]
Hi there,
I have the WhiteSur GTK theme installed in my Pop OS for a while and everything always worked flawlessly.
After the update from 20.10 to 21.04 I'm getting this weird glitch with the application's background.
Any idea what could it be? Is there any other information I can provide to help?

## Distro Info

```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```
```shell
neofetch    
             /////////////                sconetto@kenko 
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 21.04 x86_64 
    //////7676767676*//////////////       Host: XPS 15 9500 
   /////76767//7676767//////////////      Kernel: 5.11.0-7620-generic 
  /////767676///*76767///////////////     Uptime: 9 mins 
 ///////767676///76767.///7676*///////    Packages: 2160 (dpkg), 15 (flatpak),  
/////////767676//76767///767676////////   Shell: zsh 5.8 
//////////76767676767////76767/////////   Resolution: 2560x1440 
///////////76767676//////7676//////////   DE: GNOME 3.38.3 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: WhiteSur-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: WhiteSur-dark [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-10750H (12) @ 5.000GHz 
    /////767676767676767676767/////       GPU: Intel UHD Graphics 
      ///////////////////////////         Memory: 3809MiB / 15748MiB 
         /////////////////////
             /////////////
```

## Screenshot/Recording
I took a screenshot and a video because the screenshot wasn't showing it properly (on the screenshot you just have the background completely transparent).

![Screenshot from 2021-07-01 20-38-52](https://user-images.githubusercontent.com/11671985/124174939-3fd43000-daad-11eb-84c9-4a96443c3a7c.png)

https://user-images.githubusercontent.com/11671985/124175134-832e9e80-daad-11eb-9156-5504b43bad8b.mp4

**Comment by rivanfebrian123** [comment]
Could you please reinstall the theme?

**Comment by vinceliuice** [comment]
Are you sure this is a theme issue? it looks like a Graphics driver issue?

**Comment by sconetto** [comment]
@rivanfebrian123 I'll try reinstalling it today.
@vinceliuice every other aspect of the theme works, and I can run programs with my graphic card. Is there a way to check it? And as said, it worked with 20.10 (during the dist upgrade the driver stayed the same version)

**Comment by vinceliuice** [comment]
Try the last update! fixed I think

**Comment by sconetto** [comment]
Hi @vinceliuice,
Sorry for giving late feedback, yes! now everything is working :D
Thank you!

**Comment by vinceliuice** [comment]
You are welcome!
