### ISSUE TITLE
Some Applications have weird toggle button glitches

### ISSUE THREAD

**Issue by DreamTexX** [vinceliuice/WhiteSur-gtk-theme#344]
![grafik](https://user-images.githubusercontent.com/20863419/124181735-33a0a080-dab6-11eb-81e9-a08b395ec9f1.png)

Hi, some applications have this weird toggle button bug. How can i fix it?
I'm on fedora 34, X11, Gnome 40.1.0, Kernel 5.12.3-300

**Comment by rivanfebrian123** [comment]
I think this is caused by NVIDIA driver

**Comment by DreamTexX** [comment]
Seems so, thanks!
