### ISSUE TITLE
[Question] stable release package

### ISSUE THREAD

**Issue by MrAru** [vinceliuice/WhiteSur-gtk-theme#346]
I'm not familiar with GNOME and I'm sorry if I asked a stupid question.

I believe there was a folder named "stable-release" where I can download the packaged GNOME theme and use it to install this awesome theme directly. And after a certain commit, it disappeared. So I wonder where can I find this packaged theme file or how can I manually package it?

Many thanks.

**Comment by joulev** [comment]
You can clone this repo, then cd to it and run ./install.sh

**Comment by MrAru** [comment]
@joulev Thanks for the quick reply. But let me describe my position more specifically.

It was my fault, I forgot to mention that I used to be a KDE Plasma user, and I was mostly tracking updates to WhiteSur-KDE. In fact, to make the UI consistent between KDE Plasma and GNOME GTK applications, I used the functionality provided by KDE Settings to set the GNOME theme to WhiteSur-GNOME, which accepts a packaged GTK theme file as input. The more detailed information can be found at https://userbase.kde.org/System_Settings/GNOME_Application_Style_(GTK).

Yep, like you said, I can clone this repo without any problem, cd to this folder, and then execute the install.sh file. But I don't know what the difference is between installing it in this way and setting it up with KDE Settings. Are they exactly the same? I would like to know if there is a proper way to solve a similar problem.

But anyway, thanks again for your help.

**Comment by joulev** [comment]
@MrAru No need to be so polite and I didn't accuse you of anything so no need to apologise :)

As for the difference of cloning the repo and the packaged version, sorry I don't really remember... I clone because it works and it can get me the latest commit.

**Comment by vinceliuice** [comment]
There are too few people using this file, so I removed it, and it’s no different from running ./install.sh directly.

**Comment by MrAru** [comment]
Oh, thanks for your answer. Now I can just clone and install with the latest version confidently.

Issue closed.
