### ISSUE TITLE
[IMPORTANT REQUEST] Make the top panel look more like macOS.

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#347]
This is a real Mac.

![image](https://user-images.githubusercontent.com/69485578/124339239-84ca9600-db83-11eb-98b8-ac124088da61.png)

And this is what my Ubuntu Studio with GNOME 3.36 looks like.

![image](https://user-images.githubusercontent.com/69485578/124339264-b2174400-db83-11eb-8e5e-6e319937d7ac.png)

See the differences?
Well, besides the UI scale(because different monitors, etc), fonts on the top panel doesn't look like macOS at all, no bold, no stretched fonts, no nothing.
Thus, the WhiteSur Icon Theme(with customized dock icons) makes the Ethernet icon look alien, and the battery icon(not present there on my screenshot because I disabled it) is not wide-ish, same goes to volume icon and others.
My request is to make the top bar look more like a mac, then this theme will basically be perfect.
Thanks in advance.

**Comment by joulev** [comment]
@CyberAzure I have an unrelated question: How did you get that global menu bar?

I have been using [Fildem](/gonzaarcr/Fildem) to get it, but it does not work very well, especially Firefox's menu doesn't work.

**Comment by vinceliuice** [comment]
Gnome shell can not use wide-ish icons, icon on gnome-panel can only be 16px*16px, about other icons I'll adjust it more like mac

**Comment by CyberAzure** [comment]
What about the fonts? Can you make it bold?

**Comment by CyberAzure** [comment]
> @CyberAzure I have an unrelated question: How did you get that global menu bar?
> 
> I have been using [Fildem](/gonzaarcr/Fildem) to get it, but it does not work very well, especially Firefox's menu doesn't work.

[This](https://extensions.gnome.org/extension/4111/mock-universal-menu/) extension, only for aesthetic purposes unfortunately.

**Comment by vinceliuice** [comment]
No problem, by the way run `./install.sh -HD` will have bold fonts on panel

**Comment by CyberAzure** [comment]
> No problem, by the way run `./install.sh -HD` will have bold fonts on panel

Alright, will give it a try!

**Comment by CyberAzure** [comment]
Alright, now it looks bold.
But, the Nautilus got bigger, panel got bigger, etc.
Can you make the panel skinnier and still maintain the bold font?
Like and Alt version of some kind?
I'll be pretty happy :)

**Comment by vinceliuice** [comment]
no problem!

**Comment by CyberAzure** [comment]
Thank you very much Vince, you are awesome!

**Comment by rivanfebrian123** [comment]
@vinceliuice Is it possible to use semibold theme by default, I mean, without using `-HD`?

**Comment by vinceliuice** [comment]
I think we can set the font bold by default and add a slim font option on `install.sh`

**Comment by CyberAzure** [comment]
Don't forget to make the top bar "skinnier" so it looks more like macOS!

**Comment by CyberAzure** [comment]
YAY! Now the top bar is PERFECT!
Thank you so much Vince, I'm so happy rn!
<3

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by CyberAzure** [comment]
In case someone is wondering how it looks like now.

![photo_2021-07-04_23-32-54](https://user-images.githubusercontent.com/69485578/124425734-5c879680-dd3f-11eb-8d84-ebf10885d850.jpg)

(Wallpaper is a photo from Hong Kong, got from Unsplash.)

**Comment by joulev** [comment]
@vinceliuice 

> I think we can set the font bold by default and add a slim font option on `install.sh`

Just installed the new topbar and while it looks great, I have a few comments:

* In macOS as I can see the right part is not actually bold. I'm not sure if it is possible but it would be cool to have the right texts displayed in normal weight.
* and I think the slim option is not yet available? Or at least I can't find it in `./install.sh --help`.

**Comment by vinceliuice** [comment]
Could you show me some pictures? @joulev

**Comment by joulev** [comment]
@vinceliuice Sure!

![image](https://user-images.githubusercontent.com/44609036/124592467-b5fadd00-de87-11eb-8e1a-1cd73c8af79d.png)

![image](https://user-images.githubusercontent.com/44609036/124592566-cd39ca80-de87-11eb-9e3d-1d6cad466cad.png)

**Comment by CyberAzure** [comment]
>     * In macOS as I can see the right part is not actually bold. I'm not sure if it is possible but it would be cool to have the right texts displayed in normal weight.

That is indeed true, as i can see in that macOS Monterey screenshot up [here](https://user-images.githubusercontent.com/69485578/124339239-84ca9600-db83-11eb-98b8-ac124088da61.png).
Maybe the clock can be normal weight and all the rest in bold?

**Comment by joulev** [comment]
> > ```
> > * In macOS as I can see the right part is not actually bold. I'm not sure if it is possible but it would be cool to have the right texts displayed in normal weight.
> > ```
> 
> That is indeed true, as i can see in that macOS Monterey screenshot up [here](https://user-images.githubusercontent.com/69485578/124339239-84ca9600-db83-11eb-98b8-ac124088da61.png).
> Maybe the clock can be normal weight and all the rest in bold?

Actually everything on the right is normal weight. Or to be more precise, *everything* except the app name is in normal weight, but since in GNOME we only have the app names on the left, this is not a big difference.

**Comment by joulev** [comment]
@vinceliuice Although I only asked to keep everything on the right at normal weight, if possible, could you please make *only* the app name bold? This will not affect many users, but it does affect me (and some others) since I use a global menu extension (see screenshot below), so making everything bold does not look very nice. Sure this is not a big matter but it would be a really cool feature.

![image](https://user-images.githubusercontent.com/44609036/124593599-0888c900-de89-11eb-9783-1ba631f29557.png)

**Comment by vinceliuice** [comment]
Using the bold version of the Whitesur icon, the overall look is still nice to me, but I can also provide an option for this!
![Screenshot from 2021-07-06 19-26-35](https://user-images.githubusercontent.com/7604295/124594241-27d82400-de92-11eb-8269-4636b81c3f84.png)

**Comment by joulev** [comment]
> Using the bold version of the Whitesur icon, the overall look is still nice to me, but I can also provide an option for this!
> ![Screenshot from 2021-07-06 19-26-35](https://user-images.githubusercontent.com/7604295/124594241-27d82400-de92-11eb-8269-4636b81c3f84.png)

Indeed it looks nice in your screenshot. It's just that my poor screen resolution is so low that I have become bold-phobia: avoid as much bold as possible.

**Comment by vinceliuice** [comment]
No problem! I'll make the font normal size on right!

**Comment by fegasi** [comment]
How did you manage to let only the app title like that? When I type HD all the text from the top bar is set to bold ;(

> In case someone is wondering how it looks like now.
> 
> ![photo_2021-07-04_23-32-54](https://user-images.githubusercontent.com/69485578/124425734-5c879680-dd3f-11eb-8d84-ebf10885d850.jpg)
> 
> (Wallpaper is a photo from Hong Kong, got from Unsplash.)
