### ISSUE TITLE
Padding of horizontal rule in topbar dropdown is too big

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#348]
![image](https://user-images.githubusercontent.com/44609036/124341403-3ef2e980-dbe6-11eb-931f-82a693a31198.png)

Not sure how this separation line is called but I think the padding around it is too big. It would be better for "Show keyboard layout" to look vertically centred.

**Comment by vinceliuice** [comment]
I can adjust the padding more smaller
