### ISSUE TITLE
Small gap on the right side of the screen

### ISSUE THREAD

**Issue by fegasi** [vinceliuice/WhiteSur-gtk-theme#349]
Ubuntu 21.04 here (although this problem was happening on 20.04 too). Whenever an application opens a new window over the main one, there is this transparent gap on the right side of the screen. I discovered that this also happens with others themes, but the gap is smaller. Could be a configuration issue on the .css file.

Thanks.

![Screenshot from 2021-07-02 23-53-34](https://user-images.githubusercontent.com/86142943/124343230-fa406180-db97-11eb-8982-aa84389f4fe9.png)
![Screenshot from 2021-07-02 23-54-32](https://user-images.githubusercontent.com/86142943/124343232-fb718e80-db97-11eb-8426-00a69bde09b1.png)

**Comment by fegasi** [comment]
Issue fixed with the latest release! Thx!

**Comment by joulev** [comment]
It is not working for me though (Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/44609036/125270261-b128a400-e333-11eb-8870-201a21a72549.png)

**Comment by rivanfebrian123** [comment]
I think it doesn't really matter
