### ISSUE TITLE
Firefox Bookmark submenus are not visible on WhiteSur-dark themes

### ISSUE THREAD

**Issue by dbasinge** [vinceliuice/WhiteSur-gtk-theme#353]
Firefox Bookmark submenus are not visible on WhiteSur-dark themes. Folders look ok before tweak.sh -f and on light theme.

OS: Fedora release 34 (Thirty Four) x86_64 
Resolution: 1920x1080 
DE: GNOME 40.2 
WM: Mutter 
WM Theme: WhiteSur-dark 
Theme: WhiteSur-dark [GTK2/3] 
Icons: WhiteSur-dark [GTK2/3] 

WhiteSur install from GitHub

![Screenshot from 2021-07-04 07-44-38](https://user-images.githubusercontent.com/2634758/124387831-46c19500-dc9d-11eb-9422-1a89035f8cec.png)

**Comment by dbasinge** [comment]
![Screenshot from 2021-07-04 07-44-38](https://user-images.githubusercontent.com/2634758/124387814-35788880-dc9d-11eb-8567-9bb37df8f763.png)

**Comment by vinceliuice** [comment]
Fixed！
