### ISSUE TITLE
Tab title hidden in Gnome System Monitor

### ISSUE THREAD

**Issue by popykunju** [vinceliuice/WhiteSur-gtk-theme#355]
64 Bit
![Screenshot from 2021-07-06 16-57-07](https://user-images.githubusercontent.com/86592004/124592750-6ca49080-de7b-11eb-916b-ecb98f7d531f.png)

Ubuntu 21.04
File System Tab Not displaying Complete Title

**Comment by joulev** [comment]
Ubuntu 20.04: it is working very well to me.

![image](https://user-images.githubusercontent.com/44609036/124592979-49341280-de88-11eb-856c-326177e5004d.png)

**Comment by popykunju** [comment]
how did u get border around tabs?

**Comment by rivanfebrian123** [comment]
> 64 Bit
> ![Screenshot from 2021-07-06 16-57-07](https://user-images.githubusercontent.com/86592004/124592750-6ca49080-de7b-11eb-916b-ecb98f7d531f.png)
> 
> Ubuntu 21.04
> File System Tab Not displaying Complete Title

Nah, it's not actually hidden. It's just clipped

**Comment by popykunju** [comment]
You dont have icons Before Titles

**Comment by popykunju** [comment]
@rivanfebrian123 Yea Sort of

**Comment by rivanfebrian123** [comment]
> how did u get border around tabs?

The older version of GNOME System monitor does look like that

**Comment by vinceliuice** [comment]
I'll adjust this button width

**Comment by popykunju** [comment]
@rivanfebrian123 Whats With The Symbolic Icons?

**Comment by popykunju** [comment]
@vinceliuice Which CSS file I need to change?

**Comment by joulev** [comment]
> @vinceliuice Which CSS file I need to change?

No you don't need to change anything, I'm sure Vince will add a commit regarding this issue soon, after that just reinstall the theme.

**Comment by popykunju** [comment]
![Screenshot from 2021-07-06 17-11-52](https://user-images.githubusercontent.com/86592004/124594347-51d31b80-de7d-11eb-8570-2f393af41ee0.png)

**Comment by rivanfebrian123** [comment]
> @rivanfebrian123 Whats With The Symbolic Icons?

![Screenshot from 2021-07-06 18-41-58](https://user-images.githubusercontent.com/6300910/124594355-e6437b00-de89-11eb-8d09-9823d34f2f7a.png)

New GNOME apps (not popup or dialog) have this UI. It's called "libhandy"

**Comment by popykunju** [comment]
@rivanfebrian123  So The Icons Could Be Causing Those Clipping

**Comment by joulev** [comment]
> > @rivanfebrian123 Whats With The Symbolic Icons?
> 
> ![Screenshot from 2021-07-06 18-41-58](https://user-images.githubusercontent.com/6300910/124594355-e6437b00-de89-11eb-8d09-9823d34f2f7a.png)
> 
> New GNOME apps (not popup or dialog) have this UI. It's called "libhandy"

It means if I install Ubuntu 21.04 tonight I will get this UI too? :(

**Comment by popykunju** [comment]
@joulev you Should Move

**Comment by rivanfebrian123** [comment]
> @rivanfebrian123 So The Icons Could Be Causing Those Clipping

Libhandy has homogenous width by design, so both the developer and the translator should limit the text to its recommended width, and well, the themer should also increase the width of that component to fit the text

**Comment by popykunju** [comment]
@rivanfebrian123 Are you a Devoloper?

**Comment by rivanfebrian123** [comment]
> > > @rivanfebrian123 Whats With The Symbolic Icons?
> > 
> > 
> > ![Screenshot from 2021-07-06 18-41-58](https://user-images.githubusercontent.com/6300910/124594355-e6437b00-de89-11eb-8d09-9823d34f2f7a.png)
> > New GNOME apps (not popup or dialog) have this UI. It's called "libhandy"
> 
> It means if I install Ubuntu 21.04 tonight I will get this UI too? :(

Sure :D

**Comment by rivanfebrian123** [comment]
> @rivanfebrian123 Are you a Devoloper?

Yes, but I'm a part time developer and student

**Comment by vinceliuice** [comment]
Fixed! 
![Screenshot from 2021-07-06 20-02-25](https://user-images.githubusercontent.com/7604295/124596641-1ba19600-de95-11eb-9e0a-8459699a8a93.png)

**Comment by rivanfebrian123** [comment]
@vinceliuice Wow! That was so fast! I didn't even make any progress this week. I'm sorry for that

**Comment by vinceliuice** [comment]
It’s just a small issues, adjust the size and it’s ok!  😄️

**Comment by rivanfebrian123** [comment]
Hehe :) Thanks

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by popykunju** [comment]
@vinceliuice Which File Should i Change?

**Comment by vinceliuice** [comment]
Just download the last update and run `./install.sh`

**Comment by popykunju** [comment]
It seems i couldnt managed to get this work.Can u plz send me the compiled file responsible for this.
email mathewmanualpc697@gmail.com

**Comment by popykunju** [comment]
> Fixed!
> ![Screenshot from 2021-07-06 20-02-25](https://user-images.githubusercontent.com/7604295/124596641-1ba19600-de95-11eb-9e0a-8459699a8a93.png)

Which font?
