### ISSUE TITLE
Files previews doesn't fit Gnome-Sushi borders

### ISSUE THREAD

**Issue by fegasi** [vinceliuice/WhiteSur-gtk-theme#357]
When using this theme, images, videos and other files previews are slightly off the lower circular borders of Gnome-Sushi, while with themes that have squared borders that doesn't happen. It would be nice if the bottom borders of Sushi stayed squared then.

![Screenshot from 2021-07-11 04-05-55](https://user-images.githubusercontent.com/86142943/125188033-7f62f080-e200-11eb-9f8e-f5fc5cda96c8.png)
![Screenshot from 2021-07-11 04-07-59](https://user-images.githubusercontent.com/86142943/125188035-812cb400-e200-11eb-9a42-9d68f00455c7.png)

**Comment by CyberAzure** [comment]
Rounding bottom corners on most apps is not possible, unfortunately.

**Comment by vinceliuice** [comment]
No all apps support rounded bottom corners!

**Comment by fegasi** [comment]
Oh! That's unfortunate. I'll close the topic then.

**Comment by CyberAzure** [comment]
Well, at least on most of my daily use apps don't support rounded corners, like Firefox for example.
Sorry Vince.

But after analysing that specific app (GNOME Sushi), seems like Transparent/PNG images actually make the window rounded somewhat.
You can do this test yourself, just download any transparent image, for example, some letter or sign, open it, and look at the bottom corners.
