### ISSUE TITLE
Changing Firefox Color?

### ISSUE THREAD

**Issue by UnPossible-Me** [vinceliuice/WhiteSur-gtk-theme#358]
Hello,
I've been running this theme for a couple of days, and it's wonderful to use!

But while reading though the docs, there are examples of firefox in a dark/black variant as well. Pure white is quite strenuous on the eyes, and I'd like to switch. 
The question is, how do I apply those?

I've tried `./tweaks.sh -f -c dark` to no avail, and if I try to use the themes manager in firefox,
1. It only changes the color for the webpage, not the tabs bar, bookmark bar, and search bar.
2. Makes the icons white (Presumably to stand out against a black bg), but as mentions above, the color doesn't change, making them invisible.

Is there something I'm missing?

**Comment by joulev** [comment]
If you want to use dark FF theme *and* dark GTK theme, just go to GNOME Tweaks and change the theme to the dark variant (I think unless you specifically used `-c light` in `./install.sh`, you can see the dark theme in the list). Firefox will automatically change everything to dark. (If it doesn't then probably changing the FF theme to Dark (about:addons) will do it.)

If you want to use dark FF theme and *white* GTK theme, then... well, who on earth would do that, frankly speaking?

**Comment by UnPossible-Me** [comment]
That's precisely the issue, when using `./install.sh`, I choose to install both, so I would have options.
Currently my entire GTK theme is dark, but FF won't switch.

I've tried going back to light, the apps awitch to light, and when switching to dark, everything switches back just fine except FF.
I'm running Mozilla Firefox Snap for Ubuntu v90.0.

In regards to the `about:addons`, I've tried that as well, which gives me the 2 problems I've mentioned .

**Comment by joulev** [comment]
If you are using FF snap, try `./tweaks.sh -s` (applying theme to snap apps). However I don't know if it really works.

**Comment by joulev** [comment]
If you are using Ubuntu, FF should have been pre-installed, use that instead of the snap version.

**Comment by UnPossible-Me** [comment]
Oh right, that completely slipped my mind.
Unfortunately both `./tweaks.sh -s` and `./tweaks.sh -s -c dark` fail to make a difference.

I'm not on Ubuntu exactly, I'm using Zorin, and while FF does come by default, I'm using the beta.

**Comment by UnPossible-Me** [comment]
Does that mean FF is not recognized properly while running the commands? It seems to work just fine with I run `./tweaks.sh -e or -f`
```
  Executing 'snap connect firefox:gtk-3-themes w...' as root
  Executing 'snap connect firefox:icon-themes wh...' as root
```
Seems to be working.... without having an effect.

**Comment by rivanfebrian123** [comment]
@UnPossible-Me Do you have any Firefox version installed other than the Snap one?

**Comment by UnPossible-Me** [comment]
Nope, not as far as I can tell. 
I've ran `firefox -v` and checked the app store for FF.. Both come up with only 1 version.

**Comment by rivanfebrian123** [comment]
I think you have more than one Firefox versions, one from `apt`, and the other one from `snap`. Because you know, the `snap` version of Firefox has `firefox-bin` command instead of `firefox`

**Comment by UnPossible-Me** [comment]
Hmm, is there any way you know of checking? 
I installed FF dev simply by extracting it to the `/opt` directory and creating a desktop file.

I've deleted both now and running `sudo locate firefox` just returns files from snap directories and icons.
When I run `firefox` from the cli, it brings up the snap version.

I've tried running the tweaks again, but no to no avail.

**Comment by UnPossible-Me** [comment]
While removing everything, it looked like I had another version of FF installed, tried my best to remove it, but that hasn't changed anything.
Perhaps there's still bits left.
I'll try with a VM I suppose, but thanks for all the suggestions!
