### ISSUE TITLE
Weird Glitches 

### ISSUE THREAD

**Issue by KonstantMan** [vinceliuice/WhiteSur-gtk-theme#361]
I installed the newest version on Arch GNOME 40 and i get this weird artifact no matter what tweaks combination i try 
![Screenshot from 2021-07-14 04-14-05.png](https://user-images.githubusercontent.com/56481040/125545370-b435238a-8144-4fc9-80df-eb974f1ad4e5.png)
I also noticed other artifacts only when i use these particular themes like
![Screenshot from 2021-07-14 05-33-56.png](https://user-images.githubusercontent.com/56481040/125551639-47ed2cc8-2994-4f52-9a2a-7b2b8849af61.png)
![Screenshot from 2021-07-14 05-30-50.png](https://user-images.githubusercontent.com/56481040/125551645-68e1fa1e-7549-4f2b-8853-e16eedba4a9d.png)

**Comment by CyberAzure** [comment]
This is VERY strange...maybe something relating to blur effect?
I don't know how to solve this problem, but maybe this is relating to blur.
Also, check your extensions, could be that too.

**Comment by vinceliuice** [comment]
Only this theme have this issue?

**Comment by KonstantMan** [comment]
> Only this theme have this issue?

Yeah as i said only this theme has this issue

**Comment by vinceliuice** [comment]
Could you disabled all gnome-shell extensions and see if this issue still？

**Comment by KonstantMan** [comment]
> Could you disabled all gnome-shell extensions and see if this issue still？

The issue remains even if i disable every extension and i reboot

**Comment by KonstantMan** [comment]
I did a fresh install of Arch with  GNOME 40 and the issue remains so its definitely not because i deleted a file or something, i will test if there are any bugs with other transparent themes too

**Comment by MarkoSagadin** [comment]
I also have the same problems on Manjaro Gnome 40, it seems that extension blur my shell is causing the problems :(

**Comment by KonstantMan** [comment]
I tried the theme with every extension disabled it still has these weird Glitches, also with Blur my shell, i don't have the weird black shadow on the top

**Comment by KonstantMan** [comment]
So after the latest commit the issue with the weird shadows got fixed but, the glitch with the gsconmect menu remains, and i can't add any image as an Activities Background no matter of what type it is jpg or png. Also Blur my Shell does not work  in changing the activities background too
