### ISSUE TITLE
Selection Glitch

### ISSUE THREAD

**Issue by aliazhar-id** [vinceliuice/WhiteSur-gtk-theme#363]
![2021-07-14_21-30](https://user-images.githubusercontent.com/58647884/125640107-3f312a73-c00c-478a-bca4-87c64c4981a4.png)
i got this selection issue, how to fix that?

im on arch linux , with DE XFCE latest

**Comment by CyberAzure** [comment]
You said XFCE, is that correct?

**Comment by aliazhar-id** [comment]
> You said XFCE, is that correct?

yes

**Comment by CyberAzure** [comment]
1. Could be a GPU problem.
2. Could be an extension.
3. Maybe not working on XFCE.

**Comment by aliazhar-id** [comment]
> 1. Could be a GPU problem.
> 2. Could be an extension.
> 3. Maybe not working on XFCE.

ok, if this isn't a bug or glitch, can i toggle off this selection feature?, i've tried but i can't, and confused how to toggle off that, maybe you can explain it for me please, i really like this theme.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by aliazhar-id** [comment]
lol

**Comment by aliazhar-id** [comment]
Thank You!
