### ISSUE TITLE
Ubuntu Apps and Files search page glitch.

### ISSUE THREAD

**Issue by cybr17crwlr** [vinceliuice/WhiteSur-gtk-theme#364]
![Screenshot from 2021-07-15 10-33-24](https://user-images.githubusercontent.com/25867103/125731623-b5d48594-6ad0-4ae7-833b-0221ecb53dc5.png)

The Search page has this view glitch where the files list and apps list overlaps.

OS: **Ubuntu 18.04.5 LTS x86_64** 
Host: Latitude 3400 
Kernel: **5.4.0-77-generic**
Shell: **bash 4.4.20** 
Resolution: **2560x1440** 
DE: GNOME 3.28.4 
WM: GNOME Shell 
WM Theme: **WhiteSur-dark-solid-purple** 
Theme: **WhiteSur-dark-purple [GTK2/3]** 
Icons: **WhiteSur-purple-dark [GTK2/3]** 
CPU: **Intel i7-8565U (8) @ 4.600GHz** 
GPU: NVIDIA GeForce MX130 
GPU: Intel Integrated Graphics 
Memory: 5435MiB / 31992MiB

**Comment by vinceliuice** [comment]
You desktop is too old not supported!

**Comment by popykunju** [comment]
you should upgrade gnome version maybe
