### ISSUE TITLE
Arch Linux | Gnome 40 | How to change the Coloured Apple Wallpaper when using Search

### ISSUE THREAD

**Issue by rsramkis** [vinceliuice/WhiteSur-gtk-theme#365]
Hi,

In Gnome 40 you can bring up Search by pressing _SUPER KEY_. From looking at the attached screen shot you can see that there is an Apple Styled Multi-colour Wallpaper which seems to be added by the theme. 

Is there a way to change this to make it blank or some other image?  

![Screenshot from 2021-07-16 22-45-18](https://user-images.githubusercontent.com/14362317/126024766-356aa1a9-fe74-43dd-95b7-6bd03e2ed369.png)

Thank you.

**Comment by vinceliuice** [comment]
Put a png file into WhiteSur-gtk-theme-master and run ./install.sh -b [your-png-file-name].png

**Comment by vinceliuice** [comment]
or just run ./install.sh -b blank

**Comment by vinceliuice** [comment]
or you can use https://extensions.gnome.org/extension/3193/blur-my-shell/

**Comment by rsramkis** [comment]
Thank you for your suggestions. So pretty much the 'background.png' file in the /usr/share/themes/WhiteSur-dark/gnome-shell/assets" is what is being used.

Thank for your suggestions.
