### ISSUE TITLE
Change dash-to-dock Show Applications Icon ?

### ISSUE THREAD

**Issue by amirhossein-ka** [vinceliuice/WhiteSur-gtk-theme#366]
Hi, 
How can i change Dash-to-Dock Show Applications Icon? I want the default, simple one 💯

**Comment by vinceliuice** [comment]
./install.sh --normal

**Comment by amirhossein-ka** [comment]
it didnt work
I removed the theme and install it again, then restart and set the theme but it's the same

**Comment by vinceliuice** [comment]
If you installed gdm theme, then you need remove it

**Comment by thejacer87** [comment]
is there a way to change it to a different icon/svg? according to this: https://askubuntu.com/a/1263114

would just need to change one icon.

where is this view-app-grid icon stored in the current theme?

**Comment by vinceliuice** [comment]
@thejacer87 https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/e3c1398db3b2dffc7bb208a58b7e6a6af1124901/src/assets/gnome-shell/common-assets/view-app-grid.svg

**Comment by thejacer87** [comment]
so i tried putting an svg of one of the ubuntu icons from [here](https://assets.ubuntu.com/v1/9fbc8a44-circle-of-friends-web.zip)

it just makes the application button blank.

and if i try this icon from the repo: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/e3c1398db3b2dffc7bb208a58b7e6a6af1124901/src/assets/gnome-shell/activities/activities-ubuntu.svg

it's just really blurry
![image](https://user-images.githubusercontent.com/6412919/132877374-8410239b-c1ef-4d3b-af25-1108e477b251.png)

**Comment by vinceliuice** [comment]
Use ikscape to make the size bigger (like 256px)

**Comment by thejacer87** [comment]
ya that still doesnt work.

not a huge deal.. maybe something to work on later

**Comment by smileBeda** [comment]
1. Place your new custom icon somwhere
2. Create a custom theme in `/home/YOUR-USERNAME/.local/share/themes` (for example `MyTheme`
3. Inside that folder create a folder `gnome-shell`
4. Inside that folder create a `gnome-shell.css` file
5. In that file add the below contents:
```
@import url("/usr/share/themes/WhiteSur-Dark-Dark-grey/gnome-shell/gnome-shell.css");// change if you use another theme

.show-apps .show-apps-icon {
    color: transparent !important;
    background-image: url("/Path/To/Your/Custom/view-app-grid.svg");
    background-size: contain;
}
```
