### ISSUE TITLE
Backgroud not applied

### ISSUE THREAD

**Issue by luisrdzruiz** [vinceliuice/WhiteSur-gtk-theme#368]
When I installed the theme I selected a background but this not appear in overview
Install options
![image](https://user-images.githubusercontent.com/43277999/126117185-689b6d4d-6736-4ee8-92aa-fd70fb996a83.png)
Overview
![image](https://user-images.githubusercontent.com/43277999/126117017-463e78d9-8818-475b-96c3-b435daa866bd.png)

**Comment by vinceliuice** [comment]
Fixed!
