### ISSUE TITLE
Application name is not bold anymore.

### ISSUE THREAD

**Issue by CyberAzure** [vinceliuice/WhiteSur-gtk-theme#372]
Ubuntu 20.04, GNOME 3.36.

![image](https://user-images.githubusercontent.com/69485578/126616910-5822501c-a07e-4965-bfed-5ded540f04ac.png)

As you can see, the app name(In this case, Safari) is not on bold anymore.
Did that feature got removed from WhiteSur? I loved that so much...

**Comment by popykunju** [comment]
> Ubuntu 20.04, GNOME 3.36.
> 
> ![image](https://user-images.githubusercontent.com/69485578/126616910-5822501c-a07e-4965-bfed-5ded540f04ac.png)
> 
> As you can see, the app name(In this case, Safari) is not on bold anymore.
> Did that feature got removed from WhiteSur? I loved that so much...

how did you get the global menu.

**Comment by joulev** [comment]
oh and how did you install Safari on Linux?

**Comment by joulev** [comment]
![image](https://user-images.githubusercontent.com/44609036/126637700-31bff560-61df-47a0-818e-f87c7dc1cec5.png)

I just reinstalled the theme and the application name is bold.

**Comment by CyberAzure** [comment]
> how did you get the global menu.

Two extensions, [this one](https://extensions.gnome.org/extension/3703/big-sur-menu/) and [this one](https://extensions.gnome.org/extension/4111/mock-universal-menu/).

> oh and how did you install Safari on Linux?

Follow [this guide](https://askubuntu.com/questions/1062658/is-it-safe-to-change-the-name-of-a-desktop-file-in-usr-share-applications), there, you can change name and icon to anything you want, so I turned my Mozilla Firefox to Safari & put the Safari icon on it, and thus, Monterey theme on top of everything.

_Anyways..._

Closing this issue as I managed to fix it myself, seems like the default Ubuntu font doesn't like bold fonts a lot, by putting the San Francisco font, the bold texts got back again.
