### ISSUE TITLE
Buttons are not center aligned

### ISSUE THREAD

**Issue by seemsindie** [vinceliuice/WhiteSur-gtk-theme#38]
After fresh install when activated buttons text is not at the center but at the top.

![image](https://user-images.githubusercontent.com/1268576/91727442-00456a80-eba2-11ea-8b32-2099d5258e72.png)

**Comment by vinceliuice** [comment]
I also don't know how to deal with this

**Comment by TheDevtop** [comment]
You could try to change the GTK icon size, see if they will align then.

**Comment by Anmol2001** [comment]
can i try

**Comment by mepowerleo10** [comment]
You could edit the `~/.config/gtk-3.0/gtk.css` file and add the following line:
`button.text-button {
        min-height: 24px;
}
`
Worked for me... for now!
Seems this is an issue with setting the Gtk `min-height `less than 24px. There is an open issue in this gtk thread in gitlab [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/2764)

**Comment by vinceliuice** [comment]
Fixed
