### ISSUE TITLE
In firefox, icons on the right side of the urlbar (bookmark, multi account containers button) are stretched horizontally.

### ISSUE THREAD

**Issue by clyde37** [vinceliuice/WhiteSur-gtk-theme#380]
Arch/latest
Using either the Monterey or the old version do exactly the same thing.

![urlbar](https://user-images.githubusercontent.com/79387074/127911631-28092986-23da-4b1a-b30f-0e305be5aa76.png)
![icons](https://user-images.githubusercontent.com/79387074/127911632-603c4d7f-d87d-4631-8760-b01f86f77104.png)

**Comment by vinceliuice** [comment]
Update your firefox to the last version

**Comment by clyde37** [comment]
I'm on firefox nightly lol

**Comment by vinceliuice** [comment]
Oh! I'll test on nightly then

**Comment by clyde37** [comment]
Thanks, I think it happened on firefox stable too so it might just be something wrong with my setup as well

**Comment by vinceliuice** [comment]
Fixed!

**Comment by clyde37** [comment]
thanks
