### ISSUE TITLE
If there is an additional icon at clock bar, the clock display is not good

### ISSUE THREAD

**Issue by joulev** [vinceliuice/WhiteSur-gtk-theme#381]
For example, when Do Not Disturb is on:

![image](https://user-images.githubusercontent.com/44609036/128116453-024127cd-cd8b-4541-9c80-20aba0ae33f0.png)

There is a space in the left of the clock (to make sure the clock is still centered). I think it should be removed.

Information:  
Ubuntu 20.04.2  
GNOME 3.36.8

**Comment by fegasi** [comment]
This also happens with me. Confirming on Ubuntu 21.04.
