### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by oexlye08** [vinceliuice/WhiteSur-gtk-theme#383]
DEPS: 'glib2.0', 'sassc', and 'xmllint' are required for theme installation.
  DEPS: Checking your internet connection...
  DEPS ERROR: You have an internet connection issue

but i dont have problem with my connection

**Comment by vinceliuice** [comment]
You have an internet connection issue

**Comment by johnjago** [comment]
@oexlye08 How did you fix this? I had the same problem on Arch, but I just commented out the call to `prepare_deps` to bypass the check, since I for sure did have internet: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/lib-install.sh#L159

**Comment by vinceliuice** [comment]
@johnjago  My fault! I changed the wrong typo and caused this problem in install.sh, now it is fixed！

**Comment by maskrtnik01** [comment]
Hello, I have this same issue. What exactly was that typo? If there is a chance of failure on my side, what to look for? Web browser and apt install work fine, so I definitely have internet connection.

**Comment by riju-dc** [comment]
Changing ln 70 from
```bash
if ! remote_time="$(get_utc_epoch_time)"; then
```
to 
```bash
if remote_time="$(get_utc_epoch_time)"; then
```
in file `lib-install.sh` worked for me.
This essentially bypasses the `get_utc_epoch_time()` check.

**Comment by rijumone** [comment]
Changing ln 70 from
```bash
if ! remote_time="$(get_utc_epoch_time)"; then
```
to 
```bash
if remote_time="$(get_utc_epoch_time)"; then
```
in file `lib-install.sh` worked for me.
This essentially bypasses the `get_utc_epoch_time()` check.

**Comment by martinkarugaba** [comment]
> Changing ln 70 from
> 
> ```shell
> if ! remote_time="$(get_utc_epoch_time)"; then
> ```
> 
> to
> 
> ```shell
> if remote_time="$(get_utc_epoch_time)"; then
> ```
> 
> in file `lib-install.sh` worked for me. This essentially bypasses the `get_utc_epoch_time()` check.

> This has wirked for me, thank you.

**Comment by asherzod1** [comment]
Write this code on teminal 
sudo apt -y install libxml2-utils
sudo apt-get install libglib2.0-dev
sudo apt install sassc

It worked for me, I hope it works for you too
