### ISSUE TITLE
Gtk theme not installing for snaps

### ISSUE THREAD

**Issue by RJU97** [vinceliuice/WhiteSur-gtk-theme#386]
Ubuntu 21.04 (64-bit)
Kernel 5.11.0-25-generic
Snap 2.51.3
Snapd 2.51.3
Series 16

I installed the theme but it's not working for the snaps as you can see in the screenshots. I also noticed that there isn't a "themes" folder inside /snap/whitesur-gtk-theme/current/share.
![Captura de pantalla de 2021-08-06 20-01-56](https://user-images.githubusercontent.com/88565782/128583281-9d4b51ec-38b9-4a83-a11f-ffab8e0bce63.png)
![Captura de pantalla de 2021-08-06 20-02-04](https://user-images.githubusercontent.com/88565782/128583282-20f8967b-403a-434a-849d-35a2953c9a17.png)
![Captura de pantalla de 2021-08-06 20-14-02](https://user-images.githubusercontent.com/88565782/128583391-98b738e9-6512-4725-9a84-0489455396df.png)

**Comment by vinceliuice** [comment]
`./tweaks.sh -s` not work?

**Comment by RJU97** [comment]
No, I even tried to run it as root but it didn't work either.

**Comment by Lowseling** [comment]
> `./tweaks.sh -s` not work?

I have the same issue. I also tried installing the snap theme and connecting to snap apps manually. It's like snap can't find the default system theme. WhiteSur is set as default in my desktop settings and checking snap connections the theme is also set correctly.

**Comment by Lowseling** [comment]
I don't know if you are already invastigating this issue, but after some search I noticed that the "themes" folder is missing in /var/lib/snapd/snap/whitesur-gtk-theme/current/share. There is only the icons folder. I don't know if this is something that can help troubleshoot the issue.

**Comment by swiatlyk** [comment]
I have the same problem here. I can't make snap apps to respect this theme, they load the default gnome theme.

**Comment by swiatlyk** [comment]
Hmm i checked once again, but on other computer with Ubuntu 21.04 (prevoius was 20.04) and still solution is working on my side
![Zrzut ekranu z 2021-10-08 23-04-42](https://user-images.githubusercontent.com/18462928/136624805-4a41f9ad-fcad-4241-8ef9-2a5ab81464a1.png)
.

**Comment by pguedes** [comment]
tested this on my laptop with ubuntu 20.04 and @swiatlyk's proposed fix works for me

**Comment by RJU97** [comment]
@swiatlyk's proposed fix worked for me after upgrading to ubuntu 21.10.

**Comment by poldolot** [comment]
@swiatlyk it's not working for Ubuntu 22.04 :(
Themes are inside dir /snap/whitesur-gtk-theme/current/share/themes/ but the're not working.
