### ISSUE TITLE
Inverted radius of the rotation controls in Image Viewer

### ISSUE THREAD

**Issue by Lowseling** [vinceliuice/WhiteSur-gtk-theme#387]
OS: ArchLinux
Kernel: 5.13.8-arch1-1
DE: Budgie 10.5.3
Theme installed via github with ./install.sh

At the bottom of the GNOME Image Viewer application you can see that the radius of the rotation controls is inverted. I don't know if this is something with the application itself or it's a theme bug.

![Screenshot from 2021-08-07 12-09-38](https://user-images.githubusercontent.com/4274226/128596706-dfb86286-4a19-4c07-b0fb-6370c255cd4e.png)

**Comment by vinceliuice** [comment]
This can not be fixed, it does not support that
