### ISSUE TITLE
火狐浏览器外观不正常

### ISSUE THREAD

**Issue by chrisyang2003** [vinceliuice/WhiteSur-gtk-theme#389]
Ubuntu 21.04
![image](https://user-images.githubusercontent.com/63803385/129120036-fa5c04f5-f992-4ad7-abed-f433180f2389.png)

![image](https://user-images.githubusercontent.com/63803385/129120052-66a2329d-ee0f-4e20-85b9-cb3cdb575570.png)

**Comment by vinceliuice** [comment]
你火狐的版本号是多少？

**Comment by vinceliuice** [comment]
还有你左边有四个按钮需要修改设置的
要启用这个文件： @import "Monterey/left_header_button_4.css"
![Screenshot_20210812_095720](https://user-images.githubusercontent.com/7604295/129126724-7b22f50f-3c81-473b-9ace-8ddd5c72d71c.png)

**Comment by chrisyang2003** [comment]
已解决，有效
