### ISSUE TITLE
Type to Search CSS Problem in CentOS 7

### ISSUE THREAD

**Issue by bilal-hanif43** [vinceliuice/WhiteSur-gtk-theme#39]
![image](https://user-images.githubusercontent.com/26106704/91770695-0d427800-ebfb-11ea-898f-3146e58af47a.png)
![image](https://user-images.githubusercontent.com/26106704/91792407-de45f980-ec2e-11ea-932b-de1e4e2f20fa.png)

After GDM build I have this CSS problem.

**Comment by vinceliuice** [comment]
This theme only support > gnome-shell 3.22

**Comment by bilal-hanif43** [comment]
I have GNOME Shell 3.28.3

**Comment by vinceliuice** [comment]
Sorry it's 3.32,
