### ISSUE TITLE
Glitches in dconf-editor and gnome-tweaks

### ISSUE THREAD

**Issue by v1gnesh** [vinceliuice/WhiteSur-gtk-theme#395]
Hi,

With dconf-editor 3.38.2, portion of the title bar is overlapping.

![image](https://user-images.githubusercontent.com/234149/129477881-2a2bda61-8da3-416a-97a0-72b61a800398.png)

With gnome-tweaks, below is a glitch.
I don't have a recording tool to capture the launch sequence of glitches...

![image](https://user-images.githubusercontent.com/234149/129477932-eee98146-a311-4b66-b09d-452c37ee2331.png)

Thanks in advance for having a look.

Running Ubuntu 21.04 and WhiteSur-gtk-light-solid.

**Comment by kernelb00t** [comment]
Hey, does this issue still happen with the latest version of Gnome (gnome 46) ?

**Comment by v1gnesh** [comment]
Hi, no idea. I don't use WhiteSur anymore.

**Comment by kernelb00t** [comment]
Okey, can you close this issue? Thanks
