### ISSUE TITLE
Elementary os Odin - Transparent Background for notifications

### ISSUE THREAD

**Issue by prateekmedia** [vinceliuice/WhiteSur-gtk-theme#396]
Distro- Elementary os odin
Screenshot- 
![Screenshot from 2021-08-16 13-30-49](https://user-images.githubusercontent.com/41370460/129531147-532e7035-37c1-48bb-9101-7b769e1f2938.png)

Reason:
Elementary os odin have a complete rewrite of system stylesheet.

**Comment by vinceliuice** [comment]
Fixed!
