### ISSUE TITLE
Elementary os- Bugs with selection highlight when searching

### ISSUE THREAD

**Issue by prateekmedia** [vinceliuice/WhiteSur-gtk-theme#397]
In elementary os odin when searching for apps, selection hightlight is transparent:
![Screenshot from 2021-08-17 13-53-47](https://user-images.githubusercontent.com/41370460/129697236-dd5ecbe1-38d6-4e39-8e70-cfdfbfa93238.png)

Reason: e34fef3a1638bdfa573b3351a1e1453168fdb6fa

**Comment by prateekmedia** [comment]
Thanks @vinceliuice, hope you will update this on your other popular themes too.

**Comment by vinceliuice** [comment]
No problem!
