### ISSUE TITLE
GDM build fails

### ISSUE THREAD

**Issue by zeparu** [vinceliuice/WhiteSur-gtk-theme#4]
```
 ~/Repos/WhiteSur-gtk-theme   master  sudo ./install.sh --icon manjaro --gdm
Installing '/usr/share/themes/WhiteSur-light'...
Installing '/usr/share/themes/WhiteSur-light-alt'...
Installing '/usr/share/themes/WhiteSur-dark'...
Installing '/usr/share/themes/WhiteSur-dark-alt'...
Installing '/usr/share/themes/WhiteSur-light-solid'...
Installing '/usr/share/themes/WhiteSur-light-solid-alt'...
Installing '/usr/share/themes/WhiteSur-dark-solid'...
Installing '/usr/share/themes/WhiteSur-dark-solid-alt'...

Installing WhiteSur-dark gdm theme...
Installing '/usr/share/gnome-shell/gnome-shell-theme.gresource'...
/home/zepar/Repos/WhiteSur-gtk-theme/src/main/gnome-shell/gnome-shell-theme.gresource.xml: »assets/background.png« konnte in keinem Quellordner gefunden werden.
```
last line translated from german means that `assets/background.png` could not be found in any source directory

**Comment by MahdiBaghbani** [comment]
Yes, i suggest there are several mistakes in filenames.

The names are defined in [/src/main/gnome-shell/gnome-shell-theme.gresource.xml](../blob/master/src/main/gnome-shell/gnome-shell-theme.gresource.xml) as background.png

but the file in [/src/assets/gnome-shell/common-assets/background.jpg](../blob/master/src/assets/gnome-shell/common-assets/background.jpg) is in jpg format.

@vinceliuice also many filenames doesn't exists in assets directory, or many of them are placed in cinnamon directory, you can test it yourself to see it.
