### ISSUE TITLE
Files app leaving trails of mouse in Ubuntu 20.04.1

### ISSUE THREAD

**Issue by yasharya2901** [vinceliuice/WhiteSur-gtk-theme#40]
I followed this article to make my Ubuntu look like Mac (https://mashtips.com/make-ubuntu-look-like-macos-big-sur/) but I got a problem in the Files app. Here's the screen recorded issue of this: 
[Mac GTK theme bug.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/5155127/Mac.GTK.theme.bug.zip)

**Comment by vinceliuice** [comment]
You can only use solid version, solid version don't have this issue on Nvidia card

**Comment by yasharya2901** [comment]
Yeah, I do have an Nvidia card. Thanks for the suggestion but how am I supposed to clone it. Can you specify the link which I can type in Terminal?

**Comment by vinceliuice** [comment]
Just download from here and run `./install.sh -o solid`

**Comment by yasharya2901** [comment]
Okay, thanks Vince! But am I supposed to delete the previous install that saved it to the .themes folder?

**Comment by vinceliuice** [comment]
You can delete all old themes then reinstall it

**Comment by yasharya2901** [comment]
Thanks @vinceliuice! I'll get back to you when it's done

**Comment by vinceliuice** [comment]
OK!

**Comment by yasharya2901** [comment]
So, the solid theme was also installed there. Sorry to have you disturbed about this. Now it's working pretty fine, no mouse trails. Thanks, @vinceliuice! I am closing this issue since it is resolved now.
