### ISSUE TITLE
Flatpak Tweak Error

### ISSUE THREAD

**Issue by llsaboya** [vinceliuice/WhiteSur-gtk-theme#410]
I updated the theme and when i try ./tweak -F I get this:

Oops! Operation failed...

  =========== ERROR LOG ===========
  
>>>>>>> No error log found <<<<<<
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-flatpak.sh at 47
    >>> lib-install.sh
    >>> tweaks.sh
  SNIPPET:
    >>> ostree --repo="$repo_dir" init --mode=archive
  TRACE  :
    >>> signal_error
    >>> pakitheme
    >>> connect_flatpak
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu debian;pop;21.04
  SUDO   : no
  GNOME  : old
  REPO   : 2021-08-27T02:24:32-0300

  HINT: Try install depends to fix this: sudo apt install sassc libglib2.0-dev-bin libxml2-utils

  HINT: You can google or report to us the info above

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

I try the hint and those depends are already installed.

**Comment by vinceliuice** [comment]
I updated the installation method as local package installation now, which is not the same as before. Previously, it was just linking the themes folder.
