### ISSUE TITLE
Highlighted selection has square corner

### ISSUE THREAD

**Issue by Loreno10** [vinceliuice/WhiteSur-gtk-theme#413]
Fedora 34

Here's a screenshot from the Settings panel:

Before highlight:
![image](https://user-images.githubusercontent.com/10273406/131305489-b10b6b1f-597e-40b9-ae55-2b2d21d23f1a.png)

After highlight:
![image](https://user-images.githubusercontent.com/10273406/131305395-ba65ce36-d8c7-4e67-9f8c-aee4a7b279b2.png)

You can see that the bottom corners of the widget become squared after highlighting the last element on the list.

**Comment by vinceliuice** [comment]
This can not be fixed by theme, only this app update it's gtk widgets to last unified one like nautilus 40
