### ISSUE TITLE
Counter intuitive Firefox Monterey tabs

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#415]
![Screenshot from 2021-09-05 14-19-46](https://user-images.githubusercontent.com/6300910/132118917-aca387e4-bfc9-42d8-9907-23b02e17bc82.png)

I think the tab close button shouldn't be on the left, and also, it should be left-aligned

**Comment by vinceliuice** [comment]
I'll make the `left side` as a option

**Comment by rivanfebrian123** [comment]
Thanks, Vince

**Comment by vinceliuice** [comment]
You are welcome!
