### ISSUE TITLE
Make the tab width the same at the title length in Monterey style

### ISSUE THREAD

**Issue by victormihalache** [vinceliuice/WhiteSur-gtk-theme#417]
I think that in Firefox's Monterey style the tab width rhoul try to be as small as possible (althiugh a minimum has to exist) and go as wide as it can (with a max value obviously). Is this possible? I will look for and link some useful stuff later.

**Comment by kernelb00t** [comment]
I think that's the actual behavior. If this is is still important to you, please detail what you want. If not, you can close this issue.
