### ISSUE TITLE
Is it possible to apply the custom theme of Firfox to Chrome?

### ISSUE THREAD

**Issue by tmltmltml** [vinceliuice/WhiteSur-gtk-theme#42]
Thanks for your effort! @vinceliuice

**Comment by tmltmltml** [comment]
I Google it, but find user styleshetts has been removed since Chrome 33. I'd appreciate it if you could give me a clue. 
Thank you in advance!

**Comment by vinceliuice** [comment]
No Chrome not support this!

**Comment by tmltmltml** [comment]
Ok, thanks for your reply!
