### ISSUE TITLE
Narrow Handy ViewSwitcher isn't correctly aligned

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#420]
![Screenshot from 2021-09-08 14-24-45](https://user-images.githubusercontent.com/6300910/132465255-c9524288-5360-4674-bc00-844ecec7e7b3.png)

The labels should be moved a little bit to the right

Distro: Void Linux
GNOME: 40

**Comment by vinceliuice** [comment]
No problem! I'll fix this

**Comment by vinceliuice** [comment]
Fixed!
