### ISSUE TITLE
How do I do this?

### ISSUE THREAD

**Issue by pranavr2003** [vinceliuice/WhiteSur-gtk-theme#423]
I'm sorry I'm just being stupid, but this is my first proper tryst with Linux of any sort here, so help is much appreciated. I installed this on my Pi 400 - Cloned the repo, then installed the dark theme with `./install.sh -c dark`.

Now it's installed on `/home/pi/.themes` and sure enough, I see four folders there. I've Googled it, but can't find any info on how I actually use the theme, now that it's installed.

*Any* help is appreciated.

**Comment by vinceliuice** [comment]
What's your desktop？

**Comment by pranavr2003** [comment]
Raspberry Pi os

**Comment by vinceliuice** [comment]
I mean the desktop Raspberry is using

**Comment by pranavr2003** [comment]
> I mean the desktop Raspberry is using

@vinceliuice I'm not what you mean by this, but I have a Raspberry Pi 400, running Raspberry Pi OS (which is based on Debian)

**Comment by vinceliuice** [comment]
I mean you linux desktop is not supported, this is a gnome desktop theme

**Comment by pranavr2003** [comment]
```pi@raspberrypi:~ $ neofetch
  `.::///+:/-.        --///+//-:``    pi@raspberrypi 
 `+oooooooooooo:   `+oooooooooooo:    -------------- 
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l 
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 400 Rev 1.0 
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.10.60-v7l+ 
     `:++ooo/.        :+ooo+/.`       Uptime: 1 hour, 3 mins 
        ...`  `.----.` ``..           Packages: 1939 (dpkg) 
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3 
    -:::-`   .:::::::-`  `-:::-       Resolution: 1280x720 
   `::.  `.--.`  `` `.---.``.::`      DE: LXDE 
       .::::::::`  -::::::::` `       WM: Xfwm4 
 .::` .:::::::::- `::::::::::``::.    WM Theme: WhiteSur-dark 
-:::` ::::::::::.  ::::::::::.`:::-   Theme: Adwaita [GTK3] 
::::  -::::::::.   `-::::::::  ::::   Icons: Adwaita [GTK3] 
-::-   .-:::-.``....``.-::-.   -::-   Terminal: lxterminal 
 .. ``       .::::::::.     `..`..    Terminal Font: Monospace Bold 13 
   -:::-`   -::::::::::`  .:::::`     CPU: BCM2711 (4) @ 2.000GHz 
   :::::::` -::::::::::` :::::::.     Memory: 698MiB / 3837MiB 
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.                               
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`
```
@vinceliuice This is the one

**Comment by vinceliuice** [comment]
You desktop is  LXDE but I did not tested on LXDE, I don't know if it works on this desktop

**Comment by vinceliuice** [comment]
Use this to set theme:https://wiki.lxde.org/en/LXAppearance

**Comment by rivanfebrian123** [comment]
@pranavr2003 does this article help? https://www.addictivetips.com/ubuntu-linux-tips/customize-the-lxde-desktop/

**Comment by pranavr2003** [comment]
@rivanfebrian123 As a matter of fact, it does. Thanks for that

**Comment by rivanfebrian123** [comment]
Your welcome :)
