### ISSUE TITLE
 Rounded corners

### ISSUE THREAD

**Issue by wsalmeida** [vinceliuice/WhiteSur-gtk-theme#429]
I noticed that when maximizing the windows the corners lose their rounded finish
system: Debian
Desktop: Gnome 40
![Captura de tela de 2021-09-18 11-08-22](https://user-images.githubusercontent.com/38542279/133892379-e2e62ae8-3ffc-40c2-9311-6658e83f8c90.png)
file:///home/wellington/Imagens/Captura%20de%20tela%20de%202021-09-18%2011-08-22.png

**Comment by vinceliuice** [comment]
run `./install.sh --round`
