### ISSUE TITLE
Linux Mint 20 - glib-compile-resources: not found

### ISSUE THREAD

**Issue by marcossantoscs** [vinceliuice/WhiteSur-gtk-theme#43]
Hello community, I'm trying to install the theme but when executing the command, it presents the error below:

```
Installing '/usr/share/themes/WhiteSur-light'... 
./install.sh: linha 145: glib-compile-resources: not found
```

I'm using linux mint 20 xfce x64 bits.

**Comment by Anon-65535** [comment]
I figured it out:
`sudo apt update && sudo apt install libglib2.0-dev-bin`
