### ISSUE TITLE
Make window borders thiner

### ISSUE THREAD

**Issue by minhntp** [vinceliuice/WhiteSur-gtk-theme#431]
Hi. Could you make the borders thinner, like on your Mojave theme? 
The current thickness makes it hard to click a window behind the current window.
If you don't think this is a good idea, could you tell me where to adjust it myself?
Thank you.

**Comment by vinceliuice** [comment]
What boder？

**Comment by minhntp** [comment]
The top, right, bottom, left borders. 
I mean the shadows right outside of those 4 borders.
Sorry for for explaining well 😁

**Comment by vinceliuice** [comment]
Still don't get it, what's your desktop？

**Comment by minhntp** [comment]
It's gnome 3.36.
The shadow of the window is too thick. When the mouse is hover on that shadow area, if there is another window behind that shadow area, the mouse can't click through that shadow to touch that other window.

**Comment by tndev** [comment]
I have the same problem. For certain applications, the shadow counts to the window border. In my case, I have roughly 50px of shadow that count to the area where the resize cursor is shown.

**Comment by junsyw** [comment]
Hello, the following happens to me that it is difficult for me to select the borders of the application windows
![IMG_20210925_063726](https://user-images.githubusercontent.com/49370860/134770441-2391e3cb-fea1-4721-ade4-f0be8a05b333.jpg)
![IMG_20210925_063734](https://user-images.githubusercontent.com/49370860/134770443-2daef13e-7b7b-4279-a831-d8bb6cb75c54.jpg)
![IMG_20210925_063744](https://user-images.githubusercontent.com/49370860/134770445-ed2ca2ee-b9db-4cae-807e-048070848518.jpg)
.

**Comment by junsyw** [comment]
Hello, the following happens to me that it is difficult for me to select the borders of the application windows.
I have gnome 3.36.8
thank
![IMG_20210925_063726](https://user-images.githubusercontent.com/49370860/134770753-b8fcce44-4ddf-4328-aed0-38a5fba57c4c.jpg)
![IMG_20210925_063734](https://user-images.githubusercontent.com/49370860/134770755-73b5b9da-1dff-403f-bddf-8b83b79d3441.jpg)
![IMG_20210925_063744](https://user-images.githubusercontent.com/49370860/134770757-f1002bc4-c6ca-4eef-999f-11ff87928e5e.jpg)

**Comment by vinceliuice** [comment]
Thanks for the screenshot! i fixed it now

**Comment by junsyw** [comment]
> Thanks for the screenshot! i fixed it now

Thanks!
