### ISSUE TITLE
Cannot install, install hangs on progress elipses forever

### ISSUE THREAD

**Issue by tsujp** [vinceliuice/WhiteSur-gtk-theme#432]
I'm on Void Linux and I cannot get this to install, it seems to just hang on this screen -- I've left it for 30 minutes and it seems to ignore `^C`. Any ideas what could be wrong here?

![Screenshot from 2021-09-27 19-02-03](https://user-images.githubusercontent.com/4571498/134896403-c887a08f-4341-41c2-a94f-68fb0ed205c6.png)

**Comment by vinceliuice** [comment]
What command did you run?

**Comment by tsujp** [comment]
Whoops I left that out I ran `sudo ./install.sh` I tried with explicit options which worked. Is the default directory actually hardcoded to `/home/vince`?

**Comment by vinceliuice** [comment]
It should be your user folder

**Comment by vinceliuice** [comment]
If you run with sudo, then it'll install in `/usr/share/themes`

**Comment by tsujp** [comment]
Running says successful install but GNOME 40 still looks like it normally does.

```
sudo ./install.sh \
  -d "$HOME/.themes" \
  -a 'normal' \
  -t 'default' \
  -p 'default' \
  -P 'default' \
  -s 220 \
  -i standard \
  -b default \
  -m \
  -N 'mojave'
```

**Comment by rivanfebrian123** [comment]
I think there is a problem with the signal traps. Unfortunately, I can't look into the codebase right now. Still doing some collage projects

**Comment by vinceliuice** [comment]
Don't use sudo with -d "$HOME/.themes", just run `./install.sh`

**Comment by tsujp** [comment]
Right, well in both cases the theme files are there and I go to Tweaks and set the theme. That does the GTK styling for the windows, what else needs to be set?
