### ISSUE TITLE
I can't change the top left icon

### ISSUE THREAD

**Issue by Rompicapo** [vinceliuice/WhiteSur-gtk-theme#434]
I'm on arch with gnome and everything worked fine, but I can't change the top left icon, executed the command: `./install.sh --icon arch` the command is successful without any errors, after restarting the PC the icon has not changed

**Comment by vinceliuice** [comment]
Did you installed gdm theme？

**Comment by Rompicapo** [comment]
yes I installed it, everything works very well, except this little "GNOME Shell 'Activities' icon"

**Comment by kehanlu** [comment]
Same issue here

**Comment by vinceliuice** [comment]
If you installed gdm theme, then you need run `./tweaks.sh -g -i ubuntu` to make it work

**Comment by Rompicapo** [comment]
worked with `sudo ./tweaks.sh -g -i ubuntu` thanks

**Comment by vinceliuice** [comment]
You are welcome!
