### ISSUE TITLE
Linux Lite dont work

### ISSUE THREAD

**Issue by potmeL** [vinceliuice/WhiteSur-gtk-theme#436]
I have instaled this theme on linux lite 5.6, I didn't like it and now im trying to delete it, but "./install.sh -r" just delete it but dont change the theme. What I can do to recover the default theme?

**Comment by vinceliuice** [comment]
If you installed gdm theme, then run `sudo ./tweaks.sh -r -g`

**Comment by hemish04082005** [comment]
You have to change back to your theme. Linux Lite uses XFCE desktop, so you have to select the default Linux lite theme in "Appearance" app availalbe in menu

**Comment by potmeL** [comment]
> You have to change back to your theme. Linux Lite uses XFCE desktop, so you have to select the default Linux lite theme in "Appearance" app availalbe in menu

after installing the theme settings menu have no option to change theme, so i cant do it

**Comment by potmeL** [comment]
> If you installed gdm theme, then run `sudo ./tweaks.sh -r -g`

nothing changed and, I have installed gtk

**Comment by rivanfebrian123** [comment]
> > You have to change back to your theme. Linux Lite uses XFCE desktop, so you have to select the default Linux lite theme in "Appearance" app availalbe in menu
> 
> after installing the theme settings menu have no option to change theme, so i cant do it

The name is "Appearence". Go open it

**Comment by potmeL** [comment]
> > > You have to change back to your theme. Linux Lite uses XFCE desktop, so you have to select the default Linux lite theme in "Appearance" app availalbe in menu
> > 
> > 
> > after installing the theme settings menu have no option to change theme, so i cant do it
> 
> The name is "Appearence". Go open it

there is no option ( https://prnt.sc/1ucyp0w )

**Comment by vinceliuice** [comment]
You are using gnome deskop you need install `gnome-tweaks` to set the theme
