### ISSUE TITLE
New Safari

### ISSUE THREAD

**Issue by aargar1** [vinceliuice/WhiteSur-gtk-theme#437]
The newest Safari uses colour-changing header bars and the tabs are a bit different, are there plans to implement this?

<image src="https://images.macrumors.com/t/BphAJ8d3fSZgotOyq6qdt0wqoUg=/800x0/article-new/2021/07/macos-monterey-safari-beta-3.jpg?lossy">

**Comment by vinceliuice** [comment]
No problem!

**Comment by popykunju** [comment]
wait,there is a safari for linux?

**Comment by aargar1** [comment]
@popykunju, no, but there is an awesome Firefox theme that makes Firefox look just like Safari - I was asking if the theme would be updated to match the most recent Safari style.

**Comment by aargar1** [comment]
Any idea when the new theme will be available?

**Comment by vinceliuice** [comment]
Available now!
Run `./tweaks.sh -f alt` to install it

**Comment by aargar1** [comment]
Great! Is there a way to change the colour of the title bar? On the new Safari, the body element's `background-color` is automatically detected and used as the colour of the title bar. Any way to do that by this theme or by extension?

**Comment by aargar1** [comment]
Which one?
