### ISSUE TITLE
Dock Look in Zorin OS

### ISSUE THREAD

**Issue by capriciousduck** [vinceliuice/WhiteSur-gtk-theme#44]
How can I change the dock look in Zorin OS? Right now, it doesn't look good.

**Comment by vinceliuice** [comment]
What dock you are using?

**Comment by capriciousduck** [comment]
@vinceliuice The default one that comes with zorin os and they call it "Zorin Dash"

**Comment by capriciousduck** [comment]
And I found some issue with the image icons when adjusting sound and screen brightness.

See here: https://streamable.com/92p8b6


Other than these three issues I feel like I am using a real Mac. The theme is so good.

**Comment by anubra266** [comment]
I use Zorin os, not facing the Icons problem. Try the dark theme, and see if it also has the same problems.

**Comment by luke2m** [comment]
@capriciousduck You could use the [plank dock](https://www.linuxuprising.com/2019/12/a-guide-to-using-plank-dock-on-linux.html) and the [WhiteSur plank theme](https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/src/other/plank) instead of the Zorin dock.

**Comment by mBilG** [comment]
I think zorin dock uses the shell theme for theming

**Comment by rivanfebrian123** [comment]
> How can I change the dock look in Zorin OS? Right now, it doesn't look good.

You can disable Zorin Dock and enable Dash to Dock instead
