### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by Galaxy0419** [vinceliuice/WhiteSur-gtk-theme#45]
首先十分感谢您优秀的主题。

GTK和icon有以下的问题：
1. Nautilus左边列表的大小无法和标题一起调整。(这个问题能修么?)  
2. Gnome Shell的状态栏图表大小不一。(或许是上游问题?)

问题截图：
![Screenshot from 2020-09-12 17-50-51](https://user-images.githubusercontent.com/26517146/92993034-80b08780-f521-11ea-8495-d8ea97279d54.png)

**Comment by vinceliuice** [comment]
这个确实不好解决， 因为我是用个背景图片实现苹果系统的这种文件管理器结构
