### ISSUE TITLE
Icons for snap applications won't change

### ISSUE THREAD

**Issue by Khyta** [vinceliuice/WhiteSur-gtk-theme#450]
Ubuntu 20.04.3 LTS with GNOME 3.8 on Wayland.

I installed for example VS Code through the software store. The source of the application is snapcraft.io
![image](https://user-images.githubusercontent.com/33177286/137190174-2945988f-44d4-46b1-8d2a-f26d0aa8b670.png)

But the icon in the taskbar 
![image](https://user-images.githubusercontent.com/33177286/137190019-8b35f47b-2496-458d-857d-94be740c2c72.png)

and also in the launch view
![image](https://user-images.githubusercontent.com/33177286/137190284-edf1d790-145e-4eb4-8055-d44231b85eae.png)
did not change. I checked for some VS Code icons in the .icon folder and saw that there were icons available for VS Code to use.
![image](https://user-images.githubusercontent.com/33177286/137190546-89669382-6cf3-4311-a69f-21cf0dd63df8.png)

It would be cool to have the icons work correctly. 

Making ./tweaks.sh -F -s did not work. It says it connected but the icons did not change.

![image](https://user-images.githubusercontent.com/33177286/137190874-5d408e96-f448-4163-92f4-475e2782652a.png)

**Comment by aargar1** [comment]
`cd` into `WhiteSur-icon-theme` (or if it doesn't exist download it from https://github.com/vinceliuice/WhiteSur-icon-theme/), then execute the same command.
