### ISSUE TITLE
Rhythmbox buttons on Dark theme

### ISSUE THREAD

**Issue by zeparu** [vinceliuice/WhiteSur-gtk-theme#46]
![image](https://user-images.githubusercontent.com/21054889/93479910-26d30780-f8fd-11ea-932c-0ddb599bbac7.png)
![image](https://user-images.githubusercontent.com/21054889/93479954-33eff680-f8fd-11ea-8314-1459fae29e8c.png)

if you use rhythmbox with the dark theme and are using the https://github.com/fossfreedom/alternative-toolbar design, its unclear if a button is enabled or disabled (in the screenshots, repeat is enabled, shuffle is disabled)

**Comment by TheDevtop** [comment]
Is is also unclear if another theme is used? Because then it would be a Rhythmbox problem.

**Comment by zeparu** [comment]
no, the bottom screenshot is from the light theme, this only happens with the dark theme (happened with the dark theme of mcmojave too)

**Comment by TheDevtop** [comment]
I have a VM with this theme installed, I'll check it out.

**Comment by vinceliuice** [comment]
I'll fix this!
