### ISSUE TITLE
Text overflowing in nautilus sidebar

### ISSUE THREAD

**Issue by cookiengineer** [vinceliuice/WhiteSur-gtk-theme#47]
Hey there,

currently, the text is overflowing in the nautilus sidebar when the bookmarks have a too long name.

![Screenshot from 2020-09-19 22-39-04](https://user-images.githubusercontent.com/592637/93689117-c8a84f00-facb-11ea-8891-5b4669f37109.png)

I tried debugging it with the GTK debugger, but honestly I have no idea how CSS works in GTK. I tried manipulating the width/height and looked at the docs but I have no idea what I'm doing.

![screenshot-with-borders](https://user-images.githubusercontent.com/592637/93689198-76b3f900-facc-11ea-89d1-aa2051c453fb.png)

When looking at the layout borders in the GTK debugger, it seems as if the rows themselves are too wide and that the sidebar's width is too small and actually overflowing everywhere.

How would you fix an issue like that? I'd love to make a PR but I have no clue on how to even start, never made a GTK theme in the past.

**Comment by vinceliuice** [comment]
Run `./install.sh -s` to cahnge this sidebar size!
