### ISSUE TITLE
A line appear on top of nautilus window

### ISSUE THREAD

**Issue by arshadmdvr** [vinceliuice/WhiteSur-gtk-theme#472]
I using ubuntu 21.10 with gnome 40. A line appear on top of nautilus file manager window while using whitesur dark theme. I don't whether it is a bug in WhiteSur theme.
![image](https://user-images.githubusercontent.com/57001021/139775115-e6fcc090-e080-41d5-acba-af44ecfb9b92.png)

**Comment by vinceliuice** [comment]
![VirtualBox_ubuntu21](https://user-images.githubusercontent.com/7604295/139778294-9cd6742e-6c4b-474a-bf1e-174fda0f5c60.png)

**Comment by vinceliuice** [comment]
Did not find this issue

**Comment by vinceliuice** [comment]
You can restart your system, or reinstall this theme from github again!

**Comment by arshadmdvr** [comment]
It happens in all themes with rounded corners
