### ISSUE TITLE
Firefox Monterey theme: Tab bar doesn't respect add-on section

### ISSUE THREAD

**Issue by puenka** [vinceliuice/WhiteSur-gtk-theme#474]
Ubuntu 20.04, Firefox 93.0

When using multiple tabs, the tab bar section extends too far to the right in Monterey mode and thus collides with the add-ons on the right side.

![TabBar_collision](https://user-images.githubusercontent.com/2266341/140082561-a04d0a96-9766-4be4-ac19-5bd562df9cea.png)

**Comment by puenka** [comment]
On further inspection, this might not be related to the add-ons, but there seems to be an issue with the section left to the addons (Firefox Pockets, Downloads). When trying to insert "Flexible Space" in the customization menu, it's also quite glitchy.

![FlexibleSpace](https://user-images.githubusercontent.com/2266341/140083079-d435f2f7-1c38-49dd-842f-aa3bd5d54f30.png)

**Comment by vinceliuice** [comment]
Suggest you to use the alt monterey theme, this one have a lot of issues that I can't fix

**Comment by puenka** [comment]
The Monterey alt theme doesn't have the tabs in the titlebar, is that correct or can I customize this somehow?

This option also isn't documented, would you appreciate if I added it to the readme and help?

**Comment by vinceliuice** [comment]
This theme will cause this, can not customize the toolbar, Because in order to achieve this design, you can only move the tabbar to the headerbar, which does not conform to the design framework of Firefox, so it will squeeze and cover other components and make it impossible to select, And I can't do anything about this!

**Comment by vinceliuice** [comment]
You can only disable this theme first (use the default) then customize it, last enable this theme, this the only way to make it if you still want use this theme

**Comment by puenka** [comment]
I guess I can close this as "won't be fixed".
