### ISSUE TITLE
uninstall not possible

### ISSUE THREAD

**Issue by tommessb** [vinceliuice/WhiteSur-gtk-theme#475]
i tried the thome on ubuntu 21.10 but have a lot of issues.
Firefox theme was not working, like already wrote.

The top bar from gnome-shell is transparent, all content like calendar, notification is bright grey. there is an apple logo in the left corner!
I installaed the dark version, but no change. I set the theme back to Yaru-Dark from ubuntu und run ./install -r

Even after restart the top bar is still bright transparent and with the apple logo!
How do i remove it? i want to have the original ubuntu dark theme back!
Same for firefox, selected the default system theme,..but it is still rounded, with apple buttons and tabs next to adressbar,..i want to have the original firefox back!

Please write  proper uninstall instructions. It's very painful to detroy the whole gui just by installing your theme!

**Comment by vinceliuice** [comment]
Just run `sudo ./tweaks.sh -g -r` you did not uninstall the gdm theme!

**Comment by vinceliuice** [comment]
And `./tweaks.sh -f -r` ro remove firefox theme!

**Comment by tommessb** [comment]
Thanks a lot!
I didn't know that the GDM theme is changing the gnome shell top bar.
But why is it not dark when i install the dark version of your theme? all content from the top bar had grey window backgrounds.

but it's completly removed now, thanks
