### ISSUE TITLE
Max Min Close buttons aren't working on Brave Browser.

### ISSUE THREAD

**Issue by YuvrajDadheech** [vinceliuice/WhiteSur-gtk-theme#483]
![Screenshot from 2021-11-17 15-59-15](https://user-images.githubusercontent.com/69249209/142184112-896ae3b2-fb72-468e-a2f3-b9217eb066af.png)

The button theme works on Firefox but not on Brave browser. What could potentially be an issue?

**Comment by vinceliuice** [comment]
Did you set the Brave to use gtk theme
![Screenshot from 2021-11-17 19-33-39](https://user-images.githubusercontent.com/7604295/142193218-2ecc271e-db93-45ca-bf14-d26ef405c590.png)
?

**Comment by YuvrajDadheech** [comment]
> Did you set the Brave to use gtk theme ![Screenshot from 2021-11-17 19-33-39](https://user-images.githubusercontent.com/7604295/142193218-2ecc271e-db93-45ca-bf14-d26ef405c590.png) ?

Worked. Thank you.

**Comment by vinceliuice** [comment]
You are welcome!
