### ISSUE TITLE
XFCE 4.16 black menu corners if compositor is off

### ISSUE THREAD

**Issue by tuanpham-dev** [vinceliuice/WhiteSur-gtk-theme#488]
OS: Debian 11
DE: XFCE 4.16
WM: XFWM 4
Screenshot: https://imgur.com/yO6DJNN.png

Adwaita does not have this issue, the menu turns to square corner instead of round corner when compositor is off.
Also, is there any way to set xfce4-panel (Applications & Time) font weight to normal?

**Comment by liuhoward** [comment]
The same here with XFCE 4.18 no matter the compositor is off or on

![2023-07-22_11-29](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/4758314/dad7ae58-665b-4f4d-b1cf-2197484ecb20)

**Comment by vinceliuice** [comment]
Open whiskermenu setting and set menu opacity to 0

**Comment by haroldgrayman** [comment]
Thanks!
