### ISSUE TITLE
libreoffice textboxs text overlapping

### ISSUE THREAD

**Issue by eryk-2612** [vinceliuice/WhiteSur-gtk-theme#489]
OS: Linux Mint 20.2 x86_64
![screenshot](https://user-images.githubusercontent.com/94122538/142944748-b606c550-d19c-417c-9e94-c159d1320b2c.png)
Libre Office Writer

Reproduce:

1. have diffrent formated text like: title and headline 1
2. click in those texts and switch between them
![screenshot 2](https://user-images.githubusercontent.com/94122538/142945066-c78a7c48-7b2b-4491-b64c-9a15557e9d71.png)
3. the text in the format textbox overlaps (does also happen with character size)

I havent seen this issue in other themes except also in Fluent-gtk-theme and Orchis-theme

**Comment by vinceliuice** [comment]
You are not using the last version, download from github and try again

**Comment by vinceliuice** [comment]
![Screenshot from 2021-11-23 12-51-04](https://user-images.githubusercontent.com/7604295/142972882-01743d29-a151-4564-a3d9-5c5997328c85.png)

**Comment by eryk-2612** [comment]
Downloading new version of the Theme didnt help BUT updating LibreOffice fixed the issue. Thanks!

**Comment by eryk-2612** [comment]
Downloading new version of the Theme didnt help BUT updating LibreOffice fixed the issue. Thanks!

**Comment by eryk-2612** [comment]
Downloading new version of the Theme didnt help BUT updating LibreOffice fixed the issue. Thanks!

**Comment by hackingguy** [comment]
> ![Screenshot from 2021-11-23 12-51-04](https://user-images.githubusercontent.com/7604295/142972882-01743d29-a151-4564-a3d9-5c5997328c85.png)

can u tell shell theme you are using here?

**Comment by vinceliuice** [comment]
Fluent
