### ISSUE TITLE
Libadwaita support

### ISSUE THREAD

**Issue by UARTman** [vinceliuice/WhiteSur-gtk-theme#493]
Currently forcing GTK4 apps using libadwaita to use this theme results in some ugly breakage of some libadwaita's features.
You can see the extent of uglinesshere: ![side-by-side comparison](https://i.ibb.co/6sT9D6r/Screenshot-from-2021-11-27-22-47-25.png). As gnome team does not officially support theming (and in fact hard-coded libadwaita to use its default stylesheet), the burden of ensuring compatibility falls on the themes.

While libadwaita is currently under development, I believe it's going to roll out to Gnome apps in Gnome 42, and supporting it could be a good idea. 

Do you think that's doable or in scope of the project at all? If so, is there anything a person with no prior knowledge of how themes work beyond the very basics (aka me) might do to help with that?

**Comment by vinceliuice** [comment]
If Gnome not gona support theming, then the only way to use 3rd themes is to replace the libadwaita.so

**Comment by UARTman** [comment]
AFAIK, overriding the libadwaita theme via the environment variable can be done (that's how I got the breakage screenshot in the first place), and I plan on doing exactly that once Gnome 42 hits release. 

Or am I missing something?

**Comment by vinceliuice** [comment]
We can only wait for GNOME42, anyway I will fix the issues about GTK4.0 theme first.

**Comment by Aleksanaa** [comment]
Now we can test the theme's compatibility with libadwaita in this way: install libadwaita-demos (the startup command is adwaita-1-demo), use GTK_THEME= on the command line to specify the gtk theme.

**Comment by Tim-Paik** [comment]
When I try
`GTK_THEME=WhiteSur-dark-blue:dark adwaita-1-demo`
there are a lot of warnings, are these normal?
Warns like this

(adwaita-1-demo:11835): Gtk-WARNING **: 14:23:20.160: GtkImage 0x55e5af104920 reported baselines of minimum -2147483648 and natural -2147483648, but sizes of minimum 16 and natural 16. Baselines must be inside the widget size.

**Comment by vinceliuice** [comment]
Fixed

**Comment by vinceliuice** [comment]
Fixed !

**Comment by bayazidbh** [comment]
https://github.com/odziom91/libadwaita-theme-changer

Hi, I found this project that seems to be a script to change libadwaita's assets and css files, would that be useful for this theme? I think it can be integrated to the install script, but I don't know if the result will be good or bad.

**Comment by vinceliuice** [comment]
run` ./install.sh -l` to install theme for libadwaita
