### ISSUE TITLE
Problem with Firefox and Gnome Tweaks

### ISSUE THREAD

**Issue by OssNass** [vinceliuice/WhiteSur-gtk-theme#5]
I am using Gnome 3.36.2 on Manjaro.

The problem is in Firefox corners, they don't render correctly
![Screenshot from 2020-07-16 17-43-18](https://user-images.githubusercontent.com/5196218/87685292-e2f04480-c78b-11ea-833c-a64e2abf816e.png)

Also in Gnome Tweak tool, disregarding the header bar problem which repeats on several themes except adwaita, the corner renders incorrectly too:
![Screenshot from 2020-07-16 17-44-48](https://user-images.githubusercontent.com/5196218/87685478-1af78780-c78c-11ea-9214-1374442deb91.png)
![Screenshot from 2020-07-16 17-44-57](https://user-images.githubusercontent.com/5196218/87685479-1cc14b00-c78c-11ea-9800-8215b92932c5.png)

**Comment by OssNass** [comment]
Apparently both these problems are not the fault of this theme, tried another theme with similar results all be it with less rounded corners

**Comment by 420aakura** [comment]
I don't I am also seeing same problem with title bars like in Firefox, of Telegram Desktop, VS Code, VLC, Shotwell, qBittorrent and others. I think this is the problem with Gnome.
![Screenshot from 2020-07-17 15-44-09](https://user-images.githubusercontent.com/20091947/87775211-746fbd00-c845-11ea-8e8b-dae488755ff7.png)

![Screenshot from 2020-07-17 15-48-59](https://user-images.githubusercontent.com/20091947/87775217-76398080-c845-11ea-949f-fbfc373bd797.png)

![Screenshot from 2020-07-17 15-49-19](https://user-images.githubusercontent.com/20091947/87775218-76d21700-c845-11ea-9967-d7e9d0a6b636.png)

**Comment by laichiaheng** [comment]
It happens when it's in fullscreen on Manjaro.

**Comment by edwinvandeven** [comment]
Perhaps you could have a look at this for firefox: (although completely unrelated to the theme)
https://www.omgubuntu.co.uk/2020/04/fix-firefox-rounded-corners-gnome
