### ISSUE TITLE
Firefox bottom border radius not applying?

### ISSUE THREAD

**Issue by diorcula** [vinceliuice/WhiteSur-gtk-theme#501]
![image](https://user-images.githubusercontent.com/32682696/144579877-f3e92616-ded4-4483-a073-067051ee8377.png)

![image](https://user-images.githubusercontent.com/32682696/144579954-3da159cb-6e54-4998-b283-14e7a5d46457.png)

**Comment by danonGitHub-dev** [comment]
Hello

It is not a bug coming from the theme. 
You need to : disable any Firefox theme, and enable "System theme" - auto.

Additionnaly i modified toolkit.legacyUserProfileCustomizations.stylesheets to true. (about:config)

Hope this helps.
Dan

**Comment by diorcula** [comment]
> Hello
> 
> It is not a bug coming from the theme. You need to : disable any Firefox theme, and enable "System theme" - auto.
> 
> Additionnaly i modified toolkit.legacyUserProfileCustomizations.stylesheets to true. (about:config)
> 
> Hope this helps. Dan

It is what i was finding as well, since there are more screens on my Pop!_OS GNOME that still have the same sharp bottom edges.

I also already had the suggested theme enabled and the config as well!

I will close the issue

**Comment by diorcula** [comment]
It is what i was finding as well, since there are more screens on my Pop!_OS GNOME that still have the same sharp bottom edges.

I also already had the suggested theme enabled and the config as well!

I will close the issue
