### ISSUE TITLE
Missing Firefox autoscroller icon with dark theme

### ISSUE THREAD

**Issue by Naozumi2k** [vinceliuice/WhiteSur-gtk-theme#503]
There is a bug with Firefox theme that cause of missing autoscroll icon (when you press middle mouse button).
I've found that peace of css into customChrome.css fixes the issue:
```
.autoscroller {
  --panel-background: transparent !important;
  --panel-border-color: transparent !important;
  background-image: url("chrome://global/skin/icons/autoscroll.svg") !important;
}
```
Missing icon
![Selection_002](https://user-images.githubusercontent.com/25503364/144707049-7d5e7300-c75f-4d7a-9788-f31397c3ccf5.png)
Fixed icon
![Selection_003](https://user-images.githubusercontent.com/25503364/144707051-6c619a69-60ae-41ab-b8a3-c1bac8a4d661.png)

**Comment by vinceliuice** [comment]
Thanks! I'll add this fix
