### ISSUE TITLE
Lollypop search bar background broken in light theme

### ISSUE THREAD

**Issue by puenka** [vinceliuice/WhiteSur-gtk-theme#504]
I have an issue with Lollypop (1.4.23, https://wiki.gnome.org/Apps/Lollypop) when using the light version of your theme.

The search bar typically looks like this (Adwaita):
![Lollypop_searchbar_adwaita](https://user-images.githubusercontent.com/2266341/144725283-e8b622e9-a98e-489a-9828-9915722c08af.png)

However, on `WhiteSur-light-solid` (and possibly - but untested - the other light versions), the search bar takes the colour of the background instead, which doesn't contrast with the black font colour:
![Lollypop_searchbar_lighttheme](https://user-images.githubusercontent.com/2266341/144725301-def36fea-b043-4cbc-abaa-7d6c71509708.png)

When using the dark variant, there's no issue because the font colour is contrasting the blue background (still, on the dark version of Adwaita the search bar gets the gray theme colour instead of the blue background):
![Lollypop_searchbar_dark](https://user-images.githubusercontent.com/2266341/144725323-d7623665-4fa0-4dd6-9bf0-1e30fda931cd.png)

Seeing that the Adwaita theme puts colour to the search bar, I guess there's just some colour override missing for this item?

**Comment by vinceliuice** [comment]
Fixed!

**Comment by puenka** [comment]
Thank you so much for the quick fix!
Just out of curiosity because I have practically no experience with CSS: you fixed this by just setting the font colour white and highlighted the search gadget background itself by adding some low transparency white, right? I'm worried this might break applications where this gadget is used in front of an already light background ... doesn't this happen?

**Comment by vinceliuice** [comment]
See this id `.default-banner` ， This is Lollypop's unique id, so only works for Lollypop

**Comment by puenka** [comment]
Ah I see, so this would only be an issue when another app has the exact same object structure AND names for these objects!
Thanks a lot again!

**Comment by vinceliuice** [comment]
You are welcome!
