### ISSUE TITLE
Blur implementation like in https://github.com/vinceliuice/Fluent-gtk-theme

### ISSUE THREAD

**Issue by ayushhroyy** [vinceliuice/WhiteSur-gtk-theme#505]
Hello, as we are in early stages of gnome blur support some themes like materia dark and fluent ui as linked in the title have already implemented it with the help of blur me extension. It'd be awesome to see it on the whitesur theme too as that is what the macOS theme actually stands out for + whitesur theme is one of the best one's I have used, implementing blur would be great to see in it's future : ] Arigato have a nice day!

**Comment by vinceliuice** [comment]
Blur me do not support rounded corner, so whitesur will looks not good when blur me is on

**Comment by ayushhroyy** [comment]
![Screenshot from 2021-12-07 03-43-49](https://user-images.githubusercontent.com/77523847/144931410-d6f16c80-0022-4f7f-9986-5595bdb18a27.png)

**Comment by ayushhroyy** [comment]
![image](https://user-images.githubusercontent.com/77523847/144932160-6dd3dd5f-ad0d-4261-887b-f5ff0bc43e81.png)
WITH BLUR in whitesur theme and rounded corners (it already blurred the elements with transparency) [gnome 41.1]

![image](https://user-images.githubusercontent.com/77523847/144932268-184d910d-db0d-4d6c-85d7-2660ab7d3bcb.png)
WITHOUT BLUR in gnome 41.1 same theme

**Comment by vinceliuice** [comment]
![Screenshot from 2021-12-07 11-17-38](https://user-images.githubusercontent.com/7604295/144959951-82fd1004-cb99-452e-bca8-650d02af53ef.png)
This is on my desktop (x11)

**Comment by vinceliuice** [comment]
Black square under corner

**Comment by ayushhroyy** [comment]
why don't you use wayland? it has rounded corners with mutter-rounded and works perfectly

**Comment by ayushhroyy** [comment]
![image](https://user-images.githubusercontent.com/77523847/145205145-c1e31983-b348-4e3a-9834-1b45bb6f8688.png)
![image](https://user-images.githubusercontent.com/77523847/145205293-c0a73ab6-0eaa-44d6-822e-80446ed98e78.png)

Hello, i achieved proper blur along with round edges with mutter_rounded and it worked awesome with your theme, you might wanna take a look into it my configs are stated in the neofetch thank you

**Comment by vinceliuice** [comment]
How did you make this? How to fix the black squares?

**Comment by ayushhroyy** [comment]
![image](https://user-images.githubusercontent.com/77523847/145223707-19cbfe19-7a26-47a4-8b6d-8bee76a6a0e5.png)
i fixed it through mutter_rounded (https://github.com/yilozt/mutter-rounded) and input mutter_settings in the terminal and set blur for the applications i needed, it worked better than blur me extension imo

**Comment by vinceliuice** [comment]
OK! I'll try this

**Comment by ayushhroyy** [comment]
Awesome! i'll be closing this issue now have a good day

**Comment by ayushhroyy** [comment]
Awesome! i'll be closing this issue now have a good day
