### ISSUE TITLE
Manjaro | Gnome | When using File utility in Gnome desktop the Text in navigation and search appears corrupt or dithered when application is maximized

### ISSUE THREAD

**Issue by rsramkis** [vinceliuice/WhiteSur-gtk-theme#51]
When using the Gnome File utility maximized with the Whitesur theme I noticed the text looks dithered or corrupted in:

* Left Navigation
* Search field

**Gnome File Maximized Example**
![image](https://user-images.githubusercontent.com/14362317/94823563-fd70ac00-03d1-11eb-82c8-5b2fe8dbd8cd.png)

**Window mode (no issue in this mode**
![image](https://user-images.githubusercontent.com/14362317/94823620-0e212200-03d2-11eb-85d1-12dfebbd6fa4.png)

**Font Configuration:**
![image](https://user-images.githubusercontent.com/14362317/94823472-dfa34700-03d1-11eb-94d1-75ff6f3ec56d.png)

**Environment Details**

`System:    Kernel: 5.4.64-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.4-x86_64
           root=UUID=85ccbb8b-086b-4c3b-a6c8-a45951356c8e rw apparmor=1 security=apparmor
           usbcore.autosuspend=-1
           Desktop: GNOME 3.36.6 tk: GTK 3.24.23 wm: gnome-shell dm: GDM 3.36.3
           Distro: Manjaro Linux`

`Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Lenovo driver: i915 v: kernel
           bus ID: 00:02.0 chip ID: 8086:0166
           Display: x11 server: X.Org 1.20.8 compositor: gnome-shell driver: intel
           display ID: :1 screens: 1
           Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.2x8.0")
           s-diag: 414mm (16.3")
           Monitor-1: LVDS1 res: 1366x768 hz: 60 dpi: 124 size: 280x160mm (11.0x6.3")
           diag: 322mm (12.7")
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.1.7
           compat-v: 3.0 direct render: Yes`

**Comment by rivanfebrian123** [comment]
It usually happens after upgrading a system. You just need to restart your PC to fix this

**Comment by rsramkis** [comment]
> It usually happens after upgrading a system. You just need to restart your PC to fix this

Thanks for the suggestion. The system was rebooted many times before reporting this defect.

**Comment by rivanfebrian123** [comment]
But the text dithering was gone, right?

**Comment by rsramkis** [comment]
> But the text dithering was gone, right?

The defect was still there after the reboot. I don't have the ability to test this anymore as I do not have an x230 with a 1366x768 screen. As a result I will close this defect.
