### ISSUE TITLE
Metacity icons are showing unfocused one

### ISSUE THREAD

**Issue by MuhmmadZohaibImtiaz** [vinceliuice/WhiteSur-gtk-theme#52]
I applied this theme and when i maximize with the pixel saver the metacity icons are shown of unfocused window even when the window is in focus.
This problem is not with Ant theme. So particularly, how can I fix this issue.
I am trying to solve this issue by adding similar styling and building the theme as mentioned in the HACKING doc. but the issue isn't resolved.
As per guided from budgie-pixel-saver member on [issue](https://github.com/UbuntuBudgie/budgie-pixel-saver-applet/issues/4) and styling applying as per [pocillo-gtk-theme](https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/93c61557db621122aa33c05ee18bec6eb0b22e28/src/gtk-3.0/3.22/sass/apps/_budgie.scss#L175)

![Budgie pixel saver 1](https://user-images.githubusercontent.com/71523302/95976977-b4891080-0e31-11eb-9045-e8197725c2bc.png)
![Budguie Pixel Saver 2](https://user-images.githubusercontent.com/71523302/95977002-b94dc480-0e31-11eb-8ed6-ecf3e5051a6f.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed!

**Comment by MuhmmadZohaibImtiaz** [comment]
Thank you :) :+1:
