### ISSUE TITLE
Nord colour scheme option

### ISSUE THREAD

**Issue by ayushhroyy** [vinceliuice/WhiteSur-gtk-theme#520]
hello, i just found Nordsur https://github.com/nboughton/NordSur which is a fork of your theme only to provide nord color scheme option. Since it is not updated anymore, I was hoping if we could get a nord color option along with the default colour options. Thank you

**Comment by vinceliuice** [comment]
No problem!

**Comment by ayushhroyy** [comment]
Tysm! i'll be closing the issue now

**Comment by vinceliuice** [comment]
Now you can run `./install.sh --nord` to install the nord version
--------------------------
![Screenshot from 2021-12-26 22-18-09](https://user-images.githubusercontent.com/7604295/147410901-f85575d1-f55f-41fa-bff6-2e81d6fee5fa.png)

**Comment by itsTyrion** [comment]
@vinceliuice I think you forgot to add this to the instructions on the main page (Or I'm just blind :D)

**Comment by vinceliuice** [comment]
No problem!
