### ISSUE TITLE
Top bar disappear for minimized windows

### ISSUE THREAD

**Issue by Potjoe-97** [vinceliuice/WhiteSur-gtk-theme#53]
Since last gnome update (currently runnning 3.36.3), top bar of minimized window is invisible. It 
also happens with web browser pop up, and some applications even maximized. 

https://imgur.com/a/rXZdFqR

Running on pop-os 20.04.

**Comment by Shabinder** [comment]
+1 facing same issue

**Comment by Shabinder** [comment]
@vinceliuice is this fixed?

**Comment by vinceliuice** [comment]
@Shabinder It's a Gnome-tweaks app issue not theme issue!

**Comment by hossein-nahali** [comment]
Is this problem unsolvable?

**Comment by hossein-nahali** [comment]
Is this problem unsolvable?

**Comment by vinceliuice** [comment]
You can update your system version to fix it
