### ISSUE TITLE
[WhiteSur-light] Text-color of selected text black instead of white since Firefox 82

### ISSUE THREAD

**Issue by zjeffer** [vinceliuice/WhiteSur-gtk-theme#54]
I just updated Firefox from `81.0.2-1` to version `82.0-1` and saw the textcolor of selected text is still black, instead of changing to white. This makes it very unreadable because of the dark blue background.

Here's a screenshot from Reddit, but it happens on every page.

![Screenshot_20201021_190009](https://user-images.githubusercontent.com/4633209/96753166-c0477a80-13cf-11eb-8931-a012f4588487.png)

This is with `widget.content.gtk-theme-override` set to `WhiteSur-light` in `about:config`.

Edit: looks like the background-color hasn't changed, but the textcolor changed. It used to be white when selected, now it's black. WhiteSur-dark does display it correctly. This is with WhiteSur-dark:

![image](https://user-images.githubusercontent.com/4633209/96755240-becb8180-13d2-11eb-8b2c-2326c2a25fd5.png)

**Comment by vinceliuice** [comment]
Fixed
