### ISSUE TITLE
Unable to install GDM theme

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/WhiteSur-gtk-theme#548]
Hi, i've been trying to install the gdm theme on Pop!_OS 20.04 LTS, and the following error log is coming out...

FOUND  :
    >>> lib-core.sh
    >>> lib-install.sh at 131;137
    >>> tweaks.sh
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_beggy_deps
    >>> install_beggy
    >>> install_gdm_theme
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu debian;pop;20.04
  SUDO   : yes
  GNOME  : old
  REPO   : 2022-01-31T19:50:25+0530

![image](https://user-images.githubusercontent.com/88226614/152477338-bd93fd5d-e985-405e-9ea8-95ef0bf221a7.png)

**Comment by vinceliuice** [comment]
Update your system first

**Comment by vinceliuice** [comment]
Run this `sudo apt install libglib2.0-dev-bin sassc`

**Comment by Nakamerica** [comment]
> Or Run this `sudo apt install libglib2.0-dev-bin sassc`


ok thanks I will try this.

**Comment by Nakamerica** [comment]
> Or Run this `sudo apt install libglib2.0-dev-bin sassc`

it says sassc is already on the newest version...

**Comment by Nakamerica** [comment]
I'm so sorry I didn't mean to add the bug label.

**Comment by vinceliuice** [comment]
You can remove the spotify ppa then try again, it said this ppa make your system update fail

**Comment by Nakamerica** [comment]
> You can remove the spotify ppa then try again, it said this ppa make your system update fail

thanks, I will try that

**Comment by Nakamerica** [comment]
> You can remove the spotify ppa then try again, it said this ppa make your system update fail

Thank you so much, this helped :))
