### ISSUE TITLE
Uninstalling the theme

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/WhiteSur-gtk-theme#550]
Hi, i was trying to uninstall the entire theme (icons/application themes/etc), and I've deleted the necessary folders in .themes, .icons, ~/.local/share/icons, and also followed the "Quick Uninstall" guide, but I'm still able to see remnants of the theme around the system... please help me in uninstalling it fully. I've tried deleting things that say whitesur-gtk-theme and some other guides on the net but nothing seems to uninstall every trace of the theme.

**Comment by vinceliuice** [comment]
sudo ./tweaks.sh -g -r

**Comment by Nakamerica** [comment]
> sudo ./tweaks.sh -g -r

thank you so, so much. I had been going mad trying to figure it out. Your work is great, i uninstalled it to install it again to try some things, thanks for the help again.

**Comment by asifansari84** [comment]
![Screenshot from 2024-02-01 09-35-01](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/64721272/bedd00c4-c789-4a66-a9aa-4f1512c0204e)

The apple icon is still visible in the corner, the theme has to be removed completely.
Please tell me

![Screenshot from 2024-02-01 09-37-09](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/64721272/2f24a476-7cc0-406d-a04d-4f62d4982949)

This command is also not working can you tell from the beginning?

I have just installed Linux for the first time so I don't know.

**Comment by Bornunique911** [comment]
@asifansari84 Steps to be followed to uninstall the theme :
1) Locate the repository named **WhiteSur-gtk-theme** in your filesystem where you cloned it.  If you haven't cloned the repository and you are running the following command it will throw an error of `command not found` as you got in your provided screenshot :
```console
sudo ./tweaks.sh -g -r
```
2) Change the directory into that location where the repository is located by using `cd` command.
```console
cd location_of_repository
```
3) After changing the directory, using the following command you can uninstall the theme :
```console
sudo ./tweaks.sh -g -r
```
4) Reboot your device after successful uninstallation.
If you still notice that an apple icon is visible in the corner, then please check this location whereby the icons are stored.
```console
~/local/share/icons
```
You can remove the apple icon by locating it in the filesystem from there.
Caution : Removing the wrong icon file will cause multiple errors like corner icon is not displaying,etc.
