### ISSUE TITLE
'Activities' Icon does not get removed on changing theme

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/WhiteSur-gtk-theme#552]
nakamerica@anmols-vivobook-x412da 
    --------------------------------- 
OS: Pop!_OS 20.04 LTS x86_64 
Host: VivoBook_ASUSLaptop X412DA_X412DA 1.0 
Kernel: 5.15.15-76051515-generic 
Uptime: 32 mins 
Packages: 1835 (dpkg), 14 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3072x1728 
DE: GNOME 
WM: Mutter 
WM Theme: Orchis-red-dark-compact 
Theme: Orchis-red-dark-compact [GTK2/3] 
Icons: Tela-circle [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI 03:00.0 Picasso 
Memory: 3382MiB / 5944MiB 

Hi, I've installed both the Whitesur-gtk-theme along with the orchis-theme, both very pretty, but when i switch from the whitesur theme to the orchis theme, the apple icon of the 'Activities' does not return back to the original state. Is there any way i can get rid of that when I'm using the orchis theme? A screenshot is attached. 

![image](https://user-images.githubusercontent.com/88226614/152780511-5c803eb3-0b86-49e6-bf5a-7bcdafa214b1.png)

(See the top left corner)

Thank you for the help.

**Comment by vinceliuice** [comment]
Just remove the whitesur gdm theme

**Comment by Nakamerica** [comment]
> Just remove the whitesur gdm theme

ok, thank you.

**Comment by Nakamerica** [comment]
> Just remove the whitesur gdm theme

hey, i successfully removed the gdm theme, but now it seems like something else is conflicting, a screenshot is attached, i can't quite tell what the issue is... 

![image](https://user-images.githubusercontent.com/88226614/152784722-9db08789-6a3f-42eb-98e2-995c886dc29e.png)

**Comment by Nakamerica** [comment]
It was ultimately a rogue extension.
