### ISSUE TITLE
rounded bottom corners for gnome-terminal

### ISSUE THREAD

**Issue by arun54321** [vinceliuice/WhiteSur-gtk-theme#554]
![image](https://user-images.githubusercontent.com/42943340/152923263-32b19bb9-368d-45d3-95f6-108dbaac6891.png)

**Comment by vinceliuice** [comment]
You can wait the gtk4 version, gtk3 version do not support this

**Comment by catarch** [comment]
Use a github project called **mutter-rounded**, make rounded corners for all windows including Gtk3&Qt.
Link to project : _**https://github.com/yilozt/mutter-rounded**_

**Comment by arun54321** [comment]
I know it already. thanks for the info.
