### ISSUE TITLE
Google Chrome/Chromium's Icons Don't Work

### ISSUE THREAD

**Issue by CubingSoda** [vinceliuice/WhiteSur-gtk-theme#557]
Manjaro Linux, Lastest GNOME.

With the default installation, WhiteSur's close/minimize/maximize buttons work fine, except for Chrome and Chromium.
![pic](https://user-images.githubusercontent.com/82660497/153516896-49a672d7-1805-47e8-af82-6d44bd935c2f.png)

**Comment by vinceliuice** [comment]
Enable the gtk style on chrome setting

**Comment by CubingSoda** [comment]
Where is that

**Comment by vinceliuice** [comment]
![Screenshot from 2022-02-11 13-28-47](https://user-images.githubusercontent.com/7604295/153542104-276cbc37-ea11-4800-b600-1ac76b29458c.png)
