### ISSUE TITLE
Can I use standard min, max, close icons in the nord theme?

### ISSUE THREAD

**Issue by OPSJono** [vinceliuice/WhiteSur-gtk-theme#573]
Is it possible to use the standard colours for the min, max, and close icons in application windows?

I've tried updating the [_colors.scss](https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/sass/_colors.scss#L280-L301), but the colours defined for the `WM Buttons` appear to be unused.
I was hoping it's as easy as changing a few lines in the SCSS to point at the regular icons when it's the nord theme and I'm just missing where the line is I need to change.

I saw in [another question](https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/566) that extracting these icons is within the gtk gresource stuff, which I can figure out if I have to.

Thanks for all the work of putting this theme together, it's fantastic!

Edit: I'm on Fedora 34 with GNOME Shell 40.9 & Fedora 35 with GNOME Shell 41.4.

**Comment by vinceliuice** [comment]
Those are all png pictures assets

**Comment by vinceliuice** [comment]
You can modify this: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/73e6e81b81cebbe70bfa8fce071eea8a335d05f8/lib-install.sh#L433
Just remove `${colorscheme}` then install the nord version

**Comment by OPSJono** [comment]
Perfect - thank you  so much :heart:
