### ISSUE TITLE
Small design glitch 

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/WhiteSur-gtk-theme#579]
System info:
OS: EndeavourOS Linux x86_64
Host: VivoBook_ASUSLaptop X412DA_X412DA 1.0
Kernel: 5.17.0-247-tkg-pds
Uptime: 20 hours, 50 mins
Packages: 1179 (pacman), 21 (flatpak)
Shell: zsh 5.8.1 
Resolution: 1920x1080
DE: GNOME 41.5
WM: Mutter
WM Theme: WhiteSur-dark-solid
Theme: WhiteSur-dark-solid [GTK2/3] 
Icons: Colloid-teal-dracula-dark [GTK2/3]
Terminal: gnome-terminal
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
Memory: 4190MiB / 5943MiB 

Hi, I've been using this particular theme for quite sometime, and i noticed a small bug, which is easy to see in the screenshots attached:
(How it is)

![Screenshot from 2022-03-21 22-33-51](https://user-images.githubusercontent.com/88226614/160270304-4e50678d-4a8c-482e-bbfe-4a66d4c9df3b.png)

(how it should be)

![Screenshot from 2022-03-21 22-35-26](https://user-images.githubusercontent.com/88226614/160270368-076b0a40-7d5c-428a-8a62-dd810d3d3f7c.png)

If you see, the first tab has a square border shape, while the second tab has the correct rounded square border shape.

**Comment by vinceliuice** [comment]
What's your nautilus version?

**Comment by Nakamerica** [comment]
thank you.
