### ISSUE TITLE
Gedit has 90 degrees border radius on bottom left and bottom right.

### ISSUE THREAD

**Issue by vinliao** [vinceliuice/WhiteSur-gtk-theme#58]
With this theme, open gedit (it's not gedit specific btw) and notice that the bottom left and bottom right has a 90 degrees border.

It applies to gnome-terminal too. I don't think it should be 90 degrees... right?

![Screenshot from 2020-11-01 22-21-44](https://user-images.githubusercontent.com/34117807/97806978-d89d7c00-1c90-11eb-99b6-d5235b9ee72c.png)

![Screenshot from 2020-11-01 22-22-03](https://user-images.githubusercontent.com/34117807/97806977-d76c4f00-1c90-11eb-98bd-6ca5611a4b35.png)

**Comment by rivanfebrian123** [comment]
Already fixed here: https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6254031/WhiteSur-gtk-theme-backup-Apr-4.zip. Can you try it?
