### ISSUE TITLE
[Firefox theme] Incorrect shadow on the top left & right corners

### ISSUE THREAD

**Issue by noahdigesu** [vinceliuice/WhiteSur-gtk-theme#59]
![image](https://user-images.githubusercontent.com/62944748/98018716-26d18d00-1e01-11eb-918a-5ba59d34e383.png) ![image](https://user-images.githubusercontent.com/62944748/98019575-37363780-1e02-11eb-9fb4-31ceae327df7.png)

With the Firefox theme installed (from `src/other/firefox`), the shadow doesn't go properly around the corner of the window radius.

It's the _only place_ where that problem occurs, and after searching for a while I couldn't find where the issue might come from.

**I know it's quite a minor issue, so if you don't want to fix it yourself I can do it no problem, but please give me somewhere to start from** 🙂.

Have a nice evening,
Noah
<br>
_PS: Yes I'm a perfectionist 🤪._

**Comment by vinceliuice** [comment]
This is a Firefox issue, all firefox theme with circle corner will have this

**Comment by noahdigesu** [comment]
> This is a Firefox issue, all firefox theme with circle corner will have this

Okay thanks for the info!
At least that was easy to solve ahhaah
