### ISSUE TITLE
cp: cannot create directory '/root/.config/gtk-4.0': No such file or directory

### ISSUE THREAD

**Issue by miftahfaridl21** [vinceliuice/WhiteSur-gtk-theme#593]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> cp: cannot create directory '/root/.config/gtk-4.0': No such file or directory
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> cp -rf "${TMP_DIR_T}/assets" "${HOME}/.config/gtk-4.0"
  TRACE  :
    >>> signal_error
    >>> install_theemy
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : workstation;platform:f35;fedora;35
  SUDO   : yes
  GNOME  : new
  REPO   : 2022-04-18T19:33:06+0700

**Comment by vinceliuice** [comment]
Fixed !
