### ISSUE TITLE
Screenshot UI does not work with WhiteSur GDM theme [tweaks.sh] on GNOME 42

### ISSUE THREAD

**Issue by omanwhatiscomputer** [vinceliuice/WhiteSur-gtk-theme#599]
Thank you so much for making these wonderful themes. The themes work flawlessly on my distro (Pop OS 22.04) but it tends to break with the recent addition of the screenshot overlay with Gnome 42 which is triggered by the "PRINT SCREEN" button on the keyboard.

The UI shows up like this:
![wrong](https://user-images.githubusercontent.com/46564880/166093443-6e09c7d1-89e1-477a-a21e-6d28c175eda8.png)

When it is supposed to be like this:
![roight](https://user-images.githubusercontent.com/46564880/166093446-e0df84a0-b002-4215-a699-0bbf0a2305ee.png)

=====================================================================
Tested on: Pop OS 22.04 ~ GNOME 42 ~ X11 ~ Cosmic DE

**Comment by Tim-Paik** [comment]
same question!

**Comment by matmicha** [comment]
Screenshot UI is broken for me too, fixed with WhiteSur GDM theme uninstall. 

I'm on Fedora 36 (kernel 5.18.9), Wayland, GNOME 42.2
