### ISSUE TITLE
Nautilus File Manager Styling not applying in Budgie Desktop on Arch Linux

### ISSUE THREAD

**Issue by MichaelPetersen22** [vinceliuice/WhiteSur-gtk-theme#600]
I am using Arch Linux with Budgie Desktop and nautilus file manager installed, alongside gtk-engine-murrine and gtk-engines packages, Whitesur Dark (all dark themes) will usually display nautilus with white (Although occasionally it will open with a dark background but it is very difficult to replicate opening nautilus with black / dark background) when I believe expected appearance is dark nautilus, Would there be any way I myself can change it to be dark i.e. in the installed theme folder css? My guess is straight arch with budgie desktop and nautilus uses a different css tag for file manager background styling.
![Whitesur Nautilus White](https://user-images.githubusercontent.com/72793125/166108534-b53e84ae-e231-430a-82e4-2a83a0c82926.png)

**Comment by MichaelPetersen22** [comment]
I am not sure where to contact you, so I'll just add it in here, but as an update to this I have just gone through quite a few of your themes and none of them seem to change the nautilus file manager background color anymore, and in some cases breaks the manager. I am not sure if this is related to budgie or arch.
In spite of the "bugs" which I honestly did not experience at all on other distros, these themes and styles are all works of art.
Thanks for your amazing work Vince

**Comment by vinceliuice** [comment]
run `./tweaks.sh -F`

**Comment by MichaelPetersen22** [comment]
I ran it, but it does not seem to have done anything.

**Comment by vinceliuice** [comment]
Is nautilus a snap app or flatpak app ？

**Comment by vinceliuice** [comment]
Is nautilus a snap app or flatpak app？if it is a normal app then after change your theme try restart nautilus, you can use gnome-monitor to kill it and open it again

**Comment by MichaelPetersen22** [comment]
Ahh, Yep my nautilus is a normal app. I have tried making the change and then restarting nautilus via nautilus -q

**Comment by MichaelPetersen22** [comment]
Should I switch types to either flatpak or snap?

**Comment by vinceliuice** [comment]
Oh my bad, did not notice you are using the dark theme, after gnome 42 all simple THEMENAME-dark theme will have conflicts, system can not use it, you can use the whitesur-light and make the system use the dark mode, or just rename the whitesur-dark to whitesur-Dark

**Comment by vinceliuice** [comment]
I'm considering rename all dark to Dark now

**Comment by MichaelPetersen22** [comment]
Yep, changing dark to Dark fixed it. I suppose that explains why your Orchis theme works great, because they have all been renamed.
Thanks for your help!

**Comment by vinceliuice** [comment]
You are welcome

**Comment by KukicVidan** [comment]
for someone that ended up diging this problem in 2024.... and maybe randomly want nord colors to apply to all folders and windows (this is for WhiteSur Themes)...try installing it using these options:
`./install.sh -a normal -m -N stable -l --round -t all --nord  `
