### ISSUE TITLE
not compatible with gnome 42

### ISSUE THREAD

**Issue by Gictorbit** [vinceliuice/WhiteSur-gtk-theme#602]
Theme doesn't apply on all windows and top buttons in left mode has too much space
![image](https://user-images.githubusercontent.com/34630603/166136353-a3712a4e-3377-4098-ab70-7d1a1aab29c1.png)

distro specs:
```bash
OS: Arch Linux x86_64 
Kernel: 5.17.5-arch1-1 
Shell: zsh 5.8.1 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 42.0 
WM: Mutter 
WM Theme: WhiteSur-dark 
Theme: WhiteSur-dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
```

**Comment by CoolAller** [comment]
"NOME 42 will have its nautilus application move to GTK4". 
For compatibility, you need to make a theme for nautilus GTK3 and GTK4.

**Comment by frosth555** [comment]
I've met second issue only, I use gnome + light-blue theme 
![Screenshot from 2022-05-03 14-53-40](https://user-images.githubusercontent.com/22305379/166456617-e3956ff5-6d2e-44fa-ad42-a55f770597a7.png)
from top to bottom: 
firefox(beta), chrome(beta), gnome-settings, extensions, calculator, lutris, nautilus(glassy), gnome-terminal

**Comment by CoolAller** [comment]
After changing the theme, try to enter the command in the terminal:  nautilus -q
Then open nautilus again and take a look.

**Comment by Pinghigh** [comment]
> I've met second issue only, I use gnome + light-blue theme ![Screenshot from 2022-05-03 14-53-40](https://user-images.githubusercontent.com/22305379/166456617-e3956ff5-6d2e-44fa-ad42-a55f770597a7.png) from top to bottom: firefox(beta), chrome(beta), gnome-settings, extensions, calculator, lutris, nautilus(glassy), gnome-terminal
> 
> edit: looks like first issue appears only for dark theme

It has been correct after turn into the light theme. But the dark theme is still wrong
