### ISSUE TITLE
GNOME Apps Like Settings Using Light Mode Instead of dark Mode

### ISSUE THREAD

**Issue by toast-t-bread** [vinceliuice/WhiteSur-gtk-theme#606]
I have all my themes set to  WhiteSur Dark but the GNOME default apps are using light mode, anyone know why?

GNOME Tweaks using WhiteSur Dark
![image](https://user-images.githubusercontent.com/84289765/166861182-50fbfecc-5d94-441c-8fad-4263e9103a6f.png)

GNOME Settings Using WhiteSur Light Instead
![image](https://user-images.githubusercontent.com/84289765/166861238-91774598-3d92-447c-9b34-e3ff2e05deb0.png)

Pamac-manager Using WhiteSur Dark
![image](https://user-images.githubusercontent.com/84289765/166861267-4f6a1e4b-5267-4e6e-bdde-0449c1d3b30a.png)

GNOME Software Using WhiteSur Light Instead of WhiteSur Dark
![image](https://user-images.githubusercontent.com/84289765/166861298-65be6d2f-8707-42a1-9192-c3a39c178250.png)

**Comment by vinceliuice** [comment]
Fixed, run `./install.sh -l` for the libadwaita now
