### ISSUE TITLE
Install.sh worked very well yesterday, but not today.

### ISSUE THREAD

**Issue by Balbao** [vinceliuice/WhiteSur-gtk-theme#607]
=========== ERROR LOG ===========
  >>> Internal Error: File to read not found or unreadable: /home/yul/Téléchargements/WhiteSur-gtk-theme/src/main/gnome-shell/shell-none/gnome-shell-dark.scss
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 359
  SNIPPET:
    >>> sassc ${SASSC_OPT} "${THEME_SRC_DIR}/main/gnome-shell/shell-${GNOME_VERSION}/gnome-shell${color}.scss" "${TARGET_DIR}/gnome-shell.css"
  TRACE  :
    >>> signal_error
    >>> install_shelly
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : gentoo
  SUDO   : yes
  GNOME  : none
  REPO   : 2022-05-05T12:57:10+0200

I installed WhiteSur-gtk-theme yesterday, and everything worked fine. You changed the install.sh and today it doesn't work anymore.

**Comment by vinceliuice** [comment]
Fixed now!
