### ISSUE TITLE
Pantheon Files - Search Bar

### ISSUE THREAD

**Issue by btd1337** [vinceliuice/WhiteSur-gtk-theme#61]
Hey Vince, first congratulations on this great job.

Could you fix the search bar in Pantheon Files? The text is overlaying the search icon.

![Captura de tela de 2020-11-10 13-22-17](https://user-images.githubusercontent.com/11943860/98701311-e66d9400-2357-11eb-8da0-a80c75bb7ef3.png)

**Comment by vinceliuice** [comment]
Fixed
