### ISSUE TITLE
installion failed in ubuntu22.04 Gnome42

### ISSUE THREAD

**Issue by hello1234316** [vinceliuice/WhiteSur-gtk-theme#610]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: The repository 'https://ppa.launchpadcontent.net/dawidd0811/neofetch/ubuntu jammy Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  >>> E: The repository 'https://ppa.launchpadcontent.net/numix/ppa/ubuntu jammy Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  >>> E: The repository 'https://ppa.launchpadcontent.net/plushuang-tw/uget-stable/ubuntu jammy Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 131;137
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2022-05-10T23:28:08+0800

  HINT: You can google or report to us the info above 

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

**Comment by vinceliuice** [comment]
Run: `sudo apt install sassc libglib2.0-dev-bin` then install this theme

**Comment by hello1234316** [comment]
THX!
