### ISSUE TITLE
Uninstall GDM, won't revert back Default GDM Theme in Gnome 42

### ISSUE THREAD

**Issue by wukongrita** [vinceliuice/WhiteSur-gtk-theme#611]
Distro: Fedora 36
Gnome: 42.1

Hi,

After upgrade to Fedora 36, the Default Gnome 42 GDM working fine with it's default (ofcourse, this theme and GDM were still installed).

I tried to uninstall this theme and the GDM, but the default Gnome 42 GDM seems revert back to Gnome 41 and the OSD is a mess, like what #599 looks like.

But when I install the WhiteSur GDM again, the OSD working fine (still I cannot have my Gnome 42 Default GDM back)

Here is the capture if I install the WhiteSur GDM:

![image](https://user-images.githubusercontent.com/25361005/168234717-efdc1e36-428b-41ec-ab09-a6ee27eedaae.png)

Here is the capture if I switch to Default Gnome 42 GDM (with WhiteSur GDM still installed):
![image](https://user-images.githubusercontent.com/25361005/168235190-8c4c6ab3-c17b-4740-a50e-3247fe0069f4.png)
The Panel still use WhiteSur GDM, even that I have choose the Default Gnome 42 GDM... While it should looks like: https://static.gnome.org/release/42/screenshots.webm

Here is the capture if I uninstall all of the WhiteSur (GDM, GTK. etc):
![image](https://user-images.githubusercontent.com/25361005/168237072-e11293c5-b9fd-499f-9455-98ed3d657cf6.png)

The Gnome 42 Default GDM seem rolled back to Gnome 41 and the screenshot and other OSD are messy..

How do I fixed this ?

**Comment by vinceliuice** [comment]
Did you installed gdm theme before you update to gnome-shell 42?

**Comment by vinceliuice** [comment]
Try reinstall gnome-shell desktop again

**Comment by vinceliuice** [comment]
[gnome-shell-theme.gresource.tar.gz](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/8687053/gnome-shell-theme.gresource.tar.gz)

**Comment by wukongrita** [comment]
> Did you installed gdm theme before you update to gnome-shell 42?

Yes, WhiteSur has been my default theme... And I just upgrade to Fedora 36, without changing/uninstall the WhiteSur.
I guest, when I uninstall the WhiteSur, the uninstaller rolled back Gnome 41 shell theme...


> [gnome-shell-theme.gresource.tar.gz](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/8687053/gnome-shell-theme.gresource.tar.gz)
> 
> You can replace this file into `/usr/share/gnome-shell/` I upload it from my fedora 36

Thanks @vinceliuice 
This file sure rollback the default Gnome 42 shell theme again..

Could be a little modified for the uninstaller for checking the current Gnome shell theme and replace it if there is an updated one before rolled back.. ?

**Comment by vinceliuice** [comment]
I'll think about how to achieve this function you said
