### ISSUE TITLE
Dash to Dock theme Gnome 42

### ISSUE THREAD

**Issue by anggapw** [vinceliuice/WhiteSur-gtk-theme#613]
'-d' ERROR: There's no Dash to Dock installed in your system

Hi, i am using this Dash to Dock https://extensions.gnome.org/extension/5004/dash-to-dock-for-cosmic/ instead of the original, because this is only work in Gnome 42. Can you help me with the installation?

**Comment by vinceliuice** [comment]
What's your system? dash to dock works well on my desktop, if you install the one on repository

**Comment by vinceliuice** [comment]
Just remove the one install from web

**Comment by Sciroccogti** [comment]
> What's your system? dash to dock works well on my desktop, if you install the one on repository

The situation is that the original *Dash to Dock* won't work with Gnome 42, which is used in Ubuntu 21.10+, so we have to use the modified one, and that is not detected by `tweaks.sh`.

**Comment by Sciroccogti** [comment]
In `lib-core.sh`, `DASH_TO_DOCK_DIR_HOME` should be `"${MY_HOME}/.local/share/gnome-shell/extensions/dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com"`, `DASH_TO_DOCK_DIR_ROOT` should be `"/usr/share/gnome-shell/extensions/dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com"`, then *Dash to Dock for cosmic* can be detected.

**Comment by Sciroccogti** [comment]
Dash to Dock supports gnome43 now, maybe this can be closed? @anggapw
