### ISSUE TITLE
Failed installation in Ubuntu 22.04

### ISSUE THREAD

**Issue by alexandrepgui** [vinceliuice/WhiteSur-gtk-theme#623]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> No provider of 'glib2-devel' found.
  >>> No provider of 'libxml2-tools' found.
  >>> No provider of 'sassc' found.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 162
  

  Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> No provider of 'glib2-devel' found.
  >>> No provider of 'libxml2-tools' found.
  >>> No provider of 'sassc' found.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 162
  SNIPPET:
    >>> zypper in -y sassc glib2-devel libxml2-tools
  TRACE  :
    >>> signal_error
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2022-05-31T22:04:32-0300

**Comment by alexandrepgui** [comment]
Yes, I actually ran the zypper command from `lib-install.sh` directly, and the same error message appears.
```Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...
'glib2.0' not found in package names. Trying capabilities.
No provider of 'glib2.0' found.
'sassc' not found in package names. Trying capabilities.
No provider of 'sassc' found.
'xmllint' not found in package names. Trying capabilities.
No provider of 'xmllint' found.
Resolving package dependencies...
```

**Comment by vinceliuice** [comment]
Run `sudo apt install sassc libglib2.0-dev-bin libxml2-utils`
