### ISSUE TITLE
Brightness OSD progress not visible/ Sound OSD very long/short.

### ISSUE THREAD

**Issue by hackingguy** [vinceliuice/WhiteSur-gtk-theme#626]
![image](https://user-images.githubusercontent.com/28388650/171864279-c8d54e51-6f3f-49fd-88ff-09bb7e88320e.png)

Unable to see progress bar of Brightness OSD.

Found Sound Volume, length of progress bar depends upon the device name, this isn't a good practice, max and min length of OSD should be fixed.

**Comment by 3dw4rd-sn0wd3n** [comment]
![image](https://user-images.githubusercontent.com/83455051/174157709-524cd785-3eae-451e-8562-85d1a03feeca.png)
so i have same trouble, can anyone help with this?

**Comment by luisrdzruiz** [comment]
I have same issue with volume, brightness and keyboard light.
![image](https://user-images.githubusercontent.com/43277999/179794684-799c455c-dbfa-441f-b70d-dff719568268.png)
![image](https://user-images.githubusercontent.com/43277999/179795007-f4df0010-7a45-4c1b-a2d5-f968941da087.png)
