### ISSUE TITLE
Dash to Dock black rectangle appears

### ISSUE THREAD

**Issue by GenaANTG** [vinceliuice/WhiteSur-gtk-theme#632]
Hi! Thanks a lot for this theme!
After running `./tweak -d` i have a black border around a my dock panel.

`gnome-shell --version` is **42.1**
`gtk-launch --version` is **3.24.33**

P.S. In general this theme looks amazing!

![Screenshot from 2022-06-07 07-15-47](https://user-images.githubusercontent.com/12715550/172366797-028c1cf9-2f29-42bb-ae2c-42de623c04a8.png)

**Comment by vinceliuice** [comment]
Disabled blur-my-shell for dock
