### ISSUE TITLE
Installation with color doesn't work

### ISSUE THREAD

**Issue by Landris18** [vinceliuice/WhiteSur-gtk-theme#640]
When I try to execute the example in the README :

`./install.sh -c dark -c light `

It show me this error:
```
 ERROR: Unrecognized '-c' variant: 'dark'.
 ERROR: Unrecognized '-c' variant: 'light'.

 Try './install.sh --help' for more information. 
```

But the `./install --help` give me in the color section:

```
-c, --color [Light|Dark]
 Set theme color variants. Repeatable. Default is all variants
```

Then when I proceed to the installation like this : `./install.sh -c Dark -c Light `, it works.

So for me the rights arguments for the -c options are __Dark__ and __Light__ but not __dark__ and __light__ .

Thanks.

**Comment by vinceliuice** [comment]
I'll fix this
