### ISSUE TITLE
First tab in FF Monterey overflows into address bar

### ISSUE THREAD

**Issue by insidemordecai** [vinceliuice/WhiteSur-gtk-theme#649]
I'm on Firefox v102.0.1 running on Fedora 36 with Gnome 42.3.1

I don't have the Whitesur GTK theme installed but just the Firefox Monterey tweak and I have noticed the first tab (whether pinned or not) overflows into the address bar section. Not sure if that was intentional but it doesn't seem so to me.

Below is a screenshot showing a pinned Google Sheets tab

![image](https://user-images.githubusercontent.com/39312305/179518023-5a9879b6-fc86-42f5-8de6-ef13743439c3.png)

And the same tab unpinned 

![image](https://user-images.githubusercontent.com/39312305/179519604-7a50898d-d01d-49e4-be3e-85ca2edff2d8.png)

**Comment by vinceliuice** [comment]
There is 4 buttons on your left side of topbar  you need to change the config  file

**Comment by insidemordecai** [comment]
Oh, that's odd but removing the home button worked. Thanks

**Comment by insidemordecai** [comment]
in the event I want to re-add the home button (or another), where can I get the config file and what parameters need to be changed or added

**Comment by vinceliuice** [comment]
Check the readme file, you can run './tweaks.sh -f -e' to edit the config file

**Comment by insidemordecai** [comment]
Done, thanks for that.
