### ISSUE TITLE
Mixed themes Dark/Light on Pop!_OS

### ISSUE THREAD

**Issue by drm-code** [vinceliuice/WhiteSur-gtk-theme#661]
I installed the theme package manually and using the `./install.sh` file, same result, I have like the themes mixed (Dark/Light).

I logout/rebooted nothing change, I like Light theme but I can't make it work :cry:
| --- |
| ![image](https://user-images.githubusercontent.com/6596444/184177511-93e81df0-70cf-4769-93fa-84f0e2c00132.png) |
| ![image](https://user-images.githubusercontent.com/6596444/184177854-fdbf4a97-8032-47f7-a75e-98fe2888a22e.png) |
| ![image](https://user-images.githubusercontent.com/6596444/184178076-25b61cd0-7c34-457a-ab7c-e9a1e4b3a996.png) |

**Comment by vinceliuice** [comment]
Run `./install.sh -c light`

**Comment by drm-code** [comment]
> Run `./install.sh -c light`

```
./install.sh -c light

** (process:220244): WARNING **: 14:02:11.647: Failed to set RT scheduler: Operation not permitted

  ERROR: Unrecognized '-c' variant: 'light'.

  Try './install.sh --help' for more information.
```

I think it should be with capital "L", I reboot and same result, it's like the native apps like calendar, mail, nautilus, only apply the dark (which is not installed btw) 

![image](https://user-images.githubusercontent.com/6596444/184409248-d4326e44-dc0e-4011-a098-e0d4c9dd0e59.png)

**Comment by vinceliuice** [comment]
./install.sh -c Light

**Comment by drm-code** [comment]
Some days after this, I installed an extension called [Night Theme Switcher](https://nightthemeswitcher.romainvigier.fr/), apparently, that fixed the issue I was having, now I have both light and dark themes on my system, this is what I love about Linux, there's always a way to fix things. :heart:

**Comment by eduardoconde-bit** [comment]
> Some days after this, I installed an extension called [Night Theme Switcher](https://nightthemeswitcher.romainvigier.fr/), apparently, that fixed the issue I was having, now I have both light and dark themes on my system, this is what I love about Linux, there's always a way to fix things. heart

ok, good solution! thanks
