### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by PrimOox** [vinceliuice/WhiteSur-gtk-theme#667]
Oops! Operation failed...

  =========== ERROR LOG ===========

    >>> Failed to execute child process “dbus-launch” (File or directory does not exist)
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh at 182
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> notify-send "'${name}' theme has been installed. Enjoy!" "${notif_msg}" -i "dialog-information-symbolic"
  TRACE  :
    >>> signal_error
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : yes
  GNOME  : new
  REPO   : 2022-02-21T05:45:22-0300

**Comment by Chiranthan-y** [comment]
got same error!!!!

**Comment by PrimOox** [comment]
Error is gone with the new release.
