### ISSUE TITLE
Some theme config is broken on Gnome 43 control center (Quick settings)

### ISSUE THREAD

**Issue by wolf-yuan-6115** [vinceliuice/WhiteSur-gtk-theme#668]
I upgraded my system to Fedora 37 to try Gnome 43, and I have a problem with the theme

What I see:

![image](https://user-images.githubusercontent.com/58245644/186809382-edbb375b-5fb4-4afe-a7b7-d249a2c4a69f.png)

What it suppose to be:

![image](https://user-images.githubusercontent.com/58245644/186809443-06b0e32c-d01a-47a9-8114-6efac5915879.png)

**Comment by vinceliuice** [comment]
Fixed!
