### ISSUE TITLE
GDM Theme not working on Ubuntu 20.10

### ISSUE THREAD

**Issue by lenuswalker** [vinceliuice/WhiteSur-gtk-theme#67]
GDM Theme does not seem to be working on Ubuntu 20.10 with nvidia optimus. The theme folders seems to be wrong.

**Comment by axiel7** [comment]
It doesn't work on Ubuntu 20.04 too

**Comment by vinceliuice** [comment]
I'll check this

**Comment by axiel7** [comment]
@vinceliuice if this is any help:
This [script](https://github.com/thiggy01/change-gdm-background) works fine for me on Ubuntu 20.04 to change the GDM background

**Comment by vinceliuice** [comment]
Thanks! I'm working on it, it'll be fix soon!

**Comment by vinceliuice** [comment]
I updated, you can try it now, If you get any issues, you can give feedback here!
