### ISSUE TITLE
Problems with Dash to Dock

### ISSUE THREAD

**Issue by DaWhiteXD** [vinceliuice/WhiteSur-gtk-theme#670]
![Screenshot from 2022-08-28 16-48-00](https://user-images.githubusercontent.com/108514756/187065770-db77d38a-95c3-4d8d-a45c-26568a7fe845.png)
This is the problem... THere's a tiny striaght corner appears???

**Comment by DaWhiteXD** [comment]
Wait... My screenshot can't see...

**Comment by DaWhiteXD** [comment]
![20220828_164955](https://user-images.githubusercontent.com/108514756/187065879-35bf619b-d86e-4987-9241-f4e2b737c818.jpg)
This... is what I see...

**Comment by vinceliuice** [comment]
Disable blur-my-shell for dock

**Comment by DaWhiteXD** [comment]
okok

**Comment by DaWhiteXD** [comment]
Fixed Thx
