### ISSUE TITLE
The title of the app on top bar is not bold

### ISSUE THREAD

**Issue by hrqmonteiro** [vinceliuice/WhiteSur-gtk-theme#674]
![Screenshot from 2022-08-30 12-57-59](https://user-images.githubusercontent.com/17055027/187484631-5dcdd74d-075c-4437-ba5f-ad73e8e9064f.png)

My top bar was getting the title of the app bold, but when i installed the nord variant, all of the gnome-shell themes are now putting this light font. How can i remove this behavior?

**Comment by cmalvi** [comment]
I can see this problem not only in font in panel but also in the icon tray and icon in windows title bar

**Comment by hrqmonteiro** [comment]
> I can see this problem not only in font in panel but also in the icon tray and icon in windows title bar

Exactly.

And i realized this only happens when you install the nord variant. It kinda overwrite every shell themes installed, since even when i turn back to adwaita (default) it is not bold anymore.

**Comment by hrqmonteiro** [comment]
I even tried to restart all of my gnome configurations to the factory defaults, and it didn't solve it.

**Comment by cmalvi** [comment]
> > I can see this problem not only in font in panel but also in the icon tray and icon in windows title bar
> 
> Exactly.
> 
> And i realized this only happens when you install the nord variant. It kinda overwrite every shell themes installed, since even when i turn back to adwaita (default) it is not bold anymore.

Seems little different to my case, see my edited reply
