### ISSUE TITLE
Change Apple logo to Arch in the shell?

### ISSUE THREAD

**Issue by sharjeelmazhar** [vinceliuice/WhiteSur-gtk-theme#675]

**Comment by sharjeelmazhar** [comment]
Found the solution

**Comment by mashirozx** [comment]
> Found the solution

how? please 🙏

**Comment by eniskalyon** [comment]
> Found the solution

could you tell how you solved it?

**Comment by sharjeelmazhar** [comment]
Sorry, i don't remember it know, it's been so long. You can google it or ChatGPT it and i certain you will find the solutions. It also took me a few minutes to solve when i had the issue
