### ISSUE TITLE
Flatpak theme installation error

### ISSUE THREAD

**Issue by cmalvi** [vinceliuice/WhiteSur-gtk-theme#676]
Oops! Operation failed...

  =========== ERROR LOG ===========
  
>>>>>>> No error log found <<<<<<
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-flatpak.sh at 51
    >>> lib-install.sh
    >>> tweaks.sh
  SNIPPET:
    >>> cp -a "$theme_path/gtk-3.0/"* "$build_dir/files"
  TRACE  :
    >>> signal_error
    >>> pakitheme_gtk3
    >>> connect_flatpak
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : rolling;manjaro;arch
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2022-08-30T12:12:52+0200

**Comment by gustavobarbosa-web** [comment]
Just had same issue on OpenSuse Tumbleweed, fixed by running `sudo ./install.sh && sudo ./tweaks.sh -F`

Guess the script without sudo is not looking into the correct folder...

**Comment by cmalvi** [comment]
I’ve fixed the problem by adding .themes and .icons to flatpak filesystem from flatseal
