### ISSUE TITLE
gnome-terminal and mostly other gnome apps incorrect size with pop-shell-extension

### ISSUE THREAD

**Issue by cmalvi** [vinceliuice/WhiteSur-gtk-theme#679]
Asahi Arch Linux Arm - MacBook Air M1 2020 13"
Gnome 42.4
2560x1600
Wayland with fractional scaling enabled - 175%

Note: The issue seems not present on my desktop with 
Manjaro
Gnome 42.4
1920x1080 on 24"
Xorg with 100% scaling factor

The issue was not present using stock theme or pop-shell theme

![image](https://user-images.githubusercontent.com/76235393/188024757-73d5f604-62cc-47f2-b3d3-867a6bd4119b.png)

**Comment by Giovannimbesi25** [comment]
It isn't a theme bug, but a pop-shell one.
