### ISSUE TITLE
tweaks.sh -s

### ISSUE THREAD

**Issue by SecondPort** [vinceliuice/WhiteSur-gtk-theme#686]

**Comment by omariobros** [comment]
:gtk-3-themes whitesur-gtk-theme:gtk-3-themes
  TRACE  :
    >>> signal_error
    >>> connect_snap
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu debian;linuxmint;21
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2022-09-21T14:58:01+0000
