### ISSUE TITLE
[feature request] additonal accent & highlight colors

### ISSUE THREAD

**Issue by ListeningGarden** [vinceliuice/WhiteSur-gtk-theme#69]
in macos, the user is able to select from a series of colors that replaces the default blue accent for buttons, bars and other elements. this gives an additional level of personalization to their system.

![5-preferences-general-macos-catalina-big-sur-comparison](https://user-images.githubusercontent.com/36242661/99508559-bb380580-2952-11eb-9c2d-b857353aafe6.png)
![4-apple-music-preferences-macos-catalina-big-sur-comparison](https://user-images.githubusercontent.com/36242661/99509874-5bdaf500-2954-11eb-9a5f-54b6d5a5b208.png)
![5-podcasts-preferences-macos-catalina-big-sur-comparison](https://user-images.githubusercontent.com/36242661/99509883-5e3d4f00-2954-11eb-8dd9-bd41485f439b.png)

(taken from [here](https://www.andrewdenty.com/blog/2020/07/01/a-visual-comparison-of-macos-catalina-and-big-sur.html))

while an app itself to change colors on the fly would not be possible or within the scope of your work, i wanted to suggest the possibility of adding additional colors (purple, pink, green, red, etc) to match the other colors apple provides to users. i understand it would likely not be a trivial change and may be messy to upload each individually to plink, but i still think it could be a great addition to your theme as no macos recreation theme has ever used the other colors before! could also look into adding it to your mcata/mcmojave themes as well, should it not prove to be too much work. thank you for your consideration <3

**Comment by rezgi** [comment]
I second that. This theme is great and clean, but it lacks color accents. Is there a way to change the default blue ? I've seen that the css file is downloaded from the web and is not locally available.

**Comment by vinceliuice** [comment]
No problem! I'll add this support

**Comment by vinceliuice** [comment]
Now you can run ./install.sh -t to change a different accent color

**Comment by rezgi** [comment]
Thank you for the fast update ! I tried to install the accent but it doesn't show up. I used your theme simply by copying files in the .themes folder and it's the first time I used the install script. Is there a conflict somewhere ? After the install.sh nothing has been changed in the .themes folder (I installed all the dependencies and I have no error).

**Comment by vinceliuice** [comment]
Run `./install.sh -t` to install different accent color version

**Comment by vinceliuice** [comment]
you need install `sassc ``inkscape ``optipng ``dialog` for this script

**Comment by rezgi** [comment]
@vinceliuice Thanks but I had already installed all dependencies, removed the whiteSur theme I manually put in .themes and ran `./install.sh -t`. It renders a bunch of images which I guess is for inkscape theming, with an error that inkscape/fonts doesn't exist. Then in the end it sets up the .css files but nothing happens ! No whitesur theme appears in my .themes and I've searched for it but nothing.

Btw there's also a small bug where white-sur-dark-solid doesn't apply the dark theme on notifications, calendar, menus and such in Pop_OS.

Thank you.

**Comment by vinceliuice** [comment]
Download from github, don't put this in .theme, just extract it in any place and run ./install.sh -t, this will install the theme into ./theme

**Comment by vinceliuice** [comment]
Could you show me a screenshot? if you want use gnome-shell theme you make this `User Themes` active:
![Screenshot from 2020-12-28 20-55-16](https://user-images.githubusercontent.com/7604295/103215695-10523880-494f-11eb-871a-a2b890b7ba95.png)

**Comment by rezgi** [comment]
Here's a screenshot of my different windows, wasn't sure what you wanted. You can see that I have my manually installed themes in the Tweaks menu and .themes, but the script doesn't add or change anything to this list.

You can also see the terminal prompt, it renders a bunch of png of inkscape, which I'd like to deactivate btw. Then the css are configured but nothing changes for me, I don't see where this theme has been installed or setup.

![Snap 28-12 18:07 1920x1173](https://user-images.githubusercontent.com/41618561/103231375-eb9e9680-4937-11eb-95dc-1e40a3f4e887.png)
![Snap 28-12 18:07 1915x1173](https://user-images.githubusercontent.com/41618561/103231371-ea6d6980-4937-11eb-80bc-6e8f6435e477.png)
![Snap 28-12 18:09 1924x1174](https://user-images.githubusercontent.com/41618561/103231377-ec372d00-4937-11eb-9b7e-693f34ad97eb.png)
![Snap 28-12 18:00 1912x1170](https://user-images.githubusercontent.com/41618561/103231101-4aafdb80-4937-11eb-95fa-d9a0b6911844.png)

**Comment by vinceliuice** [comment]
There is a issue when you install: notify-send: command not found

**Comment by vinceliuice** [comment]
I removed `notify-send` now it's OK

**Comment by rezgi** [comment]
It works !! Thank you so much for the efficient and fast help ! Wish you a happy new year !!!

**Comment by vinceliuice** [comment]
You are welcome! happy new year !
