### ISSUE TITLE
Size of the icons too big

### ISSUE THREAD

**Issue by DavidRamiroBarragan** [vinceliuice/WhiteSur-gtk-theme#691]
![image](https://user-images.githubusercontent.com/17888187/194369890-32dfe995-110a-4d91-ab95-b4c99c835b1d.png)

![image](https://user-images.githubusercontent.com/17888187/194369671-1113eb64-64d3-49ff-a148-7fbb1c1d6432.png)

**Comment by vinceliuice** [comment]
Does this fixed now?

**Comment by mralaminahamed** [comment]
i have still suffering as the same issue. i noted for you that i have install from your latest source of Github Repository.

Screenshot:
![Screenshot from 2022-10-09 21-18-42](https://user-images.githubusercontent.com/34349365/194764902-306908fe-6599-4c1d-9a9f-ed32e5b268a2.png)

**Comment by vinceliuice** [comment]
It's fixed now!

**Comment by mralaminahamed** [comment]
> It's fixed now I think

Thank you very much!

**Comment by vinceliuice** [comment]
You are welcome!
