### ISSUE TITLE
Font and title bar problems with WhiteSur Dark

### ISSUE THREAD

**Issue by myfix16** [vinceliuice/WhiteSur-gtk-theme#694]
System: Ubuntu 22.04 LTS

The WhiteSur Light theme seems fine. But when I switch to the Dark theme, the font color in some apps like gnome-settings is wired.
![image](https://user-images.githubusercontent.com/61649477/194940065-be766fcb-dba3-4499-9880-6e02b3c4aad1.png)

Also, the title bars of some apps like gnome-terminal, screenshot-viewer are not displayed properly.
![image](https://user-images.githubusercontent.com/61649477/194940462-c333e3c3-5711-4068-9ffb-8e05e81212d1.png)

**Comment by myfix16** [comment]
The problem strangely resolved after I reinstalled Ubuntu.

**Comment by rcarmo** [comment]
I have this on Fedora 37. Removed all traces of the theme, reinstalled, got this.
