### ISSUE TITLE
Gtk-WARNING Theme parsing error: gtk.css:5469:16: not a number

### ISSUE THREAD

**Issue by luca-martino** [vinceliuice/WhiteSur-gtk-theme#699]
System info:
OS: Fedora release 36 (Thirty Six) x86_64
Kernel: 5.19.14-200.fc36.x86_64
DE: GNOME 42.5
Theme: WhiteSur-Dark-grey [GTK2/3]

Issue:
On Ásbrú Connection Manager
--- Gtk-WARNING **: ... Theme parsing error: gtk.css:5469:16: not a number
![immagine](https://user-images.githubusercontent.com/17565704/195278050-2ccf69f7-f3c4-4b4b-9313-eb3e2629484b.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by toplinden** [comment]
I get almost the same error:

```
➜  dragon human_bug_ep2.en.ass 

(dragon:147269): Gtk-WARNING **: 08:26:09.958: Theme parsing error: gtk.css:5508:16: not a number
```

- DE: Cinnamon
- Theme: WhiteSur-Dark-solid
