### ISSUE TITLE
Corner content spill-over

### ISSUE THREAD

**Issue by ListeningGarden** [vinceliuice/WhiteSur-gtk-theme#7]
Noticed on Solus Budgie, fully updated stable branch:

![Screenshot from 2020-07-16 17-58-48_edit](https://user-images.githubusercontent.com/36242661/87727553-3021e580-c78f-11ea-8439-817423291d07.png)

Nautilus has some elements which write-out over the corners and into empty space.

![Screenshot from 2020-07-16 17-59-38](https://user-images.githubusercontent.com/36242661/87727554-31531280-c78f-11ea-8974-fad123c4aeb0.png)

Some applications, such as Tilix, render fully square bottom corners while the lower part of the GTK border and underlying shadow appear rounded.

Skin is looking great so far! As always, I appreciate that your themes properly apply to raven panel and Budgie's dock. Hopefully these issues aren't too much of a hassle to work with, I know GTK can be quite constraining when doing anything outside-of-the-box.

**Comment by edwinvandeven** [comment]
Same issue here with Tilix on Pop 20.04 using Gnome 3.36. It shows the corners in the same way as the screenshot in the first comment. I noticed that your Orchis theme doesn't apply a bottom corner radius for Tilix, perhaps that could be a way to at least prevent the corners from sticking out... just having them square for now.

**Comment by vinceliuice** [comment]
I'll fix this!
