### ISSUE TITLE
Nautilus sidebar background doesn't get wider when resizing it

### ISSUE THREAD

**Issue by mind-overflow** [vinceliuice/WhiteSur-gtk-theme#70]
Nautilus' left navbar background is set at a fixed width. It should expand when the sidebar is resized, however.

<details>
  <summary>Default look</summary>

![Schermata da 2020-11-18 19-16-50](https://user-images.githubusercontent.com/67104846/99571039-17426e80-29d3-11eb-946e-a17ce7d45e48.png)
  
</details>

<details>
  <summary>How it looks when the sidebar is resized</summary>

![Schermata da 2020-11-18 19-17-03](https://user-images.githubusercontent.com/67104846/99571103-2b866b80-29d3-11eb-8673-38e32a5ff730.png)
  
</details>

<details>
  <summary>How it should look</summary>

![Schermata da 2020-11-18 19-17-25](https://user-images.githubusercontent.com/67104846/99571128-317c4c80-29d3-11eb-87ed-3151db0479e3.png)
  
</details>

**Comment by vonschutter** [comment]
Confirmed on the latest ubuntu. The Arc-Dark theme works as desired. "Borrow" some code?

**Comment by jindradev** [comment]
WhiteSur uses background-image for the desired effect, no wonder it is not resizable.

**Comment by coder8080** [comment]
Read README file. You can change nautilus sidebar size with --size key.

**Comment by mind-overflow** [comment]
> Read README file. You can change nautilus sidebar size with --size key.

That's not the same thing. By using the terminal command, you can only set the background image size when you install the theme, you can't resize it on the fly as with most other GTK themes. Also, it's limited to a max of 280px, which is still pretty small on 4K screens.
