### ISSUE TITLE
How can i edit this theme?

### ISSUE THREAD

**Issue by hrqmonteiro** [vinceliuice/WhiteSur-gtk-theme#701]
![Screenshot from 2022-10-13 19-52-30](https://user-images.githubusercontent.com/17055027/195725038-786088b6-fe14-4ea3-9792-01fa1ac56e3a.png)
![Screenshot from 2022-10-13 19-52-39](https://user-images.githubusercontent.com/17055027/195725043-f542b4c3-510f-45d0-98ae-7d56207ad689.png)

If i open some of the `gtk.css` files i only get this line, wtf...

I want to modify some things, how can i do it????

**Comment by vinceliuice** [comment]
This is gtk3 source file: https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/sass/gtk/_common-3.0.scss

**Comment by vinceliuice** [comment]
Edit it, then run: ./install.sh to install it
