### ISSUE TITLE
Theme not supporting libadwaita apps  

### ISSUE THREAD

**Issue by terminator-AK** [vinceliuice/WhiteSur-gtk-theme#705]
system info:
OS - ubuntu 22.10 (kinetic Kudu)
Gnome version - 43

Issue :
Theme title buttons are not working on libadwaita apps 

![image](https://user-images.githubusercontent.com/95540104/196480828-04c0c706-329e-4056-aef4-b9e141cc2275.png)

**Comment by vinceliuice** [comment]
Run ./install.sh -l

**Comment by terminator-AK** [comment]
When installing theme with administrative privileges (using sudo) , scripts didn't copy gtk-4.0 files to <home dir>/.config/gtk-4.0 folder

without 'sudo' it works

**Comment by vinceliuice** [comment]
Don't run -l with sudo, -l option is just link gtk-4.0 to $HOME/.config/gtk-4.0, if you run with sudo it'll links to root/.config/gtk-4.0
