### ISSUE TITLE
Nautilus and others apps not follow the theme

### ISSUE THREAD

**Issue by Razorhunter** [vinceliuice/WhiteSur-gtk-theme#706]
Nautilus, calculator, calendar (maybe some others app) not follow shell theme. And also It would be nice if the gap betweek tray icon not so wide

My system as follow
Ubuntu 22.10
Gnome 43.0

![Screenshot from 2022-10-21 15-14-33](https://user-images.githubusercontent.com/17735558/197136275-0f06d4a5-e8e4-4557-8aad-292228721ac7.png)

**Comment by vinceliuice** [comment]
Run: ./install.sh -l

**Comment by vinceliuice** [comment]
or ./install.sh --libadwaita

**Comment by vinceliuice** [comment]
Run `./install.sh --libadwaita -c Dark`  to install dark one
