### ISSUE TITLE
Ubuntu 22.10 System Menu Styling

### ISSUE THREAD

**Issue by johndzxu** [vinceliuice/WhiteSur-gtk-theme#707]
Just upgraded to Ubuntu 22.10 with GNOME 43, and the styling of the new system menu is not consistent with the theme (transparency, button color etc.).

![Screenshot from 2022-10-21 16-24-46](https://user-images.githubusercontent.com/77399093/197150319-02bb8116-12bd-4f5b-86f5-4127912bbcac.png)
![Screenshot from 2022-10-21 16-53-46](https://user-images.githubusercontent.com/77399093/197155746-6a0fdb3c-eefa-46cd-8d15-f522704bf2ca.png)

**Comment by FaboThePlayer** [comment]
Have you repaired it yet?

**Comment by johndzxu** [comment]
Yes. It's fixed after I reinstalled the theme.

**Comment by FaboThePlayer** [comment]
Thanks for responding.
