### ISSUE TITLE
Remvoal of Apple logo

### ISSUE THREAD

**Issue by pathakcodes** [vinceliuice/WhiteSur-gtk-theme#71]
Hi, I like the theme very much, but I don't want that Apple logo on the top bar (left most). Is there a way to 

1. Completely remove it.
2. Change it with the Ubuntu logo

This will make it look like a theme having its own identity

**Comment by vinceliuice** [comment]
./install.sh -i ubuntu

**Comment by collins-okafor** [comment]
Hi were you able to remove the logo?
I want to remove mine

**Comment by G-alexis-Fr** [comment]
If you already installed the theme, then go to the folder 'WhiteSur-gtk-theme' and inside open a terminal window.

Type the command that @vinceliuice gave :
`./install.sh -i ubuntu`

Then you should see your logo changing right away to the ubuntu one.

**Comment by A7Lavinraj** [comment]
after running command ./install.sh -i ubuntu the icon changes to linux icon not to ubuntu!!.
help me to change it to ubuntu

**Comment by G-alexis-Fr** [comment]
> after running command ./install.sh -i ubuntu the icon changes to linux icon not to ubuntu!!. help me to change it to ubuntu

Hmm not sure what logo you are expecting, I got the Ubuntu one like that one : [Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo-ubuntu_cof-orange-hex.svg/1200px-Logo-ubuntu_cof-orange-hex.svg.png)

Look at the doc :
` -i, --icon [standard|simple|gnome|ubuntu|tux|arch|manjaro|fedora|debian|void|opensuse|popos|mxlinux|zorin]
 Set 'WhiteSur' GDM (GNOME Shell) 'Activities' icon. Default is 'standard'`

**Comment by Matthew42x** [comment]
1. Download ubuntu svg logo from site (i believe there is one on the net)i found my debian .svg logo
2. Go to .themes/theme that you use/gnome shell folder/Assets folder and open apple logo(it is called activities.svg)
![Screenshot from 2023-08-05 15-32-41](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/141430371/7843e0a1-f733-4864-8db4-67181b5f6009)
(first on top left corner you will se 2 apple logos..you open left one in inkscape
3. Delete apple logo in inkscape and open your ubuntu logo (make sure the color is white if you use dark theme..or you can use some color if you dont like white
4. Just save the file and it should replace your apple logo instantly with desired logo

**Comment by smileBeda** [comment]
> 1. Download ubuntu svg logo from site (i believe there is one on the net)i found my debian .svg logo
> 2. Go to .themes/theme that you use/gnome shell folder/Assets folder and open apple logo(it is called activities.svg)
>    ![Screenshot from 2023-08-05 15-32-41](https://user-images.githubusercontent.com/141430371/258587456-7843e0a1-f733-4864-8db4-67181b5f6009.png)
>    (first on top left corner you will se 2 apple logos..you open left one in inkscape
> 3. Delete apple logo in inkscape and open your ubuntu logo (make sure the color is white if you use dark theme..or you can use some color if you dont like white
> 4. Just save the file and it should replace your apple logo instantly with desired logo

The only that works, even if it is a hack.

**Comment by AnikAdhikari7** [comment]
how can i remove the logo completely and instead of that want to use the gnome default workspace indicator?

**Comment by scurvydog** [comment]
I too would like the default gnome workspace indicator!

**Comment by jothi-prasath** [comment]
+1

**Comment by Udhay707** [comment]
Replace activities.svg and activities-white.svg present inside the selected theme with ubuntu svg


Attached screenshot for reference:

![Image](https://github.com/user-attachments/assets/0d240848-7a76-493b-b1e9-4d04e9ad38aa)

Note: I got my ubuntu.svg from [here](https://www.svgrepo.com/svg/25424/ubuntu-logo) and after making the lines to white

**Comment by psspsss** [comment]
> how can i remove the logo completely and instead of that want to use the gnome default workspace indicator?

not sure if this helps now, but what i did was remove the image src (the apple logo file is called activities.svg )link from the gnome-shell css file and it worked.
