### ISSUE TITLE
Telegram not allowed theme

### ISSUE THREAD

**Issue by ochornolutskyi** [vinceliuice/WhiteSur-gtk-theme#714]
Hello everyone. Today I installed your great theme, but the telegram app (installed by apt) does not support styles

telegram-desktop v4.2.4
ubuntu v22.04

Screenshot
![image](https://user-images.githubusercontent.com/46054029/198108245-c8ae158b-2fc3-4621-b176-1ca1851910ca.png)

**Comment by vinceliuice** [comment]
It not gtk app, can not be themed

**Comment by ochornolutskyi** [comment]
@vinceliuice ok, thanks. I don't remember how I installed the telegram app on another laptop with ubuntu 20.04 but it did have the custom xorg theme
