### ISSUE TITLE
oparetion failed

### ISSUE THREAD

**Issue by saeidex** [vinceliuice/WhiteSur-gtk-theme#715]
![image](https://user-images.githubusercontent.com/112776380/198285366-1aed77f5-9779-479a-876a-902dca921e7d.png)

**Comment by saeidex** [comment]
ok....
problem solved

**Comment by saeidex** [comment]
thanks
Please add (icons, toolbar_icons) on firefox/monterey.

**Comment by vinceliuice** [comment]
Run ./tweaks.sh -f to install firefox theme

**Comment by saeidex** [comment]
It was not working, that's why I installed it manually using userChrome.css
Thanks for your kind information.
