### ISSUE TITLE
Whitesur installer or tweaks is already running

### ISSUE THREAD

**Issue by ViniScardoso** [vinceliuice/WhiteSur-gtk-theme#718]
I'm on Ubuntu 22.04 and I was trying to install the firefox theme but it was not working. After some tries, when I tried to run the tweaks or install script, it showed me this message even though there is no process running.

![Screenshot from 2022-11-03 00-13-17](https://user-images.githubusercontent.com/99812824/199641149-cb06ba27-fbc8-48e9-8446-8d0ca1bb2be2.png)

**Comment by vinceliuice** [comment]
run: `rm -rf /tmp/WhiteSur.lock` then install it

**Comment by ViniScardoso** [comment]
It worked! Thanks
