### ISSUE TITLE
How can i edit this theme ?

### ISSUE THREAD

**Issue by dotsinspace** [vinceliuice/WhiteSur-gtk-theme#721]
I know that i need to edit gnome-shell.css but its too unriable and i need to create custom theme for my self. is there any tool which you have used ?. Please let me know Thanks

OOmax is bad

And is there any way to apply it too whole system...some apps still using Awainta..

Sorry for spellings

**Comment by vinceliuice** [comment]
Run `./install.sh -l`

**Comment by dotsinspace** [comment]
Can you tell me how you made it.? because I want to change the core colors of this theme not the accent color.Basically, i want create my own theme like yours
