### ISSUE TITLE
Option to tweak About Logo

### ISSUE THREAD

**Issue by Hyphaed** [vinceliuice/WhiteSur-gtk-theme#722]
Could you add an option to tweak about option?

from Distro logos to custom logo (like on wallpaper option)

![Screenshot from 2022-11-07 13-09-07](https://user-images.githubusercontent.com/19622367/200307113-98d64e80-549f-417b-9cf7-1de020382ef4.png)

**Comment by vinceliuice** [comment]
This can not set by theme
