### ISSUE TITLE
Search bar in nautilus overflowing on the sidebar

### ISSUE THREAD

**Issue by XubineX** [vinceliuice/WhiteSur-gtk-theme#723]
![image](https://user-images.githubusercontent.com/25012611/201194758-42a457fa-0aa2-4254-b156-17571beebc89.png)
I'm on linux mint cinnamon. It feels like the width on the search bar is set too big :)

**Comment by vinceliuice** [comment]
What's your nautilus version or system version?

**Comment by vinceliuice** [comment]
Fixed!

**Comment by XubineX** [comment]
Awesome! I’ll try it out when I have time. Sorry I didn’t reply to your question but I can’t get to my PC
