### ISSUE TITLE
Installation bug 

### ISSUE THREAD

**Issue by morshedulmunna** [vinceliuice/WhiteSur-gtk-theme#727]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: The repository 'cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 131;137
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2022-11-12T09:23:45+0600

  HINT: You can run: 'sudo apt install sassc libglib2.0-dev libxml2-utils' on ubuntu 18.04 or 'sudo apt install sassc libglib2.0-dev-bin' on ubuntu >= 20.04

**Comment by vinceliuice** [comment]
Disable this repository `'cdrom://Ubuntu 22.04.1 LTS Jammy Jellyfish - Release amd64 (20220809.1) jammy Release'`

**Comment by Rishix401** [comment]
> 

not working 

when i try to install it by using -

./install.sh

or

sudo ./install.sh

i also removed the repo as u said and tried many solution but it didn't work and gives error like -

  

  Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> Error: Undefined variable: "$base".
  >>>         on line 248:23 of src/sass/gtk/apps/_misc.scss
  >>>         from line 26:9 of src/sass/gtk/_apps-3.0.scss
  >>>         from line 7:9 of src/main/gtk-3.0/gtk-Dark.scss
  >>> >>     background-color: $base;
  >>> 
  >>>    ----------------------^
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> sassc ${SASSC_OPT} "${THEME_SRC_DIR}/main/gtk-3.0/gtk${color}.scss" "${TMP_DIR_T}/gtk.css"
  TRACE  :
    >>> signal_error
    >>> install_theemy
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2022-11-12T21:04:05+0530

**Comment by morshedulmunna** [comment]
I also got the same issue.

**Comment by vinceliuice** [comment]
Install the last update, this is fixed

**Comment by Rishix401** [comment]
> Install the last update, this is fixed

ya, Thnx
