### ISSUE TITLE
gtk4 apps styling is not work

### ISSUE THREAD

**Issue by gaou-piou** [vinceliuice/WhiteSur-gtk-theme#728]
i am from archlinux
gnome-shell 43.1
mutter 43.1

![screenshot](https://i.ibb.co/FBg4Rn5/Screenshot-from-2022-11-12-11-14-59.png "screenshot")

i have already linked everything from gtk-4.0 folder to ~/.config/gtk-4.0

**Comment by vinceliuice** [comment]
Run `./install.sh -l --nord -c dark`

**Comment by gaou-piou** [comment]
No. Exactly the same

**Comment by gaou-piou** [comment]
exporting GTK_THEME with the theme name on etc/environment works.
