### ISSUE TITLE
gnome-tweaks title bar displays wrong in gnome 3.38.1

### ISSUE THREAD

**Issue by suiahae** [vinceliuice/WhiteSur-gtk-theme#73]
As shown below

GIF：

![output](https://user-images.githubusercontent.com/45323123/100432398-86efe200-30d4-11eb-9d43-2d63713e3afa.gif)

Storyboard：

![image](https://user-images.githubusercontent.com/45323123/100432814-172e2700-30d5-11eb-9c23-562197ea5f17.png)

![image](https://user-images.githubusercontent.com/45323123/100432851-26ad7000-30d5-11eb-8c5f-a57867b08b48.png)

![image](https://user-images.githubusercontent.com/45323123/100432880-31680500-30d5-11eb-9e69-5edd47bae2ff.png)

![image](https://user-images.githubusercontent.com/45323123/100432912-3b8a0380-30d5-11eb-9887-8c95bf0ef6a7.png)

**Comment by Alyetama** [comment]
I have the same issue.

![](https://i.imgur.com/hokpoaD.png)

**Comment by vinceliuice** [comment]
App bug, not a theme issue

**Comment by jindradev** [comment]
Affirmative, experiencing since GNOME 3.36. Reinstall with reboot inbetween didn't help. However works correctly on newer installation of Manjaro GNOME (iso from around june 2020 i think)

**Comment by Alyetama** [comment]
Indeed, it seems like a gnome-tweaks issue rather than theme issue.  That being said, I found a workaround for it.
open `/usr/lib/python3/site-packages/gtweak/tweakview.py` and find the following line: `self.listbox.set_size_request(200, -1)`.
Replace 200 with 300 or any other greater value suitable for you.

**Comment by suiahae** [comment]
> Indeed, it seems like a gnome-tweaks issue rather than theme issue. That being said, I found a workaround for it.
> open `/usr/lib/python3/site-packages/gtweak/tweakview.py` and find the following line: `self.listbox.set_size_request(200, -1)`.
> Replace 200 with 300 or any other greater value suitable for you.

This is useful. but there is something I need show, 

1. the path is `/usr/lib/python3.9/site-packages/gtweak/tweakview.py` in fedora 33. 

2. after replacing 200 with 300, the "title bar is transparent" phenomenon that appeared when the program was opened disappeared. But when the window size is reduced, there is a problem that the upper right or upper left corner cannot be rounded. like this:

![image](https://user-images.githubusercontent.com/45323123/101844691-00350d80-3b88-11eb-8b27-eb96209469ef.png)

![image](https://user-images.githubusercontent.com/45323123/101844719-0cb96600-3b88-11eb-80a0-a96520d5fc7e.png)

**Comment by Alyetama** [comment]
Try increasing the value a bit and see if that fixes it.
