### ISSUE TITLE
Nautilus does not get reverted on uninstall

### ISSUE THREAD

**Issue by freebirb** [vinceliuice/WhiteSur-gtk-theme#735]
I just wanted to uninstall the theme, so I used the provided `./install.sh -r` function.

While the gnome-shell itself got removed, nautilus is still modified. How to remove this fruity 🍏 look?

As can be seen in my screenshot, the files got deleted out of  `~/.themes`.

![image](https://user-images.githubusercontent.com/55001076/202729243-53276a47-ee94-4992-8f6a-dcbbd2a8154e.png)

**Comment by ariaradick** [comment]
Try to run `./install.sh -r -l` to remove the libadwaita component.

**Comment by freebirb** [comment]
Thanks.
