### ISSUE TITLE
icon to show/hide password on gdm login screen not displayed

### ISSUE THREAD

**Issue by cedjo** [vinceliuice/WhiteSur-gtk-theme#74]
icon to display/hide password on gdm login screen is not found during first logon.
after logon it is displayed correctly on lock screen.
fedora 33 / gnome 3.38.1

**Comment by psychaos999** [comment]
Have the same problem, fedora 33 too

**Comment by vinceliuice** [comment]
I don't know how to fix it yet

**Comment by psychaos999** [comment]
nana4  do it right in his gdm theme from material (you share a very similar installer btw). Can't you give a peek on how he does that?
https://github.com/nana-4/materia-theme

**Comment by vinceliuice** [comment]
Thanks for this, I'll check his code to find a solution

**Comment by vinceliuice** [comment]
Fixed!
