### ISSUE TITLE
install sh error on ubuntu 22.04 even with sudo!

### ISSUE THREAD

**Issue by dani814** [vinceliuice/WhiteSur-gtk-theme#742]
=========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 131;137
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2022-11-19T19:35:36+0400

**Comment by dani814** [comment]
what should i do?

**Comment by vinceliuice** [comment]
Is that can not run success: `sudo apt update -y` ?

**Comment by dani814** [comment]
i found out what to do thank you!

**Comment by dani814** [comment]
your bigsur theme is great also!
