### ISSUE TITLE
can i change the dock to mac theme as well?

### ISSUE THREAD

**Issue by jacobsayono** [vinceliuice/WhiteSur-gtk-theme#743]
hi! i love your work, i successfully installed the themes, icons, and wallpapers.
am i able to change the dock theme as well? thanks!

**Comment by vinceliuice** [comment]
https://extensions.gnome.org/extension/307/dash-to-dock

**Comment by jacobsayono** [comment]
figured it out! also there was an issue where the dock exists both on the left and bottom but i purged the extension to fix the bug.
