### ISSUE TITLE
No update to file name while renaming files

### ISSUE THREAD

**Issue by isakhauge** [vinceliuice/WhiteSur-gtk-theme#75]
When renaming a file, the new filename is overlapping the old one when typing. There is no update to the text field while typing the new filename. See GIF below for reference.
![Demo](https://i.ibb.co/cXs6C3G/renaming.gif)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by isakhauge** [comment]
Now it works!! 🎉️ Thanks!
