### ISSUE TITLE
sudo ./tweaks.sh -s Oops! Operation failed

### ISSUE THREAD

**Issue by yuguoho** [vinceliuice/WhiteSur-gtk-theme#754]
=========== ERROR LOG ===========
  >>> 错误：没有找到 snap "whitesur-gtk-theme"
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-install.sh at 795
    >>> tweaks.sh
  SNIPPET:
    >>> snap install whitesur-gtk-theme
  TRACE  :
    >>> signal_error
    >>> connect_snap
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2022-12-06T14:46:04+0800

**Comment by vinceliuice** [comment]
Not support snap now
