### ISSUE TITLE
Panel text color is white and I want it black using WhiteSur Light

### ISSUE THREAD

**Issue by citbr** [vinceliuice/WhiteSur-gtk-theme#76]
I do not want a dark theme, so I am using WhiteSur Light, but I also would like two things which seem to be mutually exclusive: A transparent panel, and black text (not white!)  If you could please tell me how to accomplish this I would very much appreciate it.  The non-transparent (solid) versions seem to have no problem showing black text but the transparent ones do and I don't know how to fix that. The white text is really hard to read unless you use a dark background which again is not what I want.  Thank you for any suggestions you might be able to offer!

**Comment by vinceliuice** [comment]
WhiteSur-alt is black version

**Comment by citbr** [comment]
> WhiteSur-alt is black version

Not in the latest Linux Mint, the text still is white!

**Comment by vinceliuice** [comment]
I'll fix that
