### ISSUE TITLE
can someone tell why the close minimize maximize buttons didn't change

### ISSUE THREAD

**Issue by jxxt** [vinceliuice/WhiteSur-gtk-theme#761]
version: OS: Xubuntu 22.04.1 LTS x86_64 

what am I doing wrong please tell

![image](https://user-images.githubusercontent.com/63486706/208172330-d99d3515-4faf-4cbf-908a-49be42c4aa72.png)

**Comment by Irevirt** [comment]
Did you switch your gtk theme after installing it? Haven't used xfce or xubuntu in a while, but I think you can do that by going in the xfce setting manager --> Style --> and then you select the WhiteSur theme.

**Comment by jxxt** [comment]
yeah, I did change the theme.....everything changed according to the theme but just those buttons didn't change don't know why :(

**Comment by vinceliuice** [comment]
You should open `xfwm4-settings` to change the wm theme

**Comment by AlexZeitler** [comment]
@vinceliuice Thanks, this did the trick for me on Xubuntu 22.04
