### ISSUE TITLE
Uneaven gap to top bar

### ISSUE THREAD

**Issue by CuriousApe2020** [vinceliuice/WhiteSur-gtk-theme#764]
Why is the gab between the top bar and the Date/Time Menu bigger, than the gab between the top bar and the Quick settings Menu aka Popovers/Menus?

Debian 12 Gnome
![Screenshot from 2022-12-20 21-25-53](https://user-images.githubusercontent.com/75225919/208762437-c62d3f41-9519-421e-b795-74e926676397.png)
![Screenshot from 2022-12-20 21-26-00](https://user-images.githubusercontent.com/75225919/208762457-cce4d6d3-8549-49d4-9477-2658234071f7.png)

**Comment by vinceliuice** [comment]
Fixed

**Comment by CuriousApe2020** [comment]
Where in the gnome-shell.css is the gap to the Time/Calendar menu set?

**Comment by vinceliuice** [comment]
There is no such set for Calendar popup only
