### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kingrojak** [vinceliuice/WhiteSur-gtk-theme#768]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> E: The repository 'cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;22.04
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2022-12-27T12:26:14+0800

  HINT: You can run: 'sudo apt install sassc libglib2.0-dev libxml2-utils' on ubuntu 18.04 or 'sudo apt install sassc libglib2.0-dev-bin' on ubuntu >= 20.04 

  HINT: You can google or report to us the info above 

  https://github.com/vinceliuice/WhiteSur-gtk-theme/issues

**Comment by vinceliuice** [comment]
Remove this: repository 'cdrom://Ubuntu 22.04.1 LTS Jammy Jellyfish - Release amd64 (20220809.1) jammy Release'

**Comment by kingrojak** [comment]
problem fix with this .sudo apt install sassc libglib2.0-dev libxml2-utils' on ubuntu 18.04 .. but am at 20.04 version?.. btw now have new prob... my gnome shell is 42.5.. how to update to 43?.. already try sudo apt full-upgrade

**Comment by vinceliuice** [comment]
If you want upgrade to 43 maybe you need change all 20.04 system repository to 20.10 verison

**Comment by kingrojak** [comment]
> If you want upgrade to 43 maybe you need change all 20.04 system repository to 20.10 verison

Tq for advice.. I made it
