### ISSUE TITLE
gnome-console wrong colors with darker theme variant

### ISSUE THREAD

**Issue by unlwly** [vinceliuice/WhiteSur-gtk-theme#779]
GNOME 43

gnome-console has the same background color as the rest of the theme when installed with `--darker`  
when it should be darker or maybe transparent, this isn't an issue with the normal dark variant

darker:
![Screenshot from 2023-01-15 16-13-47](https://user-images.githubusercontent.com/76652465/212549755-a7e9446a-5f13-4696-aa90-a42841d68f57.png)

normal dark:
![Screenshot from 2023-01-15 16-14-42](https://user-images.githubusercontent.com/76652465/212549757-cccf58fe-57c6-4a51-9d64-80724806dc29.png)

**Comment by vinceliuice** [comment]
Gnome-console use it's own background color, can not set by theme
