### ISSUE TITLE
菜单出现透明

### ISSUE THREAD

**Issue by 93Alliance** [vinceliuice/WhiteSur-gtk-theme#78]
![image](https://user-images.githubusercontent.com/33192459/100853237-7f5c7e80-34c2-11eb-83b0-a4c63d32cd49.png)

**Comment by 93Alliance** [comment]
下载的最新版本

**Comment by vinceliuice** [comment]
你重装一下试试，是不是背景图片丢失了，我在我的cinnamon上测试了没问题啊

**Comment by 93Alliance** [comment]
我重新下载安装还是一样的结果，就是菜单会透明，我没有卸载，是直接执行
```
sudo ./install.sh
```

**Comment by vinceliuice** [comment]
不用sudo呢，直接 ./install.sh

**Comment by 93Alliance** [comment]
我需不需要把之前的主题手动删除

**Comment by vinceliuice** [comment]
你可以检查一下安装之后的目录这些文件都在不？
![Screenshot from 2020-12-02 19-16-41](https://user-images.githubusercontent.com/7604295/100866000-0a457500-34d3-11eb-9f3f-2bda56ced505.png)

**Comment by vinceliuice** [comment]
~/WhiteSur-light/cinnamon/assets/

**Comment by 93Alliance** [comment]
我把 `/usr/share/themes` 目录下的主题删除了，然后执行 install.sh 这样是可以的，很奇怪，正常应该是一样的效果。

**Comment by vinceliuice** [comment]
可能是权限出问题了

**Comment by 93Alliance** [comment]
好的，谢谢

**Comment by vinceliuice** [comment]
不客气
