### ISSUE TITLE
System panel icons look large

### ISSUE THREAD

**Issue by cesaraquino** [vinceliuice/WhiteSur-gtk-theme#780]
Good evening, I have a problem with the icons in the notification panel. I installed the theme for GDM and the system panel icons were not showing. When I uninstalled the thema from the GDM the icons came back but became large (see attached image).

![Captura desde 2023-01-15 19-44-04](https://user-images.githubusercontent.com/4138916/212591000-c68f8911-ed76-444d-a69c-424c9b9ca2b4.png)

How can I fix this? I am using Fedora 37 with Gnome 43.2.

Thanks for your help. Regards.

**Comment by vinceliuice** [comment]
You theme looks not like whitesur

**Comment by vinceliuice** [comment]
![截图 2023-01-16 12-24-47](https://user-images.githubusercontent.com/7604295/212598487-dea13dff-0343-4462-8c78-0576bcabdc4d.png)

**Comment by vinceliuice** [comment]
If the GDM theme cause this, I suggest you uninstall it: `sudo ./tweaks.sh -g -r`

**Comment by cesaraquino** [comment]
> If the GDM theme cause this, I suggest you uninstall it: `sudo ./tweaks.sh -g -r`

Hi vinceliuice! I had whitesur installed, including the GDM theme, but when I installed the GDM theme the icons in the system panel were not showing and I uninstalled it. After uninstalling the GDM theme with the command you posted, the icons remained large.

**Comment by vinceliuice** [comment]
Before you uninstall the GDM theme did you upgrade your desktop?

**Comment by vinceliuice** [comment]
Try reinstall `gnome-shell`

**Comment by cesaraquino** [comment]
> Try reinstall `gnome-shell`

Hi @vinceliuice 

I tried to uninstall gnome-shell but it returns the following error message:

> Problema: The operation would result in removing the following protected packages: gnome-shell
(try to add '--skip-broken' to skip uninstallable packages)

Adding --skip-broken doesn't work either.

I installed the Whitesur theme again, but the icons in the system panel still look big.

**Comment by vinceliuice** [comment]
Do not need uninstall it, just run: `sudo dnf reinstall gnome-shell`

**Comment by cesaraquino** [comment]
> Do not need uninstall it, just run: `sudo dnf reinstall gnome-shell`

Hi @vinceliuice, it was fixed with the command you posted. Apparently, the problem is caused by a conflict with the DASH TO PANEL extension I use on my desktop. Thanks for your help. Have a nice day.

**Comment by vinceliuice** [comment]
You are welcome
