### ISSUE TITLE
Change maximize, minimize and close button's size & style.

### ISSUE THREAD

**Issue by ruZeph** [vinceliuice/WhiteSur-gtk-theme#783]
How can I change maximize, minimize & close button's size ? Here's the default:

![Screenshot from 2023-01-22 23-42-13](https://user-images.githubusercontent.com/92640971/213932764-32d07721-0ae0-4177-818c-af5f494f95f4.png)

And can I change their style ? If yes, then how?

**Comment by l3ifk** [comment]
Did you find a solution?

**Comment by ruZeph** [comment]
> Did you find a solution?

No man. That's why I left it still open.
