### ISSUE TITLE
Buttons size for toolbaritems combined not match other navbar buttons

### ISSUE THREAD

**Issue by fragrusti** [vinceliuice/WhiteSur-gtk-theme#789]
Hi all, 

thank you for your great work. I am using Firefox Nightly on Mac OSX Monterey 12.5.1 M1. 

I had to change height and size of Combined buttons as follow, otherwise there was toomuch space as soon as I was pinning to the bar some extensions buttons:

/* Combined buttons */
#nav-bar .toolbaritem-combined-buttons toolbarbutton:not(:last-of-type):not(#hack),
/*#nav-bar #back-button:not(#hack),*/
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not(:last-of-type):not(#appMenu-zoomEnlarge-button),
#context-navigation menuitem:not(:last-of-type),
.findbar-container toolbarbutton.findbar-find-previous,
.findbar-button:not(:last-of-type) {
        max-height: 28px !important;
        min-height: 28px !important;
        /*border-top-right-radius: 0 !important;
        border-bottom-right-radius: 0 !important;
        border-right-width: 0 !important;*/
        margin-right: 0 !important;
        padding: 0 4px !important;
        min-widht: 20px !important;
}

I hope this will not broke anything elsewhere. 

Please let me know.

Just my two cents.

Ciao,
F

**Comment by vinceliuice** [comment]
Try the last update this should be fixed

**Comment by fragrusti** [comment]
Great, thank you - I just cloned the repo and it works flawlessly.
