### ISSUE TITLE
[Feat Req] Dynamic Panel Text Color

### ISSUE THREAD

**Issue by rainbowflesh** [vinceliuice/WhiteSur-gtk-theme#802]
Some time font color invisible from wallpaper.

Is it possible to add `mix-blend-mode: difference` to panel font color?

![Screenshot from 2023-02-09 14-04-38](https://user-images.githubusercontent.com/20819692/217732254-9cd156e5-7d15-4bc0-99eb-4e3bc2f248c0.png)
![Screenshot from 2023-02-09 14-05-50](https://user-images.githubusercontent.com/20819692/217732275-c40a1e7e-943f-4866-a791-1bc0b283fea4.png)
![Screenshot from 2023-02-09 14-06-27](https://user-images.githubusercontent.com/20819692/217732280-5641f4d6-d170-4efe-a1d9-eb37bbb4802c.png)

**Comment by vinceliuice** [comment]
mix-blend-mode: difference 是个啥？ gnome-shell应该不支持

**Comment by vinceliuice** [comment]
Gnome-shell的主题只是单纯的css代码，这些应该不支持
