### ISSUE TITLE
Firefox Traffic Light buttons without full Safari themes?

### ISSUE THREAD

**Issue by randomfun32123** [vinceliuice/WhiteSur-gtk-theme#803]
Hello, I really enjoy these themes for Gnome and GTK. I use Firefox as my main browser, and I don't like Safari, but I want the Traffic Light buttons on Firefox to match the rest of the theming, is there anyway to get the button theming without the rest?

Thank you.

**Comment by vinceliuice** [comment]
Change the firefox customize setting to use system theme, then use a mac theme as gtk theme, firefox will use mac theme's windows button style

**Comment by vinceliuice** [comment]
![Screenshot_20230211_194741](https://user-images.githubusercontent.com/7604295/218256404-e08401d4-0aa3-4496-8dd3-542da5757db9.png)

**Comment by randomfun32123** [comment]
Thank you! that worked.
