### ISSUE TITLE
Theme and the topbar icons are not applied to the Files

### ISSUE THREAD

**Issue by VOIDSORROW** [vinceliuice/WhiteSur-gtk-theme#806]
![Screenshot from 2023-02-14 00-24-17](https://user-images.githubusercontent.com/95509860/218549515-b7268a75-f484-4b4a-9fc3-6b5cc8733f53.png)

**Comment by Cm4nXD** [comment]
What distro version are you using? This looks like it is potentially an issue with libadwaitia. Make sure to use the -l option when installing to force libadwatia applications to use theme.

ex:
`./install -l`

**Comment by VOIDSORROW** [comment]
Thanks for the reply and I been using this 22.10 Kinetic and recently upgraded to 23 Lunatic lobster And it's awesome in Gnome 43.2 and I should try the suggested command type. Thank you

**Comment by VOIDSORROW** [comment]
The command solved my issue Thanks for that and its awesome.
And I'm using it on Lunatic Lobster (Ubuntu 23)
![Screenshot from 2023-02-14 10-04-36](https://user-images.githubusercontent.com/95509860/218640504-601916ea-e590-4764-b2c3-ba6a78f82c4a.png)
