### ISSUE TITLE
Incompatable with Gtk4 Desktop Icons NG Gnome Extension

### ISSUE THREAD

**Issue by Cm4nXD** [vinceliuice/WhiteSur-gtk-theme#807]
Ubuntu 22.10 - Gnome 43

When using this theme for whatever reason the desktop wallpaper is obstructed. According to the developer of the extension, this is because of css being overwritten by a theme.

Extension Website:
https://gitlab.com/smedius/desktop-icons-ng

Without theme installed:
![Screenshot from 2023-02-13 22-01-36](https://user-images.githubusercontent.com/92384511/218631687-2047f303-e906-4085-8d83-ddcfd87302ee.png)

With Theme installed:

![Screenshot from 2023-02-13 22-24-07](https://user-images.githubusercontent.com/92384511/218631649-66cdb917-7cf3-4aa6-9741-e6f6f2afb0f5.png)

**Comment by vinceliuice** [comment]
Did you installed this theme from github last update?

**Comment by Cm4nXD** [comment]
I made sure to recline the git repository and attempting to use the latest version right before I reported the bug. So yes, unless there has been an update in the past 12 hours?

**Comment by vinceliuice** [comment]
You must installed libadwaita themes, because this extension use gtk themes as desktop stylesheet, but if ~/.config/gtk-4.0/gtk.css have custom codes, it'll override extension's stylesheet, then it'll show nautilus window background color, so you need add this: 
```
#desktopwindow.background {
    background-color: transparent;
    background-image: none;
}
```
into `~/.config/gtk-4.0/gtk.css`

**Comment by vinceliuice** [comment]
After added it, just relogin your desktop then it'll be fixed
![Screenshot_20230211_194741](https://user-images.githubusercontent.com/7604295/218788719-daeed8e3-5219-4e0a-afd3-57adc2e20107.png)

**Comment by vinceliuice** [comment]
This is not a gnome-shell theme issue, kind of gtk-4.0 issue, I'll add this into gtk-4.0 part, then just download the last update then run ./install.sh -l then it should be fixed

**Comment by vinceliuice** [comment]
And I think maybe you could report this to https://gitlab.com/smedius/desktop-icons-ng, smedius maybe have better solutions for this
