### ISSUE TITLE
Removal of that Apple logo in the corner

### ISSUE THREAD

**Issue by mohammad-zadeed** [vinceliuice/WhiteSur-gtk-theme#809]
hi, i installed this themes from "gnome look"  . So , how can i remove that apple logo from that corner ? or how to replace that with zorin os logo?

**Comment by vinceliuice** [comment]
Run: `./install.sh --icon zorin`

**Comment by smileBeda** [comment]
> Run: `./install.sh --icon zorin`

The problem is it does not do what it says :)
Somehow the apple is stuck hard there, for many.
