### ISSUE TITLE
WhiteSur-alt still has white text in Linux Mint

### ISSUE THREAD

**Issue by citbr** [vinceliuice/WhiteSur-gtk-theme#81]
Before closing my issue #76 yesterday you said that WhiteSur-alt has black text, but that is not the case in the latest version of Linux Mint.  The text is still white.  The effect I am really trying to achieve is shown in the bar at the top of the page in this screenshot:

https://sm.pcmag.com/pcmag_in/photo/8/86-32/86-32_12xa.png

Notice it is black text on a white translucent background but the brightness is to some small degree affected by the image underneath (where the sky is darker the bar is darker and vice versa, also the color of the bar is influenced by the image underneath, so it tends to take on a more purple hue where the sky underneath is more purple).  However if your WhiteSur-alt theme really displayed text as black rather than white, that would be close enough.

**Comment by vinceliuice** [comment]
This is bigsur like theme, if you want catalina style panels you can use mojave theme
