### ISSUE TITLE
I have been trying to uninstall the theme but still this logo and the transparent bar haven't came back to default.  

### ISSUE THREAD

**Issue by YaxPrajapti** [vinceliuice/WhiteSur-gtk-theme#813]
![image](https://user-images.githubusercontent.com/92200237/221571451-413c4389-e5ff-4e75-bed8-224ddc3671e2.png)
![image](https://user-images.githubusercontent.com/92200237/221571508-91426802-b268-4ab5-b119-b7698639bc83.png)

**Comment by vinceliuice** [comment]
There is a notice in the shell: if you installed GDM theme then you need run: `sudo ./install.sh -r -g` to remove GDM theme

**Comment by vinceliuice** [comment]
It's `sudo ./tweaks.sh -r -g`
