### ISSUE TITLE
Operation failed (Fedora 37)

### ISSUE THREAD

**Issue by tdttvd** [vinceliuice/WhiteSur-gtk-theme#817]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> Error spawning command line “dbus-launch --autolaunch=88e13c0d559647f5b1e581d68c210aad --binary-syntax --close-stderr”: Child process exited with code 1
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh at 204
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> notify-send "'${name}' theme has been installed. Enjoy!" "${notif_msg}" -i "dialog-information-symbolic"
  TRACE  :
    >>> signal_error
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : workstation;platform:f37;fedora;37
  SUDO   : no
  GNOME  : 42-0
  REPO   : 2023-03-04T15:56:24+0700

**Comment by hunabku94** [comment]
Same in Archlinux
