### ISSUE TITLE
Is it possible to change the size of the top bar in Gnome

### ISSUE THREAD

**Issue by Panja0** [vinceliuice/WhiteSur-gtk-theme#819]
Is it possible to change the size of the top bar, the one with the time/date and connectivity?

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/8d1a8aaddc465d29622dc50fe6b5d93b5f516d30/src/sass/gnome-shell/common/_panel.scss#L4

**Comment by vinceliuice** [comment]
Option:
```
  -P, --panel-size [default|smaller|bigger]
 Set Gnome shell panel height size. Default is 32px
```

**Comment by Panja0** [comment]
Many thanks for the replies!

I did try to change the panel size with the -P parameter and giving the option bigger.
But it did not work. Now that I think of it I maybe did that with sudo ./tweaks.sh instead of install.sh
Will give it another try and otherwise edit the css file.

**Comment by Panja0** [comment]
I can confirm (checked shell history) I used sudo ./tweaks.sh -P bigger instead of ./install.sh
