### ISSUE TITLE
Gap between dock and edge of screen

### ISSUE THREAD

**Issue by devklick** [vinceliuice/WhiteSur-gtk-theme#826]
I'm finding that my dock has a small gap between the bottom of the dock and the bottom of the screen. This means that when your cursor as at the bottom of the screen, you cannot click any of the icons on the dock. You need to apply pressure at the bottom of the screen to show the dock, the come up a few pixels to click on an icon.
![image](https://user-images.githubusercontent.com/58235000/227068670-68fe5e2e-02bd-45a3-b0a9-a98c325ae57f.png)

I'm not sure if this is intentional, a bug, or config issue. I expect the latter, but I havent been able to identify any config values that affect this. Changing Dash To Dock to use "Panel Mode" (Position and size > Dock Size Limit > Panel Mode) does fix this, but it completely changes the doc to a full-length panel - not what I'm looking for!
![image](https://user-images.githubusercontent.com/58235000/227070235-1a329258-c24e-4151-940f-e166af78d8c8.png)

<details>
<summary>System Info:</summary>

```
NAME="Zorin OS"
VERSION="16.2"
```

</details>

<details>
<summary>Installed extensions:</summary>

```
drive-menu@gnome-shell-extensions.gcampax.github.com
remove-dropdown-arrows@mpdeimos.com
user-theme@gnome-shell-extensions.gcampax.github.com
x11gestures@joseexposito.github.io
zorin-appindicator@zorinos.com
zorin-printers@zorinos.com
zorin-window-move-effect@zorinos.com
zorin-magic-lamp-effect@zorinos.com
color-picker@tuberry
tactile@lundal.io
dash-to-dock@micxgx.gmail.com
blur-my-shell@aunetx
unite@hardpixel.eu
```

</details>

**Comment by kb-ig** [comment]
I think it's supposed to be a floating rounded dock, but there does appear to be square shape behind it that makes it look a bit strange. 

![image](https://user-images.githubusercontent.com/91877080/227180736-88a95231-2eb8-46ee-8a35-4625f81f1003.png)

I'm not sure if the image in the main description was using the correct theme (it was me on another machine / account). The image in this comment deffo uses the correct theme, but still has the strange box behind the dock

**Comment by fr3nchalp4a** [comment]
This is actual wanted behavior. What you see behind (the black square) is the box containing the dock (the container). You probably have Blur my Shell blurring the background of the dock, but as this extension is not made for this theme, it doesn't blur the correct item. 
This theme is (a lot) inspired by MacOS design, so as MacOS dock is floating, the dock is actually floating. Personally, if the dock would be sticking to the border of the screen, I would find this terribly ugly as there's no margin between the screen and the dock.

The best solution to fix you issue would be to extend the clickable space of the icons to span to the border of the screen without sticking the dock to the border. This is not very easy, as there may be need of a rewrite of how Dash to Dock works.

**Comment by fr3nchalp4a** [comment]
And for the "not clickable" icons of the dock, I couldn't reproduce it, either on 1080p display nor 768p.
![image](https://user-images.githubusercontent.com/68474172/233160582-f18a1d52-3596-48b0-a6c1-074075d30f94.png)

I see you are using Zorin OS, but they kinda have an outdated Gnome, this *may* cause issues. What screen resolution are you running ?

**Comment by devklick** [comment]
@fr3nchalp4a You're absolutely right, this is an issue caused by Blur My Shell. Disabling that extension gives me a dock like in your screenshot, floating and rounded. Likewise, having it enabled but disbaling the dash blur gives me the same as your screenshot (although obviously not blurred). 

I get this same Blur My Shell issue on both a laptop with resolution 1920x1080, and a desktop with 3440x1440. Both machines run the same version of Zorin, so it could be the outdated Gnome version.

I see there's a [reddit post](https://www.reddit.com/r/gnome/comments/za212g/how_to_properly_make_blur_my_shell_work_with_dash/) about it where the developer of Blur My Shell makes a comment:
>You can't (like, really cannot in any way) have rounded corners with dash to Dock. I spent dozens of hours trying to do it, but this comes from a bug in gnome-shell, which prevents me from changing the shape of the blurred widget.

He goes on to suggest an alternative approach, but I cant get that to work.

The "not clickable" stuff I mentioned can be ignored. I see it's now by design. I like to have my dock hidden and only revealed with pressure, which means having to go to the edge of the screen until the dock shows, then having to move _away_ from the edge in order to click the icon. I'm not particularly fond of this and prefer the Plank dock, where you can click icons when your cursor is at the edge of the screen. This means you apply pressure to the edge of the screen to reveal the dock, then just move along the edge and click below the icon (or above, or left, or right, depending on where your dock is...).

I'll clock this now as it's obviously not an issue with this theme.
