### ISSUE TITLE
Error Operation failed

### ISSUE THREAD

**Issue by Anto426** [vinceliuice/WhiteSur-gtk-theme#827]
Oops! Operation failed...

  =========== ERROR LOG ===========
  
>>>>>>> No error log found <<<<<<
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-install.sh
    >>> tweaks.sh
  SNIPPET:
    >>> mv -n "${1}"{"",".bak"}
  TRACE  :
    >>> signal_error
    >>> backup_file
    >>> install_gdm_theme
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : rolling;arch
  SUDO   : yes
  GNOME  : 42-0
  REPO   : 2023-03-16T14:25:50+0100

**Comment by ysolis** [comment]
the solution is sugested in #834
