### ISSUE TITLE
Left corners square when side drawer menu is closed on GTK 

### ISSUE THREAD

**Issue by MKrabs** [vinceliuice/WhiteSur-gtk-theme#828]
Side drawer/menu open:
![image](https://user-images.githubusercontent.com/71791731/227629152-5cca252b-5d23-4e2c-9b8a-f9d2383b538e.png)

Side drawer closed: (open screenshot to have a white background to see the corner is there, with the main body overlapping)
![image](https://user-images.githubusercontent.com/71791731/227629280-23e52dd9-5cf9-4505-a12a-a4f2c20652b7.png)

**Comment by vinceliuice** [comment]
This can not be fixed, it's a app issue,
