### ISSUE TITLE
getting undefined in notification panel 

### ISSUE THREAD

**Issue by Tusharjagi** [vinceliuice/WhiteSur-gtk-theme#829]
![Screenshot from 2023-03-25 12-14-53](https://user-images.githubusercontent.com/12596457/227701972-cc650b0e-dcfb-47dc-ade6-baccbce6f4ee.png)
![Screenshot from 2023-03-25 12-24-05](https://user-images.githubusercontent.com/12596457/227701976-e245e4ca-ce10-496d-b1e7-e7384bb8d60d.png)

**Comment by vinceliuice** [comment]
This is not a theme issue

**Comment by vinceliuice** [comment]
I don't know what app send this message, maybe it's a issue about this app

**Comment by Tusharjagi** [comment]
okay i will see what's the issue  thankyou @vinceliuice

**Comment by fr3nchalp4a** [comment]
Are you using GSConnect ? @Tusharjagi 
GSConnect redirects notifications from your phone to your PC, so that could be a GSConnect / KDEConnect issue.

**Comment by Tusharjagi** [comment]
> Are you using GSConnect ? @Tusharjagi GSConnect redirects notifications from your phone to your PC, so that could be a GSConnect / KDEConnect issue. Also don't forget to close this issue !

yes I'm using GSConnect
