### ISSUE TITLE
Firefox Corner Radius

### ISSUE THREAD

**Issue by nullket** [vinceliuice/WhiteSur-gtk-theme#83]
Great Theme! 

I just want to slightly change the corner radius of **firefox** theme (less curvature). I thought it must be `border-radius` in one of the `.css` - but which one is the correct one? Thanks in advance!

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/15a07ecb178f3c4e229128b38b5bbc352eae3430/src/other/firefox/chrome/WhiteSur/parts/csd.css#L10
