### ISSUE TITLE
Strange bands in Nautilus

### ISSUE THREAD

**Issue by federicotorrielli** [vinceliuice/WhiteSur-gtk-theme#833]
Distro: Pop_OS 22.04
Theme: WhiteSur-Dark
Description: see video

https://user-images.githubusercontent.com/31370059/228764891-2ffcecf4-89c3-430f-bbb8-da80fcaee2b1.mp4

**Comment by federicotorrielli** [comment]
> Use the solid version

It's not really a bug fix... I want to use the normal version and not have the bands on Nautilus.

**Comment by vinceliuice** [comment]
This can not be fixed, not a theme issue, only nautilus (when background have opacity) have this issue on Nvidia display card
