### ISSUE TITLE
There was a bug when reinstalling GDM

### ISSUE THREAD

**Issue by fengzhenhua-vip** [vinceliuice/WhiteSur-gtk-theme#834]
I guess `mv -n` can be modified to `mv -f`, and after the modification I solved the problem.

**Comment by fengzhenhua-vip** [comment]
WhiteSur-gtk-theme/shell/lib-core.sh

**Comment by ysolis** [comment]
duplicate #827 (btw, the solution worked for me)

**Comment by vinceliuice** [comment]
But that will overwrite the existing file (system default one)

**Comment by fengzhenhua-vip** [comment]
If a person reinstalls GDM and indicates that the previous backup is useless, he needs to back up the current files. If you keep the original backup, you can use the name of the detection backup folder and then append a number to name it, so that you can keep backing up. However, doing so will result in more and more useless folders. Therefore, only backing up the last folder is a better solution.


发送自我的盖乐世



-------- 原始信息 --------
发件人： Vince ***@***.***>
日期: 2023/3/31 11:06 (GMT+08:00)
收件人： vinceliuice/WhiteSur-gtk-theme ***@***.***>
抄送： fengzhenhua ***@***.***>, Author ***@***.***>
主题： Re: [vinceliuice/WhiteSur-gtk-theme] There was a bug when reinstalling GDM (Issue #834)


But that will overwrite the existing file (system default one)

―

**Comment by fengzhenhua-vip** [comment]
I see what you mean, we need to save the original theme folder so that we can revert to the original theme after uninstalling gdm. That can name the original theme "theme.original", and then name the installed theme "theme.bak", which can accept the override.



发送自我的盖乐世



-------- 原始信息 --------
发件人： Vince ***@***.***>
日期: 2023/3/31 11:06 (GMT+08:00)
收件人： vinceliuice/WhiteSur-gtk-theme ***@***.***>
抄送： fengzhenhua ***@***.***>, Author ***@***.***>
主题： Re: [vinceliuice/WhiteSur-gtk-theme] There was a bug when reinstalling GDM (Issue #834)


But that will overwrite the existing file (system default one)

―

**Comment by fengzhenhua-vip** [comment]
I solved the problem:
According to the original command "backup_file" to rename the folder that has not installed the bigsur theme to "foobar.bak" with "mv -n", after running this command, the original "foobar" has disappeared, so if you only use the "mv -n" command when reinstalling, it does ensure that "foobar.bak" is not overwritten, but the previously installed folder "foobar" still exists. Therefore, when installing the software again, an error will be reported. The solution is to first detect whether "foobar.bak" exists, if it exists, it is the original theme folder, so you only need to execute the delete "foobar" command. If it does not exist, it is the first time to install the bigsur theme, rename it to "foobar.bak", so that every time you execute this command, you will get the same result, that is: create or retain "foobar.bak", but remove "foobar", problem solved. The code is as follows:
backup_file() {
   if [[ -e "${1}.bak" ]]; then
      sudo rm -rf  "${1}.bak"
   else
      if [[ -f "${1}" || -d "${1}" ]]; then
	 case "${2}" in
	    sudo)
	       sudo mv -n "${1}"{"",".bak"} ;;
	    udo)
	       udo mv -n "${1}"{"",".bak"} ;;
	    *)
	       mv -n "${1}"{"",".bak"} ;;
	 esac
      fi
   fi
}

**Comment by fengzhenhua-vip** [comment]
Modify the file "shell/lib-core.sh" 

backup_file() {
  if [[ -e "${1}.bak" ]]; then
      sudo rm -rf "${1}.bak"
  else
      if [[ -f "${1}" || -d "${1}" ]]; then
          case "${2}" in
              sudo)
                    sudo mv -n "${1}"{"",".bak"} ;;
              udo)
                    udo mv -n "${1}"{"",".bak"} ;;
             *)
                    mv -n "${1}"{"",".bak"} ;;
          esac
     fi
 fi
}

**Comment by fengzhenhua-vip** [comment]
I solved the problem:
According to the original command "backup_file" to rename the folder 
that has not installed the bigsur theme to "foobar.bak" with "mv -n", 
after running this command, the original "foobar" has disappeared, so if 
you only use the "mv -n" command when reinstalling, it does ensure that 
"foobar.bak" is not overwritten, but the previously installed folder 
"foobar" still exists. Therefore, when installing the software again, an 
error will be reported. The solution is to first detect whether 
"foobar.bak" exists, if it exists, it is the original theme folder, so 
you only need to execute the delete "foobar" command. If it does not 
exist, it is the first time to install the bigsur theme, rename it to 
"foobar.bak", so that every time you execute this command, you will get 
the same result, that is: create or retain "foobar.bak", but remove 
"foobar", problem solved. The code is as follows:

backup_file() {
     if [[ -e "${1}.bak" || -e "${1}" ]]; then
         sudo rm -rf "${1}"
     elif [[ -e "${1}" ]]; ##then
         if [[ -f "${1}" || -d "${1}" ]]; then
             case "${2}" in
                 sudo)
                     sudo mv -n "${1}"{"",".bak"} ;;
                 udo)
                     udo mv -n "${1}"{"",".bak"} ;;
                 *)
                     mv -n "${1}"{"",".bak"} ;;
             esac
         fi
     fi
}

fengzhenhua-vip reacted with laugh emoji

在 2023/3/31 11:24, feng zhenhua 写道:
