### ISSUE TITLE
tweaks is not working since last gnome update (arch)

### ISSUE THREAD

**Issue by bbrx94** [vinceliuice/WhiteSur-gtk-theme#835]
![image](https://user-images.githubusercontent.com/107874456/229092469-01b840dc-2359-454b-9c3d-53834e82201f.png)

Hello,

Since my last arch update (includes gnome updates), I can't use tweak to change GDM background, I have an error when I run :+1: ❯ sudo ./tweaks.sh -g -b "/home/bbr/Images/bg.jpg"

![image](https://user-images.githubusercontent.com/107874456/229092767-a944b43e-6772-4489-9c8d-46a9a71bd852.png)

Thank you for your help and support!

Best regards,
Bruno

**Comment by vinceliuice** [comment]
Fixed now
