### ISSUE TITLE
Cannot change Activities icon from Apple Logo with HD icons

### ISSUE THREAD

**Issue by penguin-teal** [vinceliuice/WhiteSur-gtk-theme#838]
I see the Apple logo as my activities icon (even after a GNOME shell reload) and not what I set it to when I use HD icons.
```
./install.sh -HD -i arch -l -o solid -t red
```
does not work and neither does:
```
./tweaks.sh -i arch -g
```
However, when I remove the HD:
```
./install.sh -i arch -l -o solid -t red
```
it works fine. I have an NVIDIA TUXX graphics card if it matters.

**Comment by vinceliuice** [comment]
Did you installed GDM theme ?

**Comment by penguin-teal** [comment]
Yes,
I did the `-g` flag on the tweaks script, and I assume it worked because it changed the icon from the "Activities" button to the apple logo, and when I do the exact same thing but do not use the `-HD` flag it works fine and I get the arch icon.

**Comment by wheatiesthecereal** [comment]
@penguin-teal - Have you tried uninstalling the gdk theme per this thread? https://github.com/vinceliuice/WhiteSur-gtk-theme/issues/889

I was able to reproduce the apple not going away until I removed the theme and then reapplied the "./install -i <distro>" command. 

repro'd on: debian 12, openSUSE tumbleweed 20230712

@vinceliuice - might want to update the docs to say as much ;)

**Comment by penguin-teal** [comment]
xD a _little_ late but @wheatiesthecereal your solution seems to have worked
