### ISSUE TITLE
question: what value to change to round corners?

### ISSUE THREAD

**Issue by fouzan14** [vinceliuice/WhiteSur-gtk-theme#84]
hello, I would like to change the border radius of application windows on top and bottom, what values do I have to change to make them less rounder in what .scss files?

**Comment by fouzan14** [comment]
can somebody help me with this?

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/c7886cf69c78a9de297260331250139d78138ee2/src/sass/_variables.scss#L35
