### ISSUE TITLE
[firefox monterey] The playback icon overlaps the favicon on pinned tab

### ISSUE THREAD

**Issue by slmatthew** [vinceliuice/WhiteSur-gtk-theme#840]
When a video or audio is playing on a pinned tab, the speaker icon overlaps the favicon of the tab

![изображение](https://user-images.githubusercontent.com/36668268/230920777-c11a49d0-5a74-4f1a-9aea-25c6df0bb094.png)

**Comment by vinceliuice** [comment]
Fixed
