### ISSUE TITLE
主题在snap商店和控制中心不可用

### ISSUE THREAD

**Issue by littleli233** [vinceliuice/WhiteSur-gtk-theme#842]
强迫症，难受
![img](https://user-images.githubusercontent.com/110950402/231351657-d68e6965-3515-4c3b-b5d3-9c1653f9421f.png)
![img 2](https://user-images.githubusercontent.com/110950402/231351698-a870fd6e-c68e-445c-8101-ad5559495e72.png)
gnome版本是42.5

**Comment by vinceliuice** [comment]
把这个snap版本卸载掉，然后用apt安装gnome-software，snap主题要安装单独的snap版主题才能用挺麻烦的，我也不知道怎么打包snap主题

**Comment by vinceliuice** [comment]
安装主题时运行：`./install.sh -l`

**Comment by littleli233** [comment]
但是控制中心还是不能用主题

**Comment by vinceliuice** [comment]
运行了./install.sh -l 吗

**Comment by vinceliuice** [comment]
这个要 gnome-shell 主题不是软件主题了

**Comment by vinceliuice** [comment]
你需要安装gnome-shell-extensions, 还有gnome-shell-extension-manager

**Comment by vinceliuice** [comment]
![截图 2023-04-12 20-26-49](https://user-images.githubusercontent.com/7604295/231456568-5d89a1e6-f472-44b7-ac0a-cfba1602f077.png)
开启这个选项之后用gnome-tweaks设置shell主题

**Comment by vinceliuice** [comment]
不客气
