### ISSUE TITLE
How to use this theme for the login page?

### ISSUE THREAD

**Issue by devklick** [vinceliuice/WhiteSur-gtk-theme#843]
I have 3 Zorin OS machine's, all using this same theme, however only one of them use this theme for the login page, while the other two still seem to use the default login theme provided by the OS. Does anyone have any idea why this would be, or more importantly, how to go about using this theme for the login page?

**Shell Theme**
WhiteSur-Dark-solid (all machines using this)

**Versions**
- Zorin OS 16.2
- GNOME Shell 3.38.4 (Need to check the machine
(all machines using the above)

**Comment by devklick** [comment]
One key difference is that the one that works (uses the whitesur theme for login page), only has the theme installed to `/usr/share/themes`, whereas the other two (which dont use the whitesur theme for login page), have it installed to this location _and_ `/home/user/.themes`. 

Perhaps I specified the `-d` flag when installing on the working one, although I dont think this was the case (it was many many months ago, so I could be wrong)

**Comment by vinceliuice** [comment]
`sudo ./tweaks.sh -g`

**Comment by devklick** [comment]
Thank you :slightly_smiling_face:
