### ISSUE TITLE
Unable to change window's title bar. "Stuck" with dark variant.

### ISSUE THREAD

**Issue by rbarbosa34** [vinceliuice/WhiteSur-gtk-theme#846]
Before the recent GNOME update, I was able (somehow) to have a white window title bar while maintaining the dark-solid shell variant.
That is not true anymore, since I'm "forced" to have a dark title bar variant even if I select the light-solid shell theme.

Command used for instalation:
` ./install.sh --dialog -i simple -l`
using the default options during the dialog. Note that the Dark Style option in gnome is not selected.

Current behaviour is described in the following picture. I'm expecting to return to previous behaviour where I had nautilus with black variant, and the title bar of Doom Emacs with a light variant.
If such behaviour is not possible anymore, please ignore the reported issue and close it.

![image](https://user-images.githubusercontent.com/9491881/232206640-629887e7-1dd4-423d-884d-d64a1112468e.png)

**Comment by vinceliuice** [comment]
`./install.sh -l -c Light`

**Comment by mricewolf0110** [comment]
![image](https://user-images.githubusercontent.com/102027417/232308107-2a10b2bd-f990-463f-b1db-9d6949fd7e7b.png)

how could I fix the top bar?

**Comment by rbarbosa34** [comment]
> `./install.sh -l -c Light`

Using the Light modifier, also changes Nautilus to a Light schema.
The objective was to maintain the Nautilus in the Dark variant, while the remaining title bars are with the Light variant.
Such combination was possible in previous versions, but I understand if that was not the intended behaviour.

**Comment by vinceliuice** [comment]
In gnome 44 Non-csd windows use gtk-4.0 themes now, so Doom Emacs will use the same theme color as Nautilus

**Comment by rbarbosa34** [comment]
I understand the motives now. It's not a bug, but an intended behaviour.
Thank you for the clarification.
