### ISSUE TITLE
Is there a way to select which color will be installed for libadwaita?

### ISSUE THREAD

**Issue by claytonwramsey** [vinceliuice/WhiteSur-gtk-theme#848]
When running `install.sh`, it looks like the libadwaita install with `-l` only installs one color for libadwaita apps.

For instance, when I do the following:

```sh
./install.sh -l -c Light -c Dark
```

it will install the dark theme on libadwaita. I'd like to install both the light and dark themes, but have the light theme installed for libadwaita. Is this possible? If so, how can I do it?

**Comment by vinceliuice** [comment]
-l option is just link a theme to gtk4 config file. so it do mot support theme switch

**Comment by claytonwramsey** [comment]
Thanks.

For now, I've figured out a decent workaround. I simply create some links to overwrite the GTK-4 CSS:

```sh
local THEME="WhiteSur-Light"
local THEME_DIR="${HOME}/.themes/${THEME}/gtk-4.0"

mkdir -p "${HOME}/.config/gtk-4.0"
ln -sf "${THEME_DIR}/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets"
ln -sf "${THEME_DIR}/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
ln -sf "${THEME_DIR}/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
```
