### ISSUE TITLE
make activities icon a little larger

### ISSUE THREAD

**Issue by peterwu** [vinceliuice/WhiteSur-gtk-theme#85]
Would you please make the activities icon a little larger? On my Fedora system, the fedora logo is a bit too tiny. The one used in Mojave theme seems about right size to me. Thank you.

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/c7886cf69c78a9de297260331250139d78138ee2/src/sass/_variables.scss#L35
