### ISSUE TITLE
Menu desglose default in fedora 38

### ISSUE THREAD

**Issue by jesusferm** [vinceliuice/WhiteSur-gtk-theme#852]
In menu desglose apper this visual issue

- fedora 38
- dark theme gnome shell
- compile from source github
- menu config desglose not show correctly

![image](https://user-images.githubusercontent.com/5892507/233208584-c03b3938-d029-447d-b214-1b19f8eb7be4.png)

**Comment by fr3nchalp4a** [comment]
it's due to the new update of Gnome 44, and changes to the new control panel. 
I have the same problem on fedora 38 :
![image](https://user-images.githubusercontent.com/68474172/233286725-f5ff8d5f-9927-4f47-8a11-398e6cd23c23.png)

**Comment by vinceliuice** [comment]
Install the last update on github, this should be fixed

**Comment by jesusferm** [comment]
Thanks, it's works
