### ISSUE TITLE
quick settings menu toggle buttons not padded correctly

### ISSUE THREAD

**Issue by bdreaves04** [vinceliuice/WhiteSur-gtk-theme#855]
hi, my quick menu toggles are broken after updating to ubuntu 23.04 from 22.10 
![image](https://user-images.githubusercontent.com/63303767/234009333-e19938f2-b0ef-4bb0-bdac-11a02544a392.png)

**Comment by vinceliuice** [comment]
Try the last update, it's fixed already

**Comment by bdreaves04** [comment]
This was after updating to the newest release also.

**Comment by bdreaves04** [comment]
Oh wait you just released a new one my bad

**Comment by bdreaves04** [comment]
Mines fixed too now too the update thanks
