### ISSUE TITLE
Glitch around window when resize 

### ISSUE THREAD

**Issue by shanin-ivan** [vinceliuice/WhiteSur-gtk-theme#857]
Hi, i have Fedora 38 with Gnome 44, using Wayland

I recently handled a ticket #856 

I tried the new version theme. Tittle bar now works as it should, but artifacts around the window are still there when resizing the window.
![image](https://user-images.githubusercontent.com/16905671/234375142-4e3a5113-cda9-4d63-9fed-08b80006b048.png)

**Comment by vinceliuice** [comment]
What about now?

**Comment by vinceliuice** [comment]
I'm using Nvidia card and Fedora 38 with Gnome 44, but my issues are different from yours, I only have flickering in the window, your situation is gone on my desktop with the current WhiteSur version

**Comment by vinceliuice** [comment]
Could you test this for me ?
change:
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/19716ce1ebc9208600e2e6f9c7cfe7e6fa5ca771/src/sass/gtk/_common-4.0.scss#L4859
from:
`transition: $shadow_transition;`
to:
`transition: none;`
then install it to see if it fixed

**Comment by shanin-ivan** [comment]
> Could you test this for me ? change:
> 
> https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/19716ce1ebc9208600e2e6f9c7cfe7e6fa5ca771/src/sass/gtk/_common-4.0.scss#L4859
> 
> 
> from:
> `transition: $shadow_transition;`
> to:
> `transition: none;`
> then install it to see if it fixed

I tried, nothing has changed. 

I am using an Nvidia card with an open driver by default, in the settings it is displayed as "NV136"
Yesterday I tried to install a closed driver from Gnome software "NVIDIA Linux Graphics Driver", I'm not sure I used it correctly, I just installed it and rebooted the system and in the settings instead of "NV136" the full name of my video card "Nvidia GeForce 1060" began to be displayed, but as of yesterday the application window was I feel exactly the same.

I also tried switching to X.org , but this result was exactly the same.

I can try installing a closed driver again

**Comment by shanin-ivan** [comment]
I did some tests and found that with a closed driver, even without a theme, everything does not work very well
All tests were performed on the latest version with your recommendations

Open source driver:

<details>
  <summary>Without theme(Everything works well)</summary>
  
[open driver without theme.webm](https://user-images.githubusercontent.com/16905671/234566122-3b156677-89ae-4db3-b477-215b2e7b722b.webm)
 
</details>

<details>
  <summary>With theme</summary>
  
[open driver with theme.webm](https://user-images.githubusercontent.com/16905671/234566341-5cf7d98f-96f4-4c33-bdcd-724fbb6dba8b.webm)
  
</details>

Close driver:

<details>
  <summary>Without theme</summary>
  
[closed driver without theme.webm](https://user-images.githubusercontent.com/16905671/234566520-1166d92c-9381-4f22-8bb3-a2ee141653c5.webm)
  
</details>

<details>
  <summary>With theme</summary>
  
[closed driver with theme .webm](https://user-images.githubusercontent.com/16905671/234566639-8e969e1a-7caf-4bdf-8c74-2c6b35c5e55d.webm)
  
</details>

**Comment by vinceliuice** [comment]
I think this is more like a mutter issue
https://gitlab.gnome.org/GNOME/mutter/-/issues/2725
https://gitlab.gnome.org/GNOME/gtk/-/issues/5715

**Comment by shanin-ivan** [comment]
> I think this is more like a mutter issue https://gitlab.gnome.org/GNOME/mutter/-/issues/2725 https://gitlab.gnome.org/GNOME/gtk/-/issues/5715

The first link solved my problem
I just specified `XWAYLAND_NO_GLAMOR=1`
Now everything works fine for me with both an open source driver and a proprietary Nvidia driver

Thank you so much for helping to solve the problem
