### ISSUE TITLE
Window goes out of the screen when resizing from maximized window by dragging

### ISSUE THREAD

**Issue by john-ghatas** [vinceliuice/WhiteSur-gtk-theme#859]
System: Fedora 38 - Gnome 44

Issue occors on the latest repo version commit 19716ce1ebc9208600e2e6f9c7cfe7e6fa5ca771

Compiled the theme with the following  command

```
./install.sh -m --darker -l -c Dark --icon fedora -N glassy -p 60
```

**Comment by john-ghatas** [comment]
[Screencast from 2023-04-26 23-00-44.webm](https://user-images.githubusercontent.com/14125058/234701636-6dd75a44-0f04-4251-8f9c-372a88c3f0a7.webm)

Tried to record it in a screencast but with some applications (GTK 4 ones mainly system settings etc and **flatpaks do not have this issue**) it's not as much of an issue as it is with other (Mainly Tilix which I suspect is GTK3 based (?)).

**Comment by vinceliuice** [comment]
Tilix is gtk3 app

**Comment by john-ghatas** [comment]
Thanks, I tried it with other themes compatible with Gnome 44 and it has no such issues, the window titlebars keep track of the cursor instead of having a small deviation in position in the case of GTK4 apps and a huge difference with GTK3 apps

**Comment by john-ghatas** [comment]
Tilix is still a little bit problematic but not as much as it used to be before, tested other GTK 3 apps and they seem fine. Thanks for the effort, I will close the issue.

**Comment by john-ghatas** [comment]
Did some more testing with different apps, seems lik the GNOME System monitor is still hit

**Comment by john-ghatas** [comment]
For any GNOME 44/ Fedora 38 users the issue is fixed with the last gnome-mutter update for GTK3 applications as well.
