### ISSUE TITLE
Rounded corners not working on maximize windows

### ISSUE THREAD

**Issue by sajorcf** [vinceliuice/WhiteSur-gtk-theme#86]
Hi,

I am in love with this theme, but i have an issue here an it's related about the rounded corners on maximized windows.

All my maximized windows looks squared no matter what I do.

![image](https://user-images.githubusercontent.com/42658985/103147054-14980f00-471f-11eb-9291-1d56aff49c12.png)

But on normal size, it looks good.

![image](https://user-images.githubusercontent.com/42658985/103147061-22e62b00-471f-11eb-83d5-0b4cbf7c75cb.png)

In Chrome, you can even see where the border is trying to do the border-radius (disappearing the black shadow to do a radius).

![image](https://user-images.githubusercontent.com/42658985/103147077-5de85e80-471f-11eb-9e53-bad7b745cf68.png)

But it seems it is not allowing them to do it, so it stays in a square window. Also in normal size (not maximized) it works well.

I have an Intel Chipset, with an integrated graphics card. Intel® Core™ i5-10210U

Have a good night

**Comment by vinceliuice** [comment]
In order to fully cover the screen, I set the square corner when maximized

**Comment by vinceliuice** [comment]
Not a issue

**Comment by sajorcf** [comment]
How can I disable it? What line of css do i need to modify? 

I want it to look like a real big sur theme, where the border radius is setted even when on maximize

**Comment by vinceliuice** [comment]
I'll update this, don't worry

**Comment by sajorcf** [comment]
Oh wow, really thank you. When are you planning to update it? To take a reminder to download the newer version.

Thanks a lot!

**Comment by vinceliuice** [comment]
It'll be tomorrow

**Comment by zeparu** [comment]
i just noticed that the in the current version of this theme, the rounded corners of maximized windows are absent again

is this intentional and will they be added back or will it stay like this?

**Comment by vinceliuice** [comment]
I'll add this as a option back! @zeparu
