### ISSUE TITLE
..

### ISSUE THREAD

**Issue by mohammad-zadeed** [vinceliuice/WhiteSur-gtk-theme#860]

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by mohammad-zadeed** [comment]
> Run: `./install.sh -l`

still didn't change anything
[Screencast from 2023-04-28 20-19-32.webm](https://user-images.githubusercontent.com/120179019/235174465-475b0d14-3c10-4200-b06f-33193c913bce.webm)
