### ISSUE TITLE
Weird glitch bar after resizing from maximized window

### ISSUE THREAD

**Issue by john-ghatas** [vinceliuice/WhiteSur-gtk-theme#861]
System info:
Fedora 38/Gnome 44

Encountering issues after resizing from maximized window, a weird glitch bar shows up:

![image](https://user-images.githubusercontent.com/14125058/235271821-6f2a18be-dc2d-4aaf-bd09-55cbab369253.png)
![image](https://user-images.githubusercontent.com/14125058/235271836-8f330aad-1cc4-45f6-b2e1-2e0def70177a.png)

Any idea what this could be? So far only seeing it on some GTK3 apps (Flatpak and Distrobox apps [Containerized])

Not seeing this weird bug on native installed applications, neither GTK3 not GTK4 seems to show this behaviour for native installed apps.

**Comment by john-ghatas** [comment]
Please let me know if I can check out a branch to test out a patch for this if needed

**Comment by razllivan** [comment]
> Please let me know if I can check out a branch to test out a patch for this if needed

If you mean the strip in the upper right corner, then I had the same glitch. I found the solution here:
https://gitlab.gnome.org/GNOME/mutter/-/issues/2725

Setting the variable `XWAYLAND_NO_GLAMOR=1` helped me

I also tested the latest version of mutter hoping that it was fixed, but nothing has changed. You can try it, maybe it will help you too

**Comment by john-ghatas** [comment]
That won't work 100% for me since I have GUI apps layered in [distrobox](https://github.com/89luca89/distrobox) where this wouldn't be possible or too hacky to set. I tried the Vimix theme in the meanwhile which works for GNOME 44 and does not show these issues (none at all really).

**Comment by john-ghatas** [comment]
Will keep the issue closed and wait for the next Mutter releases
