### ISSUE TITLE
Firefox theme is broken after all latest updates are installed

### ISSUE THREAD

**Issue by insanity83NL** [vinceliuice/WhiteSur-gtk-theme#865]
OS: Ubuntu 22.04.2 LTS
Gnome version: 42.5
Firefox: 113.0

The Firefox theme seems to be broken after installing the latest Ubuntu/Firefox updates.
The windows close, minimize and maximize buttons overlap the tabs. Also, tabs seem to be repositioned to the top of the window, instead of underneath the url bar and window buttons.

![Screenshot from 2023-05-05 09-00-49](https://user-images.githubusercontent.com/115035124/236395688-88b43d3e-a174-43e1-b45c-d119e1ab80c8.png)

**Comment by vincentWuK** [comment]
You can temporarily avoid this problem by installing the previous version of firefox, just following the steps below:

1. uninstall the installed Firefox on your system: `sudo apt-get remove firefox`
2. Visit the Firefox FTP server to find and download the required version of Firefox. for example, to install version 78.0.1, you can find it in the directory 78.0.1/. `wget https://ftp.mozilla.org/pub/firefox/releases/78.0.1/linux-x86_64/en-US/firefox-78.0.1.tar.bz2`
3. After downloading, unzip the file: `tar xjf firefox-78.0.1.tar.bz2`
4. Move the unzipped Firefox folder to the /opt directory: `sudo mv firefox /opt/firefox78`
5. Create a symbolic link to set the newly installed version of Firefox as the system default: `sudo ln -s /opt/firefox78/firefox /usr/bin/firefox`
6. Disable firefox updates: in /opt/firefox, create a folder named "distribution", and create a file in this folder named "policies.json" and add the following code to this file: 
`{
  "policies": {
    "DisableAppUpdate": true
  }
}`
7. You can open "help" -> "about firefox" in firefox to see if "Updates disabled by your system administrator" is displayed

**Comment by insanity83NL** [comment]
Thanks @vincentWuK !

Was able to downgrade to v112.0.2, which restored the theming of Firefox !

Problem solved !
