### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by MrRevillod** [vinceliuice/WhiteSur-gtk-theme#867]
There are interface errors with the new version of gnome (44)

Example: the Quick settings panel. The new version of gnome incorporates a side button on the sides of wifi and bluetooth.

**Comment by k-caps** [comment]
> can you provide screenshots, and info about system and what version theme you're using? light blue theme from git works realy good for fedora and archlinux

On latest Ubuntu:
**Custom theme off:**  
![Screenshot from 2023-05-15 22-06-20](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/18639419/23ab2312-8041-4565-9a41-f334daa4c966)

**Custom theme on:**  

![Screenshot from 2023-05-15 22-06-44](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/18639419/61b94b3c-ebd3-493c-8e58-d1730b4bef1d)

As you can see, the arrow buttons aren't visible with WhiteSur, but they do work if you click to the right where you can just barely see the grey box.

**Comment by frosth555** [comment]
weird, it is fixed already (#832)
for reference: 
![Screenshot from 2023-05-15 22-28-53](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/22305379/afd8e9d6-821c-4aaa-9178-6e29d83d86c5)

**Comment by k-caps** [comment]
My bad; I had not run `./install.sh` after git pulling.
