### ISSUE TITLE
gnome44 - submenus has got wrong bg color in any theme

### ISSUE THREAD

**Issue by frosth555** [vinceliuice/WhiteSur-gtk-theme#870]
Archlinux / Fedora 38
Gnome Shell 44.1
git verision of themes

many extensions with sub menus are affected like feon, bing wallpapers, bubblemail... or even some apps in the tray.
eg. freon with dark theme:
![Screenshot from 2023-05-10 16-23-36](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/22305379/1fdc435a-725b-463d-b393-b484c3ccd1e9)
eg. freon with light theme:
![Screenshot from 2023-05-10 16-24-09](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/22305379/20451ea0-ce0e-46e3-b5e4-10dd38f63de6)

color can be simple fixed by adding: `background-color: transparent;` to 
.popup-sub-menu .popup-menu-item {}

but it can be a liitle bit tweaked to match look from original adwaita:
![Screenshot from 2023-05-10 16-23-24](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/22305379/c57933b6-db82-4745-9550-5677e96bd810)
![Screenshot from 2023-05-10 16-23-48](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/22305379/9c8d6f19-252b-4b47-9a99-0b3df852c286)

I made patch for gnome-shell.css directly, based on light theme (but it's aplicable for any) 
```
--- a/gnome-shell/gnome-shell.css
+++ b/gnome-shell/gnome-shell.css
@@ -3066,14 +3067,19 @@
   background-color: rgba(255, 255, 255, 0.75) !important;
   border-radius: 0 0 10px 10px;
   border: none;
-  box-shadow: none;
+  box-shadow: inset 0 1px 0 0 rgba(0, 0, 0, 0.12);
+  margin: 0 0 0 0;
 }
 
 .popup-sub-menu .popup-menu-item {
+  background-color: transparent;
   margin: 0;
-  border-radius: 10px;
-}
-
+  border-radius: 0px;
+}
+
+.popup-sub-menu .popup-menu-item:last-child {
+	border-radius: 0 0 10px 10px;
+}
 .popup-sub-menu .popup-menu-item:focus, .popup-sub-menu .popup-menu-item:hover, .popup-sub-menu .popup-menu-item:selected {
   color: white !important;
   background-color: #2E7CF7 !important;
```
hope it will help a little, unfortunately don't know how to prepare it for sources,

**Comment by vinceliuice** [comment]
Fixed now
