### ISSUE TITLE
A top border appears on windows in gnome shell 44

### ISSUE THREAD

**Issue by jesusferm** [vinceliuice/WhiteSur-gtk-theme#875]
In many applications appear border on top windows:

- gnome-shell 44
- fedora 38
- xorg mode or wayland this error/bug appear
- theme default or custom

this is a bug/error? theme gtk? gnome?

[im](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/6b45e7c69625abe20f653270a37b35b7/Screenshot_from_2023-05-15_01-27-00.png)

**Comment by vinceliuice** [comment]
Fixed!
