### ISSUE TITLE
Allow nord colors in Firefox

### ISSUE THREAD

**Issue by tlabartbarnagaud** [vinceliuice/WhiteSur-gtk-theme#877]
I've installed WhiteSur GTK theme with nord colors and then connected it to Firefox. However, the Firefox theme does not use the nord collors. Would it be possible to sync the nord colors in both GTK and Firefox?

**Comment by zachcheatham** [comment]
+1 to this. Would love to be able to use the Firefox tweak with the nord color scheme.

**Comment by arigit** [comment]
+1 as well. There seems to be a nordic theme for firefox 
FWIW: https://github.com/EliverLara/firefox-nordic-theme

**Comment by arigit** [comment]
Actually the firefox-nordic-theme looks awful in my system for some reason, and it seems to be an early fork of WhiteSur (or viceversa?) as it had the same issue with Firefox containers indicators. 

I really wanted the nord color palette in my desktop so I modified the CSS file of the WhiteSur Firefox plugin which I attach here, there is surely room for improvement but it's very usable as it is,

![image](https://github.com/user-attachments/assets/bbb27a94-ac01-40ea-ad0d-c78bd8b542bb)

This assumes that you are using the Nord palette with WhiteSur in gnome shell, "legacy apps", libadwaita, and flatpaks.
Install the WhiteSur firefox plugin as usual, and then use the attached dark.css to replace the follwing file:

If you use firefox via flatpak, this is the folder:

```/home/your_username/.var/app/org.mozilla.firefox/.mozilla/firefox/your_firefox_profile.default/chrome/WhiteSur/colors/dark.css```

If you use your distro package of firefox:

```/home/your_username/.mozilla/firefox/your_firefox_profile.default/chrome/WhiteSur/colors/dark.css```

Zip file:

[WhiteSur-Firefox-Fix-for-Nord.zip](https://github.com/user-attachments/files/17970568/WhiteSur-Firefox-Fix-for-Nord.zip)

In the attached you can find the CSS, and also drop-in replacements for the window control icons that you can use in the "titlebuttons" asset folder of the plugin:

```/home/your_username/.var/app/org.mozilla.firefox/.mozilla/firefox/your_firefox_profile.default/chrome/WhiteSur/titlebuttons```

I tried to match the colors used by WhiteSur/Nord in Nautilus as best I could.

It would be nice if one day @vinceliuice could add support for Nord in this plugin. I also did a few more tweaks:

- Search for: `.tab-context-line`
	- Inside: `.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {`
	- Add: `opacity: 0.6;`
- Change tab-bar height
	- Search: `tabs bar height`
	- Change from 32px to 40px
- Fix active tab appearance
	- Search: `Active tab`
	- Replace the box-shadow configuration with:
		- ```css
		  	box-shadow: 0px 0 var(--gnome-tabbar-tab-active-border-color), 0px 0 0px rgba(0, 0, 0, 0.08),
		  	            0px 0 var(--gnome-tabbar-tab-active-border-color), 0px 0 3px rgba(0, 0, 0, 0.08),
		  	            inset 0 -1px var(--gnome-tabbar-tab-active-border-color) !important;
		  ```

**Comment by arigit** [comment]
The only item I wanted to fix but couldn't was the initial password prompt dialog from Firefox, the one that shows up when opening firefox if you use a "Primary / Master" passwords that you allow firefox to save and auto-fill:

![image](https://github.com/user-attachments/assets/b506d76f-c536-4719-b7dd-b518bde71eff)


You can see the problem around the "Sign in" button, where the shadow box (or border?) doesn't look good, it's missing the bottom side. Other FF themes do not have this glitch.

@vinceliuice any idea of what needs to be tweaked, without breaking other dialogs?

**Comment by vinceliuice** [comment]
Now you can run: `./tweaks.sh -f nord` to install nord version

**Comment by arigit** [comment]
Thanks @vinceliuice  for all the work! fantastic. 

A few suggested tweaks to dark-nord.css, basically replacing the deep blue and deep red with nord's washed out version:

	--gnome-button-suggested-action-background: linear-gradient(to top, #5271ad 2px, #5271ad);
	--gnome-button-suggested-action-hover-background: linear-gradient(to top, #5271ad, #5271ad 1px);
	--gnome-button-suggested-action-active-background: linear-gradient(to top, #5271ad, #5271ad 1px);

	--gnome-button-destructive-action-background: linear-gradient(to top, #bf5f69 2px, #bf5f69);
	--gnome-button-destructive-action-hover-background: linear-gradient(to top, #bf5f69, #bf5f69 1px);
	--gnome-button-destructive-action-active-background: linear-gradient(to top, #bf5f69, #bf5f69 1px);

Also, the traffic lights (window controls)  that the firefox theme sets are not nord's, i.e. instead of this:

![image](https://github.com/user-attachments/assets/29cdad1e-07d9-476e-acf5-0abcd2f1cb9e)

you get the deep red, deep yellow etc. in the zip file attached to my comment above, I edited your svg icons in the "titlebuttons" folder of your theme, the "...-dark.svg" version series, using inkscape and converted the red/yellow/green variants to nord. Otherwise firefox was the only app in the desktop using the deep-color version of the traffic lights.  Ideally you could reuse those icons and include them in the theme but as a new "...dark-nord.svg" version.

**Comment by vinceliuice** [comment]
Now it's fixed
