### ISSUE TITLE
Issues with the "delete from history" button in firefox

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#879]
On Firefox homepage, choose one of the shortcuts and open its menu.

![Screenshot from 2023-05-25 21-24-08](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/397a4c60-1084-4714-8fae-fa084ef6d665)

Choose "delete from history." This menu will pop up.

![Screenshot from 2023-05-25 21-17-02](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/e7f3b081-21f2-4e13-b8f2-e43b49e138e7)

The "Delete from history" button has wrong text color. Also it doesn't get lit up when the mouse hover overs it; for example, this is what happens when the mouse hovers over the "cancel" button.
![Screenshot from 2023-05-25 21-27-26](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/b428d997-a395-4cec-a09c-1aa69914a20d)

However, clicking the button still works.

The screenshots show Firefox in default variant, but the problem exists in all three variants.

------------------------- System info -------------------------

Arch linux
X11
Gnome 44.1
Latest git version of WhiteSur-gtk-theme at the moment of writing

**Comment by vinceliuice** [comment]
Fixed

**Comment by FelixFourcolor** [comment]
Thank you very much!
