### ISSUE TITLE
snap support

### ISSUE THREAD

**Issue by MacielFede** [vinceliuice/WhiteSur-gtk-theme#881]
I know this theme doesn't support snap apps nowadays, but is there a plan to do so?
I love this theme but it's a shame that most of the apps remain unthemed by this.

Maybe there's a way that @swiatlyk (who has the snap theme if he didn't removed it from his pc, I know this because he solved it in a previous issue) uploads it to the snap store so we can all enjoy it. I know it may be an old version that could have some issues but I prefer that to no theme at all.

**Comment by vinceliuice** [comment]
I don't know how to build a snap theme

**Comment by MacielFede** [comment]
It's fine, I searched a lot how to do it but no luck yet and I don't really understand the snap packaging right now. In the mean time I will switch to Mojave

**Comment by diogodomanski** [comment]
I found an attempt to make Whitesur theme available for snap apps here: https://github.com/spider623/whitesur-snap.

Is that useful for you @vinceliuice ?
