### ISSUE TITLE
The space between buttons in Flatpak gtk-4.0 app is close

### ISSUE THREAD

**Issue by nkcong206** [vinceliuice/WhiteSur-gtk-theme#883]
I've used:
`sudo flatpak override --filesystem=xdg-config/gtk-4.0
`
and
`sudo flatpak override --env=GTK_THEME=WhiteSur-Dark-blue
`
But it seems that the buttons are spaced close together.

![243108573-0193c3d9-e059-45a1-9823-edabd5961a32](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/56025592/2afaa073-3d9b-4fcb-bb07-33c8dc2d338c)

**Comment by vinceliuice** [comment]
What's this app ?

**Comment by nkcong206** [comment]
Apps using GTK4 in Flatpak, I have tried Flatseal, G4music, Amberol. 
I have tried with some themes for these apps, when they explicitly write in gtk.css and gtk-dark.css files in gtk-4.0 folder it won't crash.
And it also shows the following error:
`(com.github.neithern.g4music:2): Gtk-WARNING **: 08:38:38.823: Theme parser error: gtk.css:1:1-57: Failed to import: The resource at “/org/gnome/theme/gtk-dark.css” does not exist 
`

**Comment by vinceliuice** [comment]
Run `./install.sh -l`

**Comment by nkcong206** [comment]
I ran the code but everything seems to be the same!

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by nkcong206** [comment]
Oh, it's ok. Thank you so much!
