### ISSUE TITLE
Buttons problem

### ISSUE THREAD

**Issue by Lianaja32** [vinceliuice/WhiteSur-gtk-theme#884]
I have installed the WhiteSur theme and the close, minimize & maximize buttons are not not supposed to look like this.

I'm running Ubuntu Unity 23.04.
![Capture d’écran du 2023-06-10 10-20-00](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/79010647/e1bbb473-38bd-45ee-af0c-39cbf6ed1298)

**Comment by vinceliuice** [comment]
It's been a long time since I've seen anyone use Unity. anyway I add it back
