### ISSUE TITLE
was the apple logo always at the top left corner for this theme?

### ISSUE THREAD

**Issue by C3OK** [vinceliuice/WhiteSur-gtk-theme#886]
hello, im slightly confused on what happened to the apple symbol for this theme at the top left corner.
was it removed? was it always there? it would usually appear when you set whitesur light or dark as the shell.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/135292904/4cf84c48-e8f5-46d5-89eb-0ef95a6079f0)

**Comment by C3OK** [comment]
im on pop os btw so it may not appear for me

**Comment by vinceliuice** [comment]
You can run: `./install.sh -i popos`

**Comment by C3OK** [comment]
it turns out that there is a gnome extension that allows this
