### ISSUE TITLE
not able to change activities icon with ./tweaks.sh

### ISSUE THREAD

**Issue by diorcula** [vinceliuice/WhiteSur-gtk-theme#887]
Although installing everything worked fine, i am not able to change the activities icon?

i run: `./tweaks.sh -i ubuntu`
in the Whitesur folder

**Comment by fr3nchalp4a** [comment]
Actual UX of commands may be redesigned, to prevent this of happening, and to clarify how it works and which commands use which flags, like this : 
```
./install.sh install -c Dark -i standard
sudo ./tweaks.sh gdm -c Light
./tweaks.sh firefox
```
instead of full flags control, which can be not that obvious for some ppl
