### ISSUE TITLE
make install.sh unattended

### ISSUE THREAD

**Issue by peterwu** [vinceliuice/WhiteSur-gtk-theme#89]
Recently, install.sh introduced some new switches (--theme, --panel, --size), which utilize dialog to interactively prompt user to pick their selection. This is all great. However, as I build rpm for the theme in an unattended build environment, live interaction is not possible in this use case.

Could you please change install.sh in such a way that if, say --size is passed without any parameter, then it pops up the dialog; if a parameter is provided, e.g. --size 220px is provided, then the popup is suppressed and the value will be taken. If you make this change for all the 3 aforementioned switches, this would allow for both interactive and unattended use cases. Thank you.

**Comment by vinceliuice** [comment]
No problem! I'll update it

**Comment by vinceliuice** [comment]
Fixed!
