### ISSUE TITLE
窗口按键不生效

### ISSUE THREAD

**Issue by ryanInf** [vinceliuice/WhiteSur-gtk-theme#904]
作者大大，感谢你做出这么优秀的主题！
在使用时发现窗口按键没有应用到主题的情况，找不到解决方法。

系统
ubuntu 22.04
gnome 42.9
Wayland

执行的命令

./install.sh -N mojave -a alt （也试过./install.sh -t all -N glassy -s 220）
./tweaks.sh -g

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/19621374/05536992-71d5-47da-b122-eef72ea18d11)

**Comment by vinceliuice** [comment]
要加`-l`选项安装 libadwaita 主题
