### ISSUE TITLE
Nautilus is Yellow

### ISSUE THREAD

**Issue by AndreaScerra** [vinceliuice/WhiteSur-gtk-theme#907]
Fedora 38, gnome 44
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/108824127/04b3fd66-3f98-40f4-a92a-101db1565fb3)

**Comment by Varad-Codes** [comment]
Have you gotten a fix yet? I also have the same issue

**Comment by AndreaScerra** [comment]
No and I don't know if someone fixed it becouse  now I'm using kde plasma with chrome os theme by Vinceliuice
![immagine](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/108824127/64823887-fbb7-4066-bc62-e52f9bc7a669)

**Comment by AndreaScerra** [comment]
No and I don't know if someone fixed it becouse now i'm using kde plasma with chrome os theme by Vinceluice
![immagine](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/108824127/4b8b038e-c0f1-4821-8853-c7fd2a776797)
