### ISSUE TITLE
Operation Failed

### ISSUE THREAD

**Issue by nusantaraja** [vinceliuice/WhiteSur-gtk-theme#919]
=========== ERROR LOG ===========
  >>> error: target not found: sassc
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> pacman -Syyu --noconfirm --needed sassc
  TRACE  :
    >>> signal_error
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : rolling;endeavouros;arch
  SUDO   : yes
  GNOME  : 44-0
  REPO   : 2023-08-12T19:13:18+0700

**Comment by vinceliuice** [comment]
Install sassc first

**Comment by nusantaraja** [comment]
DONE .. Installed direct from AUR. Thanks you
