### ISSUE TITLE
New update GDM broken log out action

### ISSUE THREAD

**Issue by sajorcf** [vinceliuice/WhiteSur-gtk-theme#92]
Hi.

I just updated and did sudo ./install -g and then restarted my gui with alt + f2 > r

My log out page has just disappeared and is black. It starts to tilt some seconds and then my pc shuts off.

I have no more images than this one when I click on Log Out.

![20201227_021747](https://user-images.githubusercontent.com/42658985/103165828-770a1180-47ea-11eb-8c54-a959bb2f17de.jpg)

At least I have autologin so I can login into my pc.

Thanks

**Comment by vinceliuice** [comment]
Could you tell me you system version?

**Comment by vinceliuice** [comment]
You can run sudo ./install.sh -g -r to remove installed gdm theme, I need some time to fix this issue

**Comment by sajorcf** [comment]
Hi,

Ubuntu 20.04, windowing version X11. Intel hd graphics.

Ok I will uninstall it, thanks

**Comment by vinceliuice** [comment]
Now! it's fixed!
