### ISSUE TITLE
Too large icons on the dock (built-in one that is in action)

### ISSUE THREAD

**Issue by Drakon1505** [vinceliuice/WhiteSur-gtk-theme#920]
The size didn't bother me too much, if only the running program indicator didn't touch the icon.
![Знімок екрана з 2023-08-23 11-33-40](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/88138327/80d56ede-8a63-43c2-af45-155fe58f7807)

**Comment by vinceliuice** [comment]
Do not use the built-in theme

**Comment by Drakon1505** [comment]
I do not use the built-in theme. I use WhiteSur (which is on the picture)

**Comment by vinceliuice** [comment]
I mean the dash-to-dock setting trun the built-in theme option off

**Comment by vinceliuice** [comment]
And make sure you are using whitesur gnome-shell theme, your shell theme looks not like whitesur

**Comment by vinceliuice** [comment]
![截图 2023-08-23 22-48-14](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/4df1089a-ae36-465b-8dae-2ac4576ee8e0)

**Comment by Drakon1505** [comment]
I don't use the dash-to-dock (and for some reason the dash-to-dock only shows programs running on a specific workspace, and I haven't figured out how to turn it off). And it's strange to fix a theme with an extension. The previous photo shows the fixed WhiteSur gtk theme. Here is the original
![Знімок екрана з 2023-08-31 16-34-57](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/88138327/6b9853f5-e4cf-4c0a-bc9a-c51a58a5a5c6)
