### ISSUE TITLE
Dropdown menupopup overflow glitch + fix

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#922]
In the firefox Whitesur theme, when opening a large dropdown menu, it's not scrollable., See screenshot
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/d7d07788-c922-49ab-b50d-efc5ae86acc3)
As you can see there's no scrollbar and the last visible item overflows weirdly, any items below the last visible are not accesible

I've found the issue comes from `--panel-shadow-margin: 3px 8px 13px !important;` inside `parts/popups.css`. It seems that any value other than a single margin for all sides breaks the scroll. For example if you set this to 4px it works. This does change the styling a bit but at least it becomes usable again

**Comment by vinceliuice** [comment]
What about now, I update it

**Comment by Laurens256** [comment]
Thanks, your code fixed it. This is what it looks like with your changes:
![Screenshot1](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/2f3ef197-650b-4c67-982a-14544750d720)
If you change `padding: 0 4px 9px !important;` to `padding: 2px 4px 9px !important;` inside `parts/popups.css`, it looks a little bit better i think:
![screenshot2](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/e3c2272d-4768-4fb5-b710-d7c6d0d3b9ed)

That's for you to decide though :) thanks for the great themes

I also tested dropdowns with less items and they also work as expected with this styling

**Comment by vinceliuice** [comment]
No problem!
