### ISSUE TITLE
How to change the panel-opacity to 0 

### ISSUE THREAD

**Issue by Panther92** [vinceliuice/WhiteSur-gtk-theme#926]
Hi Vince,
thank you for your work. I really like Vimix and now I would like to try Whitesur-dark. Is there any way to change the panel opacity to 0 if a window is not maximized? Even the default 15% is too high for my liking.

Thank you!

**Comment by vinceliuice** [comment]
Change this:
https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/0e3cc3c036e2765464d7edfd69bb60861c525722/src/sass/gnome-shell/common/_panel.scss#L51
`background-color: $panel_bg;` to `background-color: transparent;`

**Comment by kernelb00t** [comment]
@Panther92 is your issue resolved ?
