### ISSUE TITLE
assets folder missing

### ISSUE THREAD

**Issue by Varad-Codes** [vinceliuice/WhiteSur-gtk-theme#927]
OS: Fedora 38
Everything worked fine until a reboot. After the reboot, the libadwaita app theming was gone. Using the libadwaita-theme-changer I got the theme but the window title buttons were back to the defaults, After looking into the folder '.config/gtk-4.0' the assets folder link was broken, checking the install location of the theme I found the assets folder (the linked) was not present.
Other themes I had on my machine had the assets folder present
I am not sure if my observation is correct or not. I am new to gnome and theming

*Sorry for bad English, it is not my first language.

**Comment by Varad-Codes** [comment]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/117466176/6f3b9c09-3706-44db-8765-e149218f9b01)
 Also the theme doesn't work with Libadawita after a reboot of log out

**Comment by vinceliuice** [comment]
Did not find any color theme extensions, it should works...

**Comment by Varad-Codes** [comment]
reinstalling using the libadwaita flag and using just the -l flag solved it.
