### ISSUE TITLE
Unable to locate image file in pixmap_path

### ISSUE THREAD

**Issue by Guanhuai04** [vinceliuice/WhiteSur-gtk-theme#928]
Hi! When I am using opencv in c++ to show an image, the errors below exist.
![error](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/61959887/7c8735da-bd02-4b64-b20a-ae8a93456d5d)
I've checked the assets folder, there indeed isn't any png file named 'button-active-hover'.

**Comment by vinceliuice** [comment]
Fixed
