### ISSUE TITLE
Gnome 45 Nautilus & notification pannel glitch

### ISSUE THREAD

**Issue by Ravi-Kishor** [vinceliuice/WhiteSur-gtk-theme#933]
Gnome 45 Nautilus Top Bar & notification pannel Calender glitch...please fix this ik will take time...waiting patiently

**Comment by Ravi-Kishor** [comment]
[](url)
![Screenshot from 2023-09-17 01-53-48](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97280268/38e290ac-0185-44f7-9eb9-7fe16194f2b1)
![Screenshot from 2023-09-17 01-53-48](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97280268/467bf893-7252-48af-a7d4-8da663ad896c)

**Comment by RyzenDew** [comment]
Gnome 45 default theme is like Whitesur minus the color buttons so major changes happened 
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/84041391/4de8d81c-ad12-4573-93bd-7d175d3ab968)

**Comment by vinceliuice** [comment]
Fixed!
