### ISSUE TITLE
Theme not building properly when choosing to use a different theme accent color

### ISSUE THREAD

**Issue by TPO100Cofficial** [vinceliuice/WhiteSur-gtk-theme#94]
not sure what i did wrong or if this is just an issue with the theme?
doing `sudo ./install.sh -t pink -g` in the terminal leads to a lot of errors in inkscape and the theme not building properly, but only for the window content styling, title bar and desktop stay the same
![image](https://user-images.githubusercontent.com/33667869/103228195-f09b2000-490e-11eb-9f57-8fb965d44589.png)
![image](https://user-images.githubusercontent.com/33667869/103228228-06104a00-490f-11eb-9589-3deec91aef1a.png)

**Comment by TPO100Cofficial** [comment]
somewhat unrelated to this, but light themes seem to be completely broken after installing whitesur
![image](https://user-images.githubusercontent.com/33667869/103229363-9fd8f680-4911-11eb-833f-ce234112afaa.png)
![image](https://user-images.githubusercontent.com/33667869/103229441-c4cd6980-4911-11eb-97c2-c3d79b74199e.png)

**Comment by vinceliuice** [comment]
Are you using the last version on github?

**Comment by vinceliuice** [comment]
-t cannot use with -g, this is not supported, you can run `./install.sh -t pink` install pink gtk theme then run `sudo ./install.sh -g` install GDM theme

**Comment by Wello6143** [comment]
Pretty sure you are using Ubuntu LTS which has older version of inkscape that won't support `export-filename` flag. Inkscape version must be 1.0.0 or later, you can check it by execute `inkscape --version`.
If it return something like this
`Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)`
then you'll have to update inkscape.
Do this if you're using Ubuntu (or distros based on it):
```
sudo add-apt-repository ppa:inkscape.dev/stable -y
sudo apt update
sudo apt full-upgrade -y
```
then remove the corrupted theme:
```
sudo ./install.sh -r
```
Finally, try to run your install command again.
Let us know immediately if it works.

**Comment by TPO100Cofficial** [comment]
thanks, both of the above worked for building, but light themes still don't apply properly

**Comment by vinceliuice** [comment]
Assets files missing or unreadable, There is a problem with the permissions during installation or compressed package file

**Comment by vinceliuice** [comment]
Check those files: 
![Screenshot from 2020-12-30 18-31-54](https://user-images.githubusercontent.com/7604295/103345811-5af9bf00-4acd-11eb-9c3b-f59baed0f309.png)

**Comment by vinceliuice** [comment]
It they are missing or unreadable, you can download this : [2020-12-30.tar.gz](https://github.com/vinceliuice/WhiteSur-gtk-theme/archive/2020-12-30.tar.gz) and try again

**Comment by TPO100Cofficial** [comment]
got _some_ errors, but i think it built properly, thanks

**Comment by vinceliuice** [comment]
If you can not use any light themes then you need check this config file: 
![Screenshot from 2020-12-31 09-33-35](https://user-images.githubusercontent.com/7604295/103389707-73a8ba00-4b4b-11eb-9735-5bf70f4ef88c.png)

**Comment by vinceliuice** [comment]
Make sure that `gtk-application-prefer-dark-theme=0`

**Comment by TPO100Cofficial** [comment]
Thank you, this worked!
