### ISSUE TITLE
How to get Rounded Corners in dash-to-dock while using blur effect..

### ISSUE THREAD

**Issue by Divyang-lgtm** [vinceliuice/WhiteSur-gtk-theme#940]
Hey @vinceliuice , first of all thanks a lot for this amazing theme for gnome desktops env. 

Buddy, there is an issue (or is it happening in my machine only), here are some attachments,
![Screenshot 2](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/124515230/bf9ef029-c14f-4614-937d-7825cc68406d)
![Screenshot 1](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/124515230/c3987bed-a9b4-4920-95a3-283a05b2862f)
dock edges are squared-corners instead of rounded-corners while enabling blur effect to dash-to-dock extension using blur-my-shell extension.

**Comment by vinceliuice** [comment]
Nope, dash to dock do not support that

**Comment by Divyang-lgtm** [comment]
> Nope, dash to dock do not support that

Okay..Thanks buddy.
sorry for late reply..

**Comment by Divyang-lgtm** [comment]
> Overriding background in Blur my Shell creates a somewhat - transparent overlay on the dock, so you can't really fix it with theming.

yeah, we really can't fix this on our side.

**Comment by Divyang-lgtm** [comment]
> You can try to install the gnome-extensions for rounded-corners from here where your all windows will be rounded instead of squared corners : https://extensions.gnome.org/extension/5237/rounded-window-corners/ You can check out this repository for more information : https://github.com/yilozt/rounded-window-corners

I don't think so buddy...
As we are trying to implement Rounded Corners on the Edges of Dash-to-dock, while enabling blur effects.

**Comment by Divyang-lgtm** [comment]
Guys I am closing this issue...
However, it's not resolved, but I think maybe in future updates, @vinceliuice will try to resolve it..
Also, I am changing my email address (as it is so much exposed) in some time so it will not work and issue will remain open forever without any activity from my side...

Please reply @vinceliuice, should I close it (i.e. issue) , or leave as it is (i.e. remain opened).

**Comment by Bornunique911** [comment]
I think so there is a no solution to this particular issue then if it is failing then. @Divyang-lgtm

**Comment by Divyang-lgtm** [comment]
Okay then, closing this issue..
Thanks a lot Guys for your time, opinions and discussions on it.
Really appreciate that.

**Comment by SVTA-OP** [comment]
> Guys I want to close this issue... However, it's not resolved, but I think maybe in future updates, @vinceliuice will try to resolve it.. Also, I am changing my email address (as it is so much exposed) in some time so it will not work and issue will remain open forever without any activity from my side...
> 
> Please reply @vinceliuice, should I close it (i.e. issue) , or leave as it is (i.e. remain opened).

This is a blur my shell issue, auntex has said that blur features are still in beta so some bugs may occur. Disabling blur my shell fixes the matter here so, this issue should be taken up in the blur my shell repository.

**Comment by Divyang-lgtm** [comment]
> > Guys I want to close this issue... However, it's not resolved, but I think maybe in future updates, @vinceliuice will try to resolve it.. Also, I am changing my email address (as it is so much exposed) in some time so it will not work and issue will remain open forever without any activity from my side...
> > Please reply @vinceliuice, should I close it (i.e. issue) , or leave as it is (i.e. remain opened).
> 
> This is a blur my shell issue, auntex has said that blur features are still in beta so some bugs may occur. Disabling blur my shell fixes the matter here so, this issue should be taken up in the blur my shell repository.

Oh Alright.. I will try to put this issue in that repo, so that they can provide or somehow resolve this bug..
Thanks by the way.

**Comment by MeechaPooch** [comment]
Bump because this is super important!

**Comment by MeechaPooch** [comment]
With this we can make a macOs-rivalling dock on gnome!
