### ISSUE TITLE
Glitch and small alignment issue in Firefox WhiteSur

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#943]
Inside the cookie's dialog, the text in the "remove" button is misaligned
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/e9bf15f0-2205-45a4-bfff-ab2fc2a3e19a)
It can be fixed by setting `align-items: center;` on `.permission-popup-permission-remove-button`

The popup for protected surfing is broken completely
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/0ff32453-195d-4b57-b7fc-d612191be7c1)

**Comment by Laurens256** [comment]
Also found this in the urlbar when translating a page using the new beta translation feature
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/fe285d88-cc5f-4a8c-a948-d7f7eaaea0f3)

**Comment by vinceliuice** [comment]
What's your firefox version ? my firefox is 117.0.1

**Comment by Laurens256** [comment]
Sorry, I am on 118.0.1. this translate button only appeared yesterday but I noticed just now it's gone completely? Not sure if the other issues are version related, feel free to close if they are

**Comment by vinceliuice** [comment]
I update my firefox to 118 now, and fixed all issues
