### ISSUE TITLE
Activities icon in Gnome 45

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#948]
I recently updated Arch with Gnome 45, and the activities icon got glitchy.

![Screenshot from 2023-10-09 20-30-47](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/7a43ffea-002f-4202-8492-fdb8f24fd972)

(zoom in)
![Screenshot from 2023-10-09 20-27-54](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/7ab92132-4d11-43f7-b802-6c19b377d8e8)

**Comment by xnart** [comment]
For workaround you can change `activities.svg` and `activities-white.svg` with a transparent icon. Full path for these files is `~/.themes/WhiteSur-*/gnome-shell/assets`

*Transparent 48x48 icon*: ![](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/5033961/0acab451-b963-44f9-b1ec-bcc78cd08cde)

**Comment by vinceliuice** [comment]
Fixed
