### ISSUE TITLE
Black background block behind the folder panel

### ISSUE THREAD

**Issue by nova1751** [vinceliuice/WhiteSur-gtk-theme#949]
OS:Ubuntu 22.04.3 LTS  GNOME:42.9

I found that when saving images from the browser,there was a  black background block behind the folder panel.At first I thought it was due to GNOME extensions.I tried to ban all the extensions but the problem still occurred.Can anyone figure this out?The problem is just as the picture below:

<img width="556" alt="test" src="https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/97817985/9929bd98-d49c-4309-b4a4-bf5fda52f8ec">

**Comment by vinceliuice** [comment]
你需要更新你的系统，这个是gnome的bug，新版已经修复啦

**Comment by nova1751** [comment]
> 你需要更新你的系统，这个是gnome的bug，新版已经修复啦

Thanks!It worked.

**Comment by kernelb00t** [comment]
Is it still relevant with latest versions? If not, mind closing your issue.
