### ISSUE TITLE
no bold fonts on top bar (Gnome 45)

### ISSUE THREAD

**Issue by paulo-evangelista** [vinceliuice/WhiteSur-gtk-theme#954]
hey y'all!
On past Gnome versions, I had bold fonts on my top bar (just can´t remember if the theme had it by default or if I put it myself).

On gnome 45, the property `font-weight` when applied to any property relating to CSS' `#panel` has no effect whatsoever. Properties like `color, font-size, font-family` do work as expected. 

**Any idea why this happens?**

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/99093520/372a603b-5d8f-46c3-98e4-ff3bb73d6f6d)

how I generated the theme I'm currently using (also tried `-HD`):
`./install.sh -o normal -c Dark -s 220 -l --darker`
using master branch on 64e2ac5

PS: Doesn't really know if this fits as a bug or question :/

**Comment by vinceliuice** [comment]
Fixed now
