### ISSUE TITLE
Facing problem in nautilius file manager

### ISSUE THREAD

**Issue by ZRX-SIGMA** [vinceliuice/WhiteSur-gtk-theme#957]
![Screenshot from 2023-10-16 10-26-02](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/100613008/19cb99a5-5525-4714-a9af-92ec94d97325)

As you can see in my screenshot, two different types of Nautilus file manager are shown, how to fix it?

**Comment by vinceliuice** [comment]
Left is nautilus, right one is nemo, nemo is not nautilus

**Comment by ZRX-SIGMA** [comment]
Sry, right is thunar

**Comment by ZRX-SIGMA** [comment]
But am unable to set nautilus as default

**Comment by Bornunique911** [comment]
If you are using **xfce4**, then you can follow the following steps as under :
1) First open a terminal.
2) Type **xfce4-settings-manager** and hit enter. You will be greeted with a dialog box like this in the screenshot.
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/69379200/d8d30dda-a4bf-449f-be03-a82635efd866)
3) Under System tab, you will find Default Applications option. Click on it and under it click on Utilities to set your default file manager. That's it. And finally you can open your default file manager at ease.

**Comment by ZRX-SIGMA** [comment]
> If you are using **xfce4**, then you can follow the following steps as under :
> 1) First open a terminal.
> 2) Type **xfce4-settings-manager** and hit enter. You will be greeted with a dialog box like this in the screenshot.
> ![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/69379200/d8d30dda-a4bf-449f-be03-a82635efd866)
> 3) Under System tab, you will find Default Applications option. Click on it and under it click on Utilities to set your default file manager. That's it. And finally you can open your default file manager at ease.

Thanks brother

**Comment by Bornunique911** [comment]
> > If you are using **xfce4**, then you can follow the following steps as under :
> > 
> > 1. First open a terminal.
> > 2. Type **xfce4-settings-manager** and hit enter. You will be greeted with a dialog box like this in the screenshot.
> >    ![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/69379200/d8d30dda-a4bf-449f-be03-a82635efd866)
> > 3. Under System tab, you will find Default Applications option. Click on it and under it click on Utilities to set your default file manager. That's it. And finally you can open your default file manager at ease.
> 
> Thanks brother

You safely close the issue if your query is being resolved @ZRX-SIGMA .
