### ISSUE TITLE
hard to read top bar when using light-solid or light-solid-alt

### ISSUE THREAD

**Issue by peterwu** [vinceliuice/WhiteSur-gtk-theme#96]
If I configure my system to use light-solid or light-solid-alt as shell theme (the sceenshot below),  
![Screenshot from 2020-12-28 19-32-50](https://user-images.githubusercontent.com/584751/103250926-653c8180-4944-11eb-80a3-de304ed87bc3.png)

when go to the Activities Overview mode, the top bar is so dim that it's hard to read.
![hard-to-read-top-bar](https://user-images.githubusercontent.com/584751/103250972-9b7a0100-4944-11eb-8226-0f6d4e6b006f.png)

The expected should be like this ( from dark, dark-solid & light flavours )
![expected-top-bar](https://user-images.githubusercontent.com/584751/103250984-a896f000-4944-11eb-9d76-728f915abfcc.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by peterwu** [comment]
Thanks for the fix. Unfortunately, it didn't fix the problem entirely and created a new issue.

light is good;
for light-alt, when in normal mode, the text is black instead of white
![light-alt-normal](https://user-images.githubusercontent.com/584751/103297310-091a4180-49c6-11eb-911c-3e4992180119.png)
for light-alt, light-solid and light-solid-alt, when in overview mode, the logo is dark, which should be white.
![light-alt-overview](https://user-images.githubusercontent.com/584751/103297371-2a7b2d80-49c6-11eb-81bf-675ad27a3cbc.png)

hope the screenshots explain what the problems are. Thank you.

**Comment by vinceliuice** [comment]
Alt version is balck font version for light wallpapers
