### ISSUE TITLE
Gnome 45 Virtual Desktop Indicator

### ISSUE THREAD

**Issue by svta-7125** [vinceliuice/WhiteSur-gtk-theme#962]
Is it possible to set the activities icon to the virtual desktop indicator in gnome 45? The installer defaults to the apple logo.
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/117646988/201afda1-89ce-46fc-b0df-f57652e92b68)

**Comment by vinceliuice** [comment]
NJo problem! I'll add this option

**Comment by vinceliuice** [comment]
Run `./install.sh --default` to set this button to system default style

**Comment by svta-7125** [comment]
Thank you so much! I've been a fan of your theme for a year or two.
