### ISSUE TITLE
Search bar in nautilus still overflowing on the sidebar as mentioned in #723

### ISSUE THREAD

**Issue by leehyukshuai** [vinceliuice/WhiteSur-gtk-theme#964]
**System Info:** Ubuntu22.04, Gnome42.9

**Installation:** `./install.sh -o normal -HD -i ubuntu --nord`

**Problem:** Bug in #723 still exists. When Ctrl+L pressed in nautilus, the path bar will overflow.

**Screenshot:** ![screenshot 2023-10-28](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/95012398/c1492bbb-e229-47ec-ab60-5d545c7c6871)

**P.S.** Thank you for your hard work! This theme fits my tastes very well!

**Comment by vinceliuice** [comment]
![VirtualBox_Ubuntu_28_10_2023_12_39_07](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/e5ad71fd-27f8-4569-8ae2-21f20f40a0c4)

**Comment by vinceliuice** [comment]
没有发现你说的这个问题啊

**Comment by leehyukshuai** [comment]
不好意思，我之前描述不够正确，`Ctrl + F`并没有问题，然而`Ctrl + L`, `/` 和 `~` 这些快捷键都会导致此前截屏展示的问题。

Sorry this bug is not the same as #723. `Ctrl + F` is OK, but `Ctrl + L`, `/` and `~` shortcuts are buggy.

> Upper: `Ctrl + F` is OK; Lower: `Ctrl + L` is buggy.
> 
> ![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/95012398/dd3487ce-d356-452e-99d8-af2a7e15efd6)

**Comment by vinceliuice** [comment]
现在应该没问题了

**Comment by leehyukshuai** [comment]
非常感谢！确实没问题了。

另外提一个小建议，就像下面这两张图展示的这样，WhiteSur中搜索的地址框和下拉按钮之间有一个缝隙，而在默认主题yaru中，这两个部分是同属于一个整体的。所以在点击搜索时，WhiteSur地址框会发生一小段位移，而yaru则不会。

There is a gap between input box and down arrow button, so when search button is pressed, there will be a little move on input box.

![截图 2023-10-28 16-29-26](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/95012398/a545dbd8-4d4b-46a3-b36f-81274d26e1bb)

![截图 2023-10-28 16-29-50](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/95012398/49d3eeb0-dde6-47bc-9a53-82f0197a385c)

如果您有足够的时间和精力的话，希望能稍微调整一下。再次感谢作者大大！

**Comment by vinceliuice** [comment]
Ok, 我调一下

**Comment by leehyukshuai** [comment]
谢谢你的修改，现在已经没有错位了😊

**Comment by vinceliuice** [comment]
不客气
