### ISSUE TITLE
small request 

### ISSUE THREAD

**Issue by sjhaleprogrammer** [vinceliuice/WhiteSur-gtk-theme#965]
I don't know how hard this would be but can you make electron app (vscode,discord) buttons closer together like the other applications

example
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/60676867/68335ac1-6fd3-4808-99a8-454a1659a4f3)

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/60676867/c5e2d27e-6bcf-45ef-8818-6a5762b11185)

**Comment by vinceliuice** [comment]
What's your desktop version?

**Comment by sjhaleprogrammer** [comment]
gnome 44.5

**Comment by vinceliuice** [comment]
![Screenshot from 2023-10-29 14-08-03](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/8b6f2938-4db9-43e6-b004-da1e14bdee74)

**Comment by vinceliuice** [comment]
Did not find this issue

**Comment by sjhaleprogrammer** [comment]
Alright here is more detail now that it is a bug

Gnome 44.5 nixos (latest whitesur package)
Left side controls 
Seems to occur only on electron apps
I have two gpus amd vega and nvidia (laptop)
Gtk4 fix applied
Legacy apps is Whitesur dark

**Comment by sjhaleprogrammer** [comment]
> Did not find this issue

Occurs on wayland ozone electron apps using xwayland fixes but I wish to use this theme on wayland in the future

**Comment by Jason-Yang-2019** [comment]
Sorry to bump up this thread, but how do you have mac style min/mac/close icon for vscode?

I installed this theme but it seems the icons on vscode can’t be changed anyway .

**Comment by sjhaleprogrammer** [comment]
I followed the gtk4 thing on the Readme I think that's what changed it
