### ISSUE TITLE
Blurred buttons without distance to the title

### ISSUE THREAD

**Issue by missaq** [vinceliuice/WhiteSur-gtk-theme#967]
When teams are installed with Edge as PWA, the buttons top left bit blurry and the distance to the title is missing (see screenshot).
![Screenshot from 2023-10-30 08-28-22](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/1445836/71eefc05-9f67-4946-b7a5-2ccdd3f1012a)

**Comment by Arche151** [comment]
@kernelb00t I still have the issue, unfortunately. In my case when using Brave PWA's.
