### ISSUE TITLE
Firefox WhiteSur favicon issues when in meeting

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#970]
Firefox 119 but had this problem in older versions as well. Using the WhiteSur theme

When in a meeting when the browser detects the mic is being used, the microphone icon and favicon are placed weirdly under the speaker icon when the tab is not active. See attached video

https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/a15ecedf-9b6e-476d-842e-a93f6c58a6d9
<br>
Also maybe found another issue with the speaker icon but it might be intended. The speaker icon does not show but neither does the favicon when media with audio is playing on a website. When the firefox window isn't focused hower, the icon shows up again. Here's some screenshots

When window is not focused:
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/8651b255-76af-4c16-845b-d750ff7075e8)

When window is focused:
![Screenshot from 2023-11-02 09-49-52](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/251d32d7-27f7-4280-97b4-9b1a855b7f07)

Not sure if this is intended or not

**Comment by vinceliuice** [comment]
![Screenshot from 2023-11-06 05-11-22](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/7604295/085c5baf-e9b5-43b6-9222-9330136cca37)

**Comment by vinceliuice** [comment]
Did not find this issue

**Comment by Laurens256** [comment]
I will check it again

**Comment by Laurens256** [comment]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/7ca3cfbf-13fb-47a1-a0d9-3ec953350b4c)
Here's an image showing no favicon or speaker icon When playing audio in a tab. This ONLY happens when the firefox window is active. As soon as I open another program / window, the speaker icon shows up again:
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/e9b211cd-1538-4f31-acbc-9bd3af6b8fd4)

In this second screenshot, the "settings" window is active, which makes the speaker icon shows up in the firefox tab. But as soon as I focus the firefox window, the icon dissapears again. In the first screenshot, in the devtools you can see `opacity: 0` is applied to the icon, making it invisible but I'm not sure what the best way to fix this would be

**Comment by Laurens256** [comment]
I found that this code fixes the speaker icon issue for me: 

```css
.tab-icon-overlay {
	:root:not([uidensity='compact'])
		#tabbrowser-tabs:not([secondarytext-unsupported])
		.tabbrowser-tab:not(:hover)
		&[indicator-replaces-favicon] {
		opacity: 1 !important;
	}
}
```

Not sure if you want to implement this because you could not replicate the issue @vinceliuice
