### ISSUE TITLE
Is there any option to Install and edit the Chrome theme?

### ISSUE THREAD

**Issue by faha1999** [vinceliuice/WhiteSur-gtk-theme#973]
**Install and edit the Chrome theme** just like Firefox `./tweaks.sh -f`

**Comment by vinceliuice** [comment]
Nope, chrome do not support css themes like firefox

**Comment by faha1999** [comment]
Go to `chrome://settings/appearance`

sclect  **Use GTK**

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54038576/160954a3-e84f-4a4d-9dfc-08154b0221d6)

final preview: 

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54038576/4c4215ad-762b-462f-b2cc-c2d60e9c161f)
