### ISSUE TITLE
Show workspaces indicator in gnome 45.

### ISSUE THREAD

**Issue by samuelr357** [vinceliuice/WhiteSur-gtk-theme#975]
Hello. I'm using Manjaro with Gnome 45, and now as expected the new gnome has removed the activities button and started showing the workspaces indicator. I use this theme to customize my GDM with "sudo ./tweaks.sh -c Dark -g -b ./gdmback.jpg -N" however the place of the current workspaces indicator is the Apple logo, I would like to keep the indicator from gnome 45 instead of the logo. Would that be possible?

**Comment by jettrich** [comment]
Same issue here using Fedora 39. I'd prefer to completely "disable" the icon (apple, distro-icon, whatever), and keep the new activities/switch workspace indicator from GNOME 45. Currently, I get both displayed - not a showstopper, but kind of "visual confusion" ;)

**Comment by baominhngt** [comment]
You could try the workaround mentioned in #956. It works for me.

**Comment by samuelr357** [comment]
Perfect. This solved the problem, I just needed to make some adjustments.

1. First I removed the theme globally.
 `./tweaks.sh -g -r`
2. Then I changed the `_panel.scss` file located at:
`/WhiteSur-gtk-theme/src/sass/gnome-shell/common`
3. I commented out the line`background-image: url("assets/activities.svg");` :

` -natural-hpadding: $base_padding * 2;
  background-image: url("assets/activities.svg");
  background-position: center center;
  background-size: 24px 24px;
  width: 24px;
  height: 24px;
  color: transparent;
  font-size: 0;`

5. Below I added the following code:
`#panel .panel-button#panelActivities StBoxLayout {
  spacing: 5px;
}
#panel .panel-button#panelActivities .workspace-dot {
  border-radius: 999px;
  min-width: 8px;
  min-height: 8px;
  background-color: #f2f2f2;
}`
6. I replaced the file `/tmp/WhiteSur-gtk-theme/src/assets/gnome-shell/activities/activities.svg` with an empty image. PS: I simply erased the icon and replaced it.
7. After that I reinstalled the GDM theme `sudo ./tweaks.sh -c Dark -g -b ./gdmback.jpg -N` and success.

![Captura de tela de 2023-11-08 19-22-04](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/23464885/3f5d46dc-05b4-4ce6-a607-6bd2907a8f6f)

**Comment by anaseig** [comment]
Yes it works. thank you.
but it is still not fixed by default. So wouldn't it be better not to close the issue?
