### ISSUE TITLE
Window icons missing after uninstall

### ISSUE THREAD

**Issue by hirnschmalz** [vinceliuice/WhiteSur-gtk-theme#979]
After I uninstalled the theme the window icons for minimize, maximize and close are missing

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/4834988/a9b7f0bf-e75a-45bd-b9c7-29a53e7c44fd)

**Comment by hirnschmalz** [comment]
Furthermore, the Nautilus windows also looks strange now

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/4834988/fde8e0c4-e110-4806-997c-0be28bbda768)

**Comment by vinceliuice** [comment]
How did you uninstall it ?

**Comment by hirnschmalz** [comment]
I did a

```bash
./install.sh -r
./tweaks.sh -d -r
```

**Comment by vinceliuice** [comment]
`./install.sh -l -r`

**Comment by hirnschmalz** [comment]
I tried, but this does not solve my issues.

**Comment by hirnschmalz** [comment]
I had to delete my `.config/gtk-X.Y` directories to resolve the described issues.
