### ISSUE TITLE
Settings and Nautilus have visual glitches

### ISSUE THREAD

**Issue by ElStefanos** [vinceliuice/WhiteSur-gtk-theme#980]
Ubuntu 23.10 
Installation: sudo ./install.sh -N mojave -o solid -c Light -c Dark -t blue
Tweaks just gnome and firefox

There seems to be opacity problems with nautilus app
![Screenshot from 2023-11-10 16-35-05](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/46761434/5e7c72e3-1ac1-4692-950a-0baa379485db)

![Screenshot from 2023-11-10 16-35-57](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/46761434/58e11054-9b95-41a5-ad38-a27113aa8c74)

Also for the settings app it doesn't look like opacity problem
![Screenshot from 2023-11-10 16-37-29](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/46761434/5cc7f653-c1c4-48c2-ad4d-ca77ee98cbcc)

**Comment by vinceliuice** [comment]
`git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git --depth=1`
download the last update here

**Comment by ElStefanos** [comment]
Didn't fix it, also tried restarting

**Comment by sonic-warrior** [comment]
I had this issue after updating to Gnome 45. What fixed this bug in my case was to reinstall the theme using the default Nautilus theme instead of the Mojave variant.

**Comment by ElStefanos** [comment]
@sonic-warrior I went with glassy, normal, stable and mojave. That didn't fix it. Did you completely remove the theme and install it again?

**Comment by vinceliuice** [comment]
just run: `./install.sh -l`

**Comment by ElStefanos** [comment]
> just run: `./install.sh -l`

Thanks it worked!
