### ISSUE TITLE
No option for alternative variant for Firefox's window control buttons 

### ISSUE THREAD

**Issue by fernandesafp** [vinceliuice/WhiteSur-gtk-theme#982]
I use the alternative window control buttons but unfortunately there's no option on tweaks.sh to do the same for Firefox.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/43553bc2-8bc6-4b79-ba6b-ee574325f7fc)

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/4b3ba28f-1381-4673-89f7-d67e50fc8651)

**Comment by kernelb00t** [comment]
This is indeed a good feature @vinceliuice

**Comment by fernandesafp** [comment]
Indeed, especially because I like the custom Firefox themes but since I use the alt buttons I just leave it as the default.

**Comment by vinceliuice** [comment]
I rename the Alt theme version to 'Flat', now 'alt' option is alt windows button version
