### ISSUE TITLE
--darker option for Firefox theme

### ISSUE THREAD

**Issue by fernandesafp** [vinceliuice/WhiteSur-gtk-theme#983]
Would be nice to also have the --darker option from ./install.sh to Firefox.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/3afb671f-eaf4-4c12-be1c-322c12e59130)

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/f3bb4729-9c19-4626-9143-ede9899bf5dc)

**Comment by fernandesafp** [comment]
If anyone is interested in a quick fix, I edited the `/src/other/firefox/Monterey/colors/dark.css` and `/src/other/firefox/WhiteSur/colors/dark.css` files with a darker theme on my fork https://github.com/fernandesafp/WhiteSur-gtk-theme/tree/darker-firefox.

**Comment by kernelb00t** [comment]
If you are interested in making a PR to implement this, we would be very happy to implement this! If not, please close this issue.

**Comment by fernandesafp** [comment]
I only changed the css colors for the flat theme so no flags implemented or anything. @vinceliuice is it possible to have Firefox theme follow the --darker option from install.sh?

**Comment by kernelb00t** [comment]
Hello! This is possible, but it would be easier to use a flag (to be able to install firefox theme without installing the theme, letting the user choose).

PS: I read my previous message again, and I am terribly sorry for my formulation. The meaning was that you could implement it yourself, but not that this issue would not be considered if you are unable to.
