### ISSUE TITLE
Cannnot target background of selected, active app

### ISSUE THREAD

**Issue by smileBeda** [vinceliuice/WhiteSur-gtk-theme#984]
See screenshot.
The semi-transparent background of the _active_ app cannot be controlled, at all.
I have edited every single `background-color` and `background` in the gnome-shell.css and that one background won't change.

How can we change its color please?

Thanks!
![Screenshot from 2023-11-25 20-05-02](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/11800236/f60baadf-35a8-44e4-9a83-56b05700c2d4)

**Comment by kernelb00t** [comment]
Is it still relevant with latest versions? If not, mind closing your issue. @smileBeda

**Comment by smileBeda** [comment]
HI, I do not use Linux anymore.
