### ISSUE TITLE
Is there a way to reduce the titlebar height?

### ISSUE THREAD

**Issue by osBins** [vinceliuice/WhiteSur-gtk-theme#987]
I love this theme. One thing which sticks out to me and can be modified in my personal opinion is making the titlebar for applications thinner.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/70942982/06aaa452-ee73-4e4c-b655-bececc99c3df)

I have tried modifying the `headerbar` properties in `~/.config/gtk-3.0/gtk.css` > logged out and logged back in to check but nothing worked.

**Comment by kernelb00t** [comment]
Is it still relevant with latest versions? If not, mind closing your issue. @osBins
