### ISSUE TITLE
Nautilus and Inkscape: Objects that have been selected do not show a distinguishable background color

### ISSUE THREAD

**Issue by blickers** [vinceliuice/WhiteSur-gtk-theme#988]
Description of the problem:

Selections in Nautilus file manager lack distinctive colors for selected files. This frequently confuses me about which file is selected.

Inkscape is an example of an application where this situation is observed, too. In Inkscape, the "Layers and Objects" tab fails to indicate selected items through distinct colors, making it difficult to determine the current selection.

Inkscape (version 1.3):
![1](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54505861/9667d366-8357-4409-bb12-347f529fb94f)
![2](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/54505861/4f8a3077-a7fc-4bc8-b711-b0d6bda78da5)

The issue will not arise when using the GNOME default theme (Adwaita). So, there appears to be a bug in the WhiteSur-gtk-theme. Hope it will be fixed soon.

**Comment by kernelb00t** [comment]
Is it still relevant with latest versions? If not, mind closing your issue. @blickers

**Comment by blickers** [comment]
I tried the latest master branch.
Nautilus is OK.
But the Inkscape problem is still there.
So, the bug is not fixed yet.
You can test by yourself.
Seems not the right time close this issue. @kernelb00t @vinceliuice
