### ISSUE TITLE
Whitesur-dark doesn't apply a dark color to the window decoration of apps that are not from gnome

### ISSUE THREAD

**Issue by adam-devel** [vinceliuice/WhiteSur-gtk-theme#99]
the window decoration around apps like "sublime text" and "alacritty" and others that are using the default window decoration doesn't fit the dark variation of the theme

this is not the case for apps that do window decoration the way gnome does it, like "tweaks" and "nautilus":
![Screenshot from 2021-01-04 16-18-03](https://user-images.githubusercontent.com/70688335/103549945-73d8ea80-4ea8-11eb-90c5-c70ba63078d8.png)

**Comment by vinceliuice** [comment]
I'll try fix this

**Comment by adam-devel** [comment]
apparently its a problem with gnome, shell themes doesn't get applied to the title bars, i have to logout and log back in, sorry for making you deal with that
