### ISSUE TITLE
After uninstall Whitesur theme the apple logo still show over the activities button

### ISSUE THREAD

**Issue by sabamdarif** [vinceliuice/WhiteSur-gtk-theme#992]
hell: bash 5.2.21 
 Resolution: 1920x1080 
DE: GNOME 45.2 
WM: Mutter 
WM Theme: Orchis-Light 
heme: Orchis-Light [GTK2/3] 
Icons: WhiteSur [GTK2/3] 

after uninstall this theme if i apply any other theme it looks like this the apple logo apper in top of activities button 
![Screenshot from 2023-12-07 11-57-28](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/111168803/38d87eb3-4f02-459d-9d4f-cd4b251de17d)

And if i apply default theme it's change into whitesur theme 
![Screenshot from 2023-12-07 12-05-35](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/111168803/0682a30a-7ced-4445-ae70-d0d0b469e4ca)

**Comment by fr3nchalp4a** [comment]
You have to reboot (or at least restart) Gnome Shell (by logging out then in, or on X11 `alt`+`f2` then `restart`).

**Comment by sabamdarif** [comment]
> You have to reboot (or at least restart) Gnome Shell (by logging out then in, or on X11 `alt`+`f2` then `restart`).



> You have to reboot (or at least restart) Gnome Shell (by logging out then in, or on X11 `alt`+`f2` then `restart`).

![Screenshot from 2024-01-04 19-28-05](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/111168803/6930aa3c-b901-480f-862e-4fab304390e2)


still have the same issue

**Comment by greendesertsnow** [comment]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/88274580/e0a932c3-d675-41a1-b8c6-21b173cc410b)
I have the same issue.

**Comment by vinceliuice** [comment]
Remove GDM theme
