### ISSUE TITLE
Pop_Os dock has a huge extra padding when "on bottom" 

### ISSUE THREAD

**Issue by Giovannimbesi25** [vinceliuice/WhiteSur-gtk-theme#993]
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.5.6-76060506-generic 
DE: GNOME 42.5 
WM Theme: Pop 
Theme: WhiteSur-Dark-solid-orange [GTK2/3] 
Icons: WhiteSur-orange-dark [GTK2/3] 

Compared to the "on side" option, the "on bottom" option shows an extra padding/margin. Here the screenshots

![Schermata del 2023-12-07 12-52-18](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/94128698/7fe5590e-c53a-4ef8-a6ea-f606a543c303)

![Schermata del 2023-12-07 12-52-45](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/94128698/6b58af93-85d2-4a1b-bec6-05d4dbf447d9)

**Comment by fr3nchalp4a** [comment]
That's Gnome 42, and now we are at 45. That's a little bit old, so if you can get Pop OS to have a more recent Gnome version, you will then have a more recent Dash to Dock version, and so better compatibility with the theme. I don't think we can do something to patch Gnome per versions, so these bugs will always exist. You can patch yourself the theme or use an older version of the theme.

**Comment by kernelb00t** [comment]
Is it still relevant? If not, please close your issue. @Giovannimbesi25
