### ISSUE TITLE
Weird orange - ish highlight color on all gtk4 apps.

### ISSUE THREAD

**Issue by SVTA-OP** [vinceliuice/WhiteSur-gtk-theme#996]
Worked fine when I installed the first time, but reinstalling it changes the highlight color to a orange - ish yellow instead of a normal blue.  
  
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/126323835/6d7522c6-a914-496f-9fb6-f2fa9cd1c41a)
Is this a bug?

I'm using Gnome 45 (Wayland) on Fedora 39.

Thanks in advance.

**Comment by FelixFourcolor** [comment]
I think I've encountered a similar issue. What install options did you use?

**Comment by SVTA-OP** [comment]
I remember adding -t all while installing gtk4 theme with -l. Fixed the problem by choosing one color instead of installing all of them.

**Comment by FelixFourcolor** [comment]
Oh yeah, same here. `-t all -l` installs multiple gtk themes, but only one of them is installed to libadwaita.

**Comment by kernelb00t** [comment]
Is it solved? If yes please close your issue, thanks! 😉
