### ISSUE TITLE
Active Keyboard Layout Display Issue

### ISSUE THREAD

**Issue by andrei-kozel** [vinceliuice/WhiteSur-gtk-theme#998]
When the system is configured with multiple keyboard layouts, an issue arises. The active keyboard layout is displayed in a container that is twice the size of the containers for inactive layouts:
![Screenshot from 2023-12-22 11-21-59](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/1368251/ede0dae8-ab27-4198-8376-22f0fdd05b36)

![Screenshot from 2023-12-22 11-28-27](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/1368251/b1318067-defa-4889-909f-89e1cc02eb12)

**Comment by kernelb00t** [comment]
Is your issue still ongoing? If not please close your issue. @andrei-kozel

**Comment by andrei-kozel** [comment]
@kernelb00t i picked another theme.
